//! Generated by ontogen. DO NOT EDIT.

use schemars::JsonSchema;
use serde::Deserialize;

/// Input for creating a new Exercise.
#[derive(Debug, Clone, Deserialize, JsonSchema, specta::Type)]
pub struct CreateExerciseInput {
    pub id: String,
    pub name: String,
    pub muscle_group: String,
    pub equipment: String,
    #[serde(default)]
    pub notes: Option<String>,
}

/// Input for updating an existing Exercise.
/// All fields are optional; only provided fields are updated.
#[derive(Debug, Clone, Deserialize, JsonSchema, specta::Type)]
pub struct UpdateExerciseInput {
    #[serde(default)]
    pub name: Option<String>,
    #[serde(default)]
    pub muscle_group: Option<String>,
    #[serde(default)]
    pub equipment: Option<String>,
    #[serde(default)]
    pub notes: Option<Option<String>>,
}
