//! Generated by ontogen. DO NOT EDIT.

use schemars::JsonSchema;
use serde::Deserialize;

/// Input for creating a new Document.
#[derive(Debug, Clone, Deserialize, JsonSchema, specta::Type)]
pub struct CreateDocumentInput {
    #[serde(default)]
    pub id: String,
    pub title: String,
    #[serde(default)]
    pub match_id: Option<String>,
    #[serde(default)]
    pub ref_id: Option<String>,
    #[serde(default)]
    pub r#loop: Vec<String>,
    pub body: String,
}

/// Input for updating an existing Document.
/// All fields are optional; only provided fields are updated.
#[derive(Debug, Clone, Deserialize, JsonSchema, specta::Type)]
pub struct UpdateDocumentInput {
    #[serde(default)]
    pub title: Option<String>,
    #[serde(default, deserialize_with = "double_option")]
    pub match_id: Option<Option<String>>,
    #[serde(default, deserialize_with = "double_option")]
    pub ref_id: Option<Option<String>>,
    #[serde(default)]
    pub r#loop: Option<Vec<String>>,
    #[serde(default)]
    pub body: Option<String>,
}

fn double_option<'de, T, D>(de: D) -> Result<Option<Option<T>>, D::Error>
where
    T: Deserialize<'de>,
    D: serde::Deserializer<'de>,
{
    Deserialize::deserialize(de).map(Some)
}
