//! Generated by ontogen. DO NOT EDIT.

use schemars::JsonSchema;
use serde::Deserialize;

/// Input for creating a new Path.
#[derive(Debug, Clone, Deserialize, JsonSchema, specta::Type)]
pub struct CreatePathInput {
    #[serde(default)]
    pub id: String,
    pub title: String,
}

/// Input for updating an existing Path.
/// All fields are optional; only provided fields are updated.
#[derive(Debug, Clone, Deserialize, JsonSchema, specta::Type)]
pub struct UpdatePathInput {
    #[serde(default)]
    pub title: Option<String>,
}
