//! Generated by ontogen. DO NOT EDIT.

use schemars::JsonSchema;
use serde::Deserialize;

/// Input for creating a new Request.
#[derive(Debug, Clone, Deserialize, JsonSchema, specta::Type)]
pub struct CreateRequestInput {
    #[serde(default)]
    pub id: String,
    pub title: String,
}

/// Input for updating an existing Request.
/// All fields are optional; only provided fields are updated.
#[derive(Debug, Clone, Deserialize, JsonSchema, specta::Type)]
pub struct UpdateRequestInput {
    #[serde(default)]
    pub title: Option<String>,
}
