#![allow(dead_code, unused_imports, clippy::pedantic, clippy::needless_borrow)]
//! Auto-generated HTTP route handlers. DO NOT EDIT.
//!
//! Generated by ontogen from API source files. Apart from the route
//! handlers, named like the IPC commands, every item this file defines is
//! `Ontogen`- or `ontogen_`-prefixed, and every runtime item is imported
//! under an `Ontogen` alias or named by its `::`-rooted path, so the only
//! types and modules it names bare are your own types and API modules.

use ::axum::extract::{RawQuery as OntogenRawQuery, State as OntogenState};
use ::axum::http::{Method as OntogenMethod, StatusCode as OntogenStatusCode};
use ::axum::response::Response as OntogenResponse;
use ::ontogen_jsonapi::extract::{
    AcceptGuard as OntogenAcceptGuard, Body as OntogenBody, NoParams as OntogenNoParams, Path as OntogenPath,
    Query as OntogenQuery, RouteQuery as OntogenRouteQuery,
};
use ::ontogen_jsonapi::links::CanonicalQuery as OntogenCanonicalQuery;
use ::ontogen_jsonapi::request::{
    Endpoint as OntogenEndpoint, LinkedId as OntogenLinkedId, ResourceData as OntogenResourceData,
};
use ::ontogen_jsonapi::{
    AnyResource as OntogenAnyResource, Document as OntogenDocument, ErrorObject as OntogenErrorObject,
    Included as OntogenIncluded, Linkage as OntogenLinkage, Links as OntogenLinks, LookupKey as OntogenLookupKey,
    PageMeta as OntogenPageMeta, QueryParams as OntogenQueryParams, QuerySpec as OntogenQuerySpec,
    Relationship as OntogenRelationship, ResourceIdentifier as OntogenResourceIdentifier,
    ResourceObject as OntogenResourceObject,
};

use crate::AppState;
use crate::api::v1::{epic, tag, task};
use crate::schema::{
    CreateEpicInput, CreateTagInput, CreateTaskInput, Epic, ListTasksQuery, Tag, Task, UpdateEpicInput, UpdateTagInput,
    UpdateTaskInput,
};

/// An `AppError` as an error object: the status its variant's name gives,
/// and the name in snake_case as the code.
fn ontogen_app_error(e: crate::schema::AppError) -> OntogenErrorObject {
    let (status, code) = match &e {
        crate::schema::AppError::TaskNotFound(..) => (OntogenStatusCode::NOT_FOUND, "task_not_found"),
        crate::schema::AppError::TaskIdRequired(..) => (OntogenStatusCode::BAD_REQUEST, "task_id_required"),
        crate::schema::AppError::TaskAlreadyExists(..) => (OntogenStatusCode::CONFLICT, "task_already_exists"),
        crate::schema::AppError::EpicNotFound(..) => (OntogenStatusCode::NOT_FOUND, "epic_not_found"),
        crate::schema::AppError::EpicIdRequired(..) => (OntogenStatusCode::BAD_REQUEST, "epic_id_required"),
        crate::schema::AppError::EpicAlreadyExists(..) => (OntogenStatusCode::CONFLICT, "epic_already_exists"),
        crate::schema::AppError::TagNotFound(..) => (OntogenStatusCode::NOT_FOUND, "tag_not_found"),
        crate::schema::AppError::TagIdRequired(..) => (OntogenStatusCode::BAD_REQUEST, "tag_id_required"),
        crate::schema::AppError::TagAlreadyExists(..) => (OntogenStatusCode::CONFLICT, "tag_already_exists"),
        crate::schema::AppError::Md(..) => (OntogenStatusCode::INTERNAL_SERVER_ERROR, "md"),
    };
    OntogenErrorObject::app(status, code, e.to_string())
}

/// A failure no `AppError` describes: opening the store, a scope accessor,
/// or an op with another error type.
fn ontogen_internal_error(e: impl ::std::fmt::Display) -> OntogenErrorObject {
    OntogenErrorObject::internal(e.to_string())
}

/// The method fallback of a route serving `allowed`: `405` with `Allow`.
fn ontogen_allow<const N: usize>(
    allowed: [OntogenMethod; N],
) -> impl Fn(OntogenMethod) -> ::std::future::Ready<OntogenResponse> + Clone + Send + Sync + 'static {
    move |method| ::std::future::ready(::ontogen_jsonapi::error::method_not_allowed(&method, &allowed))
}

/// `ids` with each id of `linked` it lacks appended, or `None` when it lacks
/// none: a relationship `POST` that adds nothing writes nothing.
fn ontogen_added(ids: &[String], linked: &[OntogenLinkedId]) -> Option<Vec<String>> {
    let added: Vec<String> = linked.iter().map(|l| l.id.clone()).filter(|id| !ids.contains(id)).collect();
    (!added.is_empty()).then(|| [ids, added.as_slice()].concat())
}

/// `ids` without the ids of `linked`, or `None` when it holds none of them: a
/// relationship `DELETE` that removes nothing writes nothing.
fn ontogen_removed(ids: &[String], linked: &[OntogenLinkedId]) -> Option<Vec<String>> {
    let kept: Vec<String> = ids.iter().filter(|id| !linked.iter().any(|l| l.id == **id)).cloned().collect();
    (kept.len() != ids.len()).then_some(kept)
}

// ── JSON:API resources ──

struct OntogenListParams;

impl OntogenRouteQuery for OntogenListParams {
    const SPEC: OntogenQuerySpec = OntogenQuerySpec { sort: true, include: true, ..OntogenQuerySpec::NONE };
}

struct OntogenPagedListParams;

impl OntogenRouteQuery for OntogenPagedListParams {
    const SPEC: OntogenQuerySpec = OntogenQuerySpec { sort: true, include: true, page: true, ..OntogenQuerySpec::NONE };
}

struct OntogenGetParams;

impl OntogenRouteQuery for OntogenGetParams {
    const SPEC: OntogenQuerySpec = OntogenQuerySpec { include: true, ..OntogenQuerySpec::NONE };
}

/// The effective `(offset, limit)` of a paginated list.
fn ontogen_page(
    query: &OntogenQueryParams,
    default_limit: u32,
    max_limit: u32,
) -> Result<(u32, u32), OntogenErrorObject> {
    let offset = query.page_offset()?.unwrap_or(0);
    let limit = query.page_limit()?.unwrap_or(default_limit).min(max_limit);
    Ok((offset, limit))
}

/// Sets `name` when the request document carried it.
fn ontogen_set_field(
    fields: &mut ::serde_json::Map<String, ::serde_json::Value>,
    name: &str,
    value: Option<&::serde_json::Value>,
) {
    if let Some(value) = value {
        fields.insert(name.to_owned(), value.clone());
    }
}

/// A create or update input from the fields its request document set. Each
/// field was checked against its type, so a failure here is the server's.
fn ontogen_from_fields<T: ::serde::de::DeserializeOwned>(
    fields: ::serde_json::Map<String, ::serde_json::Value>,
) -> Result<T, OntogenErrorObject> {
    ::serde_json::from_value(::serde_json::Value::Object(fields)).map_err(ontogen_internal_error)
}

// ── `epics` ──

/// `Epic`'s attributes: every field but the id and the relations, in
/// declaration order.
struct OntogenEpicResourceAttributes<'a>(&'a Epic);

impl ::serde::Serialize for OntogenEpicResourceAttributes<'_> {
    fn serialize<S: ::serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        use ::serde::ser::SerializeStruct;
        let mut attributes = serializer.serialize_struct("OntogenEpicResourceAttributes", 3)?;
        attributes.serialize_field("title", &self.0.title)?;
        attributes.serialize_field("status", &self.0.status)?;
        attributes.serialize_field("body", &self.0.body)?;
        attributes.end()
    }
}

/// `entity` as a resource object of type `epics`, its `links.self`
/// under `collection`.
fn ontogen_epic_as_resource<'a>(
    entity: &'a Epic,
    collection: &str,
) -> OntogenResourceObject<OntogenEpicResourceAttributes<'a>> {
    let self_link = format!("{collection}/{}", ::ontogen_jsonapi::links::encode_path_segment(&entity.id));
    OntogenResourceObject::new("epics", entity.id.clone(), OntogenEpicResourceAttributes(entity), self_link)
}

/// The id an `{id}` path segment names.
fn ontogen_epic_lookup_key(id: &OntogenLookupKey) -> Result<&str, OntogenErrorObject> {
    id.as_str().ok_or_else(|| ontogen_app_error(crate::schema::AppError::EpicNotFound(id.to_string())))
}

/// The fields a create or update document for `epics` sets, named as
/// the input's fields, each member checked against the schema.
fn ontogen_epic_request_fields(
    data: &OntogenResourceData,
    create: bool,
) -> Result<::serde_json::Map<String, ::serde_json::Value>, OntogenErrorObject> {
    let attributes = data.attributes.as_ref();
    ::ontogen_jsonapi::request::check_attribute_names(attributes, "epics", &["title", "status", "body"], &[])?;
    let mut fields = ::serde_json::Map::new();
    if create {
        fields.insert("id".to_owned(), ::serde_json::Value::String(data.id.clone().unwrap_or_default()));
    }
    ontogen_set_field(
        &mut fields,
        "title",
        ::ontogen_jsonapi::request::attribute::<String>(attributes, "title", create)?,
    );
    ontogen_set_field(
        &mut fields,
        "status",
        ::ontogen_jsonapi::request::attribute::<String>(attributes, "status", create)?,
    );
    ontogen_set_field(
        &mut fields,
        "body",
        ::ontogen_jsonapi::request::attribute::<String>(attributes, "body", create)?,
    );
    ::ontogen_jsonapi::request::check_relationship_names(data.relationships()?, "epics", &[])?;
    Ok(fields)
}

// ── `tags` ──

/// `Tag`'s attributes: every field but the id and the relations, in
/// declaration order.
struct OntogenTagResourceAttributes<'a>(&'a Tag);

impl ::serde::Serialize for OntogenTagResourceAttributes<'_> {
    fn serialize<S: ::serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        use ::serde::ser::SerializeStruct;
        let mut attributes = serializer.serialize_struct("OntogenTagResourceAttributes", 1)?;
        attributes.serialize_field("title", &self.0.title)?;
        attributes.end()
    }
}

/// `entity` as a resource object of type `tags`, its `links.self`
/// under `collection`.
fn ontogen_tag_as_resource<'a>(
    entity: &'a Tag,
    collection: &str,
) -> OntogenResourceObject<OntogenTagResourceAttributes<'a>> {
    let self_link = format!("{collection}/{}", ::ontogen_jsonapi::links::encode_path_segment(&entity.id));
    OntogenResourceObject::new("tags", entity.id.clone(), OntogenTagResourceAttributes(entity), self_link)
}

/// The id an `{id}` path segment names.
fn ontogen_tag_lookup_key(id: &OntogenLookupKey) -> Result<&str, OntogenErrorObject> {
    id.as_str().ok_or_else(|| ontogen_app_error(crate::schema::AppError::TagNotFound(id.to_string())))
}

/// The fields a create or update document for `tags` sets, named as
/// the input's fields, each member checked against the schema.
fn ontogen_tag_request_fields(
    data: &OntogenResourceData,
    create: bool,
) -> Result<::serde_json::Map<String, ::serde_json::Value>, OntogenErrorObject> {
    let attributes = data.attributes.as_ref();
    ::ontogen_jsonapi::request::check_attribute_names(attributes, "tags", &["title"], &[])?;
    let mut fields = ::serde_json::Map::new();
    if create {
        fields.insert("id".to_owned(), ::serde_json::Value::String(data.id.clone().unwrap_or_default()));
    }
    ontogen_set_field(
        &mut fields,
        "title",
        ::ontogen_jsonapi::request::attribute::<String>(attributes, "title", create)?,
    );
    ::ontogen_jsonapi::request::check_relationship_names(data.relationships()?, "tags", &[])?;
    Ok(fields)
}

// ── `tasks` ──

/// `Task`'s attributes: every field but the id and the relations, in
/// declaration order.
struct OntogenTaskResourceAttributes<'a>(&'a Task);

impl ::serde::Serialize for OntogenTaskResourceAttributes<'_> {
    fn serialize<S: ::serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        use ::serde::ser::SerializeStruct;
        let mut attributes = serializer.serialize_struct("OntogenTaskResourceAttributes", 4)?;
        attributes.serialize_field("title", &self.0.title)?;
        attributes.serialize_field("status", &self.0.status)?;
        attributes.serialize_field("created", &self.0.created)?;
        attributes.serialize_field("body", &self.0.body)?;
        attributes.end()
    }
}

/// `entity` as a resource object of type `tasks`, its `links.self`
/// under `collection`.
fn ontogen_task_as_resource<'a>(
    entity: &'a Task,
    collection: &str,
) -> OntogenResourceObject<OntogenTaskResourceAttributes<'a>> {
    let self_link = format!("{collection}/{}", ::ontogen_jsonapi::links::encode_path_segment(&entity.id));
    OntogenResourceObject::new("tasks", entity.id.clone(), OntogenTaskResourceAttributes(entity), self_link.clone())
        .with_relationship(
            "epic",
            OntogenRelationship::new(
                OntogenLinks::new(format!("{self_link}/relationships/epic")).with_related(format!("{self_link}/epic")),
                OntogenLinkage::ToOne(
                    entity.epic_id.as_ref().map(|id| OntogenResourceIdentifier::new("epics", id.as_str())),
                ),
            ),
        )
        .with_relationship(
            "tags",
            OntogenRelationship::new(
                OntogenLinks::new(format!("{self_link}/relationships/tags")).with_related(format!("{self_link}/tags")),
                OntogenLinkage::ToMany(
                    entity.tags.iter().map(|id| OntogenResourceIdentifier::new("tags", id.as_str())).collect(),
                ),
            ),
        )
        .with_relationship(
            "parent",
            OntogenRelationship::new(
                OntogenLinks::new(format!("{self_link}/relationships/parent"))
                    .with_related(format!("{self_link}/parent")),
                OntogenLinkage::ToOne(
                    entity.parent_id.as_ref().map(|id| OntogenResourceIdentifier::new("tasks", id.as_str())),
                ),
            ),
        )
        .with_relationship(
            "subtasks",
            OntogenRelationship::new(
                OntogenLinks::new(format!("{self_link}/relationships/subtasks"))
                    .with_related(format!("{self_link}/subtasks")),
                OntogenLinkage::ToMany(
                    entity.subtasks.iter().map(|id| OntogenResourceIdentifier::new("tasks", id.as_str())).collect(),
                ),
            ),
        )
}

/// The id an `{id}` path segment names.
fn ontogen_task_lookup_key(id: &OntogenLookupKey) -> Result<&str, OntogenErrorObject> {
    id.as_str().ok_or_else(|| ontogen_app_error(crate::schema::AppError::TaskNotFound(id.to_string())))
}

/// The ids a request document for `tasks` links, by relationship, to
/// be checked to name resources that exist.
#[derive(Default)]
struct OntogenTaskLinkedIds {
    epic_id: Option<OntogenLinkedId>,
    tags: Vec<OntogenLinkedId>,
    parent_id: Option<OntogenLinkedId>,
    subtasks: Vec<OntogenLinkedId>,
}

/// The fields a create or update document for `tasks` sets, named as
/// the input's fields, each member checked against the schema.
fn ontogen_task_request_fields(
    data: &OntogenResourceData,
    create: bool,
) -> Result<(::serde_json::Map<String, ::serde_json::Value>, OntogenTaskLinkedIds), OntogenErrorObject> {
    let attributes = data.attributes.as_ref();
    ::ontogen_jsonapi::request::check_attribute_names(
        attributes,
        "tasks",
        &["title", "status", "created", "body"],
        &[("epic_id", "epic"), ("tags", "tags"), ("parent_id", "parent"), ("subtasks", "subtasks")],
    )?;
    let mut fields = ::serde_json::Map::new();
    if create {
        fields.insert("id".to_owned(), ::serde_json::Value::String(data.id.clone().unwrap_or_default()));
    }
    ontogen_set_field(
        &mut fields,
        "title",
        ::ontogen_jsonapi::request::attribute::<String>(attributes, "title", create)?,
    );
    ontogen_set_field(
        &mut fields,
        "status",
        ::ontogen_jsonapi::request::attribute::<String>(attributes, "status", create)?,
    );
    ontogen_set_field(
        &mut fields,
        "created",
        ::ontogen_jsonapi::request::attribute::<String>(attributes, "created", create)?,
    );
    ontogen_set_field(
        &mut fields,
        "body",
        ::ontogen_jsonapi::request::attribute::<String>(attributes, "body", create)?,
    );
    let relationships = data.relationships()?;
    ::ontogen_jsonapi::request::check_relationship_names(
        relationships,
        "tasks",
        &["epic", "tags", "parent", "subtasks"],
    )?;
    let mut linked = OntogenTaskLinkedIds::default();
    if let Some(rel) = relationships.and_then(|r| r.get("epic")) {
        let id = ::ontogen_jsonapi::request::to_one(rel, "/data/relationships/epic", "epics", true)?;
        fields.insert("epic_id".to_owned(), id.clone().map_or(::serde_json::Value::Null, ::serde_json::Value::String));
        linked.epic_id = id.map(|id| OntogenLinkedId { id, pointer: "/data/relationships/epic/data".to_owned() });
    }
    if let Some(rel) = relationships.and_then(|r| r.get("tags")) {
        let ids = ::ontogen_jsonapi::request::to_many_linked(rel, "/data/relationships/tags", "tags", None)?;
        fields.insert("tags".to_owned(), ids.iter().map(|l| ::serde_json::Value::String(l.id.clone())).collect());
        linked.tags = ids;
    }
    if let Some(rel) = relationships.and_then(|r| r.get("parent")) {
        let id = ::ontogen_jsonapi::request::to_one(rel, "/data/relationships/parent", "tasks", true)?;
        fields
            .insert("parent_id".to_owned(), id.clone().map_or(::serde_json::Value::Null, ::serde_json::Value::String));
        linked.parent_id = id.map(|id| OntogenLinkedId { id, pointer: "/data/relationships/parent/data".to_owned() });
    }
    if let Some(rel) = relationships.and_then(|r| r.get("subtasks")) {
        let ids = ::ontogen_jsonapi::request::to_many_linked(rel, "/data/relationships/subtasks", "tasks", None)?;
        fields.insert("subtasks".to_owned(), ids.iter().map(|l| ::serde_json::Value::String(l.id.clone())).collect());
        linked.subtasks = ids;
    }
    Ok((fields, linked))
}

/// Checks that each id a create or update document for `tasks` links
/// names a resource that exists, in the order the document was read.
async fn ontogen_task_check_linked(state: &AppState, linked: &OntogenTaskLinkedIds) -> Result<(), OntogenErrorObject> {
    let store = state.store().await.map_err(ontogen_internal_error)?;
    if let Some(linked) = &linked.epic_id {
        match epic::get_by_id(&store, &linked.id).await {
            Ok(_) => {}
            Err(crate::schema::AppError::EpicNotFound(..)) => return Err(linked.not_found("epics")),
            Err(e) => return Err(ontogen_app_error(e)),
        }
    }
    for linked in &linked.tags {
        match tag::get_by_id(&store, &linked.id).await {
            Ok(_) => {}
            Err(crate::schema::AppError::TagNotFound(..)) => return Err(linked.not_found("tags")),
            Err(e) => return Err(ontogen_app_error(e)),
        }
    }
    if let Some(linked) = &linked.parent_id {
        match task::get_by_id(&store, &linked.id).await {
            Ok(_) => {}
            Err(crate::schema::AppError::TaskNotFound(..)) => return Err(linked.not_found("tasks")),
            Err(e) => return Err(ontogen_app_error(e)),
        }
    }
    for linked in &linked.subtasks {
        match task::get_by_id(&store, &linked.id).await {
            Ok(_) => {}
            Err(crate::schema::AppError::TaskNotFound(..)) => return Err(linked.not_found("tasks")),
            Err(e) => return Err(ontogen_app_error(e)),
        }
    }
    Ok(())
}

/// The `tasks` resource `id` names, read as its `GET` reads it: the
/// parent of a relationship route.
async fn ontogen_task_read(state: &AppState, id: &OntogenLookupKey) -> Result<Task, OntogenErrorObject> {
    let store = state.store().await.map_err(ontogen_internal_error)?;
    task::get_by_id(&store, ontogen_task_lookup_key(id)?).await.map_err(ontogen_app_error)
}

/// Sets the relation field `field` of the `tasks` resource `id` to
/// `value` through `task::update`, as a resource `PATCH` naming only that
/// relationship does.
async fn ontogen_task_write_field(
    state: &AppState,
    id: &str,
    field: &str,
    value: ::serde_json::Value,
) -> Result<(), OntogenErrorObject> {
    let input: UpdateTaskInput = ontogen_from_fields(::serde_json::Map::from_iter([(field.to_owned(), value)]))?;
    let store = state.store().await.map_err(ontogen_internal_error)?;
    task::update(&store, id, input).await.map_err(ontogen_app_error)?;
    Ok(())
}

/// The `epics` resources `ids` name, in order, without the ids that
/// name none.
async fn ontogen_epic_fetch(state: &AppState, ids: &[String]) -> Result<Vec<Epic>, OntogenErrorObject> {
    let store = state.store().await.map_err(ontogen_internal_error)?;
    let mut found = Vec::with_capacity(ids.len());
    for id in ids {
        match epic::get_by_id(&store, id).await {
            Ok(entity) => found.push(entity),
            Err(crate::schema::AppError::EpicNotFound(..)) => {}
            Err(e) => return Err(ontogen_app_error(e)),
        }
    }
    Ok(found)
}

/// Checks, in order, that each of `ids` names a resource of type `epics`.
async fn ontogen_epic_check_ids(state: &AppState, ids: &[OntogenLinkedId]) -> Result<(), OntogenErrorObject> {
    let store = state.store().await.map_err(ontogen_internal_error)?;
    for linked in ids {
        match epic::get_by_id(&store, &linked.id).await {
            Ok(_) => {}
            Err(crate::schema::AppError::EpicNotFound(..)) => return Err(linked.not_found("epics")),
            Err(e) => return Err(ontogen_app_error(e)),
        }
    }
    Ok(())
}

/// The `tags` resources `ids` name, in order, without the ids that
/// name none.
async fn ontogen_tag_fetch(state: &AppState, ids: &[String]) -> Result<Vec<Tag>, OntogenErrorObject> {
    let store = state.store().await.map_err(ontogen_internal_error)?;
    let mut found = Vec::with_capacity(ids.len());
    for id in ids {
        match tag::get_by_id(&store, id).await {
            Ok(entity) => found.push(entity),
            Err(crate::schema::AppError::TagNotFound(..)) => {}
            Err(e) => return Err(ontogen_app_error(e)),
        }
    }
    Ok(found)
}

/// Checks, in order, that each of `ids` names a resource of type `tags`.
async fn ontogen_tag_check_ids(state: &AppState, ids: &[OntogenLinkedId]) -> Result<(), OntogenErrorObject> {
    let store = state.store().await.map_err(ontogen_internal_error)?;
    for linked in ids {
        match tag::get_by_id(&store, &linked.id).await {
            Ok(_) => {}
            Err(crate::schema::AppError::TagNotFound(..)) => return Err(linked.not_found("tags")),
            Err(e) => return Err(ontogen_app_error(e)),
        }
    }
    Ok(())
}

/// The `tasks` resources `ids` name, in order, without the ids that
/// name none.
async fn ontogen_task_fetch(state: &AppState, ids: &[String]) -> Result<Vec<Task>, OntogenErrorObject> {
    let store = state.store().await.map_err(ontogen_internal_error)?;
    let mut found = Vec::with_capacity(ids.len());
    for id in ids {
        match task::get_by_id(&store, id).await {
            Ok(entity) => found.push(entity),
            Err(crate::schema::AppError::TaskNotFound(..)) => {}
            Err(e) => return Err(ontogen_app_error(e)),
        }
    }
    Ok(found)
}

/// Checks, in order, that each of `ids` names a resource of type `tasks`.
async fn ontogen_task_check_ids(state: &AppState, ids: &[OntogenLinkedId]) -> Result<(), OntogenErrorObject> {
    let store = state.store().await.map_err(ontogen_internal_error)?;
    for linked in ids {
        match task::get_by_id(&store, &linked.id).await {
            Ok(_) => {}
            Err(crate::schema::AppError::TaskNotFound(..)) => return Err(linked.not_found("tasks")),
            Err(e) => return Err(ontogen_app_error(e)),
        }
    }
    Ok(())
}

/// The resources `paths` include for `entities`, path by path and each in
/// linkage order: each once, and none of `entities` among them. `paths` are
/// those `include_paths` admitted, so no other path occurs.
async fn ontogen_task_included(
    state: &AppState,
    entities: &[Task],
    paths: &[&str],
) -> Result<Vec<OntogenAnyResource>, OntogenErrorObject> {
    let mut included = OntogenIncluded::new("tasks", entities.iter().map(|entity| entity.id.as_str()));
    for path in paths {
        match *path {
            "epic" => {
                let ids = included.new_ids("epics", entities.iter().filter_map(|entity| entity.epic_id.as_deref()));
                let collection = "/api/epics";
                for related in ontogen_epic_fetch(state, &ids).await? {
                    included.push(ontogen_epic_as_resource(&related, collection))?;
                }
            }
            "tags" => {
                let ids =
                    included.new_ids("tags", entities.iter().flat_map(|entity| entity.tags.iter().map(String::as_str)));
                let collection = "/api/tags";
                for related in ontogen_tag_fetch(state, &ids).await? {
                    included.push(ontogen_tag_as_resource(&related, collection))?;
                }
            }
            "parent" => {
                let ids = included.new_ids("tasks", entities.iter().filter_map(|entity| entity.parent_id.as_deref()));
                let collection = "/api/tasks";
                for related in ontogen_task_fetch(state, &ids).await? {
                    included.push(ontogen_task_as_resource(&related, collection))?;
                }
            }
            "subtasks" => {
                let ids = included
                    .new_ids("tasks", entities.iter().flat_map(|entity| entity.subtasks.iter().map(String::as_str)));
                let collection = "/api/tasks";
                for related in ontogen_task_fetch(state, &ids).await? {
                    included.push(ontogen_task_as_resource(&related, collection))?;
                }
            }
            _ => {}
        }
    }
    Ok(included.finish())
}

// ── Epic Handlers ──

async fn epic_list(
    OntogenState(ontogen_state): OntogenState<::std::sync::Arc<AppState>>,
    _: OntogenAcceptGuard,
    query: OntogenQuery<OntogenPagedListParams>,
) -> Result<OntogenResponse, OntogenErrorObject> {
    let order = query.sort_order("epics")?;
    let include = query.include_paths("epics", &[], &[])?;
    let (offset, limit) = ontogen_page(&query, 20, 100)?;
    let link_query = query.link_query(include.as_deref())?;
    let ontogen_store = ontogen_state.store().await.map_err(ontogen_internal_error)?;
    let items = epic::list(&ontogen_store, &order, Some(u64::from(limit)), Some(u64::from(offset)))
        .await
        .map_err(ontogen_app_error)?;
    let total = epic::count(&ontogen_store).await.map_err(ontogen_app_error)?;
    let collection = "/api/epics";
    let data: Vec<_> = items.iter().map(|entity| ontogen_epic_as_resource(entity, collection)).collect();
    let links = ::ontogen_jsonapi::links::pagination_links(collection, &link_query, offset, limit, total);
    let mut document = OntogenDocument::new(data, links).with_meta(OntogenPageMeta { total, limit, offset });
    if include.is_some() {
        document = document.with_included(Vec::new());
    }
    Ok(::ontogen_jsonapi::response::ok(&document))
}

async fn epic_get_by_id(
    OntogenState(ontogen_state): OntogenState<::std::sync::Arc<AppState>>,
    _: OntogenAcceptGuard,
    OntogenPath(id): OntogenPath<OntogenLookupKey>,
    query: OntogenQuery<OntogenGetParams>,
) -> Result<OntogenResponse, OntogenErrorObject> {
    let include = query.include_paths("epics", &[], &[])?;
    let link_query = query.link_query(include.as_deref())?;
    let ontogen_store = ontogen_state.store().await.map_err(ontogen_internal_error)?;
    let entity = epic::get_by_id(&ontogen_store, ontogen_epic_lookup_key(&id)?).await.map_err(ontogen_app_error)?;
    let collection = "/api/epics";
    let mut document = OntogenDocument::resource(ontogen_epic_as_resource(&entity, collection), &link_query);
    if include.is_some() {
        document = document.with_included(Vec::new());
    }
    Ok(::ontogen_jsonapi::response::ok(&document))
}

async fn epic_create(
    OntogenState(ontogen_state): OntogenState<::std::sync::Arc<AppState>>,
    _: OntogenAcceptGuard,
    query: Result<OntogenQuery<OntogenNoParams>, OntogenErrorObject>,
    body: OntogenBody,
) -> Result<OntogenResponse, OntogenErrorObject> {
    query?;
    let body = body.into_bytes()?;
    let collection = "/api/epics";
    let endpoint = OntogenEndpoint { type_name: "epics", path: collection };
    let data = ::ontogen_jsonapi::request::parse_create(&body, endpoint, |id| {
        ::ontogen_core::id::validate_id(id).map_err(|e| e.reason)
    })?;
    let fields = ontogen_epic_request_fields(&data, true)?;
    let input: CreateEpicInput = ontogen_from_fields(fields)?;
    let ontogen_store = ontogen_state.store().await.map_err(ontogen_internal_error)?;
    let entity = epic::create(&ontogen_store, input).await.map_err(|e| match e {
        e @ crate::schema::AppError::EpicAlreadyExists(..) if data.id.is_some() => {
            ontogen_app_error(e).with_pointer("/data/id")
        }
        e => ontogen_app_error(e),
    })?;
    let document =
        OntogenDocument::resource(ontogen_epic_as_resource(&entity, collection), &OntogenCanonicalQuery::new());
    let location = document.data().and_then(OntogenResourceObject::links).map(OntogenLinks::self_link);
    Ok(::ontogen_jsonapi::response::created(location, &document))
}

async fn epic_update(
    OntogenState(ontogen_state): OntogenState<::std::sync::Arc<AppState>>,
    _: OntogenAcceptGuard,
    path_params: Result<OntogenPath<OntogenLookupKey>, OntogenErrorObject>,
    query: Result<OntogenQuery<OntogenNoParams>, OntogenErrorObject>,
    body: OntogenBody,
) -> Result<OntogenResponse, OntogenErrorObject> {
    let OntogenPath(id) = path_params?;
    query?;
    let body = body.into_bytes()?;
    let collection = "/api/epics";
    let path = format!("{collection}/{id}");
    let endpoint = OntogenEndpoint { type_name: "epics", path: &path };
    let data = ::ontogen_jsonapi::request::parse_update(&body, endpoint, &id)?;
    let fields = ontogen_epic_request_fields(&data, false)?;
    let input: UpdateEpicInput = ontogen_from_fields(fields)?;
    let ontogen_store = ontogen_state.store().await.map_err(ontogen_internal_error)?;
    let entity = epic::update(&ontogen_store, ontogen_epic_lookup_key(&id)?, input).await.map_err(ontogen_app_error)?;
    Ok(::ontogen_jsonapi::response::ok(&OntogenDocument::resource(
        ontogen_epic_as_resource(&entity, collection),
        &OntogenCanonicalQuery::new(),
    )))
}

async fn epic_delete(
    OntogenState(ontogen_state): OntogenState<::std::sync::Arc<AppState>>,
    _: OntogenAcceptGuard,
    OntogenPath(id): OntogenPath<OntogenLookupKey>,
    _: OntogenQuery<OntogenNoParams>,
) -> Result<OntogenResponse, OntogenErrorObject> {
    let ontogen_store = ontogen_state.store().await.map_err(ontogen_internal_error)?;
    epic::delete(&ontogen_store, ontogen_epic_lookup_key(&id)?).await.map_err(ontogen_app_error)?;
    Ok(::ontogen_jsonapi::response::no_content())
}

// ── Tag Handlers ──

async fn tag_list(
    OntogenState(ontogen_state): OntogenState<::std::sync::Arc<AppState>>,
    _: OntogenAcceptGuard,
    query: OntogenQuery<OntogenPagedListParams>,
) -> Result<OntogenResponse, OntogenErrorObject> {
    let order = query.sort_order("tags")?;
    let include = query.include_paths("tags", &[], &[])?;
    let (offset, limit) = ontogen_page(&query, 20, 100)?;
    let link_query = query.link_query(include.as_deref())?;
    let ontogen_store = ontogen_state.store().await.map_err(ontogen_internal_error)?;
    let items = tag::list(&ontogen_store, &order, Some(u64::from(limit)), Some(u64::from(offset)))
        .await
        .map_err(ontogen_app_error)?;
    let total = tag::count(&ontogen_store).await.map_err(ontogen_app_error)?;
    let collection = "/api/tags";
    let data: Vec<_> = items.iter().map(|entity| ontogen_tag_as_resource(entity, collection)).collect();
    let links = ::ontogen_jsonapi::links::pagination_links(collection, &link_query, offset, limit, total);
    let mut document = OntogenDocument::new(data, links).with_meta(OntogenPageMeta { total, limit, offset });
    if include.is_some() {
        document = document.with_included(Vec::new());
    }
    Ok(::ontogen_jsonapi::response::ok(&document))
}

async fn tag_get_by_id(
    OntogenState(ontogen_state): OntogenState<::std::sync::Arc<AppState>>,
    _: OntogenAcceptGuard,
    OntogenPath(id): OntogenPath<OntogenLookupKey>,
    query: OntogenQuery<OntogenGetParams>,
) -> Result<OntogenResponse, OntogenErrorObject> {
    let include = query.include_paths("tags", &[], &[])?;
    let link_query = query.link_query(include.as_deref())?;
    let ontogen_store = ontogen_state.store().await.map_err(ontogen_internal_error)?;
    let entity = tag::get_by_id(&ontogen_store, ontogen_tag_lookup_key(&id)?).await.map_err(ontogen_app_error)?;
    let collection = "/api/tags";
    let mut document = OntogenDocument::resource(ontogen_tag_as_resource(&entity, collection), &link_query);
    if include.is_some() {
        document = document.with_included(Vec::new());
    }
    Ok(::ontogen_jsonapi::response::ok(&document))
}

async fn tag_create(
    OntogenState(ontogen_state): OntogenState<::std::sync::Arc<AppState>>,
    _: OntogenAcceptGuard,
    query: Result<OntogenQuery<OntogenNoParams>, OntogenErrorObject>,
    body: OntogenBody,
) -> Result<OntogenResponse, OntogenErrorObject> {
    query?;
    let body = body.into_bytes()?;
    let collection = "/api/tags";
    let endpoint = OntogenEndpoint { type_name: "tags", path: collection };
    let data = ::ontogen_jsonapi::request::parse_create(&body, endpoint, |id| {
        ::ontogen_core::id::validate_id(id).map_err(|e| e.reason)
    })?;
    let fields = ontogen_tag_request_fields(&data, true)?;
    let input: CreateTagInput = ontogen_from_fields(fields)?;
    let ontogen_store = ontogen_state.store().await.map_err(ontogen_internal_error)?;
    let entity = tag::create(&ontogen_store, input).await.map_err(|e| match e {
        e @ crate::schema::AppError::TagAlreadyExists(..) if data.id.is_some() => {
            ontogen_app_error(e).with_pointer("/data/id")
        }
        e => ontogen_app_error(e),
    })?;
    let document =
        OntogenDocument::resource(ontogen_tag_as_resource(&entity, collection), &OntogenCanonicalQuery::new());
    let location = document.data().and_then(OntogenResourceObject::links).map(OntogenLinks::self_link);
    Ok(::ontogen_jsonapi::response::created(location, &document))
}

async fn tag_update(
    OntogenState(ontogen_state): OntogenState<::std::sync::Arc<AppState>>,
    _: OntogenAcceptGuard,
    path_params: Result<OntogenPath<OntogenLookupKey>, OntogenErrorObject>,
    query: Result<OntogenQuery<OntogenNoParams>, OntogenErrorObject>,
    body: OntogenBody,
) -> Result<OntogenResponse, OntogenErrorObject> {
    let OntogenPath(id) = path_params?;
    query?;
    let body = body.into_bytes()?;
    let collection = "/api/tags";
    let path = format!("{collection}/{id}");
    let endpoint = OntogenEndpoint { type_name: "tags", path: &path };
    let data = ::ontogen_jsonapi::request::parse_update(&body, endpoint, &id)?;
    let fields = ontogen_tag_request_fields(&data, false)?;
    let input: UpdateTagInput = ontogen_from_fields(fields)?;
    let ontogen_store = ontogen_state.store().await.map_err(ontogen_internal_error)?;
    let entity = tag::update(&ontogen_store, ontogen_tag_lookup_key(&id)?, input).await.map_err(ontogen_app_error)?;
    Ok(::ontogen_jsonapi::response::ok(&OntogenDocument::resource(
        ontogen_tag_as_resource(&entity, collection),
        &OntogenCanonicalQuery::new(),
    )))
}

async fn tag_delete(
    OntogenState(ontogen_state): OntogenState<::std::sync::Arc<AppState>>,
    _: OntogenAcceptGuard,
    OntogenPath(id): OntogenPath<OntogenLookupKey>,
    _: OntogenQuery<OntogenNoParams>,
) -> Result<OntogenResponse, OntogenErrorObject> {
    let ontogen_store = ontogen_state.store().await.map_err(ontogen_internal_error)?;
    tag::delete(&ontogen_store, ontogen_tag_lookup_key(&id)?).await.map_err(ontogen_app_error)?;
    Ok(::ontogen_jsonapi::response::no_content())
}

// ── Task Handlers ──

async fn task_get_by_id(
    OntogenState(ontogen_state): OntogenState<::std::sync::Arc<AppState>>,
    _: OntogenAcceptGuard,
    OntogenPath(id): OntogenPath<OntogenLookupKey>,
    query: OntogenQuery<OntogenGetParams>,
) -> Result<OntogenResponse, OntogenErrorObject> {
    let include = query.include_paths("tasks", &["epic", "tags", "parent", "subtasks"], &[])?;
    let link_query = query.link_query(include.as_deref())?;
    let ontogen_store = ontogen_state.store().await.map_err(ontogen_internal_error)?;
    let entity = task::get_by_id(&ontogen_store, ontogen_task_lookup_key(&id)?).await.map_err(ontogen_app_error)?;
    let collection = "/api/tasks";
    let mut document = OntogenDocument::resource(ontogen_task_as_resource(&entity, collection), &link_query);
    if let Some(paths) = &include {
        document = document
            .with_included(ontogen_task_included(&ontogen_state, ::std::slice::from_ref(&entity), paths).await?);
    }
    Ok(::ontogen_jsonapi::response::ok(&document))
}

async fn task_create(
    OntogenState(ontogen_state): OntogenState<::std::sync::Arc<AppState>>,
    _: OntogenAcceptGuard,
    query: Result<OntogenQuery<OntogenNoParams>, OntogenErrorObject>,
    body: OntogenBody,
) -> Result<OntogenResponse, OntogenErrorObject> {
    query?;
    let body = body.into_bytes()?;
    let collection = "/api/tasks";
    let endpoint = OntogenEndpoint { type_name: "tasks", path: collection };
    let data = ::ontogen_jsonapi::request::parse_create(&body, endpoint, |id| {
        ::ontogen_core::id::validate_id(id).map_err(|e| e.reason)
    })?;
    let (fields, linked) = ontogen_task_request_fields(&data, true)?;
    let input: CreateTaskInput = ontogen_from_fields(fields)?;
    let ontogen_store = ontogen_state.store().await.map_err(ontogen_internal_error)?;
    ontogen_task_check_linked(&ontogen_state, &linked).await?;
    let entity = task::create(&ontogen_store, input).await.map_err(|e| match e {
        e @ crate::schema::AppError::TaskAlreadyExists(..) if data.id.is_some() => {
            ontogen_app_error(e).with_pointer("/data/id")
        }
        e => ontogen_app_error(e),
    })?;
    let document =
        OntogenDocument::resource(ontogen_task_as_resource(&entity, collection), &OntogenCanonicalQuery::new());
    let location = document.data().and_then(OntogenResourceObject::links).map(OntogenLinks::self_link);
    Ok(::ontogen_jsonapi::response::created(location, &document))
}

async fn task_update(
    OntogenState(ontogen_state): OntogenState<::std::sync::Arc<AppState>>,
    _: OntogenAcceptGuard,
    path_params: Result<OntogenPath<OntogenLookupKey>, OntogenErrorObject>,
    query: Result<OntogenQuery<OntogenNoParams>, OntogenErrorObject>,
    body: OntogenBody,
) -> Result<OntogenResponse, OntogenErrorObject> {
    let OntogenPath(id) = path_params?;
    query?;
    let body = body.into_bytes()?;
    let collection = "/api/tasks";
    let path = format!("{collection}/{id}");
    let endpoint = OntogenEndpoint { type_name: "tasks", path: &path };
    let data = ::ontogen_jsonapi::request::parse_update(&body, endpoint, &id)?;
    let (fields, linked) = ontogen_task_request_fields(&data, false)?;
    let input: UpdateTaskInput = ontogen_from_fields(fields)?;
    let ontogen_store = ontogen_state.store().await.map_err(ontogen_internal_error)?;
    ontogen_task_check_linked(&ontogen_state, &linked).await?;
    let entity = task::update(&ontogen_store, ontogen_task_lookup_key(&id)?, input).await.map_err(ontogen_app_error)?;
    Ok(::ontogen_jsonapi::response::ok(&OntogenDocument::resource(
        ontogen_task_as_resource(&entity, collection),
        &OntogenCanonicalQuery::new(),
    )))
}

async fn task_delete(
    OntogenState(ontogen_state): OntogenState<::std::sync::Arc<AppState>>,
    _: OntogenAcceptGuard,
    OntogenPath(id): OntogenPath<OntogenLookupKey>,
    _: OntogenQuery<OntogenNoParams>,
) -> Result<OntogenResponse, OntogenErrorObject> {
    let ontogen_store = ontogen_state.store().await.map_err(ontogen_internal_error)?;
    task::delete(&ontogen_store, ontogen_task_lookup_key(&id)?).await.map_err(ontogen_app_error)?;
    Ok(::ontogen_jsonapi::response::no_content())
}

struct OntogenTaskListFilterParams;

impl OntogenRouteQuery for OntogenTaskListFilterParams {
    const SPEC: OntogenQuerySpec = OntogenQuerySpec {
        filter: &[],
        filter_fields: Some(::ontogen_jsonapi::filter_fields::<ListTasksQuery>),
        sort: true,
        include: true,
        page: true,
        ..OntogenQuerySpec::NONE
    };
}

async fn task_list(
    OntogenState(ontogen_state): OntogenState<::std::sync::Arc<AppState>>,
    _: OntogenAcceptGuard,
    query: OntogenQuery<OntogenTaskListFilterParams>,
) -> Result<OntogenResponse, OntogenErrorObject> {
    let ontogen_filter: ListTasksQuery = query.filter()?;
    let order = query.sort_order("tasks")?;
    let include = query.include_paths("tasks", &["epic", "tags", "parent", "subtasks"], &[])?;
    let (offset, limit) = ontogen_page(&query, 20, 100)?;
    let link_query = query.link_query(include.as_deref())?;
    let ontogen_store = ontogen_state.store().await.map_err(ontogen_internal_error)?;
    let items =
        task::list(&ontogen_store, ontogen_filter.clone(), &order, Some(u64::from(limit)), Some(u64::from(offset)))
            .await
            .map_err(ontogen_app_error)?;
    let total = task::count(&ontogen_store, ontogen_filter).await.map_err(ontogen_app_error)?;
    let collection = "/api/tasks";
    let data: Vec<_> = items.iter().map(|entity| ontogen_task_as_resource(entity, collection)).collect();
    let links = ::ontogen_jsonapi::links::pagination_links(collection, &link_query, offset, limit, total);
    let mut document = OntogenDocument::new(data, links).with_meta(OntogenPageMeta { total, limit, offset });
    if let Some(paths) = &include {
        document = document.with_included(ontogen_task_included(&ontogen_state, &items, paths).await?);
    }
    Ok(::ontogen_jsonapi::response::ok(&document))
}

async fn ontogen_task_relationship_get(
    OntogenState(ontogen_state): OntogenState<::std::sync::Arc<AppState>>,
    _: OntogenAcceptGuard,
    OntogenPath((id, rel)): OntogenPath<(OntogenLookupKey, OntogenLookupKey)>,
    OntogenRawQuery(ontogen_raw_query): OntogenRawQuery,
) -> Result<OntogenResponse, OntogenErrorObject> {
    let ontogen_collection = "/api/tasks";
    match rel.as_str() {
        Some("epic") => {
            OntogenQueryParams::parse(ontogen_raw_query.as_deref(), &OntogenQuerySpec::NONE)?;
            let ontogen_entity = ontogen_task_read(&ontogen_state, &id).await?;
            let ontogen_base =
                format!("{ontogen_collection}/{}", ::ontogen_jsonapi::links::encode_path_segment(&ontogen_entity.id));
            let ontogen_links = OntogenLinks::new(format!("{ontogen_base}/relationships/epic"))
                .with_related(format!("{ontogen_base}/epic"));
            let ontogen_data = OntogenLinkage::ToOne(
                ontogen_entity
                    .epic_id
                    .as_ref()
                    .map(|ontogen_member| OntogenResourceIdentifier::new("epics", ontogen_member.as_str())),
            );
            Ok(::ontogen_jsonapi::response::ok(&OntogenDocument::new(ontogen_data, ontogen_links)))
        }
        Some("tags") => {
            OntogenQueryParams::parse(ontogen_raw_query.as_deref(), &OntogenQuerySpec::NONE)?;
            let ontogen_entity = ontogen_task_read(&ontogen_state, &id).await?;
            let ontogen_base =
                format!("{ontogen_collection}/{}", ::ontogen_jsonapi::links::encode_path_segment(&ontogen_entity.id));
            let ontogen_links = OntogenLinks::new(format!("{ontogen_base}/relationships/tags"))
                .with_related(format!("{ontogen_base}/tags"));
            let ontogen_data = OntogenLinkage::ToMany(
                ontogen_entity
                    .tags
                    .iter()
                    .map(|ontogen_member| OntogenResourceIdentifier::new("tags", ontogen_member.as_str()))
                    .collect(),
            );
            Ok(::ontogen_jsonapi::response::ok(&OntogenDocument::new(ontogen_data, ontogen_links)))
        }
        Some("parent") => {
            OntogenQueryParams::parse(ontogen_raw_query.as_deref(), &OntogenQuerySpec::NONE)?;
            let ontogen_entity = ontogen_task_read(&ontogen_state, &id).await?;
            let ontogen_base =
                format!("{ontogen_collection}/{}", ::ontogen_jsonapi::links::encode_path_segment(&ontogen_entity.id));
            let ontogen_links = OntogenLinks::new(format!("{ontogen_base}/relationships/parent"))
                .with_related(format!("{ontogen_base}/parent"));
            let ontogen_data = OntogenLinkage::ToOne(
                ontogen_entity
                    .parent_id
                    .as_ref()
                    .map(|ontogen_member| OntogenResourceIdentifier::new("tasks", ontogen_member.as_str())),
            );
            Ok(::ontogen_jsonapi::response::ok(&OntogenDocument::new(ontogen_data, ontogen_links)))
        }
        Some("subtasks") => {
            OntogenQueryParams::parse(ontogen_raw_query.as_deref(), &OntogenQuerySpec::NONE)?;
            let ontogen_entity = ontogen_task_read(&ontogen_state, &id).await?;
            let ontogen_base =
                format!("{ontogen_collection}/{}", ::ontogen_jsonapi::links::encode_path_segment(&ontogen_entity.id));
            let ontogen_links = OntogenLinks::new(format!("{ontogen_base}/relationships/subtasks"))
                .with_related(format!("{ontogen_base}/subtasks"));
            let ontogen_data = OntogenLinkage::ToMany(
                ontogen_entity
                    .subtasks
                    .iter()
                    .map(|ontogen_member| OntogenResourceIdentifier::new("tasks", ontogen_member.as_str()))
                    .collect(),
            );
            Ok(::ontogen_jsonapi::response::ok(&OntogenDocument::new(ontogen_data, ontogen_links)))
        }
        _ => Err(::ontogen_jsonapi::error::no_such_relationship("tasks", &rel)),
    }
}

async fn ontogen_task_relationship_patch(
    OntogenState(ontogen_state): OntogenState<::std::sync::Arc<AppState>>,
    _: OntogenAcceptGuard,
    ontogen_path: Result<OntogenPath<(OntogenLookupKey, OntogenLookupKey)>, OntogenErrorObject>,
    ontogen_query: Result<OntogenQuery<OntogenNoParams>, OntogenErrorObject>,
    ontogen_body: OntogenBody,
) -> Result<OntogenResponse, OntogenErrorObject> {
    let OntogenPath((id, rel)) = ontogen_path?;
    match rel.as_str() {
        Some("epic") => {
            ontogen_query?;
            let ontogen_bytes = ontogen_body.into_bytes()?;
            let ontogen_linked = ::ontogen_jsonapi::request::to_one(
                &::ontogen_jsonapi::request::parse_relationship(&ontogen_bytes)?,
                "",
                "epics",
                true,
            )?
            .map(|ontogen_member| OntogenLinkedId { id: ontogen_member, pointer: "/data".to_owned() });
            let ontogen_entity = ontogen_task_read(&ontogen_state, &id).await?;
            ontogen_epic_check_ids(&ontogen_state, ontogen_linked.as_slice()).await?;
            ontogen_task_write_field(
                &ontogen_state,
                &ontogen_entity.id,
                "epic_id",
                ontogen_linked.map(|ontogen_member| ontogen_member.id).into(),
            )
            .await?;
            Ok(::ontogen_jsonapi::response::no_content())
        }
        Some("tags") => {
            ontogen_query?;
            let ontogen_bytes = ontogen_body.into_bytes()?;
            let ontogen_linked = ::ontogen_jsonapi::request::to_many_linked(
                &::ontogen_jsonapi::request::parse_relationship(&ontogen_bytes)?,
                "",
                "tags",
                None,
            )?;
            let ontogen_entity = ontogen_task_read(&ontogen_state, &id).await?;
            ontogen_tag_check_ids(&ontogen_state, &ontogen_linked).await?;
            ontogen_task_write_field(
                &ontogen_state,
                &ontogen_entity.id,
                "tags",
                ontogen_linked.into_iter().map(|ontogen_member| ontogen_member.id).collect(),
            )
            .await?;
            Ok(::ontogen_jsonapi::response::no_content())
        }
        Some("parent") => {
            ontogen_query?;
            let ontogen_bytes = ontogen_body.into_bytes()?;
            let ontogen_linked = ::ontogen_jsonapi::request::to_one(
                &::ontogen_jsonapi::request::parse_relationship(&ontogen_bytes)?,
                "",
                "tasks",
                true,
            )?
            .map(|ontogen_member| OntogenLinkedId { id: ontogen_member, pointer: "/data".to_owned() });
            let ontogen_entity = ontogen_task_read(&ontogen_state, &id).await?;
            ontogen_task_check_ids(&ontogen_state, ontogen_linked.as_slice()).await?;
            ontogen_task_write_field(
                &ontogen_state,
                &ontogen_entity.id,
                "parent_id",
                ontogen_linked.map(|ontogen_member| ontogen_member.id).into(),
            )
            .await?;
            Ok(::ontogen_jsonapi::response::no_content())
        }
        Some("subtasks") => {
            ontogen_query?;
            let ontogen_bytes = ontogen_body.into_bytes()?;
            let ontogen_linked = ::ontogen_jsonapi::request::to_many_linked(
                &::ontogen_jsonapi::request::parse_relationship(&ontogen_bytes)?,
                "",
                "tasks",
                None,
            )?;
            let ontogen_entity = ontogen_task_read(&ontogen_state, &id).await?;
            ontogen_task_check_ids(&ontogen_state, &ontogen_linked).await?;
            ontogen_task_write_field(
                &ontogen_state,
                &ontogen_entity.id,
                "subtasks",
                ontogen_linked.into_iter().map(|ontogen_member| ontogen_member.id).collect(),
            )
            .await?;
            Ok(::ontogen_jsonapi::response::no_content())
        }
        _ => Err(::ontogen_jsonapi::error::no_such_relationship("tasks", &rel)),
    }
}

async fn ontogen_task_relationship_post(
    OntogenState(ontogen_state): OntogenState<::std::sync::Arc<AppState>>,
    _: OntogenAcceptGuard,
    ontogen_path: Result<OntogenPath<(OntogenLookupKey, OntogenLookupKey)>, OntogenErrorObject>,
    ontogen_query: Result<OntogenQuery<OntogenNoParams>, OntogenErrorObject>,
    ontogen_body: OntogenBody,
) -> Result<OntogenResponse, OntogenErrorObject> {
    let OntogenPath((id, rel)) = ontogen_path?;
    match rel.as_str() {
        Some("epic") => {
            ontogen_query?;
            Err(::ontogen_jsonapi::error::relationship_update_unsupported("tasks", "epic", "POST"))
        }
        Some("tags") => {
            ontogen_query?;
            let ontogen_bytes = ontogen_body.into_bytes()?;
            let ontogen_linked = ::ontogen_jsonapi::request::to_many_linked(
                &::ontogen_jsonapi::request::parse_relationship(&ontogen_bytes)?,
                "",
                "tags",
                Some(1),
            )?;
            let ontogen_entity = ontogen_task_read(&ontogen_state, &id).await?;
            ontogen_tag_check_ids(&ontogen_state, &ontogen_linked).await?;
            if let Some(ontogen_ids) = ontogen_added(&ontogen_entity.tags, &ontogen_linked) {
                ontogen_task_write_field(&ontogen_state, &ontogen_entity.id, "tags", ontogen_ids.into()).await?;
            }
            Ok(::ontogen_jsonapi::response::no_content())
        }
        Some("parent") => {
            ontogen_query?;
            Err(::ontogen_jsonapi::error::relationship_update_unsupported("tasks", "parent", "POST"))
        }
        Some("subtasks") => {
            ontogen_query?;
            let ontogen_bytes = ontogen_body.into_bytes()?;
            let ontogen_linked = ::ontogen_jsonapi::request::to_many_linked(
                &::ontogen_jsonapi::request::parse_relationship(&ontogen_bytes)?,
                "",
                "tasks",
                Some(1),
            )?;
            let ontogen_entity = ontogen_task_read(&ontogen_state, &id).await?;
            ontogen_task_check_ids(&ontogen_state, &ontogen_linked).await?;
            if let Some(ontogen_ids) = ontogen_added(&ontogen_entity.subtasks, &ontogen_linked) {
                ontogen_task_write_field(&ontogen_state, &ontogen_entity.id, "subtasks", ontogen_ids.into()).await?;
            }
            Ok(::ontogen_jsonapi::response::no_content())
        }
        _ => Err(::ontogen_jsonapi::error::no_such_relationship("tasks", &rel)),
    }
}

async fn ontogen_task_relationship_delete(
    OntogenState(ontogen_state): OntogenState<::std::sync::Arc<AppState>>,
    _: OntogenAcceptGuard,
    ontogen_path: Result<OntogenPath<(OntogenLookupKey, OntogenLookupKey)>, OntogenErrorObject>,
    ontogen_query: Result<OntogenQuery<OntogenNoParams>, OntogenErrorObject>,
    ontogen_body: OntogenBody,
) -> Result<OntogenResponse, OntogenErrorObject> {
    let OntogenPath((id, rel)) = ontogen_path?;
    match rel.as_str() {
        Some("epic") => {
            ontogen_query?;
            Err(::ontogen_jsonapi::error::relationship_update_unsupported("tasks", "epic", "DELETE"))
        }
        Some("tags") => {
            ontogen_query?;
            let ontogen_bytes = ontogen_body.into_bytes()?;
            let ontogen_linked = ::ontogen_jsonapi::request::to_many_linked(
                &::ontogen_jsonapi::request::parse_relationship(&ontogen_bytes)?,
                "",
                "tags",
                Some(1),
            )?;
            let ontogen_entity = ontogen_task_read(&ontogen_state, &id).await?;
            if let Some(ontogen_ids) = ontogen_removed(&ontogen_entity.tags, &ontogen_linked) {
                ontogen_task_write_field(&ontogen_state, &ontogen_entity.id, "tags", ontogen_ids.into()).await?;
            }
            Ok(::ontogen_jsonapi::response::no_content())
        }
        Some("parent") => {
            ontogen_query?;
            Err(::ontogen_jsonapi::error::relationship_update_unsupported("tasks", "parent", "DELETE"))
        }
        Some("subtasks") => {
            ontogen_query?;
            let ontogen_bytes = ontogen_body.into_bytes()?;
            let ontogen_linked = ::ontogen_jsonapi::request::to_many_linked(
                &::ontogen_jsonapi::request::parse_relationship(&ontogen_bytes)?,
                "",
                "tasks",
                Some(1),
            )?;
            let ontogen_entity = ontogen_task_read(&ontogen_state, &id).await?;
            if let Some(ontogen_ids) = ontogen_removed(&ontogen_entity.subtasks, &ontogen_linked) {
                ontogen_task_write_field(&ontogen_state, &ontogen_entity.id, "subtasks", ontogen_ids.into()).await?;
            }
            Ok(::ontogen_jsonapi::response::no_content())
        }
        _ => Err(::ontogen_jsonapi::error::no_such_relationship("tasks", &rel)),
    }
}

async fn ontogen_task_related_get(
    OntogenState(ontogen_state): OntogenState<::std::sync::Arc<AppState>>,
    _: OntogenAcceptGuard,
    OntogenPath((id, rel)): OntogenPath<(OntogenLookupKey, OntogenLookupKey)>,
    OntogenRawQuery(ontogen_raw_query): OntogenRawQuery,
) -> Result<OntogenResponse, OntogenErrorObject> {
    let ontogen_collection = "/api/tasks";
    match rel.as_str() {
        Some("epic") => {
            OntogenQueryParams::parse(ontogen_raw_query.as_deref(), &OntogenQuerySpec::NONE)?;
            let ontogen_entity = ontogen_task_read(&ontogen_state, &id).await?;
            let ontogen_related = ontogen_epic_fetch(&ontogen_state, ontogen_entity.epic_id.as_slice()).await?;
            let ontogen_data =
                ontogen_related.first().map(|ontogen_member| ontogen_epic_as_resource(ontogen_member, "/api/epics"));
            let ontogen_self = format!(
                "{ontogen_collection}/{}/epic",
                ::ontogen_jsonapi::links::encode_path_segment(&ontogen_entity.id)
            );
            Ok(::ontogen_jsonapi::response::ok(&OntogenDocument::new(ontogen_data, OntogenLinks::new(ontogen_self))))
        }
        Some("tags") => {
            OntogenQueryParams::parse(ontogen_raw_query.as_deref(), &OntogenQuerySpec::NONE)?;
            let ontogen_entity = ontogen_task_read(&ontogen_state, &id).await?;
            let ontogen_related = ontogen_tag_fetch(&ontogen_state, &ontogen_entity.tags).await?;
            let ontogen_data: Vec<_> = ontogen_related
                .iter()
                .map(|ontogen_member| ontogen_tag_as_resource(ontogen_member, "/api/tags"))
                .collect();
            let ontogen_self = format!(
                "{ontogen_collection}/{}/tags",
                ::ontogen_jsonapi::links::encode_path_segment(&ontogen_entity.id)
            );
            Ok(::ontogen_jsonapi::response::ok(&OntogenDocument::new(ontogen_data, OntogenLinks::new(ontogen_self))))
        }
        Some("parent") => {
            OntogenQueryParams::parse(ontogen_raw_query.as_deref(), &OntogenQuerySpec::NONE)?;
            let ontogen_entity = ontogen_task_read(&ontogen_state, &id).await?;
            let ontogen_related = ontogen_task_fetch(&ontogen_state, ontogen_entity.parent_id.as_slice()).await?;
            let ontogen_data =
                ontogen_related.first().map(|ontogen_member| ontogen_task_as_resource(ontogen_member, "/api/tasks"));
            let ontogen_self = format!(
                "{ontogen_collection}/{}/parent",
                ::ontogen_jsonapi::links::encode_path_segment(&ontogen_entity.id)
            );
            Ok(::ontogen_jsonapi::response::ok(&OntogenDocument::new(ontogen_data, OntogenLinks::new(ontogen_self))))
        }
        Some("subtasks") => {
            OntogenQueryParams::parse(ontogen_raw_query.as_deref(), &OntogenQuerySpec::NONE)?;
            let ontogen_entity = ontogen_task_read(&ontogen_state, &id).await?;
            let ontogen_related = ontogen_task_fetch(&ontogen_state, &ontogen_entity.subtasks).await?;
            let ontogen_data: Vec<_> = ontogen_related
                .iter()
                .map(|ontogen_member| ontogen_task_as_resource(ontogen_member, "/api/tasks"))
                .collect();
            let ontogen_self = format!(
                "{ontogen_collection}/{}/subtasks",
                ::ontogen_jsonapi::links::encode_path_segment(&ontogen_entity.id)
            );
            Ok(::ontogen_jsonapi::response::ok(&OntogenDocument::new(ontogen_data, OntogenLinks::new(ontogen_self))))
        }
        _ => Err(::ontogen_jsonapi::error::no_such_relationship("tasks", &rel)),
    }
}

/// Generated routes. Call this from your main router.
pub fn entity_routes() -> ::axum::Router<::std::sync::Arc<AppState>> {
    ::axum::Router::new()
        .route(
            "/api/epics",
            ::axum::routing::get(epic_list)
                .post(epic_create)
                .fallback(ontogen_allow([OntogenMethod::GET, OntogenMethod::POST])),
        )
        .route(
            "/api/epics/{id}",
            ::axum::routing::get(epic_get_by_id).patch(epic_update).delete(epic_delete).fallback(ontogen_allow([
                OntogenMethod::GET,
                OntogenMethod::PATCH,
                OntogenMethod::DELETE,
            ])),
        )
        .route(
            "/api/tags",
            ::axum::routing::get(tag_list)
                .post(tag_create)
                .fallback(ontogen_allow([OntogenMethod::GET, OntogenMethod::POST])),
        )
        .route(
            "/api/tags/{id}",
            ::axum::routing::get(tag_get_by_id).patch(tag_update).delete(tag_delete).fallback(ontogen_allow([
                OntogenMethod::GET,
                OntogenMethod::PATCH,
                OntogenMethod::DELETE,
            ])),
        )
        .route(
            "/api/tasks/{id}",
            ::axum::routing::get(task_get_by_id).patch(task_update).delete(task_delete).fallback(ontogen_allow([
                OntogenMethod::GET,
                OntogenMethod::PATCH,
                OntogenMethod::DELETE,
            ])),
        )
        .route(
            "/api/tasks",
            ::axum::routing::post(task_create)
                .get(task_list)
                .fallback(ontogen_allow([OntogenMethod::POST, OntogenMethod::GET])),
        )
        .route(
            "/api/tasks/{id}/relationships/{rel}",
            ::axum::routing::get(ontogen_task_relationship_get)
                .patch(ontogen_task_relationship_patch)
                .post(ontogen_task_relationship_post)
                .delete(ontogen_task_relationship_delete)
                .fallback(ontogen_allow([
                    OntogenMethod::GET,
                    OntogenMethod::PATCH,
                    OntogenMethod::POST,
                    OntogenMethod::DELETE,
                ])),
        )
        .route(
            "/api/tasks/{id}/{rel}",
            ::axum::routing::get(ontogen_task_related_get).fallback(ontogen_allow([OntogenMethod::GET])),
        )
}
