#![allow(dead_code, unused_imports, clippy::pedantic, clippy::needless_borrow)]
//! Auto-generated HTTP route handlers. DO NOT EDIT.
//!
//! Generated by ontogen from API source files.

use axum::extract::{RawQuery as OntogenRawQuery, State as OntogenState};
use axum::http::{Method as OntogenMethod, StatusCode as OntogenStatusCode};
use axum::response::Response as OntogenResponse;
use ontogen_jsonapi::extract::{
    AcceptGuard as OntogenAcceptGuard, Body as OntogenBody, NoParams as OntogenNoParams, Path as OntogenPath,
    Query as OntogenQuery, RouteQuery as OntogenRouteQuery,
};
use ontogen_jsonapi::links::CanonicalQuery as OntogenCanonicalQuery;
use ontogen_jsonapi::request::{
    Endpoint as OntogenEndpoint, LinkedId as OntogenLinkedId, ResourceData as OntogenResourceData,
};
use ontogen_jsonapi::{
    AnyResource as OntogenAnyResource, Document as OntogenDocument, ErrorObject as OntogenErrorObject,
    Included as OntogenIncluded, Linkage as OntogenLinkage, Links as OntogenLinks, LookupKey as OntogenLookupKey,
    QueryParams as OntogenQueryParams, QuerySpec as OntogenQuerySpec, Relationship as OntogenRelationship,
    ResourceIdentifier as OntogenResourceIdentifier, ResourceObject as OntogenResourceObject,
};

use crate::AppState;
use crate::api::v1::note;
use crate::schema::{CreateNoteInput, Note, UpdateNoteInput};

/// An `AppError` as an error object: the status its variant's name gives,
/// and the name in snake_case as the code.
fn ontogen_app_error(e: crate::schema::AppError) -> OntogenErrorObject {
    let (status, code) = match &e {
        crate::schema::AppError::NoteNotFound(..) => (OntogenStatusCode::NOT_FOUND, "note_not_found"),
        crate::schema::AppError::NoteIdRequired(..) => (OntogenStatusCode::BAD_REQUEST, "note_id_required"),
        crate::schema::AppError::NoteAlreadyExists(..) => (OntogenStatusCode::CONFLICT, "note_already_exists"),
        crate::schema::AppError::Md(..) => (OntogenStatusCode::INTERNAL_SERVER_ERROR, "md"),
    };
    OntogenErrorObject::app(status, code, e.to_string())
}

/// A failure no `AppError` describes: opening the store, a scope accessor,
/// or an op with another error type.
fn ontogen_internal_error(e: impl std::fmt::Display) -> OntogenErrorObject {
    OntogenErrorObject::internal(e.to_string())
}

/// The method fallback of a route serving `allowed`: `405` with `Allow`.
fn ontogen_allow<const N: usize>(
    allowed: [OntogenMethod; N],
) -> impl Fn(OntogenMethod) -> std::future::Ready<OntogenResponse> + Clone + Send + Sync + 'static {
    move |method| std::future::ready(ontogen_jsonapi::error::method_not_allowed(&method, &allowed))
}

/// `ids` with each id of `linked` it lacks appended, or `None` when it lacks
/// none: a relationship `POST` that adds nothing writes nothing.
fn ontogen_added(ids: &[String], linked: &[OntogenLinkedId]) -> Option<Vec<String>> {
    let added: Vec<String> = linked.iter().map(|l| l.id.clone()).filter(|id| !ids.contains(id)).collect();
    (!added.is_empty()).then(|| [ids, added.as_slice()].concat())
}

/// `ids` without the ids of `linked`, or `None` when it holds none of them: a
/// relationship `DELETE` that removes nothing writes nothing.
fn ontogen_removed(ids: &[String], linked: &[OntogenLinkedId]) -> Option<Vec<String>> {
    let kept: Vec<String> = ids.iter().filter(|id| !linked.iter().any(|l| l.id == **id)).cloned().collect();
    (kept.len() != ids.len()).then_some(kept)
}

// ── JSON:API resources ──

struct OntogenListParams;

impl OntogenRouteQuery for OntogenListParams {
    const SPEC: OntogenQuerySpec = OntogenQuerySpec { sort: true, include: true, ..OntogenQuerySpec::NONE };
}

struct OntogenPagedListParams;

impl OntogenRouteQuery for OntogenPagedListParams {
    const SPEC: OntogenQuerySpec = OntogenQuerySpec { sort: true, include: true, page: true, ..OntogenQuerySpec::NONE };
}

struct OntogenGetParams;

impl OntogenRouteQuery for OntogenGetParams {
    const SPEC: OntogenQuerySpec = OntogenQuerySpec { include: true, ..OntogenQuerySpec::NONE };
}

/// The effective `(offset, limit)` of a paginated list.
fn ontogen_page(
    query: &OntogenQueryParams,
    default_limit: u32,
    max_limit: u32,
) -> Result<(u32, u32), OntogenErrorObject> {
    let offset = query.page_offset()?.unwrap_or(0);
    let limit = query.page_limit()?.unwrap_or(default_limit).min(max_limit);
    Ok((offset, limit))
}

/// Sets `name` when the request document carried it.
fn ontogen_set_field(
    fields: &mut serde_json::Map<String, serde_json::Value>,
    name: &str,
    value: Option<&serde_json::Value>,
) {
    if let Some(value) = value {
        fields.insert(name.to_owned(), value.clone());
    }
}

/// A create or update input from the fields its request document set. Each
/// field was checked against its type, so a failure here is the server's.
fn ontogen_from_fields<T: serde::de::DeserializeOwned>(
    fields: serde_json::Map<String, serde_json::Value>,
) -> Result<T, OntogenErrorObject> {
    serde_json::from_value(serde_json::Value::Object(fields)).map_err(ontogen_internal_error)
}

// ── `notes` ──

/// `Note`'s attributes: every field but the id and the relations, in
/// declaration order.
struct OntogenNoteResourceAttributes<'a>(&'a Note);

impl serde::Serialize for OntogenNoteResourceAttributes<'_> {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        use serde::ser::SerializeStruct;
        let mut attributes = serializer.serialize_struct("OntogenNoteResourceAttributes", 2)?;
        attributes.serialize_field("title", &self.0.title)?;
        attributes.serialize_field("body", &self.0.body)?;
        attributes.end()
    }
}

/// `entity` as a resource object of type `notes`, its `links.self`
/// under `collection`.
fn ontogen_note_as_resource<'a>(
    entity: &'a Note,
    collection: &str,
) -> OntogenResourceObject<OntogenNoteResourceAttributes<'a>> {
    let self_link = format!("{collection}/{}", ontogen_jsonapi::links::encode_path_segment(&entity.id));
    OntogenResourceObject::new("notes", entity.id.clone(), OntogenNoteResourceAttributes(entity), self_link.clone())
        .with_relationship(
            "links",
            OntogenRelationship::new(
                OntogenLinks::new(format!("{self_link}/relationships/links"))
                    .with_related(format!("{self_link}/links")),
                OntogenLinkage::ToMany(
                    entity.links.iter().map(|id| OntogenResourceIdentifier::new("notes", id.as_str())).collect(),
                ),
            ),
        )
}

/// The id an `{id}` path segment names.
fn ontogen_note_lookup_key(id: &OntogenLookupKey) -> Result<&str, OntogenErrorObject> {
    id.as_str().ok_or_else(|| ontogen_app_error(crate::schema::AppError::NoteNotFound(id.to_string())))
}

/// The ids a request document for `notes` links, by relationship, to
/// be checked to name resources that exist.
#[derive(Default)]
struct OntogenNoteLinkedIds {
    links: Vec<OntogenLinkedId>,
}

/// The fields a create or update document for `notes` sets, named as
/// the input's fields, each member checked against the schema.
fn ontogen_note_request_fields(
    data: &OntogenResourceData,
    create: bool,
) -> Result<(serde_json::Map<String, serde_json::Value>, OntogenNoteLinkedIds), OntogenErrorObject> {
    let attributes = data.attributes.as_ref();
    ontogen_jsonapi::request::check_attribute_names(attributes, "notes", &["title", "body"], &[("links", "links")])?;
    let mut fields = serde_json::Map::new();
    if create {
        fields.insert("id".to_owned(), serde_json::Value::String(data.id.clone().unwrap_or_default()));
    }
    ontogen_set_field(
        &mut fields,
        "title",
        ontogen_jsonapi::request::attribute::<String>(attributes, "title", create)?,
    );
    ontogen_set_field(&mut fields, "body", ontogen_jsonapi::request::attribute::<String>(attributes, "body", create)?);
    let relationships = data.relationships()?;
    ontogen_jsonapi::request::check_relationship_names(relationships, "notes", &["links"])?;
    let mut linked = OntogenNoteLinkedIds::default();
    if let Some(rel) = relationships.and_then(|r| r.get("links")) {
        let ids = ontogen_jsonapi::request::to_many_linked(rel, "/data/relationships/links", "notes", None)?;
        fields.insert("links".to_owned(), ids.iter().map(|l| serde_json::Value::String(l.id.clone())).collect());
        linked.links = ids;
    }
    Ok((fields, linked))
}

/// Checks that each id a create or update document for `notes` links
/// names a resource that exists, in the order the document was read.
async fn ontogen_note_check_linked(state: &AppState, linked: &OntogenNoteLinkedIds) -> Result<(), OntogenErrorObject> {
    let store = state.store().await.map_err(ontogen_internal_error)?;
    for linked in &linked.links {
        match note::get_by_id(&store, &linked.id).await {
            Ok(_) => {}
            Err(crate::schema::AppError::NoteNotFound(..)) => return Err(linked.not_found("notes")),
            Err(e) => return Err(ontogen_app_error(e)),
        }
    }
    Ok(())
}

/// The `notes` resource `id` names, read as its `GET` reads it: the
/// parent of a relationship route.
async fn ontogen_note_read(state: &AppState, id: &OntogenLookupKey) -> Result<Note, OntogenErrorObject> {
    let store = state.store().await.map_err(ontogen_internal_error)?;
    note::get_by_id(&store, ontogen_note_lookup_key(id)?).await.map_err(ontogen_app_error)
}

/// Sets the relation field `field` of the `notes` resource `id` to
/// `value` through `note::update`, as a resource `PATCH` naming only that
/// relationship does.
async fn ontogen_note_write_field(
    state: &AppState,
    id: &str,
    field: &str,
    value: serde_json::Value,
) -> Result<(), OntogenErrorObject> {
    let input: UpdateNoteInput = ontogen_from_fields(serde_json::Map::from_iter([(field.to_owned(), value)]))?;
    let store = state.store().await.map_err(ontogen_internal_error)?;
    note::update(&store, id, input).await.map_err(ontogen_app_error)?;
    Ok(())
}

/// The `notes` resources `ids` name, in order, without the ids that
/// name none.
async fn ontogen_note_fetch(state: &AppState, ids: &[String]) -> Result<Vec<Note>, OntogenErrorObject> {
    let store = state.store().await.map_err(ontogen_internal_error)?;
    let mut found = Vec::with_capacity(ids.len());
    for id in ids {
        match note::get_by_id(&store, id).await {
            Ok(entity) => found.push(entity),
            Err(crate::schema::AppError::NoteNotFound(..)) => {}
            Err(e) => return Err(ontogen_app_error(e)),
        }
    }
    Ok(found)
}

/// Checks, in order, that each of `ids` names a resource of type `notes`.
async fn ontogen_note_check_ids(state: &AppState, ids: &[OntogenLinkedId]) -> Result<(), OntogenErrorObject> {
    let store = state.store().await.map_err(ontogen_internal_error)?;
    for linked in ids {
        match note::get_by_id(&store, &linked.id).await {
            Ok(_) => {}
            Err(crate::schema::AppError::NoteNotFound(..)) => return Err(linked.not_found("notes")),
            Err(e) => return Err(ontogen_app_error(e)),
        }
    }
    Ok(())
}

/// The resources `paths` include for `entities`, path by path and each in
/// linkage order: each once, and none of `entities` among them. `paths` are
/// those `include_paths` admitted, so no other path occurs.
async fn ontogen_note_included(
    state: &AppState,
    entities: &[Note],
    paths: &[&str],
) -> Result<Vec<OntogenAnyResource>, OntogenErrorObject> {
    let mut included = OntogenIncluded::new("notes", entities.iter().map(|entity| entity.id.as_str()));
    for path in paths {
        if *path == "links" {
            let ids =
                included.new_ids("notes", entities.iter().flat_map(|entity| entity.links.iter().map(String::as_str)));
            let collection = "/api/notes";
            for related in ontogen_note_fetch(state, &ids).await? {
                included.push(ontogen_note_as_resource(&related, collection))?;
            }
        }
    }
    Ok(included.finish())
}

// ── Note Handlers ──

async fn note_list(
    OntogenState(ontogen_state): OntogenState<std::sync::Arc<AppState>>,
    _: OntogenAcceptGuard,
    query: OntogenQuery<OntogenListParams>,
) -> Result<OntogenResponse, OntogenErrorObject> {
    let order = query.sort_order("notes")?;
    let include = query.include_paths("notes", &["links"], &[])?;
    let link_query = query.link_query(include.as_deref())?;
    let ontogen_store = ontogen_state.store().await.map_err(ontogen_internal_error)?;
    let items = note::list(&ontogen_store, &order).await.map_err(ontogen_app_error)?;
    let collection = "/api/notes";
    let data: Vec<_> = items.iter().map(|entity| ontogen_note_as_resource(entity, collection)).collect();
    let mut document = OntogenDocument::new(data, OntogenLinks::new(link_query.href(collection)));
    if let Some(paths) = &include {
        document = document.with_included(ontogen_note_included(&ontogen_state, &items, paths).await?);
    }
    Ok(ontogen_jsonapi::response::ok(&document))
}

async fn note_get_by_id(
    OntogenState(ontogen_state): OntogenState<std::sync::Arc<AppState>>,
    _: OntogenAcceptGuard,
    OntogenPath(id): OntogenPath<OntogenLookupKey>,
    query: OntogenQuery<OntogenGetParams>,
) -> Result<OntogenResponse, OntogenErrorObject> {
    let include = query.include_paths("notes", &["links"], &[])?;
    let link_query = query.link_query(include.as_deref())?;
    let ontogen_store = ontogen_state.store().await.map_err(ontogen_internal_error)?;
    let entity = note::get_by_id(&ontogen_store, ontogen_note_lookup_key(&id)?).await.map_err(ontogen_app_error)?;
    let collection = "/api/notes";
    let mut document = OntogenDocument::resource(ontogen_note_as_resource(&entity, collection), &link_query);
    if let Some(paths) = &include {
        document =
            document.with_included(ontogen_note_included(&ontogen_state, std::slice::from_ref(&entity), paths).await?);
    }
    Ok(ontogen_jsonapi::response::ok(&document))
}

async fn note_create(
    OntogenState(ontogen_state): OntogenState<std::sync::Arc<AppState>>,
    _: OntogenAcceptGuard,
    query: Result<OntogenQuery<OntogenNoParams>, OntogenErrorObject>,
    body: OntogenBody,
) -> Result<OntogenResponse, OntogenErrorObject> {
    query?;
    let body = body.into_bytes()?;
    let collection = "/api/notes";
    let endpoint = OntogenEndpoint { type_name: "notes", path: collection };
    let data = ontogen_jsonapi::request::parse_create(&body, endpoint, |id| {
        ontogen_core::id::validate_id(id).map_err(|e| e.reason)
    })?;
    let (fields, linked) = ontogen_note_request_fields(&data, true)?;
    let input: CreateNoteInput = ontogen_from_fields(fields)?;
    let ontogen_store = ontogen_state.store().await.map_err(ontogen_internal_error)?;
    ontogen_note_check_linked(&ontogen_state, &linked).await?;
    let entity = note::create(&ontogen_store, input).await.map_err(|e| match e {
        e @ crate::schema::AppError::NoteAlreadyExists(..) if data.id.is_some() => {
            ontogen_app_error(e).with_pointer("/data/id")
        }
        e => ontogen_app_error(e),
    })?;
    let document =
        OntogenDocument::resource(ontogen_note_as_resource(&entity, collection), &OntogenCanonicalQuery::new());
    let location = document.data().and_then(OntogenResourceObject::links).map(OntogenLinks::self_link);
    Ok(ontogen_jsonapi::response::created(location, &document))
}

async fn note_update(
    OntogenState(ontogen_state): OntogenState<std::sync::Arc<AppState>>,
    _: OntogenAcceptGuard,
    path_params: Result<OntogenPath<OntogenLookupKey>, OntogenErrorObject>,
    query: Result<OntogenQuery<OntogenNoParams>, OntogenErrorObject>,
    body: OntogenBody,
) -> Result<OntogenResponse, OntogenErrorObject> {
    let OntogenPath(id) = path_params?;
    query?;
    let body = body.into_bytes()?;
    let collection = "/api/notes";
    let path = format!("{collection}/{id}");
    let endpoint = OntogenEndpoint { type_name: "notes", path: &path };
    let data = ontogen_jsonapi::request::parse_update(&body, endpoint, &id)?;
    let (fields, linked) = ontogen_note_request_fields(&data, false)?;
    let input: UpdateNoteInput = ontogen_from_fields(fields)?;
    let ontogen_store = ontogen_state.store().await.map_err(ontogen_internal_error)?;
    ontogen_note_check_linked(&ontogen_state, &linked).await?;
    let entity = note::update(&ontogen_store, ontogen_note_lookup_key(&id)?, input).await.map_err(ontogen_app_error)?;
    Ok(ontogen_jsonapi::response::ok(&OntogenDocument::resource(
        ontogen_note_as_resource(&entity, collection),
        &OntogenCanonicalQuery::new(),
    )))
}

async fn note_delete(
    OntogenState(ontogen_state): OntogenState<std::sync::Arc<AppState>>,
    _: OntogenAcceptGuard,
    OntogenPath(id): OntogenPath<OntogenLookupKey>,
    _: OntogenQuery<OntogenNoParams>,
) -> Result<OntogenResponse, OntogenErrorObject> {
    let ontogen_store = ontogen_state.store().await.map_err(ontogen_internal_error)?;
    note::delete(&ontogen_store, ontogen_note_lookup_key(&id)?).await.map_err(ontogen_app_error)?;
    Ok(ontogen_jsonapi::response::no_content())
}

async fn ontogen_note_relationship_get(
    OntogenState(ontogen_state): OntogenState<std::sync::Arc<AppState>>,
    _: OntogenAcceptGuard,
    OntogenPath((id, rel)): OntogenPath<(OntogenLookupKey, OntogenLookupKey)>,
    OntogenRawQuery(ontogen_raw_query): OntogenRawQuery,
) -> Result<OntogenResponse, OntogenErrorObject> {
    let ontogen_collection = "/api/notes";
    match rel.as_str() {
        Some("links") => {
            OntogenQueryParams::parse(ontogen_raw_query.as_deref(), &OntogenQuerySpec::NONE)?;
            let ontogen_entity = ontogen_note_read(&ontogen_state, &id).await?;
            let ontogen_base =
                format!("{ontogen_collection}/{}", ontogen_jsonapi::links::encode_path_segment(&ontogen_entity.id));
            let ontogen_links = OntogenLinks::new(format!("{ontogen_base}/relationships/links"))
                .with_related(format!("{ontogen_base}/links"));
            let ontogen_data = OntogenLinkage::ToMany(
                ontogen_entity
                    .links
                    .iter()
                    .map(|ontogen_member| OntogenResourceIdentifier::new("notes", ontogen_member.as_str()))
                    .collect(),
            );
            Ok(ontogen_jsonapi::response::ok(&OntogenDocument::new(ontogen_data, ontogen_links)))
        }
        _ => Err(ontogen_jsonapi::error::relationship_not_found("notes", &rel)),
    }
}

async fn ontogen_note_relationship_patch(
    OntogenState(ontogen_state): OntogenState<std::sync::Arc<AppState>>,
    _: OntogenAcceptGuard,
    ontogen_path: Result<OntogenPath<(OntogenLookupKey, OntogenLookupKey)>, OntogenErrorObject>,
    ontogen_query: Result<OntogenQuery<OntogenNoParams>, OntogenErrorObject>,
    ontogen_body: OntogenBody,
) -> Result<OntogenResponse, OntogenErrorObject> {
    let OntogenPath((id, rel)) = ontogen_path?;
    match rel.as_str() {
        Some("links") => {
            ontogen_query?;
            let ontogen_bytes = ontogen_body.into_bytes()?;
            let ontogen_linked = ontogen_jsonapi::request::to_many_linked(
                &ontogen_jsonapi::request::parse_relationship(&ontogen_bytes)?,
                "",
                "notes",
                None,
            )?;
            let ontogen_entity = ontogen_note_read(&ontogen_state, &id).await?;
            ontogen_note_check_ids(&ontogen_state, &ontogen_linked).await?;
            ontogen_note_write_field(
                &ontogen_state,
                &ontogen_entity.id,
                "links",
                ontogen_linked.into_iter().map(|ontogen_member| ontogen_member.id).collect(),
            )
            .await?;
            Ok(ontogen_jsonapi::response::no_content())
        }
        _ => Err(ontogen_jsonapi::error::relationship_not_found("notes", &rel)),
    }
}

async fn ontogen_note_relationship_post(
    OntogenState(ontogen_state): OntogenState<std::sync::Arc<AppState>>,
    _: OntogenAcceptGuard,
    ontogen_path: Result<OntogenPath<(OntogenLookupKey, OntogenLookupKey)>, OntogenErrorObject>,
    ontogen_query: Result<OntogenQuery<OntogenNoParams>, OntogenErrorObject>,
    ontogen_body: OntogenBody,
) -> Result<OntogenResponse, OntogenErrorObject> {
    let OntogenPath((id, rel)) = ontogen_path?;
    match rel.as_str() {
        Some("links") => {
            ontogen_query?;
            let ontogen_bytes = ontogen_body.into_bytes()?;
            let ontogen_linked = ontogen_jsonapi::request::to_many_linked(
                &ontogen_jsonapi::request::parse_relationship(&ontogen_bytes)?,
                "",
                "notes",
                Some(1),
            )?;
            let ontogen_entity = ontogen_note_read(&ontogen_state, &id).await?;
            ontogen_note_check_ids(&ontogen_state, &ontogen_linked).await?;
            if let Some(ontogen_ids) = ontogen_added(&ontogen_entity.links, &ontogen_linked) {
                ontogen_note_write_field(&ontogen_state, &ontogen_entity.id, "links", ontogen_ids.into()).await?;
            }
            Ok(ontogen_jsonapi::response::no_content())
        }
        _ => Err(ontogen_jsonapi::error::relationship_not_found("notes", &rel)),
    }
}

async fn ontogen_note_relationship_delete(
    OntogenState(ontogen_state): OntogenState<std::sync::Arc<AppState>>,
    _: OntogenAcceptGuard,
    ontogen_path: Result<OntogenPath<(OntogenLookupKey, OntogenLookupKey)>, OntogenErrorObject>,
    ontogen_query: Result<OntogenQuery<OntogenNoParams>, OntogenErrorObject>,
    ontogen_body: OntogenBody,
) -> Result<OntogenResponse, OntogenErrorObject> {
    let OntogenPath((id, rel)) = ontogen_path?;
    match rel.as_str() {
        Some("links") => {
            ontogen_query?;
            let ontogen_bytes = ontogen_body.into_bytes()?;
            let ontogen_linked = ontogen_jsonapi::request::to_many_linked(
                &ontogen_jsonapi::request::parse_relationship(&ontogen_bytes)?,
                "",
                "notes",
                Some(1),
            )?;
            let ontogen_entity = ontogen_note_read(&ontogen_state, &id).await?;
            if let Some(ontogen_ids) = ontogen_removed(&ontogen_entity.links, &ontogen_linked) {
                ontogen_note_write_field(&ontogen_state, &ontogen_entity.id, "links", ontogen_ids.into()).await?;
            }
            Ok(ontogen_jsonapi::response::no_content())
        }
        _ => Err(ontogen_jsonapi::error::relationship_not_found("notes", &rel)),
    }
}

async fn ontogen_note_related_get(
    OntogenState(ontogen_state): OntogenState<std::sync::Arc<AppState>>,
    _: OntogenAcceptGuard,
    OntogenPath((id, rel)): OntogenPath<(OntogenLookupKey, OntogenLookupKey)>,
    OntogenRawQuery(ontogen_raw_query): OntogenRawQuery,
) -> Result<OntogenResponse, OntogenErrorObject> {
    let ontogen_collection = "/api/notes";
    match rel.as_str() {
        Some("links") => {
            OntogenQueryParams::parse(ontogen_raw_query.as_deref(), &OntogenQuerySpec::NONE)?;
            let ontogen_entity = ontogen_note_read(&ontogen_state, &id).await?;
            let ontogen_related = ontogen_note_fetch(&ontogen_state, &ontogen_entity.links).await?;
            let ontogen_data: Vec<_> = ontogen_related
                .iter()
                .map(|ontogen_member| ontogen_note_as_resource(ontogen_member, "/api/notes"))
                .collect();
            let ontogen_self = format!(
                "{ontogen_collection}/{}/links",
                ontogen_jsonapi::links::encode_path_segment(&ontogen_entity.id)
            );
            Ok(ontogen_jsonapi::response::ok(&OntogenDocument::new(ontogen_data, OntogenLinks::new(ontogen_self))))
        }
        _ => Err(ontogen_jsonapi::error::relationship_not_found("notes", &rel)),
    }
}

/// Generated routes. Call this from your main router.
pub fn entity_routes() -> axum::Router<std::sync::Arc<AppState>> {
    axum::Router::new()
        .route(
            "/api/notes",
            axum::routing::get(note_list)
                .post(note_create)
                .fallback(ontogen_allow([OntogenMethod::GET, OntogenMethod::POST])),
        )
        .route(
            "/api/notes/{id}",
            axum::routing::get(note_get_by_id).patch(note_update).delete(note_delete).fallback(ontogen_allow([
                OntogenMethod::GET,
                OntogenMethod::PATCH,
                OntogenMethod::DELETE,
            ])),
        )
        .route(
            "/api/notes/{id}/relationships/{rel}",
            axum::routing::get(ontogen_note_relationship_get)
                .patch(ontogen_note_relationship_patch)
                .post(ontogen_note_relationship_post)
                .delete(ontogen_note_relationship_delete)
                .fallback(ontogen_allow([
                    OntogenMethod::GET,
                    OntogenMethod::PATCH,
                    OntogenMethod::POST,
                    OntogenMethod::DELETE,
                ])),
        )
        .route(
            "/api/notes/{id}/{rel}",
            axum::routing::get(ontogen_note_related_get).fallback(ontogen_allow([OntogenMethod::GET])),
        )
}
