#![allow(clippy::too_many_lines, clippy::format_push_string)]

//! Generate a unified TypeScript transport layer from API modules.
//!
//! Produces a single file containing:
//! - `Transport` interface
//! - `createHttpTransport()` - fetch-based HTTP implementation
//! - `createIpcTransport()` - Tauri IPC invoke-based implementation

use std::fs;
use std::path::Path;

use ontogen_core::ir::OpKind;

use crate::clients::config::Config;
use crate::clients::generators::jsonapi::{self, crud_resource};
use crate::clients::generators::{FallbackRecord, command_name, ts_params_in_declaration_order};
use crate::servers::classify::{classify_op, is_read_op};
use crate::servers::parse::{ApiModule, EventFn, Param, is_page_param, is_resume_param};
use crate::servers::types::{
    collect_ts_import, event_name, extract_input_type, rust_type_to_ts, snake_to_camel, strip_ref,
};

/// Returns `", projectId?: string"` when route_prefix is configured, else `""`.
fn ts_trailing_prefix_param(config: &Config) -> String {
    match &config.route_prefix {
        Some(prefix) => {
            let pp = &prefix.params[0];
            format!(", {}?: {}", snake_to_camel(&pp.name), pp.ts_type)
        }
        None => String::new(),
    }
}

/// Returns `"projectId?: string"` when route_prefix is configured, else `""`.
fn ts_prefix_param_only(config: &Config) -> String {
    match &config.route_prefix {
        Some(prefix) => {
            let pp = &prefix.params[0];
            format!("{}?: {}", snake_to_camel(&pp.name), pp.ts_type)
        }
        None => String::new(),
    }
}

/// Returns the IPC invoke arg fragment for project_id, e.g., `, projectId: projectId ?? null`.
///
/// Uses camelCase key because Tauri v2's `#[tauri::command]` deserializes args
/// with `#[serde(rename_all = "camelCase")]`.
fn ts_ipc_prefix_arg(config: &Config) -> String {
    match &config.route_prefix {
        Some(prefix) => {
            let pp = &prefix.params[0];
            let camel = snake_to_camel(&pp.name);
            format!(", {camel}: {camel} ?? null")
        }
        None => String::new(),
    }
}

/// Returns the IPC invoke arg fragment without leading comma, e.g., `projectId: projectId ?? null`.
///
/// Uses camelCase key because Tauri v2's `#[tauri::command]` deserializes args
/// with `#[serde(rename_all = "camelCase")]`.
fn ts_ipc_prefix_arg_only(config: &Config) -> String {
    match &config.route_prefix {
        Some(prefix) => {
            let pp = &prefix.params[0];
            let camel = snake_to_camel(&pp.name);
            format!("{camel}: {camel} ?? null")
        }
        None => String::new(),
    }
}

/// Generate the unified transport layer and write to the output file.
///
/// Returns a [`FallbackRecord`] for every type referenced by the generated TS
/// surface that wasn't exported from `bindings.ts` and therefore had to be
/// stubbed as `Record<string, unknown>`. Callers (notably `generate_transport`
/// in `src/servers/mod.rs`) emit a `cargo:warning=` for each so silent
/// untyping shows up at build time. (OF-006)
pub fn generate(output: &Path, bindings_path: &Path, modules: &[ApiModule], config: &Config) -> Vec<FallbackRecord> {
    let mut out = String::new();

    // Read bindings.ts to discover exported types
    let bindings_content = fs::read_to_string(bindings_path).unwrap_or_default();
    let exported_types: Vec<String> = bindings_content
        .lines()
        .filter_map(|line| {
            line.strip_prefix("export type ")
                .or_else(|| line.strip_prefix("export interface "))
                .and_then(|rest| rest.split(|c: char| !c.is_alphanumeric() && c != '_').next().map(|s| s.to_string()))
        })
        .collect();

    out.push_str(
        "// Auto-generated transport layer. DO NOT EDIT.\n\
         // Generated by ontogen from API source files.\n\n",
    );

    // Collect all types needed
    let mut import_types: Vec<String> = Vec::new();
    for m in modules {
        if m.functions.is_empty() {
            continue;
        }
        for f in &m.functions {
            let cmd_name = command_name(&m.name, f, config);
            if cmd_name.is_empty() || config.ts_skip_commands.contains(&cmd_name) {
                continue;
            }
            let ts_ret = rust_type_to_ts(&f.return_type);
            collect_ts_import(&ts_ret, &mut import_types);
            for p in &f.params {
                let ty = extract_input_type(&p.ty);
                let ts_ty = rust_type_to_ts(&ty);
                collect_ts_import(&ts_ty, &mut import_types);
            }
        }
    }

    for m in modules {
        for ev in &m.events {
            collect_ts_import(&rust_type_to_ts(&ev.item_type), &mut import_types);
            for p in &ev.params {
                collect_ts_import(&rust_type_to_ts(&strip_ref(&p.ty)), &mut import_types);
            }
        }
    }

    // Each flattener returns its entity type, whichever CRUD methods are emitted.
    let resources = jsonapi::crud_resources(modules, config);
    for r in &resources {
        collect_ts_import(&r.entity.name, &mut import_types);
    }

    import_types.sort();
    import_types.dedup();

    let (available, missing): (Vec<_>, Vec<_>) = import_types.iter().partition(|t| exported_types.contains(t));

    // Compute relative import path from output file to bindings file
    let bindings_import_path = {
        let output_dir = output.parent().unwrap_or(Path::new("."));
        let bindings_abs = fs::canonicalize(bindings_path).unwrap_or_else(|_| bindings_path.to_path_buf());
        let output_abs = fs::canonicalize(output_dir).unwrap_or_else(|_| output_dir.to_path_buf());
        let rel = crate::utils::relative_path(&output_abs, &bindings_abs);
        let rel_str = rel.to_string_lossy().replace('\\', "/");
        let rel_str = rel_str.strip_suffix(".ts").unwrap_or(&rel_str);
        if rel_str.starts_with('.') { rel_str.to_string() } else { format!("./{}", rel_str) }
    };

    if !available.is_empty() {
        out.push_str("import type {\n");
        for t in &available {
            out.push_str(&format!("  {},\n", t));
        }
        out.push_str(&format!("}} from '{}';\n\n", bindings_import_path));
    }

    // IPC imports - must be at top level for lint compliance
    let has_events = modules.iter().any(|m| !m.events.is_empty());
    if has_events {
        out.push_str("import { Channel, invoke } from '@tauri-apps/api/core';\n");
    } else {
        out.push_str("import { invoke } from '@tauri-apps/api/core';\n");
    }
    let has_legacy_events = modules.iter().any(|m| m.events.iter().any(EventFn::is_legacy));
    if has_legacy_events {
        out.push_str("import { listen } from '@tauri-apps/api/event';\n");
    }
    out.push('\n');

    let fallbacks: Vec<FallbackRecord> = missing
        .iter()
        .map(|t| FallbackRecord {
            output: output.to_path_buf(),
            bindings_path: bindings_path.to_path_buf(),
            type_name: (*t).clone(),
        })
        .collect();

    for t in &missing {
        out.push_str(&format!(
            "// TODO: Type '{t}' not yet exported from bindings.ts - using placeholder\n\
             type {t} = Record<string, unknown>;\n\n"
        ));
    }

    // ── PaginatedResult<T> (when pagination is enabled) ──
    if config.any_pagination() {
        out.push_str(
            "export interface PaginatedResult<T> {\n\
             \x20 items: T[];\n\
             \x20 total: number;\n\
             \x20 limit: number;\n\
             \x20 offset: number;\n\
             }\n\n",
        );
    }

    if has_events {
        out.push_str(SUBSCRIPTION_TYPES);
    }

    // ── Transport Interface ──
    generate_transport_interface(&mut out, modules, config);

    // ── HTTP Helpers ──
    out.push_str(jsonapi::JSON_API_TYPES);
    generate_http_helpers(&mut out, modules, config);
    if has_events {
        out.push_str(SSE_SUBSCRIBE_HELPER);
    }
    if !resources.is_empty() {
        out.push_str(jsonapi::RESOURCE_HELPERS);
        for r in &resources {
            out.push_str(&jsonapi::resource_codec(r));
        }
    }

    // ── createHttpTransport ──
    generate_http_transport(&mut out, modules, config);

    // ── createIpcTransport ──
    if has_events {
        out.push_str(IPC_SUBSCRIBE_HELPER);
    }
    generate_ipc_transport(&mut out, modules, config);

    if let Some(parent) = output.parent() {
        fs::create_dir_all(parent).expect("Failed to create output directory");
    }
    crate::write_and_format_ts(output, out, &config.ts_formatter).expect("Failed to write transport generated file");

    fallbacks
}

/// Generate the `Transport` interface.
fn generate_transport_interface(out: &mut String, modules: &[ApiModule], config: &Config) {
    let pp_trailing = ts_trailing_prefix_param(config);
    let pp_only = ts_prefix_param_only(config);

    out.push_str("// ── Transport Interface ──\n\n");
    out.push_str("export interface Transport {\n");

    for m in modules {
        if m.functions.is_empty() {
            continue;
        }

        for f in &m.functions {
            let cmd_name = command_name(&m.name, f, config);
            if cmd_name.is_empty() || config.ts_skip_commands.contains(&cmd_name) {
                continue;
            }

            let op = classify_op(f);
            let camel = snake_to_camel(&cmd_name);
            let ts_ret = rust_type_to_ts(&f.return_type);
            let returns_unit = f.return_type == "()";
            let ret_str = if returns_unit { "null" } else { &ts_ret };

            match op {
                OpKind::List => {
                    let query_param = f.params.iter().find(|p| p.ty.contains("Query"));
                    // Pagination only applies when the list function returns Vec<T>;
                    // custom result types are passed through unchanged.
                    let paginated =
                        config.pagination_for(&m.name, f.surface).is_some() && f.return_type.starts_with("Vec<");
                    // A list that takes the page owns its limit/offset: they are never caller params.
                    let plain_params: Vec<&Param> = f
                        .params
                        .iter()
                        .filter(|p| {
                            !p.ty.contains("Query") && !p.ty.contains("Input") && (!f.takes_page() || !is_page_param(p))
                        })
                        .collect();

                    let mut params = Vec::new();
                    // Plain params first (e.g., workflowId: string)
                    for pp in &plain_params {
                        let ts_ty = rust_type_to_ts(&strip_ref(&pp.ty));
                        params.push(format!("{}: {}", snake_to_camel(&pp.name), ts_ty));
                    }
                    // Typed query struct (optional)
                    if let Some(qp) = query_param {
                        let qt = rust_type_to_ts(&extract_input_type(&qp.ty));
                        params.push(format!("query?: {}", qt));
                    }
                    // Pagination params
                    if paginated {
                        params.push("limit?: number".to_string());
                        params.push("offset?: number".to_string());
                    }
                    // Route prefix param
                    if !pp_only.is_empty() {
                        params.push(pp_only.clone());
                    }
                    let params_str = params.join(", ");
                    let return_type = if paginated {
                        let item_type = ret_str.strip_suffix("[]").unwrap_or(ret_str);
                        format!("PaginatedResult<{}>", item_type)
                    } else {
                        ret_str.to_string()
                    };
                    out.push_str(&format!("  {}({}): Promise<{}>;\n", camel, params_str, return_type));
                }
                OpKind::GetById => {
                    out.push_str(&format!("  {}(id: string{pp_trailing}): Promise<{}>;\n", camel, ret_str));
                }
                OpKind::Create => {
                    let input_type = rust_type_to_ts(&extract_input_type(&f.params[0].ty));
                    out.push_str(&format!("  {}(input: {}{pp_trailing}): Promise<{}>;\n", camel, input_type, ret_str));
                }
                OpKind::Update => {
                    let input_type = rust_type_to_ts(&extract_input_type(&f.params[1].ty));
                    out.push_str(&format!(
                        "  {}(id: string, input: {}{pp_trailing}): Promise<{}>;\n",
                        camel, input_type, ret_str
                    ));
                }
                OpKind::Delete => {
                    out.push_str(&format!("  {}(id: string{pp_trailing}): Promise<null>;\n", camel));
                }
                OpKind::JunctionList { .. } => {
                    // JunctionList follows the same pagination rules as List:
                    // when config.pagination is set and the return is Vec<T>,
                    // the method returns PaginatedResult<T> and accepts
                    // limit/offset. Without this the interface and HTTP/IPC
                    // implementations get out of sync.
                    let paginated =
                        config.pagination_for(&m.name, f.surface).is_some() && f.return_type.starts_with("Vec<");
                    let mut params = ts_params_in_declaration_order(f);
                    if paginated {
                        params.push("limit?: number".to_string());
                        params.push("offset?: number".to_string());
                    }
                    if !pp_only.is_empty() {
                        params.push(pp_only.clone());
                    }
                    let params_str = params.join(", ");
                    let return_type = if paginated {
                        let item_type = ret_str.strip_suffix("[]").unwrap_or(ret_str);
                        format!("PaginatedResult<{}>", item_type)
                    } else {
                        ret_str.to_string()
                    };
                    out.push_str(&format!("  {}({}): Promise<{}>;\n", camel, params_str, return_type));
                }
                OpKind::JunctionAdd { .. } | OpKind::JunctionRemove { .. } | OpKind::CustomGet | OpKind::CustomPost => {
                    let mut params = ts_params_in_declaration_order(f);
                    if !pp_only.is_empty() {
                        params.push(pp_only.clone());
                    }
                    let params_str = params.join(", ");
                    out.push_str(&format!("  {}({}): Promise<{}>;\n", camel, params_str, ret_str));
                }
                OpKind::EventStream => continue,
            }
        }
    }

    // Event subscriptions
    for m in modules {
        for ev in &m.events {
            out.push_str(&format!("  {};\n", subscribe_signature(ev, config)));
        }
    }

    // Legacy global event listeners (parameterless sync ops only)
    for m in modules {
        for ev in m.events.iter().filter(|ev| ev.is_legacy()) {
            let camel = snake_to_camel(&ev.name);
            out.push_str(&format!(
                "  on{}(callback: (payload: unknown) => void{pp_trailing}): Promise<() => void>;\n",
                capitalize_first(&camel)
            ));
        }
    }

    out.push_str("}\n\n");
}

/// Generate HTTP helper functions.
fn generate_http_helpers(out: &mut String, modules: &[ApiModule], config: &Config) {
    out.push_str(&jsonapi::http_helpers(jsonapi::needs_put(modules, config)));
    out.push_str(TO_QUERY_STRING);

    // Add scopedPath helper when route_prefix is configured
    if let Some(prefix) = &config.route_prefix {
        // Build URL template from segments, e.g., "projects/:project_id" → "/projects/${encodeURIComponent(projectId)}"
        let mut url_parts = String::new();
        for segment in prefix.segments.split('/') {
            url_parts.push('/');
            if let Some(param_name) = segment.strip_prefix(':') {
                url_parts.push_str(&format!("${{encodeURIComponent({})}}", snake_to_camel(param_name)));
            } else {
                url_parts.push_str(segment);
            }
        }
        let pp_camel = snake_to_camel(&prefix.params[0].name);
        out.push_str(&format!(
            "function scopedPath({pp_camel}: string | undefined, path: string): string {{\n\
             \x20 if ({pp_camel}) {{\n\
             \x20   return `{url_parts}${{path}}`;\n\
             \x20 }}\n\
             \x20 return path;\n\
             }}\n\n",
        ));
    }
}

/// Generate `createHttpTransport()`.
fn generate_http_transport(out: &mut String, modules: &[ApiModule], config: &Config) {
    let pp_trailing = ts_trailing_prefix_param(config);
    let pp_only = ts_prefix_param_only(config);
    let has_prefix = config.route_prefix.is_some();
    let pp_camel = config.route_prefix.as_ref().map(|p| snake_to_camel(&p.params[0].name)).unwrap_or_default();

    // Helper to wrap path with scopedPath when prefix is configured
    let sp = |path: &str| -> String {
        if has_prefix { format!("scopedPath({}, '{}')", pp_camel, path) } else { format!("'{}'", path) }
    };
    let sp_template = |path: &str| -> String {
        if has_prefix { format!("scopedPath({}, `{}`)", pp_camel, path) } else { format!("`{}`", path) }
    };

    out.push_str("// ── HTTP Transport ──\n\n");
    out.push_str("export function createHttpTransport(): Transport {\n");
    out.push_str("  return {\n");

    for m in modules {
        if m.functions.is_empty() {
            continue;
        }
        let module = &m.name;
        // Use kebab-case URL plural to match the routes registered by http.rs
        // (e.g., `destination-skills`, not `destination_skills`). Singleton
        // modules collapse to their singular kebab form via `url_for_module`.
        let plural = config.naming.url_for_module(m);
        let resource = crud_resource(m, config);

        for f in &m.functions {
            let op = classify_op(f);
            let cmd_name = command_name(module, f, config);
            if cmd_name.is_empty() || config.ts_skip_commands.contains(&cmd_name) {
                continue;
            }

            let camel = snake_to_camel(&cmd_name);
            let ts_ret = rust_type_to_ts(&f.return_type);
            let returns_unit = f.return_type == "()";
            let ret_str = if returns_unit { "null".to_string() } else { ts_ret.clone() };

            match op {
                OpKind::List => {
                    let query_param = f.params.iter().find(|p| p.ty.contains("Query"));
                    // Pagination only applies when the list function returns Vec<T>;
                    // custom result types are passed through unchanged.
                    let paginated =
                        config.pagination_for(&m.name, f.surface).is_some() && f.return_type.starts_with("Vec<");
                    // A list that takes the page owns its limit/offset: they are never caller params.
                    let plain_params: Vec<&Param> = f
                        .params
                        .iter()
                        .filter(|p| {
                            !p.ty.contains("Query") && !p.ty.contains("Input") && (!f.takes_page() || !is_page_param(p))
                        })
                        .collect();

                    let mut params = Vec::new();
                    for pp in &plain_params {
                        let ts_ty = rust_type_to_ts(&strip_ref(&pp.ty));
                        params.push(format!("{}: {}", snake_to_camel(&pp.name), ts_ty));
                    }
                    if let Some(qp) = query_param {
                        let qt = rust_type_to_ts(&extract_input_type(&qp.ty));
                        params.push(format!("query?: {}", qt));
                    }
                    if paginated {
                        params.push("limit?: number".to_string());
                        params.push("offset?: number".to_string());
                    }
                    if !pp_only.is_empty() {
                        params.push(pp_only.clone());
                    }
                    let params_str = params.join(", ");

                    let return_type = if paginated {
                        let item_type = ret_str.strip_suffix("[]").unwrap_or(ret_str.as_str());
                        format!("PaginatedResult<{}>", item_type)
                    } else {
                        ret_str.clone()
                    };

                    // A resource collection pages with the JSON:API `page` family;
                    // a module with no entity behind it keeps flat `limit`/`offset`.
                    let page_args = if resource.is_some() { "page: { offset, limit }" } else { "limit, offset" };
                    let path_expr = if query_param.is_some() && plain_params.is_empty() {
                        // Typed query struct: serialize as query string
                        let qs_arg = if paginated {
                            format!("toQueryString({{ ...query, {page_args} }})")
                        } else {
                            "toQueryString(query ?? {})".to_string()
                        };
                        sp_template(&format!("/{plural}${{{qs_arg}}}"))
                    } else if !plain_params.is_empty() {
                        // Scoped params as query string (e.g., ?workflow_id=xxx)
                        let mut query_parts = Vec::new();
                        for pp in &plain_params {
                            let camel_name = snake_to_camel(&pp.name);
                            query_parts.push(format!("{}=${{encodeURIComponent({})}}", pp.name, camel_name));
                        }
                        let qs = query_parts.join("&");
                        if paginated {
                            sp_template(&format!("/{plural}?{qs}&${{toQueryString({{ {page_args} }}).slice(1)}}"))
                        } else {
                            sp_template(&format!("/{plural}?{qs}"))
                        }
                    } else if paginated {
                        sp_template(&format!("/{plural}${{toQueryString({{ {page_args} }})}}"))
                    } else {
                        sp(&format!("/{plural}"))
                    };
                    let body = match resource {
                        Some(r) if paginated => format!(
                            "const {{ data, meta }} = await httpGet<JsonApiPageDocument>({path_expr});\n\
                             \x20     return {{ items: data.map({flatten}), total: meta.total, limit: meta.limit, offset: meta.offset }};",
                            flatten = jsonapi::flatten_fn(r),
                        ),
                        Some(r) => format!(
                            "const {{ data }} = await httpGet<JsonApiCollectionDocument>({path_expr});\n\
                             \x20     return data.map({});",
                            jsonapi::flatten_fn(r),
                        ),
                        None => format!("return httpGet({path_expr});"),
                    };
                    out.push_str(&format!(
                        "    async {camel}({params_str}): Promise<{return_type}> {{\n\
                         \x20     {body}\n\
                         \x20   }},\n",
                    ));
                }
                OpKind::GetById => {
                    let path_expr = sp_template(&format!("/{plural}/${{encodeURIComponent(id)}}"));
                    let body = match resource {
                        Some(r) => format!(
                            "const {{ data }} = await httpGet<JsonApiResourceDocument>({path_expr});\n\
                             \x20     return {}(data);",
                            jsonapi::flatten_fn(r)
                        ),
                        None => format!("return httpGet({path_expr});"),
                    };
                    out.push_str(&format!(
                        "    async {camel}(id: string{pp_trailing}): Promise<{ret_str}> {{\n\
                         \x20     {body}\n\
                         \x20   }},\n",
                    ));
                }
                OpKind::Create => {
                    let input_type = rust_type_to_ts(&extract_input_type(&f.params[0].ty));
                    let path_expr = sp(&format!("/{plural}"));
                    let body = match resource {
                        Some(r) => format!(
                            "const {{ data }} = await httpPost<JsonApiResourceDocument>({path_expr}, {}(input));\n\
                             \x20     return {}(data);",
                            jsonapi::unflatten_fn(r),
                            jsonapi::flatten_fn(r)
                        ),
                        None => format!("return httpPost<{ret_str}>({path_expr}, input);"),
                    };
                    out.push_str(&format!(
                        "    async {camel}(input: {input_type}{pp_trailing}): Promise<{ret_str}> {{\n\
                         \x20     {body}\n\
                         \x20   }},\n",
                    ));
                }
                OpKind::Update => {
                    let input_type = rust_type_to_ts(&extract_input_type(&f.params[1].ty));
                    let path_expr = sp_template(&format!("/{plural}/${{encodeURIComponent(id)}}"));
                    let body = match resource {
                        Some(r) => format!(
                            "const {{ data }} = await httpPatch<JsonApiResourceDocument>(\n\
                             \x20       {path_expr},\n\
                             \x20       {}(input, id),\n\
                             \x20     );\n\
                             \x20     return {}(data);",
                            jsonapi::unflatten_fn(r),
                            jsonapi::flatten_fn(r)
                        ),
                        None => format!("return httpPut<{ret_str}>({path_expr}, input);"),
                    };
                    out.push_str(&format!(
                        "    async {camel}(id: string, input: {input_type}{pp_trailing}): Promise<{ret_str}> {{\n\
                         \x20     {body}\n\
                         \x20   }},\n",
                    ));
                }
                OpKind::Delete => {
                    let path_expr = sp_template(&format!("/{plural}/${{encodeURIComponent(id)}}"));
                    out.push_str(&format!(
                        "    async {}(id: string{pp_trailing}): Promise<null> {{\n\
                         \x20     await httpDelete({path_expr});\n\
                         \x20     return null;\n\
                         \x20   }},\n",
                        camel,
                    ));
                }
                OpKind::JunctionList { ref child_segment } => {
                    // Junction list: `GET /<plural>/<parent_id>/<child_segment>`.
                    // The parent_id is the first (and only non-pagination) plain param.
                    let parent_param = f.params.first().map(|p| snake_to_camel(&p.name)).unwrap_or_default();
                    let paginated =
                        config.pagination_for(&m.name, f.surface).is_some() && f.return_type.starts_with("Vec<");
                    let return_type = if paginated {
                        let item_type = ret_str.strip_suffix("[]").unwrap_or(ret_str.as_str());
                        format!("PaginatedResult<{}>", item_type)
                    } else {
                        ret_str.clone()
                    };
                    let mut params = vec![format!("{parent_param}: string")];
                    if paginated {
                        params.push("limit?: number".to_string());
                        params.push("offset?: number".to_string());
                    }
                    if !pp_only.is_empty() {
                        params.push(pp_only.clone());
                    }
                    let params_str = params.join(", ");
                    let path_expr = if paginated {
                        sp_template(&format!(
                            "/{plural}/${{encodeURIComponent({parent_param})}}/{child_segment}${{toQueryString({{ limit, offset }})}}"
                        ))
                    } else {
                        sp_template(&format!("/{plural}/${{encodeURIComponent({parent_param})}}/{child_segment}"))
                    };
                    out.push_str(&format!(
                        "    async {camel}({params_str}): Promise<{return_type}> {{\n\
                         \x20     return httpGet({path_expr});\n\
                         \x20   }},\n",
                    ));
                }
                OpKind::JunctionAdd { ref child_segment } => {
                    // Junction add: `POST /<plural>/<parent_id>/<child_segment>` with
                    // body `{ <child_id_field>: <childId> }`. The Rust handler
                    // extracts `child_id` from the body using the service
                    // function's second parameter name.
                    let parent_param = f.params.first().map(|p| snake_to_camel(&p.name)).unwrap_or_default();
                    let child_id_field =
                        f.params.get(1).map(|p| p.name.clone()).unwrap_or_else(|| "child_id".to_string());
                    let child_param = snake_to_camel(&child_id_field);
                    let mut params = vec![format!("{parent_param}: string"), format!("{child_param}: string")];
                    if !pp_only.is_empty() {
                        params.push(pp_only.clone());
                    }
                    let params_str = params.join(", ");
                    let path_expr =
                        sp_template(&format!("/{plural}/${{encodeURIComponent({parent_param})}}/{child_segment}"));
                    out.push_str(&format!(
                        "    async {camel}({params_str}): Promise<null> {{\n\
                         \x20     await httpPost({path_expr}, {{ {child_id_field}: {child_param} }});\n\
                         \x20     return null;\n\
                         \x20   }},\n",
                    ));
                }
                OpKind::JunctionRemove { ref child_segment } => {
                    // Junction remove: `DELETE /<plural>/<parent_id>/<child_segment>/<child_id>`
                    let parent_param = f.params.first().map(|p| snake_to_camel(&p.name)).unwrap_or_default();
                    let child_param =
                        f.params.get(1).map(|p| snake_to_camel(&p.name)).unwrap_or_else(|| "childId".to_string());
                    let mut params = vec![format!("{parent_param}: string"), format!("{child_param}: string")];
                    if !pp_only.is_empty() {
                        params.push(pp_only.clone());
                    }
                    let params_str = params.join(", ");
                    let path_expr = sp_template(&format!(
                        "/{plural}/${{encodeURIComponent({parent_param})}}/{child_segment}/${{encodeURIComponent({child_param})}}"
                    ));
                    out.push_str(&format!(
                        "    async {camel}({params_str}): Promise<null> {{\n\
                         \x20     await httpDelete({path_expr});\n\
                         \x20     return null;\n\
                         \x20   }},\n",
                    ));
                }
                OpKind::CustomGet | OpKind::CustomPost => {
                    generate_http_custom_method(out, m, f, config);
                }
                OpKind::EventStream => continue,
            }
        }
    }

    // Event subscriptions over SSE
    for m in modules {
        for ev in &m.events {
            generate_http_subscribe_method(out, ev, config);
        }
    }

    // Legacy SSE listeners (parameterless sync ops only)
    for m in modules {
        for ev in m.events.iter().filter(|ev| ev.is_legacy()) {
            let camel = snake_to_camel(&ev.name);
            let ev_name = ev.name.replace('_', "-");
            let route_path = if let Some(override_path) = config.sse_route_overrides.get(&ev.name) {
                override_path.clone()
            } else {
                format!("/api/events/{}", ev_name)
            };

            if config.route_prefix.is_some() {
                // When route_prefix is configured, accept optional projectId and
                // use scoped path when provided.
                // Use addEventListener with the named event type - onmessage only
                // catches unnamed SSE events, but the backend sends named events
                // via `.event("{ev_name}")`.
                out.push_str(&format!(
                    "    async on{cap}(callback: (payload: unknown) => void{pp_trailing}): Promise<() => void> {{\n\
                     \x20     let es: EventSource | null = null;\n\
                     \x20     let reconnectTimer: ReturnType<typeof setTimeout> | null = null;\n\
                     \x20     const url = `${{BASE}}${{scopedPath(projectId, '{sse_path}')}}`;\n\
                     \x20     function connect() {{\n\
                     \x20       es = new EventSource(url);\n\
                     \x20       es.addEventListener('{ev_name}', (event: MessageEvent) => {{\n\
                     \x20         try {{ callback(JSON.parse(event.data)); }}\n\
                     \x20         catch {{ callback({{}}); }}\n\
                     \x20       }});\n\
                     \x20       es.onerror = () => {{\n\
                     \x20         es?.close();\n\
                     \x20         es = null;\n\
                     \x20         reconnectTimer = setTimeout(connect, 3000);\n\
                     \x20       }};\n\
                     \x20     }}\n\
                     \x20     connect();\n\
                     \x20     return () => {{\n\
                     \x20       if (reconnectTimer) clearTimeout(reconnectTimer);\n\
                     \x20       es?.close();\n\
                     \x20       es = null;\n\
                     \x20     }};\n\
                     \x20   }},\n",
                    cap = capitalize_first(&camel),
                    sse_path = route_path.strip_prefix("/api").unwrap_or(&route_path),
                ));
            } else {
                out.push_str(&format!(
                    "    async on{cap}(callback: (payload: unknown) => void): Promise<() => void> {{\n\
                     \x20     let es: EventSource | null = null;\n\
                     \x20     let reconnectTimer: ReturnType<typeof setTimeout> | null = null;\n\
                     \x20     function connect() {{\n\
                     \x20       es = new EventSource('{route_path}');\n\
                     \x20       es.addEventListener('{ev_name}', (event: MessageEvent) => {{\n\
                     \x20         try {{ callback(JSON.parse(event.data)); }}\n\
                     \x20         catch {{ callback({{}}); }}\n\
                     \x20       }});\n\
                     \x20       es.onerror = () => {{\n\
                     \x20         es?.close();\n\
                     \x20         es = null;\n\
                     \x20         reconnectTimer = setTimeout(connect, 3000);\n\
                     \x20       }};\n\
                     \x20     }}\n\
                     \x20     connect();\n\
                     \x20     return () => {{\n\
                     \x20       if (reconnectTimer) clearTimeout(reconnectTimer);\n\
                     \x20       es?.close();\n\
                     \x20       es = null;\n\
                     \x20     }};\n\
                     \x20   }},\n",
                    cap = capitalize_first(&camel),
                ));
            }
        }
    }

    out.push_str("  };\n");
    out.push_str("}\n\n");
}

/// Generate `createIpcTransport()`.
fn generate_ipc_transport(out: &mut String, modules: &[ApiModule], config: &Config) {
    let pp_trailing = ts_trailing_prefix_param(config);
    let pp_only = ts_prefix_param_only(config);
    let ipc_arg = ts_ipc_prefix_arg(config);
    let ipc_arg_only = ts_ipc_prefix_arg_only(config);

    out.push_str(
        "// ── IPC Transport ──\n\n\
         export function createIpcTransport(): Transport {\n\
         \x20 return {\n",
    );

    for m in modules {
        if m.functions.is_empty() {
            continue;
        }
        let module = &m.name;

        for f in &m.functions {
            let op = classify_op(f);
            let cmd_name = command_name(module, f, config);
            if cmd_name.is_empty() || config.ts_skip_commands.contains(&cmd_name) {
                continue;
            }

            let camel = snake_to_camel(&cmd_name);
            let ts_ret = rust_type_to_ts(&f.return_type);
            let returns_unit = f.return_type == "()";
            let ret_str = if returns_unit { "null".to_string() } else { ts_ret.clone() };
            // The Rust IPC command name (snake_case)
            let invoke_name = &cmd_name;

            match op {
                OpKind::List => {
                    let query_param = f.params.iter().find(|p| p.ty.contains("Query"));
                    // Pagination only applies when the list function returns Vec<T>;
                    // custom result types are passed through unchanged.
                    let paginated =
                        config.pagination_for(&m.name, f.surface).is_some() && f.return_type.starts_with("Vec<");
                    // A list that takes the page owns its limit/offset: they are never caller params.
                    let plain_params: Vec<&Param> = f
                        .params
                        .iter()
                        .filter(|p| {
                            !p.ty.contains("Query") && !p.ty.contains("Input") && (!f.takes_page() || !is_page_param(p))
                        })
                        .collect();

                    let mut params = Vec::new();
                    for pp in &plain_params {
                        let ts_ty = rust_type_to_ts(&strip_ref(&pp.ty));
                        params.push(format!("{}: {}", snake_to_camel(&pp.name), ts_ty));
                    }
                    if let Some(qp) = query_param {
                        let qt = rust_type_to_ts(&extract_input_type(&qp.ty));
                        params.push(format!("query?: {}", qt));
                    }
                    if paginated {
                        params.push("limit?: number".to_string());
                        params.push("offset?: number".to_string());
                    }
                    if !pp_only.is_empty() {
                        params.push(pp_only.clone());
                    }
                    let params_str = params.join(", ");

                    let return_type = if paginated {
                        let item_type = ret_str.strip_suffix("[]").unwrap_or(ret_str.as_str());
                        format!("PaginatedResult<{}>", item_type)
                    } else {
                        ret_str.clone()
                    };

                    // Build invoke args
                    let mut invoke_args = Vec::new();
                    for pp in &plain_params {
                        invoke_args.push(snake_to_camel(&pp.name));
                    }
                    if query_param.is_some() {
                        invoke_args.push("query: query ?? {}".to_string());
                    }
                    if paginated {
                        invoke_args.push("limit: limit ?? null".to_string());
                        invoke_args.push("offset: offset ?? null".to_string());
                    }
                    if !ipc_arg_only.is_empty() {
                        invoke_args.push(ipc_arg_only.clone());
                    }

                    if invoke_args.is_empty() {
                        out.push_str(&format!(
                            "    async {}({}): Promise<{}> {{\n\
                             \x20     return invoke('{invoke_name}');\n\
                             \x20   }},\n",
                            camel, params_str, return_type,
                        ));
                    } else {
                        let args_str = invoke_args.join(", ");
                        out.push_str(&format!(
                            "    async {}({}): Promise<{}> {{\n\
                             \x20     return invoke('{invoke_name}', {{ {} }});\n\
                             \x20   }},\n",
                            camel, params_str, return_type, args_str,
                        ));
                    }
                }
                OpKind::GetById => {
                    out.push_str(&format!(
                        "    async {}(id: string{pp_trailing}): Promise<{}> {{\n\
                         \x20     return invoke('{invoke_name}', {{ id{ipc_arg} }});\n\
                         \x20   }},\n",
                        camel, ret_str,
                    ));
                }
                OpKind::Create => {
                    let input_type = rust_type_to_ts(&extract_input_type(&f.params[0].ty));
                    out.push_str(&format!(
                        "    async {}(input: {}{pp_trailing}): Promise<{}> {{\n\
                         \x20     return invoke('{invoke_name}', {{ input{ipc_arg} }});\n\
                         \x20   }},\n",
                        camel, input_type, ret_str,
                    ));
                }
                OpKind::Update => {
                    let input_type = rust_type_to_ts(&extract_input_type(&f.params[1].ty));
                    out.push_str(&format!(
                        "    async {}(id: string, input: {}{pp_trailing}): Promise<{}> {{\n\
                         \x20     return invoke('{invoke_name}', {{ id, input{ipc_arg} }});\n\
                         \x20   }},\n",
                        camel, input_type, ret_str,
                    ));
                }
                OpKind::Delete => {
                    out.push_str(&format!(
                        "    async {}(id: string{pp_trailing}): Promise<null> {{\n\
                         \x20     await invoke('{invoke_name}', {{ id{ipc_arg} }});\n\
                         \x20     return null;\n\
                         \x20   }},\n",
                        camel,
                    ));
                }
                OpKind::JunctionList { .. } => {
                    // JunctionList IPC mirrors the HTTP paginated variant:
                    // when pagination is enabled and the return is Vec<T>,
                    // accept limit/offset and invoke with those args; the
                    // Rust handler returns PaginatedResult<T>.
                    let paginated =
                        config.pagination_for(&m.name, f.surface).is_some() && f.return_type.starts_with("Vec<");
                    let return_type = if paginated {
                        let item_type = ret_str.strip_suffix("[]").unwrap_or(ret_str.as_str());
                        format!("PaginatedResult<{}>", item_type)
                    } else {
                        ret_str.clone()
                    };
                    let parent_param = f.params.first().map(|p| snake_to_camel(&p.name)).unwrap_or_default();
                    let mut params = vec![format!("{parent_param}: string")];
                    let mut invoke_args = vec![parent_param.clone()];
                    if paginated {
                        params.push("limit?: number".to_string());
                        params.push("offset?: number".to_string());
                        invoke_args.push("limit: limit ?? null".to_string());
                        invoke_args.push("offset: offset ?? null".to_string());
                    }
                    if !pp_only.is_empty() {
                        params.push(pp_only.clone());
                    }
                    if !ipc_arg_only.is_empty() {
                        invoke_args.push(ipc_arg_only.clone());
                    }
                    let params_str = params.join(", ");
                    let args_str = invoke_args.join(", ");
                    out.push_str(&format!(
                        "    async {camel}({params_str}): Promise<{return_type}> {{\n\
                         \x20     return invoke('{invoke_name}', {{ {args_str} }});\n\
                         \x20   }},\n",
                    ));
                }
                OpKind::JunctionAdd { .. } | OpKind::JunctionRemove { .. } => {
                    // JunctionAdd/Remove have exactly 2 string params, no pagination.
                    // The generic custom IPC path produces correct output.
                    generate_ipc_custom_method(out, f, &cmd_name, config);
                }
                OpKind::CustomGet | OpKind::CustomPost => {
                    generate_ipc_custom_method(out, f, &cmd_name, config);
                }
                OpKind::EventStream => continue,
            }
        }
    }

    // Event subscriptions over a per-subscriber Channel
    for m in modules {
        for ev in &m.events {
            generate_ipc_subscribe_method(out, ev, config);
        }
    }

    // Legacy global listeners via Tauri listen (parameterless sync ops only)
    for m in modules {
        for ev in m.events.iter().filter(|ev| ev.is_legacy()) {
            let camel = snake_to_camel(&ev.name);
            let ev_name = ev.name.replace('_', "-");

            // Accept _projectId to match Transport interface, even though
            // Tauri listen is not project-scoped (IPC events are global).
            let ipc_pp = if pp_trailing.is_empty() { String::new() } else { pp_trailing.replace(", ", ", _") };
            out.push_str(&format!(
                "    async on{cap}(callback: (payload: unknown) => void{ipc_pp}): Promise<() => void> {{\n\
                 \x20     const unlisten = await listen('{ev_name}', (event: {{ payload: unknown }}) => {{\n\
                 \x20       callback(event.payload);\n\
                 \x20     }});\n\
                 \x20     return unlisten;\n\
                 \x20   }},\n",
                cap = capitalize_first(&camel),
            ));
        }
    }

    out.push_str("  };\n");
    out.push_str("}\n");
}

/// Builds `?a=1&b=x` from the defined values. An object value is a JSON:API
/// parameter family: `{ page: { offset: 0 } }` gives `page%5Boffset%5D=0`.
/// An array value repeats its key.
const TO_QUERY_STRING: &str = "\
function toQueryString(params: Record<string, unknown>): string {
  const parts: string[] = [];
  const push = (key: string, value: unknown) => {
    if (value == null) return;
    for (const v of Array.isArray(value) ? value : [value]) {
      parts.push(`${key}=${encodeURIComponent(String(v))}`);
    }
  };
  for (const [key, value] of Object.entries(params)) {
    if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
      for (const [member, v] of Object.entries(value)) {
        push(`${encodeURIComponent(key)}%5B${encodeURIComponent(member)}%5D`, v);
      }
    } else {
      push(encodeURIComponent(key), value);
    }
  }
  return parts.length > 0 ? `?${parts.join('&')}` : '';
}

";

/// Handler and frame types shared by every `subscribeX` method.
const SUBSCRIPTION_TYPES: &str = "\
// ── Event Subscriptions ──

export interface SubscriptionHandlers<T> {
  /** An event. `id` is its resume id, or null for an op that is not resumable. */
  onEvent: (data: T, id: string | null) => void;
  /** The subscription fell behind and `skipped` events were dropped. */
  onLag?: (skipped: number) => void;
  /** Fires on the first connect and on every reconnect: the hook for a catch-up read. */
  onOpen?: () => void;
  onError?: (err: unknown) => void;
}

type EventFrame<T> = { kind: 'event'; id: string | null; data: T } | { kind: 'lag'; skipped: number };

";

/// The SSE subscription loop shared by every HTTP `subscribeX` method.
///
/// Every error closes the `EventSource` and reconnects after a capped
/// exponential backoff with jitter; the reconnect passes the last seen id as
/// the `resume` query param (a new `EventSource` sends no `Last-Event-ID`).
const SSE_SUBSCRIBE_HELPER: &str = "\
const SSE_RETRY_BASE_MS = 500;
const SSE_RETRY_MAX_MS = 30000;

function subscribeSse<T>(
  url: (resume: string | null) => string,
  eventName: string,
  initialResume: string | null,
  handlers: SubscriptionHandlers<T>,
): () => void {
  let source: EventSource | null = null;
  let timer: ReturnType<typeof setTimeout> | null = null;
  let lastId = initialResume;
  let attempt = 0;
  let closed = false;
  function connect() {
    if (closed) return;
    const es = new EventSource(url(lastId));
    source = es;
    es.onopen = () => {
      attempt = 0;
      handlers.onOpen?.();
    };
    es.addEventListener(eventName, (event: MessageEvent) => {
      const id = event.lastEventId || null;
      if (id) lastId = id;
      let data: T;
      try {
        data = JSON.parse(event.data);
      } catch (err) {
        handlers.onError?.(err);
        return;
      }
      handlers.onEvent(data, id);
    });
    es.addEventListener('lag', (event: MessageEvent) => {
      try {
        handlers.onLag?.(JSON.parse(event.data).skipped);
      } catch (err) {
        handlers.onError?.(err);
      }
    });
    es.onerror = (err: Event) => {
      es.close();
      if (source === es) source = null;
      if (closed) return;
      handlers.onError?.(err);
      const delay = Math.min(SSE_RETRY_MAX_MS, SSE_RETRY_BASE_MS * 2 ** attempt);
      attempt += 1;
      timer = setTimeout(connect, delay / 2 + Math.random() * (delay / 2));
    };
  }
  connect();
  return () => {
    closed = true;
    if (timer) clearTimeout(timer);
    source?.close();
    source = null;
  };
}

";

/// The Channel subscription shared by every IPC `subscribeX` method.
const IPC_SUBSCRIBE_HELPER: &str = "\
// ── IPC Helpers ──

async function subscribeIpc<T>(
  command: string,
  unsubscribeCommand: string,
  args: Record<string, unknown>,
  handlers: SubscriptionHandlers<T>,
): Promise<() => void> {
  const channel = new Channel<EventFrame<T>>();
  channel.onmessage = (frame) => {
    if (frame.kind === 'event') handlers.onEvent(frame.data, frame.id ?? null);
    else handlers.onLag?.(frame.skipped);
  };
  const id = await invoke<number>(command, { ...args, channel });
  handlers.onOpen?.();
  return () => {
    invoke(unsubscribeCommand, { id }).catch((err: unknown) => handlers.onError?.(err));
  };
}

";

/// `subscribeVaultNoteChanges`.
fn subscribe_method_name(ev: &EventFn) -> String {
    format!("subscribe{}", capitalize_first(&snake_to_camel(&ev.name)))
}

/// The `args` object type: required params required, `Option` params
/// optional, plus the route-prefix param when one is configured.
fn subscribe_args_type(ev: &EventFn, config: &Config) -> String {
    let mut fields: Vec<String> = ev
        .params
        .iter()
        .map(|p| {
            let ts = rust_type_to_ts(&strip_ref(&p.ty));
            let optional = if p.ty.starts_with("Option<") { "?" } else { "" };
            format!("{}{optional}: {ts}", snake_to_camel(&p.name))
        })
        .collect();
    let pp_only = ts_prefix_param_only(config);
    if !pp_only.is_empty() {
        fields.push(pp_only);
    }
    if fields.is_empty() { "Record<string, never>".to_string() } else { format!("{{ {} }}", fields.join("; ")) }
}

/// `subscribeX(args: {...}, handlers: SubscriptionHandlers<T>): Promise<() => void>`.
fn subscribe_signature(ev: &EventFn, config: &Config) -> String {
    format!(
        "{}(args: {}, handlers: SubscriptionHandlers<{}>): Promise<() => void>",
        subscribe_method_name(ev),
        subscribe_args_type(ev, config),
        rust_type_to_ts(&ev.item_type),
    )
}

/// The HTTP `subscribeX`: builds the SSE URL from the args (path params
/// interpolated, optional params and `resume` on the query string) and hands
/// it to `subscribeSse`.
fn generate_http_subscribe_method(out: &mut String, ev: &EventFn, config: &Config) {
    let route = ev.sse_route(&config.sse_route_overrides);
    let route = route.strip_prefix("/api").unwrap_or(&route);
    let template = route
        .split('/')
        .map(|seg| match seg.strip_prefix(':') {
            Some(name) => format!("${{encodeURIComponent(String(args.{}))}}", snake_to_camel(name)),
            None => seg.to_string(),
        })
        .collect::<Vec<_>>()
        .join("/");
    let path_expr = match &config.route_prefix {
        Some(prefix) => format!("scopedPath(args.{}, `{template}`)", snake_to_camel(&prefix.params[0].name)),
        None => format!("`{template}`"),
    };
    let query: Vec<String> = ev
        .query_params()
        .iter()
        .map(|p| {
            if is_resume_param(p) {
                format!("{}: resume", p.name)
            } else {
                format!("{}: args.{}", p.name, snake_to_camel(&p.name))
            }
        })
        .collect();
    let query_expr =
        if query.is_empty() { String::new() } else { format!(" + toQueryString({{ {} }})", query.join(", ")) };
    let resume_arg = if query.is_empty() || !ev.is_resumable() { "_resume" } else { "resume" };
    let initial = if ev.is_resumable() { "args.resume ?? null" } else { "null" };
    out.push_str(&format!(
        "    async {sig} {{\n\
         \x20     return subscribeSse(\n\
         \x20       ({resume_arg}) => `${{BASE}}${{{path_expr}}}`{query_expr},\n\
         \x20       '{ev_name}',\n\
         \x20       {initial},\n\
         \x20       handlers,\n\
         \x20     );\n\
         \x20   }},\n",
        sig = subscribe_signature(ev, config),
        ev_name = event_name(&ev.name),
    ));
}

/// The IPC `subscribeX`: calls `{fn}_subscribe` with the args and a new
/// `Channel`; the returned function calls `{fn}_unsubscribe`. The route
/// prefix is not sent: IPC subscriptions are not project-scoped.
fn generate_ipc_subscribe_method(out: &mut String, ev: &EventFn, config: &Config) {
    let args: Vec<String> = ev
        .params
        .iter()
        .map(|p| {
            let camel = snake_to_camel(&p.name);
            if p.ty.starts_with("Option<") {
                format!("{camel}: args.{camel} ?? null")
            } else {
                format!("{camel}: args.{camel}")
            }
        })
        .collect();
    // With no params the args object is unused (the route prefix is not sent).
    let (sig, args_obj) = if args.is_empty() {
        (subscribe_signature(ev, config).replacen("(args:", "(_args:", 1), "{}".to_string())
    } else {
        (subscribe_signature(ev, config), format!("{{ {} }}", args.join(", ")))
    };
    out.push_str(&format!(
        "    async {sig} {{\n\
         \x20     return subscribeIpc('{fn_name}_subscribe', '{fn_name}_unsubscribe', {args_obj}, handlers);\n\
         \x20   }},\n",
        fn_name = ev.name,
    ));
}

/// Generate a custom HTTP method (GET or POST with various param shapes).
fn generate_http_custom_method(
    out: &mut String,
    module: &crate::servers::parse::ApiModule,
    f: &crate::servers::parse::ApiFn,
    config: &Config,
) {
    let fn_name = &f.name;
    let name = module.name.as_str();
    let cmd_name = command_name(name, f, config);
    let camel = snake_to_camel(&cmd_name);
    let ts_ret = rust_type_to_ts(&f.return_type);
    let is_get = is_read_op(&classify_op(f));
    let action = config.naming.derive_action(name, fn_name);
    // Use kebab-case URL plural to match http.rs route registration. Singleton
    // modules collapse to the singular kebab form via `url_for_module`.
    let plural = config.naming.url_for_module(module);
    let returns_unit = f.return_type == "()";
    let has_prefix = config.route_prefix.is_some();
    let pp_camel = config.route_prefix.as_ref().map(|p| snake_to_camel(&p.params[0].name)).unwrap_or_default();
    let pp_only = ts_prefix_param_only(config);

    let body_struct: Option<&Param> = f.params.iter().find(|p| p.ty.contains("Input"));
    let query_params: Vec<&Param> = f.params.iter().filter(|p| p.ty.starts_with("Option<")).collect();
    let path_params: Vec<&Param> = if is_get {
        f.params.iter().filter(|p| !p.ty.starts_with("Option<") && !p.ty.contains("Input")).collect()
    } else {
        vec![]
    };
    let body_fields: Vec<&Param> = if !is_get && body_struct.is_none() {
        f.params.iter().filter(|p| !p.ty.starts_with("Option<") && !p.ty.contains("Input")).collect()
    } else {
        vec![]
    };

    let mut route_path = format!("/{}", plural);
    if !action.is_empty() {
        route_path.push_str(&format!("/{}", action));
    }

    // A POST that carries query params needs the templated path (so `${params}`
    // interpolates); one that does not keeps the plain literal.
    fn post_path_expr(
        sp: &dyn Fn(&str) -> String,
        sp_template: &dyn Fn(&str) -> String,
        route_path: &str,
        has_query: bool,
    ) -> String {
        if has_query { sp_template(&format!("{route_path}${{params}}")) } else { sp(route_path) }
    }

    // Optional params ride the QUERY STRING on both methods, not just GET.
    // `http.rs` emits a `Query(...)` extractor whenever any param is
    // `Option<T>`, regardless of the route's method — so a POST whose params
    // are all optional has a server reading them from a query string the
    // client never sends. Every argument arrives `None`, with no compile
    // error and no runtime error: the call simply does nothing, quietly.
    //
    // This builder is therefore shared by the GET and POST arms below rather
    // than living inside the GET one.
    let build_query = |query_params: &[&Param]| -> Option<String> {
        if query_params.is_empty() {
            return None;
        }
        let query_parts: Vec<String> = query_params
            .iter()
            .map(|qp| {
                let camel_name = snake_to_camel(&qp.name);
                format!("{camel_name} != null ? `{}=${{encodeURIComponent({camel_name})}}` : ''", qp.name)
            })
            .collect();
        Some(if query_parts.len() == 1 {
            format!(
                "const params = {} != null ? `?${{{}}}` : ''",
                snake_to_camel(&query_params[0].name),
                query_parts[0]
            )
        } else {
            format!(
                "const parts = [{}].filter(Boolean);\n\
                 \x20       const params = parts.length > 0 ? `?${{parts.join('&')}}` : ''",
                query_parts.join(", ")
            )
        })
    };

    // Helper closures for scoped paths
    let sp = |path: &str| -> String {
        if has_prefix { format!("scopedPath({}, '{}')", pp_camel, path) } else { format!("'{}'", path) }
    };
    let sp_template = |path: &str| -> String {
        if has_prefix { format!("scopedPath({}, `{}`)", pp_camel, path) } else { format!("`{}`", path) }
    };

    let mut ts_params = ts_params_in_declaration_order(f);
    if !pp_only.is_empty() {
        ts_params.push(pp_only.clone());
    }
    let params_str = ts_params.join(", ");
    let ret_str = if returns_unit { "null".to_string() } else { ts_ret.clone() };

    if is_get && path_params.is_empty() && query_params.is_empty() {
        let path_expr = sp(&route_path);
        out.push_str(&format!(
            "    async {camel}({params_str}): Promise<{ret_str}> {{\n\
             \x20     return httpGet({path_expr});\n\
             \x20   }},\n",
        ));
    } else if is_get && !path_params.is_empty() && query_params.is_empty() {
        let mut url = route_path.clone();
        for p in &path_params {
            url.push_str(&format!("/${{encodeURIComponent({})}}", snake_to_camel(&p.name)));
        }
        let path_expr = sp_template(&url);
        out.push_str(&format!(
            "    async {camel}({params_str}): Promise<{ret_str}> {{\n\
             \x20     return httpGet({path_expr});\n\
             \x20   }},\n",
        ));
    } else if is_get && !query_params.is_empty() {
        // Path segments come before the query string — http.rs registers the
        // route as `/{plural}/{action}/{path_param}`, so a fn mixing a required
        // path param with optional query params must keep both.
        let mut url = route_path.clone();
        for p in &path_params {
            url.push_str(&format!("/${{encodeURIComponent({})}}", snake_to_camel(&p.name)));
        }
        let query_build = build_query(&query_params).expect("branch guarded on non-empty query_params");
        let path_expr = sp_template(&format!("{}${{params}}", url));
        out.push_str(&format!(
            "    async {camel}({params_str}): Promise<{ret_str}> {{\n\
             \x20     {query_build};\n\
             \x20     return httpGet({path_expr});\n\
             \x20   }},\n",
        ));
    } else if body_struct.is_some() {
        let post_query = build_query(&query_params);
        let path_expr = post_path_expr(&sp, &sp_template, &route_path, post_query.is_some());
        let prelude = post_query.as_ref().map(|q| format!("      {q};\n")).unwrap_or_default();
        if returns_unit {
            out.push_str(&format!(
                "    async {camel}({params_str}): Promise<null> {{\n{prelude}\
                 \x20     await httpPost({path_expr}, input);\n\
                 \x20     return null;\n\
                 \x20   }},\n",
            ));
        } else {
            out.push_str(&format!(
                "    async {camel}({params_str}): Promise<{ret_str}> {{\n{prelude}\
                 \x20     return httpPost<{ret_str}>({path_expr}, input);\n\
                 \x20   }},\n",
            ));
        }
    } else if !body_fields.is_empty() {
        let post_query = build_query(&query_params);
        let prelude = post_query.as_ref().map(|q| format!("      {q};\n")).unwrap_or_default();
        let body_obj: Vec<String> = body_fields
            .iter()
            .map(|bf| {
                let camel_name = snake_to_camel(&bf.name);
                if camel_name == bf.name { bf.name.clone() } else { format!("{}: {}", bf.name, camel_name) }
            })
            .collect();
        let body_str = format!("{{ {} }}", body_obj.join(", "));
        let path_expr = post_path_expr(&sp, &sp_template, &route_path, post_query.is_some());
        if returns_unit {
            out.push_str(&format!(
                "    async {camel}({params_str}): Promise<null> {{\n{prelude}\
                 \x20     await httpPost({path_expr}, {body_str});\n\
                 \x20     return null;\n\
                 \x20   }},\n",
            ));
        } else {
            out.push_str(&format!(
                "    async {camel}({params_str}): Promise<{ret_str}> {{\n{prelude}\
                 \x20     return httpPost<{ret_str}>({path_expr}, {body_str});\n\
                 \x20   }},\n",
            ));
        }
    } else {
        // POST whose only params, if any, are optional — they ride the query
        // string, exactly as the server's `Query(...)` extractor expects.
        let post_query = build_query(&query_params);
        let prelude = post_query.as_ref().map(|q| format!("      {q};\n")).unwrap_or_default();
        let path_expr = post_path_expr(&sp, &sp_template, &route_path, post_query.is_some());
        if returns_unit {
            out.push_str(&format!(
                "    async {camel}({params_str}): Promise<null> {{\n{prelude}\
                 \x20     await httpPost({path_expr});\n\
                 \x20     return null;\n\
                 \x20   }},\n",
            ));
        } else {
            out.push_str(&format!(
                "    async {camel}({params_str}): Promise<{ret_str}> {{\n{prelude}\
                 \x20     return httpPost<{ret_str}>({path_expr});\n\
                 \x20   }},\n",
            ));
        }
    }
}

/// Generate a custom IPC method.
fn generate_ipc_custom_method(out: &mut String, f: &crate::servers::parse::ApiFn, cmd_name: &str, config: &Config) {
    let camel = snake_to_camel(cmd_name);
    let ts_ret = rust_type_to_ts(&f.return_type);
    let returns_unit = f.return_type == "()";
    let ret_str = if returns_unit { "null".to_string() } else { ts_ret.clone() };
    let pp_only = ts_prefix_param_only(config);
    let ipc_arg = ts_ipc_prefix_arg(config);

    let has_params = !f.params.is_empty();
    let has_prefix = !pp_only.is_empty();

    if !has_params && !has_prefix {
        if returns_unit {
            out.push_str(&format!(
                "    async {camel}(): Promise<null> {{\n\
                 \x20     await invoke('{cmd_name}');\n\
                 \x20     return null;\n\
                 \x20   }},\n",
            ));
        } else {
            out.push_str(&format!(
                "    async {camel}(): Promise<{ret_str}> {{\n\
                 \x20     return invoke('{cmd_name}');\n\
                 \x20   }},\n",
            ));
        }
    } else {
        // Build param list and invoke args
        // `rust_type_to_ts` already maps `Option<T>` to `T | null`, matching
        // the Transport interface signature built by `build_ts_params`.
        let mut ts_params: Vec<String> =
            f.params.iter().map(|p| format!("{}: {}", snake_to_camel(&p.name), rust_type_to_ts(&p.ty))).collect();
        if has_prefix {
            ts_params.push(pp_only.clone());
        }
        let params_str = ts_params.join(", ");

        // Build invoke args object - Tauri expects snake_case keys for IPC
        let invoke_args: Vec<String> = f.params.iter().map(|p| snake_to_camel(&p.name)).collect();
        let ipc_arg_only = ts_ipc_prefix_arg_only(config);
        let args_str = if invoke_args.is_empty() && !ipc_arg_only.is_empty() {
            format!("{{ {ipc_arg_only} }}")
        } else {
            format!("{{ {}{ipc_arg} }}", invoke_args.join(", "))
        };

        if returns_unit {
            out.push_str(&format!(
                "    async {camel}({params_str}): Promise<null> {{\n\
                 \x20     await invoke('{cmd_name}', {args_str});\n\
                 \x20     return null;\n\
                 \x20   }},\n",
            ));
        } else {
            out.push_str(&format!(
                "    async {camel}({params_str}): Promise<{ret_str}> {{\n\
                 \x20     return invoke('{cmd_name}', {args_str});\n\
                 \x20   }},\n",
            ));
        }
    }
}

/// Capitalize the first character of a string.
fn capitalize_first(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        None => String::new(),
        Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
    }
}
