#![allow(clippy::too_many_lines, clippy::format_push_string)]

//! Generate a unified TypeScript transport layer from API modules.
//!
//! Produces a single file containing:
//! - `Transport` interface
//! - `createHttpTransport()` - fetch-based HTTP implementation
//! - `createIpcTransport()` - Tauri IPC invoke-based implementation

use std::fs;
use std::path::Path;

use ontogen_core::ir::OpKind;

use crate::clients::config::Config;
use crate::clients::generators::jsonapi;
use crate::clients::generators::{FallbackRecord, command_name};
use crate::resource::member_name;
use crate::servers::classify::classify_op;
use crate::servers::parse::{ApiModule, EventFn, is_resume_param};
use crate::servers::types::{event_name, ipc_arg_key, snake_to_camel, ts_key, ts_param};

/// Returns `", projectId?: string"` when route_prefix is configured, else `""`.
fn ts_trailing_prefix_param(config: &Config) -> String {
    match &config.route_prefix {
        Some(prefix) => {
            let pp = &prefix.params[0];
            format!(", {}?: {}", ts_param(&pp.name), pp.ts_type)
        }
        None => String::new(),
    }
}

/// `projectId?: string` when a route prefix is configured.
fn ts_prefix_param(config: &Config) -> Option<String> {
    Some(ts_prefix_param_only(config)).filter(|p| !p.is_empty())
}

/// Returns `"projectId?: string"` when route_prefix is configured, else `""`.
fn ts_prefix_param_only(config: &Config) -> String {
    match &config.route_prefix {
        Some(prefix) => {
            let pp = &prefix.params[0];
            format!("{}?: {}", ts_param(&pp.name), pp.ts_type)
        }
        None => String::new(),
    }
}

/// Returns the IPC invoke arg fragment for project_id, e.g., `, projectId: projectId ?? null`.
fn ts_ipc_prefix_arg(config: &Config) -> String {
    let arg = ts_ipc_prefix_arg_only(config);
    if arg.is_empty() { arg } else { format!(", {arg}") }
}

/// Returns the IPC invoke arg fragment without leading comma, e.g., `projectId: projectId ?? null`.
fn ts_ipc_prefix_arg_only(config: &Config) -> String {
    match &config.route_prefix {
        Some(prefix) => {
            let name = &prefix.params[0].name;
            invoke_member(name, &format!("{} ?? null", ts_param(name)))
        }
        None => String::new(),
    }
}

/// The invoke payload member that sends `value` as the command argument
/// `param`, under the key Tauri reads it from: `key: value`, or the
/// shorthand `key` when `value` is the bare TS name the key matches.
fn invoke_member(param: &str, value: &str) -> String {
    let key = ipc_arg_key(param);
    if key == value { key } else { format!("{}: {value}", ts_key(&key)) }
}

/// [`invoke_member`] sending the argument's own TS parameter.
fn invoke_arg(param: &str) -> String {
    invoke_member(param, &ts_param(param))
}

/// The module specifier a client at `output` imports the bindings file at
/// `bindings_path` by: relative, with no `.ts` extension.
pub(super) fn bindings_import_path(output: &Path, bindings_path: &Path) -> String {
    let output_dir = output.parent().unwrap_or(Path::new("."));
    let bindings_abs = fs::canonicalize(bindings_path).unwrap_or_else(|_| bindings_path.to_path_buf());
    let output_abs = fs::canonicalize(output_dir).unwrap_or_else(|_| output_dir.to_path_buf());
    let rel = crate::utils::relative_path(&output_abs, &bindings_abs);
    let rel_str = rel.to_string_lossy().replace('\\', "/");
    let rel_str = rel_str.strip_suffix(".ts").unwrap_or(&rel_str);
    if rel_str.starts_with('.') { rel_str.to_string() } else { format!("./{rel_str}") }
}

/// Generate the unified transport layer and write to the output file.
///
/// Returns a [`FallbackRecord`] for every type referenced by the generated TS
/// surface that wasn't exported from `bindings.ts` and therefore had to be
/// stubbed as `Record<string, unknown>`. Callers (notably `generate_transport`
/// in `src/servers/mod.rs`) emit a `cargo:warning=` for each so silent
/// untyping shows up at build time. (OF-006)
pub fn generate(output: &Path, bindings_path: &Path, modules: &[ApiModule], config: &Config) -> Vec<FallbackRecord> {
    let mut out = String::new();

    // Read bindings.ts to discover exported types
    let bindings_content = fs::read_to_string(bindings_path).unwrap_or_default();
    let exported_types: Vec<String> = bindings_content
        .lines()
        .filter_map(|line| {
            line.strip_prefix("export type ")
                .or_else(|| line.strip_prefix("export interface "))
                .and_then(|rest| rest.split(|c: char| !c.is_alphanumeric() && c != '_').next().map(|s| s.to_string()))
        })
        .collect();

    out.push_str(
        "// Auto-generated transport layer. DO NOT EDIT.\n\
         // Generated by ontogen from API source files. DOM and JavaScript globals\n\
         // are written `globalThis.X`, since your types may share their names\n\
         // (`Response`, `Map`, `Event`).\n\n",
    );

    let import_types = jsonapi::imported_types(modules, config, true);
    let resources = jsonapi::served_resources(modules, config, true);
    let (available, missing): (Vec<_>, Vec<_>) = import_types.iter().partition(|t| exported_types.contains(t));

    let bindings_import_path = bindings_import_path(output, bindings_path);

    if !available.is_empty() {
        out.push_str("import type {\n");
        for t in &available {
            out.push_str(&format!("  {},\n", t));
        }
        out.push_str(&format!("}} from '{}';\n\n", bindings_import_path));
    }

    // IPC imports - must be at top level for lint compliance. `Channel` is
    // renamed so that an entity may be called `Channel`.
    let has_events = modules.iter().any(|m| !m.events.is_empty());
    if has_events {
        out.push_str("import { Channel as IpcChannel, invoke } from '@tauri-apps/api/core';\n");
    } else {
        out.push_str("import { invoke } from '@tauri-apps/api/core';\n");
    }
    let has_legacy_events = modules.iter().any(|m| m.events.iter().any(EventFn::is_legacy));
    if has_legacy_events {
        out.push_str("import { listen } from '@tauri-apps/api/event';\n");
    }
    out.push('\n');

    let fallbacks: Vec<FallbackRecord> = missing
        .iter()
        .map(|t| FallbackRecord {
            output: output.to_path_buf(),
            bindings_path: bindings_path.to_path_buf(),
            type_name: (*t).clone(),
        })
        .collect();

    for t in &missing {
        out.push_str(&format!(
            "// TODO: Type '{t}' not yet exported from bindings.ts - using placeholder\n\
             type {t} = Record<string, unknown>;\n\n"
        ));
    }

    // ── PaginatedResult<T> (when pagination is enabled) ──
    if config.any_pagination() {
        out.push_str(jsonapi::PAGINATED_RESULT);
    }
    out.push_str(&jsonapi::sort_types(modules, config));

    if has_events {
        out.push_str(SUBSCRIPTION_TYPES);
    }

    // ── Transport Interface ──
    generate_transport_interface(&mut out, modules, config);

    // ── HTTP Helpers ──
    out.push_str(jsonapi::JSON_API_TYPES);
    generate_http_helpers(&mut out, config);
    if has_events {
        out.push_str(SSE_SUBSCRIBE_HELPER);
        out.push_str(jsonapi::META_RESULT);
    }
    if !resources.is_empty() {
        out.push_str(jsonapi::RESOURCE_HELPERS);
        for r in &resources {
            out.push_str(&jsonapi::resource_codec(r));
        }
    }

    // ── createHttpTransport ──
    generate_http_transport(&mut out, modules, config);

    // ── createIpcTransport ──
    if has_events {
        out.push_str(IPC_SUBSCRIBE_HELPER);
    }
    generate_ipc_transport(&mut out, modules, config);

    if let Some(parent) = output.parent() {
        fs::create_dir_all(parent).expect("Failed to create output directory");
    }
    crate::write_and_format_ts(output, out, &config.ts_formatter).expect("Failed to write transport generated file");

    fallbacks
}

/// Generate the `Transport` interface.
fn generate_transport_interface(out: &mut String, modules: &[ApiModule], config: &Config) {
    let pp_trailing = ts_trailing_prefix_param(config);
    let prefix = ts_prefix_param(config);

    out.push_str("// ── Transport Interface ──\n\n");
    out.push_str("export interface Transport {\n");

    for m in modules {
        for f in &m.functions {
            let cmd_name = command_name(&m.name, f, config);
            if cmd_name.is_empty() || config.ts_skip_commands.contains(&cmd_name) {
                continue;
            }
            // The HTTP impl's own signature, so the two cannot drift.
            let Some(method) = jsonapi::method(m, f, config, None) else { continue };
            out.push_str(&format!(
                "  {}({}): Promise<{}>;\n",
                snake_to_camel(&cmd_name),
                method.signature(prefix.clone()),
                method.return_type
            ));
        }
    }

    // Event subscriptions
    for m in modules {
        for ev in &m.events {
            out.push_str(&format!("  {};\n", subscribe_signature(ev, config)));
        }
    }

    // Legacy global event listeners (parameterless sync ops only)
    for m in modules {
        for ev in m.events.iter().filter(|ev| ev.is_legacy()) {
            let camel = snake_to_camel(&ev.name);
            out.push_str(&format!(
                "  on{}(callback: (payload: unknown) => void{pp_trailing}): Promise<() => void>;\n",
                capitalize_first(&camel)
            ));
        }
    }

    out.push_str("}\n\n");
}

/// Generate HTTP helper functions.
fn generate_http_helpers(out: &mut String, config: &Config) {
    out.push_str(&jsonapi::http_helpers());

    // Add scopedPath helper when route_prefix is configured
    if let Some(prefix) = &config.route_prefix {
        // Build URL template from segments, e.g., "projects/:project_id" → "/projects/${encodeURIComponent(projectId)}"
        let mut url_parts = String::new();
        for segment in prefix.segments.split('/') {
            url_parts.push('/');
            if let Some(param_name) = segment.strip_prefix(':') {
                url_parts.push_str(&format!("${{encodeURIComponent({})}}", ts_param(param_name)));
            } else {
                url_parts.push_str(segment);
            }
        }
        let pp_camel = ts_param(&prefix.params[0].name);
        out.push_str(&format!(
            "function scopedPath({pp_camel}: string | undefined, path: string): string {{\n\
             \x20 if ({pp_camel}) {{\n\
             \x20   return `{url_parts}${{path}}`;\n\
             \x20 }}\n\
             \x20 return path;\n\
             }}\n\n",
        ));
    }
}

/// Generate `createHttpTransport()`.
fn generate_http_transport(out: &mut String, modules: &[ApiModule], config: &Config) {
    let pp_trailing = ts_trailing_prefix_param(config);
    let scope = config.route_prefix.as_ref().map(|p| ts_param(&p.params[0].name));

    out.push_str("// ── HTTP Transport ──\n\n");
    out.push_str("export function createHttpTransport(): Transport {\n");
    out.push_str("  return {\n");

    for m in modules {
        for f in &m.functions {
            let cmd_name = command_name(&m.name, f, config);
            if cmd_name.is_empty() || config.ts_skip_commands.contains(&cmd_name) {
                continue;
            }
            let Some(method) = jsonapi::method(m, f, config, scope.as_deref()) else { continue };
            // An op served unscoped only takes the prefix argument to match
            // the interface, and ignores it.
            let unused = jsonapi::scope_of(m, f, config, scope.as_deref()).is_none();
            let prefix = ts_prefix_param(config).map(|p| if unused { format!("_{p}") } else { p });
            out.push_str(&format!(
                "    async {}({}): Promise<{}> {{\n      {}\n    }},\n",
                snake_to_camel(&cmd_name),
                method.signature(prefix),
                method.return_type,
                method.body.join("\n").replace('\n', "\n      "),
            ));
        }
    }

    // Event subscriptions over SSE
    for m in modules {
        for ev in &m.events {
            generate_http_subscribe_method(out, ev, config);
        }
    }

    // Legacy SSE listeners (parameterless sync ops only)
    for m in modules {
        for ev in m.events.iter().filter(|ev| ev.is_legacy()) {
            let camel = snake_to_camel(&ev.name);
            let ev_name = ev.name.replace('_', "-");
            let route_path = if let Some(override_path) = config.sse_route_overrides.get(&ev.name) {
                override_path.clone()
            } else {
                format!("/api/events/{}", ev_name)
            };

            if let Some(scope) = &scope {
                // When route_prefix is configured, accept optional projectId and
                // use scoped path when provided.
                // Use addEventListener with the named event type - onmessage only
                // catches unnamed SSE events, but the backend sends named events
                // via `.event("{ev_name}")`.
                out.push_str(&format!(
                    "    async on{cap}(callback: (payload: unknown) => void{pp_trailing}): Promise<() => void> {{\n\
                     \x20     let es: globalThis.EventSource | null = null;\n\
                     \x20     let reconnectTimer: ReturnType<typeof setTimeout> | null = null;\n\
                     \x20     const url = `${{BASE}}${{scopedPath({scope}, '{sse_path}')}}`;\n\
                     \x20     function connect() {{\n\
                     \x20       es = new globalThis.EventSource(url);\n\
                     \x20       es.addEventListener('{ev_name}', (event: globalThis.MessageEvent) => {{\n\
                     \x20         try {{ callback({decode}); }}\n\
                     \x20         catch {{ callback({{}}); }}\n\
                     \x20       }});\n\
                     \x20       es.onerror = () => {{\n\
                     \x20         es?.close();\n\
                     \x20         es = null;\n\
                     \x20         reconnectTimer = setTimeout(connect, 3000);\n\
                     \x20       }};\n\
                     \x20     }}\n\
                     \x20     connect();\n\
                     \x20     return () => {{\n\
                     \x20       if (reconnectTimer) clearTimeout(reconnectTimer);\n\
                     \x20       es?.close();\n\
                     \x20       es = null;\n\
                     \x20     }};\n\
                     \x20   }},\n",
                    cap = capitalize_first(&camel),
                    sse_path = route_path.strip_prefix("/api").unwrap_or(&route_path),
                    decode = jsonapi::decode_event_frame(ev, config, "JSON.parse(event.data)"),
                ));
            } else {
                out.push_str(&format!(
                    "    async on{cap}(callback: (payload: unknown) => void): Promise<() => void> {{\n\
                     \x20     let es: globalThis.EventSource | null = null;\n\
                     \x20     let reconnectTimer: ReturnType<typeof setTimeout> | null = null;\n\
                     \x20     function connect() {{\n\
                     \x20       es = new globalThis.EventSource('{route_path}');\n\
                     \x20       es.addEventListener('{ev_name}', (event: globalThis.MessageEvent) => {{\n\
                     \x20         try {{ callback({decode}); }}\n\
                     \x20         catch {{ callback({{}}); }}\n\
                     \x20       }});\n\
                     \x20       es.onerror = () => {{\n\
                     \x20         es?.close();\n\
                     \x20         es = null;\n\
                     \x20         reconnectTimer = setTimeout(connect, 3000);\n\
                     \x20       }};\n\
                     \x20     }}\n\
                     \x20     connect();\n\
                     \x20     return () => {{\n\
                     \x20       if (reconnectTimer) clearTimeout(reconnectTimer);\n\
                     \x20       es?.close();\n\
                     \x20       es = null;\n\
                     \x20     }};\n\
                     \x20   }},\n",
                    cap = capitalize_first(&camel),
                    decode = jsonapi::decode_event_frame(ev, config, "JSON.parse(event.data)"),
                ));
            }
        }
    }

    out.push_str("  };\n");
    out.push_str("}\n\n");
}

/// Generate `createIpcTransport()`.
fn generate_ipc_transport(out: &mut String, modules: &[ApiModule], config: &Config) {
    let pp_trailing = ts_trailing_prefix_param(config);
    let pp_only = ts_prefix_param_only(config);
    let ipc_arg = ts_ipc_prefix_arg(config);
    let ipc_arg_only = ts_ipc_prefix_arg_only(config);

    out.push_str(
        "// ── IPC Transport ──\n\n\
         export function createIpcTransport(): Transport {\n\
         \x20 return {\n",
    );

    for m in modules {
        if m.functions.is_empty() {
            continue;
        }
        let module = &m.name;

        for f in &m.functions {
            let op = classify_op(m, f);
            let cmd_name = command_name(module, f, config);
            if cmd_name.is_empty() || config.ts_skip_commands.contains(&cmd_name) {
                continue;
            }

            let camel = snake_to_camel(&cmd_name);
            let ts_ret = config.ts_type(&f.return_type);
            let returns_unit = f.return_type == "()";
            let ret_str = if returns_unit { "null".to_string() } else { ts_ret.clone() };
            // The Rust IPC command name (snake_case)
            let invoke_name = &cmd_name;

            match op {
                OpKind::List => {
                    // The interface's signature, so the IPC half cannot drift
                    // from it. Its arguments are the Tauri command's (servers'
                    // ipc.rs): the `*Query` struct as `query`, each bare
                    // filter under the key Tauri derives from its name.
                    let method = jsonapi::method(m, f, config, None).expect("a list is not an event op");
                    let mut invoke_args: Vec<String> =
                        f.bare_filters().into_iter().map(|p| invoke_arg(&p.name)).collect();
                    if f.filter_struct().is_some() {
                        // A required `query` is always sent; an optional one
                        // defaults to the empty filter the command reads.
                        invoke_args.push(
                            if jsonapi::query_required(f, config) { "query" } else { "query: query ?? {}" }.to_string(),
                        );
                    }
                    // An absent `sort` is dropped from the invoke payload,
                    // which the command reads as `None`.
                    if method.options.is_some() {
                        invoke_args.push("sort: options?.sort".to_string());
                    }
                    if jsonapi::is_paginated(m, f, config) {
                        invoke_args.push("limit: limit ?? null".to_string());
                        invoke_args.push("offset: offset ?? null".to_string());
                    }
                    if !ipc_arg_only.is_empty() {
                        invoke_args.push(ipc_arg_only.clone());
                    }
                    let invoke = if invoke_args.is_empty() {
                        format!("invoke('{invoke_name}')")
                    } else {
                        format!("invoke('{invoke_name}', {{ {} }})", invoke_args.join(", "))
                    };
                    out.push_str(&format!(
                        "    async {camel}({}): Promise<{}> {{\n\
                         \x20     return {invoke};\n\
                         \x20   }},\n",
                        method.signature(ts_prefix_param(config)),
                        method.return_type,
                    ));
                }
                OpKind::GetById => {
                    out.push_str(&format!(
                        "    async {}(id: string{pp_trailing}): Promise<{}> {{\n\
                         \x20     return invoke('{invoke_name}', {{ id{ipc_arg} }});\n\
                         \x20   }},\n",
                        camel, ret_str,
                    ));
                }
                OpKind::Create => {
                    let input_type = config.ts_type(&f.params[0].ty);
                    out.push_str(&format!(
                        "    async {}(input: {}{pp_trailing}): Promise<{}> {{\n\
                         \x20     return invoke('{invoke_name}', {{ input{ipc_arg} }});\n\
                         \x20   }},\n",
                        camel, input_type, ret_str,
                    ));
                }
                OpKind::Update => {
                    let input_type = config.ts_type(&f.params[1].ty);
                    out.push_str(&format!(
                        "    async {}(id: string, input: {}{pp_trailing}): Promise<{}> {{\n\
                         \x20     return invoke('{invoke_name}', {{ id, input{ipc_arg} }});\n\
                         \x20   }},\n",
                        camel, input_type, ret_str,
                    ));
                }
                OpKind::Delete => {
                    out.push_str(&format!(
                        "    async {}(id: string{pp_trailing}): Promise<null> {{\n\
                         \x20     await invoke('{invoke_name}', {{ id{ipc_arg} }});\n\
                         \x20     return null;\n\
                         \x20   }},\n",
                        camel,
                    ));
                }
                OpKind::JunctionList { .. } => {
                    // JunctionList IPC mirrors the HTTP paginated variant:
                    // when pagination is enabled and the return is Vec<T>,
                    // accept limit/offset and invoke with those args; the
                    // Rust handler returns PaginatedResult<T>.
                    let paginated =
                        config.pagination_for(&m.name, f.surface).is_some() && f.return_type.starts_with("Vec<");
                    let return_type = if paginated {
                        let item_type = ret_str.strip_suffix("[]").unwrap_or(ret_str.as_str());
                        format!("PaginatedResult<{}>", item_type)
                    } else {
                        ret_str.clone()
                    };
                    let parent = &f.params[0].name;
                    let mut params = vec![format!("{}: string", ts_param(parent))];
                    let mut invoke_args = vec![invoke_arg(parent)];
                    if paginated {
                        params.push("limit?: number".to_string());
                        params.push("offset?: number".to_string());
                        invoke_args.push("limit: limit ?? null".to_string());
                        invoke_args.push("offset: offset ?? null".to_string());
                    }
                    if !pp_only.is_empty() {
                        params.push(pp_only.clone());
                    }
                    if !ipc_arg_only.is_empty() {
                        invoke_args.push(ipc_arg_only.clone());
                    }
                    let params_str = params.join(", ");
                    let args_str = invoke_args.join(", ");
                    out.push_str(&format!(
                        "    async {camel}({params_str}): Promise<{return_type}> {{\n\
                         \x20     return invoke('{invoke_name}', {{ {args_str} }});\n\
                         \x20   }},\n",
                    ));
                }
                // A junction add or remove resolves to `null` whatever the fn
                // returns, as the `Transport` interface and the HTTP route
                // (`204`) have it.
                OpKind::JunctionAdd { .. } | OpKind::JunctionRemove { .. } => {
                    generate_ipc_custom_method(out, f, &cmd_name, config, true);
                }
                OpKind::CustomGet | OpKind::CustomPost => {
                    generate_ipc_custom_method(out, f, &cmd_name, config, false);
                }
                OpKind::EventStream => continue,
            }
        }
    }

    // Event subscriptions over a per-subscriber Channel
    for m in modules {
        for ev in &m.events {
            generate_ipc_subscribe_method(out, ev, config);
        }
    }

    // Legacy global listeners via Tauri listen (parameterless sync ops only)
    for m in modules {
        for ev in m.events.iter().filter(|ev| ev.is_legacy()) {
            let camel = snake_to_camel(&ev.name);
            let ev_name = ev.name.replace('_', "-");

            // Accept _projectId to match Transport interface, even though
            // Tauri listen is not project-scoped (IPC events are global).
            let ipc_pp = if pp_trailing.is_empty() { String::new() } else { pp_trailing.replace(", ", ", _") };
            out.push_str(&format!(
                "    async on{cap}(callback: (payload: unknown) => void{ipc_pp}): Promise<() => void> {{\n\
                 \x20     const unlisten = await listen('{ev_name}', (event: {{ payload: unknown }}) => {{\n\
                 \x20       callback(event.payload);\n\
                 \x20     }});\n\
                 \x20     return unlisten;\n\
                 \x20   }},\n",
                cap = capitalize_first(&camel),
            ));
        }
    }

    out.push_str("  };\n");
    out.push_str("}\n");
}

/// Handler and frame types shared by every `subscribeX` method.
const SUBSCRIPTION_TYPES: &str = "\
// ── Event Subscriptions ──

export interface SubscriptionHandlers<T> {
  /** An event. `id` is its resume id, or null for an op that is not resumable. */
  onEvent: (data: T, id: string | null) => void;
  /** The subscription fell behind and `skipped` events were dropped. */
  onLag?: (skipped: number) => void;
  /** Fires on the first connect and on every reconnect: the hook for a catch-up read. */
  onOpen?: () => void;
  onError?: (err: unknown) => void;
}

type EventFrame<T> = { kind: 'event'; id: string | null; data: T } | { kind: 'lag'; skipped: number };

";

/// The SSE subscription loop shared by every HTTP `subscribeX` method.
/// `decode` turns a parsed frame into the item the handlers receive.
///
/// Every error closes the `EventSource` and reconnects after a capped
/// exponential backoff with jitter; the reconnect passes the last seen id as
/// the `resume` query param (a new `EventSource` sends no `Last-Event-ID`).
const SSE_SUBSCRIBE_HELPER: &str = "\
const SSE_RETRY_BASE_MS = 500;
const SSE_RETRY_MAX_MS = 30000;

function subscribeSse<T>(
  url: (resume: string | null) => string,
  eventName: string,
  initialResume: string | null,
  decode: (frame: unknown) => T,
  handlers: SubscriptionHandlers<T>,
): () => void {
  let source: globalThis.EventSource | null = null;
  let timer: ReturnType<typeof setTimeout> | null = null;
  let lastId = initialResume;
  let attempt = 0;
  let closed = false;
  function connect() {
    if (closed) return;
    const es = new globalThis.EventSource(url(lastId));
    source = es;
    es.onopen = () => {
      attempt = 0;
      handlers.onOpen?.();
    };
    es.addEventListener(eventName, (event: globalThis.MessageEvent) => {
      const id = event.lastEventId || null;
      if (id) lastId = id;
      let data: T;
      try {
        data = decode(JSON.parse(event.data));
      } catch (err) {
        handlers.onError?.(err);
        return;
      }
      handlers.onEvent(data, id);
    });
    es.addEventListener('lag', (event: globalThis.MessageEvent) => {
      try {
        handlers.onLag?.(JSON.parse(event.data).skipped);
      } catch (err) {
        handlers.onError?.(err);
      }
    });
    es.onerror = (err: globalThis.Event) => {
      es.close();
      if (source === es) source = null;
      if (closed) return;
      handlers.onError?.(err);
      const delay = Math.min(SSE_RETRY_MAX_MS, SSE_RETRY_BASE_MS * 2 ** attempt);
      attempt += 1;
      timer = setTimeout(connect, delay / 2 + Math.random() * (delay / 2));
    };
  }
  connect();
  return () => {
    closed = true;
    if (timer) clearTimeout(timer);
    source?.close();
    source = null;
  };
}

";

/// The Channel subscription shared by every IPC `subscribeX` method.
const IPC_SUBSCRIBE_HELPER: &str = "\
// ── IPC Helpers ──

async function subscribeIpc<T>(
  command: string,
  unsubscribeCommand: string,
  args: Record<string, unknown>,
  handlers: SubscriptionHandlers<T>,
): Promise<() => void> {
  const channel = new IpcChannel<EventFrame<T>>();
  channel.onmessage = (frame) => {
    if (frame.kind === 'event') handlers.onEvent(frame.data, frame.id ?? null);
    else handlers.onLag?.(frame.skipped);
  };
  const id = await invoke<number>(command, { ...args, channel });
  handlers.onOpen?.();
  return () => {
    invoke(unsubscribeCommand, { id }).catch((err: unknown) => handlers.onError?.(err));
  };
}

";

/// `subscribeVaultNoteChanges`.
fn subscribe_method_name(ev: &EventFn) -> String {
    format!("subscribe{}", capitalize_first(&snake_to_camel(&ev.name)))
}

/// The `args` object type: required params required, `Option` params
/// optional, plus the route-prefix param when one is configured.
fn subscribe_args_type(ev: &EventFn, config: &Config) -> String {
    let mut fields: Vec<String> = ev
        .params
        .iter()
        .map(|p| {
            let ts = config.ts_type(&p.ty);
            let optional = if p.ty.starts_with("Option<") { "?" } else { "" };
            format!("{}{optional}: {ts}", ts_key(&ipc_arg_key(&p.name)))
        })
        .collect();
    let pp_only = ts_prefix_param_only(config);
    if !pp_only.is_empty() {
        fields.push(pp_only);
    }
    if fields.is_empty() { "Record<string, never>".to_string() } else { format!("{{ {} }}", fields.join("; ")) }
}

/// The subscription argument carrying the event op parameter `param`, which
/// [`subscribe_args_type`] names by its IPC key: `args.parentId`.
fn event_arg(param: &str) -> String {
    let key = ipc_arg_key(param);
    let member = ts_key(&key);
    if member == key { format!("args.{key}") } else { format!("args[{member}]") }
}

/// `subscribeX(args: {...}, handlers: SubscriptionHandlers<T>): Promise<() => void>`.
fn subscribe_signature(ev: &EventFn, config: &Config) -> String {
    format!(
        "{}(args: {}, handlers: SubscriptionHandlers<{}>): Promise<() => void>",
        subscribe_method_name(ev),
        subscribe_args_type(ev, config),
        config.ts_type(&ev.item_type),
    )
}

/// The HTTP `subscribeX`: builds the SSE URL from the args (path params
/// interpolated, optional params and `resume` on the query string) and hands
/// it to `subscribeSse` with the item's frame decoder.
fn generate_http_subscribe_method(out: &mut String, ev: &EventFn, config: &Config) {
    let route = ev.sse_route(&config.sse_route_overrides);
    let route = route.strip_prefix("/api").unwrap_or(&route);
    let template = route
        .split('/')
        .map(|seg| match seg.strip_prefix(':') {
            Some(name) => format!("${{encodeURIComponent(String({}))}}", event_arg(name)),
            None => seg.to_string(),
        })
        .collect::<Vec<_>>()
        .join("/");
    let path_expr = match &config.route_prefix {
        Some(prefix) => format!("scopedPath(args.{}, `{template}`)", ts_param(&prefix.params[0].name)),
        None => format!("`{template}`"),
    };
    let query: Vec<String> = ev
        .query_params()
        .iter()
        .map(|p| {
            if is_resume_param(p) {
                format!("{}: resume", member_name(&p.name))
            } else {
                format!("{}: {}", member_name(&p.name), event_arg(&p.name))
            }
        })
        .collect();
    let query_expr =
        if query.is_empty() { String::new() } else { format!(" + toQueryString({{ {} }})", query.join(", ")) };
    let resume_arg = if query.is_empty() || !ev.is_resumable() { "_resume" } else { "resume" };
    let initial = if ev.is_resumable() { "args.resume ?? null" } else { "null" };
    out.push_str(&format!(
        "    async {sig} {{\n\
         \x20     return subscribeSse(\n\
         \x20       ({resume_arg}) => `${{BASE}}${{{path_expr}}}`{query_expr},\n\
         \x20       '{ev_name}',\n\
         \x20       {initial},\n\
         \x20       (frame) => {decode},\n\
         \x20       handlers,\n\
         \x20     );\n\
         \x20   }},\n",
        sig = subscribe_signature(ev, config),
        ev_name = event_name(&ev.name),
        decode = jsonapi::decode_event_frame(ev, config, "frame"),
    ));
}

/// The IPC `subscribeX`: calls `{fn}_subscribe` with the args and a new
/// `Channel`; the returned function calls `{fn}_unsubscribe`. The route
/// prefix is not sent: IPC subscriptions are not project-scoped.
fn generate_ipc_subscribe_method(out: &mut String, ev: &EventFn, config: &Config) {
    let args: Vec<String> = ev
        .params
        .iter()
        .map(|p| {
            let value = event_arg(&p.name);
            let value = if p.ty.starts_with("Option<") { format!("{value} ?? null") } else { value };
            invoke_member(&p.name, &value)
        })
        .collect();
    // With no params the args object is unused (the route prefix is not sent).
    let (sig, args_obj) = if args.is_empty() {
        (subscribe_signature(ev, config).replacen("(args:", "(_args:", 1), "{}".to_string())
    } else {
        (subscribe_signature(ev, config), format!("{{ {} }}", args.join(", ")))
    };
    out.push_str(&format!(
        "    async {sig} {{\n\
         \x20     return subscribeIpc('{fn_name}_subscribe', '{fn_name}_unsubscribe', {args_obj}, handlers);\n\
         \x20   }},\n",
        fn_name = ev.name,
    ));
}

/// Generate a custom IPC method.
fn generate_ipc_custom_method(
    out: &mut String,
    f: &crate::servers::parse::ApiFn,
    cmd_name: &str,
    config: &Config,
    resolves_null: bool,
) {
    let camel = snake_to_camel(cmd_name);
    let ts_ret = config.ts_type(&f.return_type);
    let returns_unit = resolves_null || f.return_type == "()";
    let ret_str = if returns_unit { "null".to_string() } else { ts_ret.clone() };
    let pp_only = ts_prefix_param_only(config);
    let ipc_arg = ts_ipc_prefix_arg(config);

    let has_params = !f.params.is_empty();
    let has_prefix = !pp_only.is_empty();

    if !has_params && !has_prefix {
        if returns_unit {
            out.push_str(&format!(
                "    async {camel}(): Promise<null> {{\n\
                 \x20     await invoke('{cmd_name}');\n\
                 \x20     return null;\n\
                 \x20   }},\n",
            ));
        } else {
            out.push_str(&format!(
                "    async {camel}(): Promise<{ret_str}> {{\n\
                 \x20     return invoke('{cmd_name}');\n\
                 \x20   }},\n",
            ));
        }
    } else {
        // Build param list and invoke args
        // `rust_type_to_ts` already maps `Option<T>` to `T | null`, matching
        // the Transport interface signature built by `build_ts_params`.
        let mut ts_params: Vec<String> =
            f.params.iter().map(|p| format!("{}: {}", ts_param(&p.name), config.ts_type(&p.ty))).collect();
        if has_prefix {
            ts_params.push(pp_only.clone());
        }
        let params_str = ts_params.join(", ");

        let invoke_args: Vec<String> = f.params.iter().map(|p| invoke_arg(&p.name)).collect();
        let ipc_arg_only = ts_ipc_prefix_arg_only(config);
        let args_str = if invoke_args.is_empty() && !ipc_arg_only.is_empty() {
            format!("{{ {ipc_arg_only} }}")
        } else {
            format!("{{ {}{ipc_arg} }}", invoke_args.join(", "))
        };

        if returns_unit {
            out.push_str(&format!(
                "    async {camel}({params_str}): Promise<null> {{\n\
                 \x20     await invoke('{cmd_name}', {args_str});\n\
                 \x20     return null;\n\
                 \x20   }},\n",
            ));
        } else {
            out.push_str(&format!(
                "    async {camel}({params_str}): Promise<{ret_str}> {{\n\
                 \x20     return invoke('{cmd_name}', {args_str});\n\
                 \x20   }},\n",
            ));
        }
    }
}

/// Capitalize the first character of a string.
fn capitalize_first(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        None => String::new(),
        Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
    }
}
