//! Generate the Store layer: CRUD methods with lifecycle hooks, Update structs,
//! From impls, and populate_relations helpers.
//!
//! For each entity, generates a `store/generated/{entity}.rs` containing:
//! - `{Entity}Update` struct with `apply()` method
//! - `From<Create{Entity}Input> for {Entity}` impl
//! - `From<Update{Entity}Input> for {Entity}Update` impl
//! - `impl Store` block with list, get, create, update, delete (all calling hooks)
//! - `populate_{entity}_relations()` for entities with junction/has_many fields
//!
//! Also scaffolds `store/hooks/{entity}.rs` with no-op lifecycle hook functions:
//! - `before_create`, `after_create`, `before_update`, `after_update`,
//!   `before_delete`, `after_delete`
//!
//! Hook files are written once and never overwritten — fill in your custom logic.

mod gen_crud;
mod gen_hooks;
mod gen_update;
pub(crate) mod helpers;
#[cfg(test)]
mod tests;

use std::fs;

use crate::ir::{CrudOp, ScaffoldMeta, Source, StoreMethodKind, StoreMethodMeta, StoreOutput};
use crate::schema::model::EntityDef;
use crate::{CodegenError, SeaOrmOutput, StoreConfig};

// ─── Public API ──────────────────────────────────────────────────────────────

/// Generate store layer code for the given entities.
///
/// Writes generated CRUD files to `config.output_dir` and scaffolds hook files
/// in `config.hooks_dir`. Returns `StoreOutput` metadata for downstream
/// generators (gen_api, gen_servers).
pub fn generate(
    entities: &[EntityDef],
    _seaorm: Option<&SeaOrmOutput>,
    config: &StoreConfig,
) -> Result<StoreOutput, CodegenError> {
    let output_dir = &config.output_dir;
    fs::create_dir_all(output_dir)
        .map_err(|e| CodegenError::Store(format!("Failed to create {}: {e}", output_dir.display())))?;

    // Clean stale files from previous entity names
    let expected: std::collections::HashSet<String> = entities
        .iter()
        .map(|e| format!("{}.rs", helpers::to_snake_case(&e.name)))
        .chain(std::iter::once("mod.rs".to_string()))
        .collect();
    crate::clean_generated_dir(output_dir, &expected);

    let mut all_methods: Vec<StoreMethodMeta> = Vec::new();
    let mut mod_names: Vec<String> = Vec::new();

    for entity in entities {
        let snake = helpers::to_snake_case(&entity.name);

        // Generate the entity's store module
        let code = generate_entity_store(entity);

        let path = output_dir.join(format!("{snake}.rs"));
        crate::write_and_format(&path, &code)?;

        // Collect method metadata for downstream consumers
        let methods = collect_method_meta(entity);
        all_methods.extend(methods);
        mod_names.push(snake);
    }

    // Write mod.rs
    mod_names.sort();
    let mod_rs = generate_mod_rs(&mod_names);
    let path = output_dir.join("mod.rs");
    crate::write_and_format(&path, &mod_rs)?;

    // Scaffold hook files (only creates files that don't exist yet)
    let mut scaffolded_hooks = Vec::new();
    if let Some(hooks_dir) = &config.hooks_dir {
        let created = gen_hooks::scaffold_hooks(entities, hooks_dir).map_err(CodegenError::Store)?;

        for entity in entities {
            let snake = helpers::to_snake_case(&entity.name);
            let was_created = created.contains(&snake);
            if was_created {
                scaffolded_hooks.push(ScaffoldMeta {
                    entity_name: entity.name.clone(),
                    file_path: hooks_dir.join(format!("{snake}.rs")),
                    functions: vec![
                        "before_create".into(),
                        "after_create".into(),
                        "before_update".into(),
                        "after_update".into(),
                        "before_delete".into(),
                        "after_delete".into(),
                    ],
                });
            }
        }
    }

    Ok(StoreOutput { methods: all_methods, scaffolded_hooks, change_channels: Vec::new() })
}

// ─── Per-entity generation ───────────────────────────────────────────────────

/// Generate the complete store module source for one entity.
fn generate_entity_store(entity: &EntityDef) -> String {
    let snake = helpers::to_snake_case(&entity.name);
    let mut code = String::with_capacity(4096);

    code.push_str("//! Generated by ontogen. DO NOT EDIT.\n\n");
    code.push_str("use sea_orm::{ActiveModelTrait, EntityTrait, QuerySelect};\n\n");

    // Additional imports for entities with has_many relations
    if entity.has_many_relations().next().is_some() {
        code.push_str("use sea_orm::{ColumnTrait, QueryFilter};\n");
    }

    // Imports (sorted alphabetically for rustfmt compliance)
    code.push_str(&format!("use crate::persistence::db::entities::{snake};\n"));
    code.push_str(&format!("use crate::schema::{};\n", entity.name));
    code.push_str("use crate::schema::{AppError, ChangeOp, EntityKind};\n\n");
    code.push_str(&format!("use crate::store::hooks::{snake} as hooks;\n"));
    code.push_str("use crate::store::Store;\n\n");

    // Update struct + apply + From impls
    gen_update::generate_update_struct(&mut code, entity);
    gen_update::generate_apply_method(&mut code, entity);
    gen_update::generate_from_update_input(&mut code, entity);
    gen_update::generate_from_create_input(&mut code, entity);

    // CRUD impl block (with hook calls)
    gen_crud::generate_crud_impl(&mut code, entity);

    code
}

// ─── Metadata collection ─────────────────────────────────────────────────────

/// Collect StoreMethodMeta for all generated CRUD methods on this entity.
fn collect_method_meta(entity: &EntityDef) -> Vec<StoreMethodMeta> {
    let snake = helpers::to_snake_case(&entity.name);
    let plural = helpers::pluralize(&snake);
    let source = Source::Generated { module_path: format!("crate::store::generated::{snake}") };

    vec![
        StoreMethodMeta {
            entity_name: entity.name.clone(),
            name: format!("list_{plural}"),
            kind: StoreMethodKind::Crud(CrudOp::List),
            params: vec![],
            return_type: format!("Vec<{}>", entity.name),
            source: source.clone(),
        },
        StoreMethodMeta {
            entity_name: entity.name.clone(),
            name: format!("get_{snake}"),
            kind: StoreMethodKind::Crud(CrudOp::Get),
            params: vec![],
            return_type: entity.name.clone(),
            source: source.clone(),
        },
        StoreMethodMeta {
            entity_name: entity.name.clone(),
            name: format!("create_{snake}"),
            kind: StoreMethodKind::Crud(CrudOp::Create),
            params: vec![],
            return_type: entity.name.clone(),
            source: source.clone(),
        },
        StoreMethodMeta {
            entity_name: entity.name.clone(),
            name: format!("update_{snake}"),
            kind: StoreMethodKind::Crud(CrudOp::Update),
            params: vec![],
            return_type: entity.name.clone(),
            source: source.clone(),
        },
        StoreMethodMeta {
            entity_name: entity.name.clone(),
            name: format!("delete_{snake}"),
            kind: StoreMethodKind::Crud(CrudOp::Delete),
            params: vec![],
            return_type: "()".to_string(),
            source,
        },
    ]
}

// ─── mod.rs generation ───────────────────────────────────────────────────────

fn generate_mod_rs(mod_names: &[String]) -> String {
    let mut code = String::new();
    code.push_str("//! Generated by ontogen. DO NOT EDIT.\n\n");
    for name in mod_names {
        code.push_str(&format!("pub mod {name};\n"));
    }
    code
}
