#![allow(dead_code, unused_imports, clippy::pedantic, clippy::needless_borrow)]
//! Auto-generated HTTP route handlers. DO NOT EDIT.
//!
//! Generated by ontogen from API source files.

use std::sync::Arc;

use axum::{
    Router,
    extract::{RawQuery, State},
    http::{Method, StatusCode},
    response::Response,
    routing::get,
};
use ontogen_jsonapi::{
    Document, ErrorCode, ErrorObject, Linkage, Links, LookupKey, QueryParams, QuerySpec, Relationship,
    ResourceIdentifier, ResourceObject,
    error::{method_not_allowed, relationship_not_found, relationship_update_unsupported},
    extract::{AcceptGuard, Body, NoParams, Path, Query, RouteQuery},
    links::encode_path_segment,
    request::{self, Endpoint, LinkedId, ResourceData},
    response,
};
use serde::Serialize;

use crate::AppState;
use crate::api::v1::{exercise, tag, workout, workout_set};
use crate::schema::{
    CreateExerciseInput, CreateTagInput, CreateWorkoutInput, CreateWorkoutSetInput, Exercise, Tag, UpdateExerciseInput,
    UpdateTagInput, UpdateWorkoutInput, UpdateWorkoutSetInput, Workout, WorkoutSet,
};

/// An `AppError` as an error object: the status its variant's name gives,
/// and the name in snake_case as the code.
fn ontogen_app_error(e: crate::schema::AppError) -> ErrorObject {
    let (status, code) = match &e {
        crate::schema::AppError::ExerciseNotFound(..) => (StatusCode::NOT_FOUND, "exercise_not_found"),
        crate::schema::AppError::ExerciseIdRequired(..) => (StatusCode::BAD_REQUEST, "exercise_id_required"),
        crate::schema::AppError::ExerciseAlreadyExists(..) => (StatusCode::CONFLICT, "exercise_already_exists"),
        crate::schema::AppError::WorkoutNotFound(..) => (StatusCode::NOT_FOUND, "workout_not_found"),
        crate::schema::AppError::WorkoutIdRequired(..) => (StatusCode::BAD_REQUEST, "workout_id_required"),
        crate::schema::AppError::WorkoutAlreadyExists(..) => (StatusCode::CONFLICT, "workout_already_exists"),
        crate::schema::AppError::WorkoutSetNotFound(..) => (StatusCode::NOT_FOUND, "workout_set_not_found"),
        crate::schema::AppError::WorkoutSetIdRequired(..) => (StatusCode::BAD_REQUEST, "workout_set_id_required"),
        crate::schema::AppError::WorkoutSetAlreadyExists(..) => (StatusCode::CONFLICT, "workout_set_already_exists"),
        crate::schema::AppError::TagNotFound(..) => (StatusCode::NOT_FOUND, "tag_not_found"),
        crate::schema::AppError::TagIdRequired(..) => (StatusCode::BAD_REQUEST, "tag_id_required"),
        crate::schema::AppError::TagAlreadyExists(..) => (StatusCode::CONFLICT, "tag_already_exists"),
        crate::schema::AppError::Md(..) => (StatusCode::INTERNAL_SERVER_ERROR, "md"),
    };
    ErrorObject::app(status, code, e.to_string())
}

/// A failure no `AppError` describes: opening the store, a scope accessor,
/// or an op with another error type.
fn ontogen_internal_error(e: impl std::fmt::Display) -> ErrorObject {
    ErrorObject::internal(e.to_string())
}

/// The method fallback of a route serving `allowed`: `405` with `Allow`.
fn allow<const N: usize>(
    allowed: [Method; N],
) -> impl Fn(Method) -> std::future::Ready<Response> + Clone + Send + Sync + 'static {
    move |method| std::future::ready(method_not_allowed(&method, &allowed))
}

/// `ids` with each id of `linked` it lacks appended, or `None` when it lacks
/// none: a relationship `POST` that adds nothing writes nothing.
fn ontogen_added(ids: &[String], linked: &[LinkedId]) -> Option<Vec<String>> {
    let added: Vec<String> = linked.iter().map(|l| l.id.clone()).filter(|id| !ids.contains(id)).collect();
    (!added.is_empty()).then(|| [ids, added.as_slice()].concat())
}

/// `ids` without the ids of `linked`, or `None` when it holds none of them: a
/// relationship `DELETE` that removes nothing writes nothing.
fn ontogen_removed(ids: &[String], linked: &[LinkedId]) -> Option<Vec<String>> {
    let kept: Vec<String> = ids.iter().filter(|id| !linked.iter().any(|l| l.id == **id)).cloned().collect();
    (kept.len() != ids.len()).then_some(kept)
}

// ── JSON:API resources ──

struct ListParams;

impl RouteQuery for ListParams {
    const SPEC: QuerySpec = QuerySpec { sort: true, include: true, ..QuerySpec::NONE };
}

struct PagedListParams;

impl RouteQuery for PagedListParams {
    const SPEC: QuerySpec = QuerySpec { sort: true, include: true, page: true, ..QuerySpec::NONE };
}

struct GetParams;

impl RouteQuery for GetParams {
    const SPEC: QuerySpec = QuerySpec { include: true, ..QuerySpec::NONE };
}

/// No list takes an `order` argument, so every `sort` asks for an order the
/// server does not support.
fn refuse_sort(query: &QueryParams, type_name: &str) -> Result<(), ErrorObject> {
    match query.sort()? {
        None => Ok(()),
        Some(_) => Err(ErrorObject::new(ErrorCode::InvalidSortField, format!("`{type_name}` cannot be sorted"))
            .with_parameter("sort")),
    }
}

/// No route includes related resources, so every `include` names a path the
/// server cannot include.
fn refuse_include(query: &QueryParams, type_name: &str) -> Result<(), ErrorObject> {
    match query.include()? {
        None => Ok(()),
        Some(_) => Err(ErrorObject::new(
            ErrorCode::InvalidIncludePath,
            format!("`{type_name}` has no relationship that can be included"),
        )
        .with_parameter("include")),
    }
}

/// The effective `(offset, limit)` of a paginated list.
fn page(query: &QueryParams, default_limit: u32, max_limit: u32) -> Result<(u32, u32), ErrorObject> {
    let offset = query.page_offset()?.unwrap_or(0);
    let limit = query.page_limit()?.unwrap_or(default_limit).min(max_limit);
    Ok((offset, limit))
}

/// Sets `name` when the request document carried it.
fn set_field(fields: &mut serde_json::Map<String, serde_json::Value>, name: &str, value: Option<&serde_json::Value>) {
    if let Some(value) = value {
        fields.insert(name.to_owned(), value.clone());
    }
}

/// A create or update input from the fields its request document set. Each
/// field was checked against its type, so a failure here is the server's.
fn from_fields<T: serde::de::DeserializeOwned>(
    fields: serde_json::Map<String, serde_json::Value>,
) -> Result<T, ErrorObject> {
    serde_json::from_value(serde_json::Value::Object(fields)).map_err(ontogen_internal_error)
}

// ── `exercises` ──

/// `Exercise`'s attributes: every field but the id and the relations, in
/// declaration order.
struct ExerciseResourceAttributes<'a>(&'a Exercise);

impl Serialize for ExerciseResourceAttributes<'_> {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        use serde::ser::SerializeStruct;
        let mut attributes = serializer.serialize_struct("ExerciseResourceAttributes", 4)?;
        attributes.serialize_field("name", &self.0.name)?;
        attributes.serialize_field("muscle_group", &self.0.muscle_group)?;
        attributes.serialize_field("equipment", &self.0.equipment)?;
        attributes.serialize_field("notes", &self.0.notes)?;
        attributes.end()
    }
}

/// `entity` as a resource object of type `exercises`, its `links.self`
/// under `collection`.
fn exercise_as_resource<'a>(entity: &'a Exercise, collection: &str) -> ResourceObject<ExerciseResourceAttributes<'a>> {
    let self_link = format!("{collection}/{}", encode_path_segment(&entity.id));
    ResourceObject::new("exercises", entity.id.clone(), ExerciseResourceAttributes(entity), self_link)
}

/// The id an `{id}` path segment names.
fn exercise_lookup_key(id: &LookupKey) -> Result<&str, ErrorObject> {
    id.as_str().ok_or_else(|| ontogen_app_error(crate::schema::AppError::ExerciseNotFound(id.to_string())))
}

/// The fields a create or update document for `exercises` sets, named as
/// the input's fields, each member checked against the schema.
fn exercise_request_fields(
    data: &ResourceData,
    create: bool,
) -> Result<serde_json::Map<String, serde_json::Value>, ErrorObject> {
    let attributes = data.attributes.as_ref();
    request::check_attribute_names(attributes, "exercises", &["name", "muscle_group", "equipment", "notes"], &[])?;
    let mut fields = serde_json::Map::new();
    if create {
        fields.insert("id".to_owned(), serde_json::Value::String(data.id.clone().unwrap_or_default()));
    }
    set_field(&mut fields, "name", request::attribute::<String>(attributes, "name", create)?);
    set_field(&mut fields, "muscle_group", request::attribute::<String>(attributes, "muscle_group", create)?);
    set_field(&mut fields, "equipment", request::attribute::<String>(attributes, "equipment", create)?);
    set_field(&mut fields, "notes", request::attribute::<Option<String>>(attributes, "notes", false)?);
    request::check_relationship_names(data.relationships()?, "exercises", &[])?;
    Ok(fields)
}

// ── `tags` ──

/// `Tag`'s attributes: every field but the id and the relations, in
/// declaration order.
struct TagResourceAttributes<'a>(&'a Tag);

impl Serialize for TagResourceAttributes<'_> {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        use serde::ser::SerializeStruct;
        let mut attributes = serializer.serialize_struct("TagResourceAttributes", 1)?;
        attributes.serialize_field("name", &self.0.name)?;
        attributes.end()
    }
}

/// `entity` as a resource object of type `tags`, its `links.self`
/// under `collection`.
fn tag_as_resource<'a>(entity: &'a Tag, collection: &str) -> ResourceObject<TagResourceAttributes<'a>> {
    let self_link = format!("{collection}/{}", encode_path_segment(&entity.id));
    ResourceObject::new("tags", entity.id.clone(), TagResourceAttributes(entity), self_link)
}

/// The id an `{id}` path segment names.
fn tag_lookup_key(id: &LookupKey) -> Result<&str, ErrorObject> {
    id.as_str().ok_or_else(|| ontogen_app_error(crate::schema::AppError::TagNotFound(id.to_string())))
}

/// The fields a create or update document for `tags` sets, named as
/// the input's fields, each member checked against the schema.
fn tag_request_fields(
    data: &ResourceData,
    create: bool,
) -> Result<serde_json::Map<String, serde_json::Value>, ErrorObject> {
    let attributes = data.attributes.as_ref();
    request::check_attribute_names(attributes, "tags", &["name"], &[])?;
    let mut fields = serde_json::Map::new();
    if create {
        fields.insert("id".to_owned(), serde_json::Value::String(data.id.clone().unwrap_or_default()));
    }
    set_field(&mut fields, "name", request::attribute::<String>(attributes, "name", create)?);
    request::check_relationship_names(data.relationships()?, "tags", &[])?;
    Ok(fields)
}

// ── `workouts` ──

/// `Workout`'s attributes: every field but the id and the relations, in
/// declaration order.
struct WorkoutResourceAttributes<'a>(&'a Workout);

impl Serialize for WorkoutResourceAttributes<'_> {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        use serde::ser::SerializeStruct;
        let mut attributes = serializer.serialize_struct("WorkoutResourceAttributes", 5)?;
        attributes.serialize_field("name", &self.0.name)?;
        attributes.serialize_field("date", &self.0.date)?;
        attributes.serialize_field("duration_minutes", &self.0.duration_minutes)?;
        attributes.serialize_field("notes", &self.0.notes)?;
        attributes.serialize_field("created_at", &self.0.created_at)?;
        attributes.end()
    }
}

/// `entity` as a resource object of type `workouts`, its `links.self`
/// under `collection`.
fn workout_as_resource<'a>(entity: &'a Workout, collection: &str) -> ResourceObject<WorkoutResourceAttributes<'a>> {
    let self_link = format!("{collection}/{}", encode_path_segment(&entity.id));
    ResourceObject::new("workouts", entity.id.clone(), WorkoutResourceAttributes(entity), self_link.clone())
        .with_relationship(
            "tags",
            Relationship::new(
                Links::new(format!("{self_link}/relationships/tags")).with_related(format!("{self_link}/tags")),
                Linkage::ToMany(entity.tags.iter().map(|id| ResourceIdentifier::new("tags", id.as_str())).collect()),
            ),
        )
}

/// The id an `{id}` path segment names.
fn workout_lookup_key(id: &LookupKey) -> Result<&str, ErrorObject> {
    id.as_str().ok_or_else(|| ontogen_app_error(crate::schema::AppError::WorkoutNotFound(id.to_string())))
}

/// The ids a request document for `workouts` links, by relationship, to
/// be checked to name resources that exist.
#[derive(Default)]
struct WorkoutLinkedIds {
    tags: Vec<LinkedId>,
}

/// The fields a create or update document for `workouts` sets, named as
/// the input's fields, each member checked against the schema.
fn workout_request_fields(
    data: &ResourceData,
    create: bool,
) -> Result<(serde_json::Map<String, serde_json::Value>, WorkoutLinkedIds), ErrorObject> {
    let attributes = data.attributes.as_ref();
    request::check_attribute_names(
        attributes,
        "workouts",
        &["name", "date", "duration_minutes", "notes", "created_at"],
        &[("tags", "tags")],
    )?;
    let mut fields = serde_json::Map::new();
    if create {
        fields.insert("id".to_owned(), serde_json::Value::String(data.id.clone().unwrap_or_default()));
    }
    set_field(&mut fields, "name", request::attribute::<Option<String>>(attributes, "name", false)?);
    set_field(&mut fields, "date", request::attribute::<String>(attributes, "date", create)?);
    set_field(
        &mut fields,
        "duration_minutes",
        request::attribute::<Option<i32>>(attributes, "duration_minutes", false)?,
    );
    set_field(&mut fields, "notes", request::attribute::<Option<String>>(attributes, "notes", false)?);
    set_field(&mut fields, "created_at", request::attribute::<String>(attributes, "created_at", create)?);
    let relationships = data.relationships()?;
    request::check_relationship_names(relationships, "workouts", &["tags"])?;
    let mut linked = WorkoutLinkedIds::default();
    if let Some(rel) = relationships.and_then(|r| r.get("tags")) {
        let ids = request::to_many_linked(rel, "/data/relationships/tags", "tags", None)?;
        fields.insert("tags".to_owned(), ids.iter().map(|l| serde_json::Value::String(l.id.clone())).collect());
        linked.tags = ids;
    }
    Ok((fields, linked))
}

/// Checks that each id a create or update document for `workouts` links
/// names a resource that exists, in the order the document was read.
async fn workout_check_linked(state: &AppState, linked: &WorkoutLinkedIds) -> Result<(), ErrorObject> {
    let store = state.store().await.map_err(ontogen_internal_error)?;
    for linked in &linked.tags {
        match tag::get_by_id(&store, &linked.id).await {
            Ok(_) => {}
            Err(crate::schema::AppError::TagNotFound(..)) => return Err(linked.not_found("tags")),
            Err(e) => return Err(ontogen_app_error(e)),
        }
    }
    Ok(())
}

// ── `workout-sets` ──

/// `WorkoutSet`'s attributes: every field but the id and the relations, in
/// declaration order.
struct WorkoutSetResourceAttributes<'a>(&'a WorkoutSet);

impl Serialize for WorkoutSetResourceAttributes<'_> {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        use serde::ser::SerializeStruct;
        let mut attributes = serializer.serialize_struct("WorkoutSetResourceAttributes", 5)?;
        attributes.serialize_field("set_number", &self.0.set_number)?;
        attributes.serialize_field("weight_grams", &self.0.weight_grams)?;
        attributes.serialize_field("reps", &self.0.reps)?;
        attributes.serialize_field("rpe", &self.0.rpe)?;
        attributes.serialize_field("notes", &self.0.notes)?;
        attributes.end()
    }
}

/// `entity` as a resource object of type `workout-sets`, its `links.self`
/// under `collection`.
fn workout_set_as_resource<'a>(
    entity: &'a WorkoutSet,
    collection: &str,
) -> ResourceObject<WorkoutSetResourceAttributes<'a>> {
    let self_link = format!("{collection}/{}", encode_path_segment(&entity.id));
    ResourceObject::new("workout-sets", entity.id.clone(), WorkoutSetResourceAttributes(entity), self_link.clone())
        .with_relationship(
            "workout",
            Relationship::new(
                Links::new(format!("{self_link}/relationships/workout")).with_related(format!("{self_link}/workout")),
                Linkage::ToOne(Some(ResourceIdentifier::new("workouts", entity.workout_id.as_str()))),
            ),
        )
        .with_relationship(
            "exercise",
            Relationship::new(
                Links::new(format!("{self_link}/relationships/exercise")).with_related(format!("{self_link}/exercise")),
                Linkage::ToOne(Some(ResourceIdentifier::new("exercises", entity.exercise_id.as_str()))),
            ),
        )
}

/// The id an `{id}` path segment names.
fn workout_set_lookup_key(id: &LookupKey) -> Result<&str, ErrorObject> {
    id.as_str().ok_or_else(|| ontogen_app_error(crate::schema::AppError::WorkoutSetNotFound(id.to_string())))
}

/// The ids a request document for `workout-sets` links, by relationship, to
/// be checked to name resources that exist.
#[derive(Default)]
struct WorkoutSetLinkedIds {
    workout: Option<LinkedId>,
    exercise: Option<LinkedId>,
}

/// The fields a create or update document for `workout-sets` sets, named as
/// the input's fields, each member checked against the schema.
fn workout_set_request_fields(
    data: &ResourceData,
    create: bool,
) -> Result<(serde_json::Map<String, serde_json::Value>, WorkoutSetLinkedIds), ErrorObject> {
    let attributes = data.attributes.as_ref();
    request::check_attribute_names(
        attributes,
        "workout-sets",
        &["set_number", "weight_grams", "reps", "rpe", "notes"],
        &[("workout_id", "workout"), ("exercise_id", "exercise")],
    )?;
    let mut fields = serde_json::Map::new();
    if create {
        fields.insert("id".to_owned(), serde_json::Value::String(data.id.clone().unwrap_or_default()));
    }
    set_field(&mut fields, "set_number", request::attribute::<i32>(attributes, "set_number", create)?);
    set_field(&mut fields, "weight_grams", request::attribute::<i32>(attributes, "weight_grams", create)?);
    set_field(&mut fields, "reps", request::attribute::<i32>(attributes, "reps", create)?);
    set_field(&mut fields, "rpe", request::attribute::<Option<i32>>(attributes, "rpe", false)?);
    set_field(&mut fields, "notes", request::attribute::<Option<String>>(attributes, "notes", false)?);
    let relationships = data.relationships()?;
    request::check_relationship_names(relationships, "workout-sets", &["workout", "exercise"])?;
    let mut linked = WorkoutSetLinkedIds::default();
    match relationships.and_then(|r| r.get("workout")) {
        Some(rel) => {
            let id = request::to_one(rel, "/data/relationships/workout", "workouts", false)?;
            fields
                .insert("workout_id".to_owned(), id.clone().map_or(serde_json::Value::Null, serde_json::Value::String));
            linked.workout = id.map(|id| LinkedId { id, pointer: "/data/relationships/workout/data".to_owned() });
        }
        None if create => return Err(request::missing_relationship("workout", relationships)),
        None => {}
    }
    match relationships.and_then(|r| r.get("exercise")) {
        Some(rel) => {
            let id = request::to_one(rel, "/data/relationships/exercise", "exercises", false)?;
            fields.insert(
                "exercise_id".to_owned(),
                id.clone().map_or(serde_json::Value::Null, serde_json::Value::String),
            );
            linked.exercise = id.map(|id| LinkedId { id, pointer: "/data/relationships/exercise/data".to_owned() });
        }
        None if create => return Err(request::missing_relationship("exercise", relationships)),
        None => {}
    }
    Ok((fields, linked))
}

/// Checks that each id a create or update document for `workout-sets` links
/// names a resource that exists, in the order the document was read.
async fn workout_set_check_linked(state: &AppState, linked: &WorkoutSetLinkedIds) -> Result<(), ErrorObject> {
    let store = state.store().await.map_err(ontogen_internal_error)?;
    if let Some(linked) = &linked.workout {
        match workout::get_by_id(&store, &linked.id).await {
            Ok(_) => {}
            Err(crate::schema::AppError::WorkoutNotFound(..)) => return Err(linked.not_found("workouts")),
            Err(e) => return Err(ontogen_app_error(e)),
        }
    }
    if let Some(linked) = &linked.exercise {
        match exercise::get_by_id(&store, &linked.id).await {
            Ok(_) => {}
            Err(crate::schema::AppError::ExerciseNotFound(..)) => return Err(linked.not_found("exercises")),
            Err(e) => return Err(ontogen_app_error(e)),
        }
    }
    Ok(())
}

/// The `workouts` resource `id` names, read as its `GET` reads it: the
/// parent of a relationship route.
async fn ontogen_workout_read(state: &AppState, id: &LookupKey) -> Result<Workout, ErrorObject> {
    let store = state.store().await.map_err(ontogen_internal_error)?;
    workout::get_by_id(&store, workout_lookup_key(id)?).await.map_err(ontogen_app_error)
}

/// Sets the relation field `field` of the `workouts` resource `id` to
/// `value` through `workout::update`, as a resource `PATCH` naming only that
/// relationship does.
async fn ontogen_workout_write_field(
    state: &AppState,
    id: &str,
    field: &str,
    value: serde_json::Value,
) -> Result<(), ErrorObject> {
    let input: UpdateWorkoutInput = from_fields(serde_json::Map::from_iter([(field.to_owned(), value)]))?;
    let store = state.store().await.map_err(ontogen_internal_error)?;
    workout::update(&store, id, input).await.map_err(ontogen_app_error)?;
    Ok(())
}

/// The `tags` resources `ids` name, in order, without the ids that
/// name none.
async fn ontogen_tag_fetch(state: &AppState, ids: &[String]) -> Result<Vec<Tag>, ErrorObject> {
    let store = state.store().await.map_err(ontogen_internal_error)?;
    let mut found = Vec::with_capacity(ids.len());
    for id in ids {
        match tag::get_by_id(&store, id).await {
            Ok(entity) => found.push(entity),
            Err(crate::schema::AppError::TagNotFound(..)) => {}
            Err(e) => return Err(ontogen_app_error(e)),
        }
    }
    Ok(found)
}

/// Checks that a `tags` resource exists for each of `ids`, in order.
async fn ontogen_tag_check_ids(state: &AppState, ids: &[LinkedId]) -> Result<(), ErrorObject> {
    let store = state.store().await.map_err(ontogen_internal_error)?;
    for linked in ids {
        match tag::get_by_id(&store, &linked.id).await {
            Ok(_) => {}
            Err(crate::schema::AppError::TagNotFound(..)) => return Err(linked.not_found("tags")),
            Err(e) => return Err(ontogen_app_error(e)),
        }
    }
    Ok(())
}

/// The `workout-sets` resource `id` names, read as its `GET` reads it: the
/// parent of a relationship route.
async fn ontogen_workout_set_read(state: &AppState, id: &LookupKey) -> Result<WorkoutSet, ErrorObject> {
    let store = state.store().await.map_err(ontogen_internal_error)?;
    workout_set::get_by_id(&store, workout_set_lookup_key(id)?).await.map_err(ontogen_app_error)
}

/// Sets the relation field `field` of the `workout-sets` resource `id` to
/// `value` through `workout_set::update`, as a resource `PATCH` naming only that
/// relationship does.
async fn ontogen_workout_set_write_field(
    state: &AppState,
    id: &str,
    field: &str,
    value: serde_json::Value,
) -> Result<(), ErrorObject> {
    let input: UpdateWorkoutSetInput = from_fields(serde_json::Map::from_iter([(field.to_owned(), value)]))?;
    let store = state.store().await.map_err(ontogen_internal_error)?;
    workout_set::update(&store, id, input).await.map_err(ontogen_app_error)?;
    Ok(())
}

/// The `workouts` resources `ids` name, in order, without the ids that
/// name none.
async fn ontogen_workout_fetch(state: &AppState, ids: &[String]) -> Result<Vec<Workout>, ErrorObject> {
    let store = state.store().await.map_err(ontogen_internal_error)?;
    let mut found = Vec::with_capacity(ids.len());
    for id in ids {
        match workout::get_by_id(&store, id).await {
            Ok(entity) => found.push(entity),
            Err(crate::schema::AppError::WorkoutNotFound(..)) => {}
            Err(e) => return Err(ontogen_app_error(e)),
        }
    }
    Ok(found)
}

/// Checks that a `workouts` resource exists for each of `ids`, in order.
async fn ontogen_workout_check_ids(state: &AppState, ids: &[LinkedId]) -> Result<(), ErrorObject> {
    let store = state.store().await.map_err(ontogen_internal_error)?;
    for linked in ids {
        match workout::get_by_id(&store, &linked.id).await {
            Ok(_) => {}
            Err(crate::schema::AppError::WorkoutNotFound(..)) => return Err(linked.not_found("workouts")),
            Err(e) => return Err(ontogen_app_error(e)),
        }
    }
    Ok(())
}

/// The `exercises` resources `ids` name, in order, without the ids that
/// name none.
async fn ontogen_exercise_fetch(state: &AppState, ids: &[String]) -> Result<Vec<Exercise>, ErrorObject> {
    let store = state.store().await.map_err(ontogen_internal_error)?;
    let mut found = Vec::with_capacity(ids.len());
    for id in ids {
        match exercise::get_by_id(&store, id).await {
            Ok(entity) => found.push(entity),
            Err(crate::schema::AppError::ExerciseNotFound(..)) => {}
            Err(e) => return Err(ontogen_app_error(e)),
        }
    }
    Ok(found)
}

/// Checks that a `exercises` resource exists for each of `ids`, in order.
async fn ontogen_exercise_check_ids(state: &AppState, ids: &[LinkedId]) -> Result<(), ErrorObject> {
    let store = state.store().await.map_err(ontogen_internal_error)?;
    for linked in ids {
        match exercise::get_by_id(&store, &linked.id).await {
            Ok(_) => {}
            Err(crate::schema::AppError::ExerciseNotFound(..)) => return Err(linked.not_found("exercises")),
            Err(e) => return Err(ontogen_app_error(e)),
        }
    }
    Ok(())
}

// ── Exercise Handlers ──

async fn exercise_list(
    State(ontogen_state): State<Arc<AppState>>,
    _: AcceptGuard,
    query: Query<ListParams>,
) -> Result<Response, ErrorObject> {
    refuse_sort(&query, "exercises")?;
    refuse_include(&query, "exercises")?;
    let ontogen_store = ontogen_state.store().await.map_err(ontogen_internal_error)?;
    let items = exercise::list(&ontogen_store).await.map_err(ontogen_app_error)?;
    let collection = "/api/exercises";
    let data: Vec<_> = items.iter().map(|entity| exercise_as_resource(entity, collection)).collect();
    Ok(response::ok(&Document::new(data, Links::new(collection))))
}

async fn exercise_get_by_id(
    State(ontogen_state): State<Arc<AppState>>,
    _: AcceptGuard,
    Path(id): Path<LookupKey>,
    query: Query<GetParams>,
) -> Result<Response, ErrorObject> {
    refuse_include(&query, "exercises")?;
    let ontogen_store = ontogen_state.store().await.map_err(ontogen_internal_error)?;
    let entity = exercise::get_by_id(&ontogen_store, exercise_lookup_key(&id)?).await.map_err(ontogen_app_error)?;
    let collection = "/api/exercises";
    let resource = exercise_as_resource(&entity, collection);
    let links = Links::new(resource.links().self_link());
    Ok(response::ok(&Document::new(resource, links)))
}

async fn exercise_create(
    State(ontogen_state): State<Arc<AppState>>,
    _: AcceptGuard,
    query: Result<Query<NoParams>, ErrorObject>,
    body: Body,
) -> Result<Response, ErrorObject> {
    query?;
    let body = body.into_bytes()?;
    let collection = "/api/exercises";
    let endpoint = Endpoint { type_name: "exercises", path: collection };
    let data = request::parse_create(&body, endpoint, |id| ontogen_core::id::validate_id(id).map_err(|e| e.reason))?;
    let fields = exercise_request_fields(&data, true)?;
    let input: CreateExerciseInput = from_fields(fields)?;
    let ontogen_store = ontogen_state.store().await.map_err(ontogen_internal_error)?;
    let entity = exercise::create(&ontogen_store, input).await.map_err(|e| match e {
        e @ crate::schema::AppError::ExerciseAlreadyExists(..) if data.id.is_some() => {
            ontogen_app_error(e).with_pointer("/data/id")
        }
        e => ontogen_app_error(e),
    })?;
    let resource = exercise_as_resource(&entity, collection);
    let location = resource.links().self_link().to_owned();
    let links = Links::new(location.as_str());
    Ok(response::created(&location, &Document::new(resource, links)))
}

async fn exercise_update(
    State(ontogen_state): State<Arc<AppState>>,
    _: AcceptGuard,
    path_params: Result<Path<LookupKey>, ErrorObject>,
    query: Result<Query<NoParams>, ErrorObject>,
    body: Body,
) -> Result<Response, ErrorObject> {
    let Path(id) = path_params?;
    query?;
    let body = body.into_bytes()?;
    let collection = "/api/exercises";
    let path = format!("{collection}/{id}");
    let endpoint = Endpoint { type_name: "exercises", path: &path };
    let data = request::parse_update(&body, endpoint, &id)?;
    let fields = exercise_request_fields(&data, false)?;
    let input: UpdateExerciseInput = from_fields(fields)?;
    let ontogen_store = ontogen_state.store().await.map_err(ontogen_internal_error)?;
    let entity = exercise::update(&ontogen_store, exercise_lookup_key(&id)?, input).await.map_err(ontogen_app_error)?;
    let resource = exercise_as_resource(&entity, collection);
    let links = Links::new(resource.links().self_link());
    Ok(response::ok(&Document::new(resource, links)))
}

async fn exercise_delete(
    State(ontogen_state): State<Arc<AppState>>,
    _: AcceptGuard,
    Path(id): Path<LookupKey>,
    _: Query<NoParams>,
) -> Result<Response, ErrorObject> {
    let ontogen_store = ontogen_state.store().await.map_err(ontogen_internal_error)?;
    exercise::delete(&ontogen_store, exercise_lookup_key(&id)?).await.map_err(ontogen_app_error)?;
    Ok(response::no_content())
}

// ── Tag Handlers ──

async fn tag_list(
    State(ontogen_state): State<Arc<AppState>>,
    _: AcceptGuard,
    query: Query<ListParams>,
) -> Result<Response, ErrorObject> {
    refuse_sort(&query, "tags")?;
    refuse_include(&query, "tags")?;
    let ontogen_store = ontogen_state.store().await.map_err(ontogen_internal_error)?;
    let items = tag::list(&ontogen_store).await.map_err(ontogen_app_error)?;
    let collection = "/api/tags";
    let data: Vec<_> = items.iter().map(|entity| tag_as_resource(entity, collection)).collect();
    Ok(response::ok(&Document::new(data, Links::new(collection))))
}

async fn tag_get_by_id(
    State(ontogen_state): State<Arc<AppState>>,
    _: AcceptGuard,
    Path(id): Path<LookupKey>,
    query: Query<GetParams>,
) -> Result<Response, ErrorObject> {
    refuse_include(&query, "tags")?;
    let ontogen_store = ontogen_state.store().await.map_err(ontogen_internal_error)?;
    let entity = tag::get_by_id(&ontogen_store, tag_lookup_key(&id)?).await.map_err(ontogen_app_error)?;
    let collection = "/api/tags";
    let resource = tag_as_resource(&entity, collection);
    let links = Links::new(resource.links().self_link());
    Ok(response::ok(&Document::new(resource, links)))
}

async fn tag_create(
    State(ontogen_state): State<Arc<AppState>>,
    _: AcceptGuard,
    query: Result<Query<NoParams>, ErrorObject>,
    body: Body,
) -> Result<Response, ErrorObject> {
    query?;
    let body = body.into_bytes()?;
    let collection = "/api/tags";
    let endpoint = Endpoint { type_name: "tags", path: collection };
    let data = request::parse_create(&body, endpoint, |id| ontogen_core::id::validate_id(id).map_err(|e| e.reason))?;
    let fields = tag_request_fields(&data, true)?;
    let input: CreateTagInput = from_fields(fields)?;
    let ontogen_store = ontogen_state.store().await.map_err(ontogen_internal_error)?;
    let entity = tag::create(&ontogen_store, input).await.map_err(|e| match e {
        e @ crate::schema::AppError::TagAlreadyExists(..) if data.id.is_some() => {
            ontogen_app_error(e).with_pointer("/data/id")
        }
        e => ontogen_app_error(e),
    })?;
    let resource = tag_as_resource(&entity, collection);
    let location = resource.links().self_link().to_owned();
    let links = Links::new(location.as_str());
    Ok(response::created(&location, &Document::new(resource, links)))
}

async fn tag_update(
    State(ontogen_state): State<Arc<AppState>>,
    _: AcceptGuard,
    path_params: Result<Path<LookupKey>, ErrorObject>,
    query: Result<Query<NoParams>, ErrorObject>,
    body: Body,
) -> Result<Response, ErrorObject> {
    let Path(id) = path_params?;
    query?;
    let body = body.into_bytes()?;
    let collection = "/api/tags";
    let path = format!("{collection}/{id}");
    let endpoint = Endpoint { type_name: "tags", path: &path };
    let data = request::parse_update(&body, endpoint, &id)?;
    let fields = tag_request_fields(&data, false)?;
    let input: UpdateTagInput = from_fields(fields)?;
    let ontogen_store = ontogen_state.store().await.map_err(ontogen_internal_error)?;
    let entity = tag::update(&ontogen_store, tag_lookup_key(&id)?, input).await.map_err(ontogen_app_error)?;
    let resource = tag_as_resource(&entity, collection);
    let links = Links::new(resource.links().self_link());
    Ok(response::ok(&Document::new(resource, links)))
}

async fn tag_delete(
    State(ontogen_state): State<Arc<AppState>>,
    _: AcceptGuard,
    Path(id): Path<LookupKey>,
    _: Query<NoParams>,
) -> Result<Response, ErrorObject> {
    let ontogen_store = ontogen_state.store().await.map_err(ontogen_internal_error)?;
    tag::delete(&ontogen_store, tag_lookup_key(&id)?).await.map_err(ontogen_app_error)?;
    Ok(response::no_content())
}

// ── Workout Handlers ──

async fn workout_list(
    State(ontogen_state): State<Arc<AppState>>,
    _: AcceptGuard,
    query: Query<ListParams>,
) -> Result<Response, ErrorObject> {
    refuse_sort(&query, "workouts")?;
    refuse_include(&query, "workouts")?;
    let ontogen_store = ontogen_state.store().await.map_err(ontogen_internal_error)?;
    let items = workout::list(&ontogen_store).await.map_err(ontogen_app_error)?;
    let collection = "/api/workouts";
    let data: Vec<_> = items.iter().map(|entity| workout_as_resource(entity, collection)).collect();
    Ok(response::ok(&Document::new(data, Links::new(collection))))
}

async fn workout_get_by_id(
    State(ontogen_state): State<Arc<AppState>>,
    _: AcceptGuard,
    Path(id): Path<LookupKey>,
    query: Query<GetParams>,
) -> Result<Response, ErrorObject> {
    refuse_include(&query, "workouts")?;
    let ontogen_store = ontogen_state.store().await.map_err(ontogen_internal_error)?;
    let entity = workout::get_by_id(&ontogen_store, workout_lookup_key(&id)?).await.map_err(ontogen_app_error)?;
    let collection = "/api/workouts";
    let resource = workout_as_resource(&entity, collection);
    let links = Links::new(resource.links().self_link());
    Ok(response::ok(&Document::new(resource, links)))
}

async fn workout_create(
    State(ontogen_state): State<Arc<AppState>>,
    _: AcceptGuard,
    query: Result<Query<NoParams>, ErrorObject>,
    body: Body,
) -> Result<Response, ErrorObject> {
    query?;
    let body = body.into_bytes()?;
    let collection = "/api/workouts";
    let endpoint = Endpoint { type_name: "workouts", path: collection };
    let data = request::parse_create(&body, endpoint, |id| ontogen_core::id::validate_id(id).map_err(|e| e.reason))?;
    let (fields, linked) = workout_request_fields(&data, true)?;
    let input: CreateWorkoutInput = from_fields(fields)?;
    let ontogen_store = ontogen_state.store().await.map_err(ontogen_internal_error)?;
    workout_check_linked(&ontogen_state, &linked).await?;
    let entity = workout::create(&ontogen_store, input).await.map_err(|e| match e {
        e @ crate::schema::AppError::WorkoutAlreadyExists(..) if data.id.is_some() => {
            ontogen_app_error(e).with_pointer("/data/id")
        }
        e => ontogen_app_error(e),
    })?;
    let resource = workout_as_resource(&entity, collection);
    let location = resource.links().self_link().to_owned();
    let links = Links::new(location.as_str());
    Ok(response::created(&location, &Document::new(resource, links)))
}

async fn workout_update(
    State(ontogen_state): State<Arc<AppState>>,
    _: AcceptGuard,
    path_params: Result<Path<LookupKey>, ErrorObject>,
    query: Result<Query<NoParams>, ErrorObject>,
    body: Body,
) -> Result<Response, ErrorObject> {
    let Path(id) = path_params?;
    query?;
    let body = body.into_bytes()?;
    let collection = "/api/workouts";
    let path = format!("{collection}/{id}");
    let endpoint = Endpoint { type_name: "workouts", path: &path };
    let data = request::parse_update(&body, endpoint, &id)?;
    let (fields, linked) = workout_request_fields(&data, false)?;
    let input: UpdateWorkoutInput = from_fields(fields)?;
    let ontogen_store = ontogen_state.store().await.map_err(ontogen_internal_error)?;
    workout_check_linked(&ontogen_state, &linked).await?;
    let entity = workout::update(&ontogen_store, workout_lookup_key(&id)?, input).await.map_err(ontogen_app_error)?;
    let resource = workout_as_resource(&entity, collection);
    let links = Links::new(resource.links().self_link());
    Ok(response::ok(&Document::new(resource, links)))
}

async fn workout_delete(
    State(ontogen_state): State<Arc<AppState>>,
    _: AcceptGuard,
    Path(id): Path<LookupKey>,
    _: Query<NoParams>,
) -> Result<Response, ErrorObject> {
    let ontogen_store = ontogen_state.store().await.map_err(ontogen_internal_error)?;
    workout::delete(&ontogen_store, workout_lookup_key(&id)?).await.map_err(ontogen_app_error)?;
    Ok(response::no_content())
}

async fn ontogen_workout_relationship_get(
    State(ontogen_state): State<Arc<AppState>>,
    _: AcceptGuard,
    Path((id, rel)): Path<(LookupKey, LookupKey)>,
    RawQuery(ontogen_raw_query): RawQuery,
) -> Result<Response, ErrorObject> {
    let ontogen_collection = "/api/workouts";
    match rel.as_str() {
        Some("tags") => {
            QueryParams::parse(ontogen_raw_query.as_deref(), &QuerySpec::NONE)?;
            let ontogen_entity = ontogen_workout_read(&ontogen_state, &id).await?;
            let ontogen_base = format!("{ontogen_collection}/{}", encode_path_segment(&ontogen_entity.id));
            let ontogen_links =
                Links::new(format!("{ontogen_base}/relationships/tags")).with_related(format!("{ontogen_base}/tags"));
            let ontogen_data = Linkage::ToMany(
                ontogen_entity
                    .tags
                    .iter()
                    .map(|ontogen_member| ResourceIdentifier::new("tags", ontogen_member.as_str()))
                    .collect(),
            );
            Ok(response::ok(&Document::new(ontogen_data, ontogen_links)))
        }
        _ => Err(relationship_not_found("workouts", &rel)),
    }
}

async fn ontogen_workout_relationship_patch(
    State(ontogen_state): State<Arc<AppState>>,
    _: AcceptGuard,
    ontogen_path: Result<Path<(LookupKey, LookupKey)>, ErrorObject>,
    ontogen_query: Result<Query<NoParams>, ErrorObject>,
    ontogen_body: Body,
) -> Result<Response, ErrorObject> {
    let Path((id, rel)) = ontogen_path?;
    match rel.as_str() {
        Some("tags") => {
            ontogen_query?;
            let ontogen_bytes = ontogen_body.into_bytes()?;
            let ontogen_linked =
                request::to_many_linked(&request::parse_relationship(&ontogen_bytes)?, "", "tags", None)?;
            let ontogen_entity = ontogen_workout_read(&ontogen_state, &id).await?;
            ontogen_tag_check_ids(&ontogen_state, &ontogen_linked).await?;
            ontogen_workout_write_field(
                &ontogen_state,
                &ontogen_entity.id,
                "tags",
                ontogen_linked.into_iter().map(|ontogen_member| ontogen_member.id).collect(),
            )
            .await?;
            Ok(response::no_content())
        }
        _ => Err(relationship_not_found("workouts", &rel)),
    }
}

async fn ontogen_workout_relationship_post(
    State(ontogen_state): State<Arc<AppState>>,
    _: AcceptGuard,
    ontogen_path: Result<Path<(LookupKey, LookupKey)>, ErrorObject>,
    ontogen_query: Result<Query<NoParams>, ErrorObject>,
    ontogen_body: Body,
) -> Result<Response, ErrorObject> {
    let Path((id, rel)) = ontogen_path?;
    match rel.as_str() {
        Some("tags") => {
            ontogen_query?;
            let ontogen_bytes = ontogen_body.into_bytes()?;
            let ontogen_linked =
                request::to_many_linked(&request::parse_relationship(&ontogen_bytes)?, "", "tags", Some(1))?;
            let ontogen_entity = ontogen_workout_read(&ontogen_state, &id).await?;
            ontogen_tag_check_ids(&ontogen_state, &ontogen_linked).await?;
            if let Some(ontogen_ids) = ontogen_added(&ontogen_entity.tags, &ontogen_linked) {
                ontogen_workout_write_field(&ontogen_state, &ontogen_entity.id, "tags", ontogen_ids.into()).await?;
            }
            Ok(response::no_content())
        }
        _ => Err(relationship_not_found("workouts", &rel)),
    }
}

async fn ontogen_workout_relationship_delete(
    State(ontogen_state): State<Arc<AppState>>,
    _: AcceptGuard,
    ontogen_path: Result<Path<(LookupKey, LookupKey)>, ErrorObject>,
    ontogen_query: Result<Query<NoParams>, ErrorObject>,
    ontogen_body: Body,
) -> Result<Response, ErrorObject> {
    let Path((id, rel)) = ontogen_path?;
    match rel.as_str() {
        Some("tags") => {
            ontogen_query?;
            let ontogen_bytes = ontogen_body.into_bytes()?;
            let ontogen_linked =
                request::to_many_linked(&request::parse_relationship(&ontogen_bytes)?, "", "tags", Some(1))?;
            let ontogen_entity = ontogen_workout_read(&ontogen_state, &id).await?;
            if let Some(ontogen_ids) = ontogen_removed(&ontogen_entity.tags, &ontogen_linked) {
                ontogen_workout_write_field(&ontogen_state, &ontogen_entity.id, "tags", ontogen_ids.into()).await?;
            }
            Ok(response::no_content())
        }
        _ => Err(relationship_not_found("workouts", &rel)),
    }
}

async fn ontogen_workout_related_get(
    State(ontogen_state): State<Arc<AppState>>,
    _: AcceptGuard,
    Path((id, rel)): Path<(LookupKey, LookupKey)>,
    RawQuery(ontogen_raw_query): RawQuery,
) -> Result<Response, ErrorObject> {
    let ontogen_collection = "/api/workouts";
    match rel.as_str() {
        Some("tags") => {
            QueryParams::parse(ontogen_raw_query.as_deref(), &QuerySpec::NONE)?;
            let ontogen_entity = ontogen_workout_read(&ontogen_state, &id).await?;
            let ontogen_related = ontogen_tag_fetch(&ontogen_state, &ontogen_entity.tags).await?;
            let ontogen_data: Vec<_> =
                ontogen_related.iter().map(|ontogen_member| tag_as_resource(ontogen_member, "/api/tags")).collect();
            let ontogen_self = format!("{ontogen_collection}/{}/tags", encode_path_segment(&ontogen_entity.id));
            Ok(response::ok(&Document::new(ontogen_data, Links::new(ontogen_self))))
        }
        _ => Err(relationship_not_found("workouts", &rel)),
    }
}

// ── Workout_set Handlers ──

async fn workout_set_list(
    State(ontogen_state): State<Arc<AppState>>,
    _: AcceptGuard,
    query: Query<ListParams>,
) -> Result<Response, ErrorObject> {
    refuse_sort(&query, "workout-sets")?;
    refuse_include(&query, "workout-sets")?;
    let ontogen_store = ontogen_state.store().await.map_err(ontogen_internal_error)?;
    let items = workout_set::list(&ontogen_store).await.map_err(ontogen_app_error)?;
    let collection = "/api/workout-sets";
    let data: Vec<_> = items.iter().map(|entity| workout_set_as_resource(entity, collection)).collect();
    Ok(response::ok(&Document::new(data, Links::new(collection))))
}

async fn workout_set_get_by_id(
    State(ontogen_state): State<Arc<AppState>>,
    _: AcceptGuard,
    Path(id): Path<LookupKey>,
    query: Query<GetParams>,
) -> Result<Response, ErrorObject> {
    refuse_include(&query, "workout-sets")?;
    let ontogen_store = ontogen_state.store().await.map_err(ontogen_internal_error)?;
    let entity =
        workout_set::get_by_id(&ontogen_store, workout_set_lookup_key(&id)?).await.map_err(ontogen_app_error)?;
    let collection = "/api/workout-sets";
    let resource = workout_set_as_resource(&entity, collection);
    let links = Links::new(resource.links().self_link());
    Ok(response::ok(&Document::new(resource, links)))
}

async fn workout_set_create(
    State(ontogen_state): State<Arc<AppState>>,
    _: AcceptGuard,
    query: Result<Query<NoParams>, ErrorObject>,
    body: Body,
) -> Result<Response, ErrorObject> {
    query?;
    let body = body.into_bytes()?;
    let collection = "/api/workout-sets";
    let endpoint = Endpoint { type_name: "workout-sets", path: collection };
    let data = request::parse_create(&body, endpoint, |id| ontogen_core::id::validate_id(id).map_err(|e| e.reason))?;
    let (fields, linked) = workout_set_request_fields(&data, true)?;
    let input: CreateWorkoutSetInput = from_fields(fields)?;
    let ontogen_store = ontogen_state.store().await.map_err(ontogen_internal_error)?;
    workout_set_check_linked(&ontogen_state, &linked).await?;
    let entity = workout_set::create(&ontogen_store, input).await.map_err(|e| match e {
        e @ crate::schema::AppError::WorkoutSetAlreadyExists(..) if data.id.is_some() => {
            ontogen_app_error(e).with_pointer("/data/id")
        }
        e => ontogen_app_error(e),
    })?;
    let resource = workout_set_as_resource(&entity, collection);
    let location = resource.links().self_link().to_owned();
    let links = Links::new(location.as_str());
    Ok(response::created(&location, &Document::new(resource, links)))
}

async fn workout_set_update(
    State(ontogen_state): State<Arc<AppState>>,
    _: AcceptGuard,
    path_params: Result<Path<LookupKey>, ErrorObject>,
    query: Result<Query<NoParams>, ErrorObject>,
    body: Body,
) -> Result<Response, ErrorObject> {
    let Path(id) = path_params?;
    query?;
    let body = body.into_bytes()?;
    let collection = "/api/workout-sets";
    let path = format!("{collection}/{id}");
    let endpoint = Endpoint { type_name: "workout-sets", path: &path };
    let data = request::parse_update(&body, endpoint, &id)?;
    let (fields, linked) = workout_set_request_fields(&data, false)?;
    let input: UpdateWorkoutSetInput = from_fields(fields)?;
    let ontogen_store = ontogen_state.store().await.map_err(ontogen_internal_error)?;
    workout_set_check_linked(&ontogen_state, &linked).await?;
    let entity =
        workout_set::update(&ontogen_store, workout_set_lookup_key(&id)?, input).await.map_err(ontogen_app_error)?;
    let resource = workout_set_as_resource(&entity, collection);
    let links = Links::new(resource.links().self_link());
    Ok(response::ok(&Document::new(resource, links)))
}

async fn workout_set_delete(
    State(ontogen_state): State<Arc<AppState>>,
    _: AcceptGuard,
    Path(id): Path<LookupKey>,
    _: Query<NoParams>,
) -> Result<Response, ErrorObject> {
    let ontogen_store = ontogen_state.store().await.map_err(ontogen_internal_error)?;
    workout_set::delete(&ontogen_store, workout_set_lookup_key(&id)?).await.map_err(ontogen_app_error)?;
    Ok(response::no_content())
}

async fn ontogen_workout_set_relationship_get(
    State(ontogen_state): State<Arc<AppState>>,
    _: AcceptGuard,
    Path((id, rel)): Path<(LookupKey, LookupKey)>,
    RawQuery(ontogen_raw_query): RawQuery,
) -> Result<Response, ErrorObject> {
    let ontogen_collection = "/api/workout-sets";
    match rel.as_str() {
        Some("workout") => {
            QueryParams::parse(ontogen_raw_query.as_deref(), &QuerySpec::NONE)?;
            let ontogen_entity = ontogen_workout_set_read(&ontogen_state, &id).await?;
            let ontogen_base = format!("{ontogen_collection}/{}", encode_path_segment(&ontogen_entity.id));
            let ontogen_links = Links::new(format!("{ontogen_base}/relationships/workout"))
                .with_related(format!("{ontogen_base}/workout"));
            let ontogen_data =
                Linkage::ToOne(Some(ResourceIdentifier::new("workouts", ontogen_entity.workout_id.as_str())));
            Ok(response::ok(&Document::new(ontogen_data, ontogen_links)))
        }
        Some("exercise") => {
            QueryParams::parse(ontogen_raw_query.as_deref(), &QuerySpec::NONE)?;
            let ontogen_entity = ontogen_workout_set_read(&ontogen_state, &id).await?;
            let ontogen_base = format!("{ontogen_collection}/{}", encode_path_segment(&ontogen_entity.id));
            let ontogen_links = Links::new(format!("{ontogen_base}/relationships/exercise"))
                .with_related(format!("{ontogen_base}/exercise"));
            let ontogen_data =
                Linkage::ToOne(Some(ResourceIdentifier::new("exercises", ontogen_entity.exercise_id.as_str())));
            Ok(response::ok(&Document::new(ontogen_data, ontogen_links)))
        }
        _ => Err(relationship_not_found("workout-sets", &rel)),
    }
}

async fn ontogen_workout_set_relationship_patch(
    State(ontogen_state): State<Arc<AppState>>,
    _: AcceptGuard,
    ontogen_path: Result<Path<(LookupKey, LookupKey)>, ErrorObject>,
    ontogen_query: Result<Query<NoParams>, ErrorObject>,
    ontogen_body: Body,
) -> Result<Response, ErrorObject> {
    let Path((id, rel)) = ontogen_path?;
    match rel.as_str() {
        Some("workout") => {
            ontogen_query?;
            let ontogen_bytes = ontogen_body.into_bytes()?;
            let ontogen_linked = request::to_one(&request::parse_relationship(&ontogen_bytes)?, "", "workouts", false)?
                .map(|ontogen_member| LinkedId { id: ontogen_member, pointer: "/data".to_owned() });
            let ontogen_entity = ontogen_workout_set_read(&ontogen_state, &id).await?;
            ontogen_workout_check_ids(&ontogen_state, ontogen_linked.as_slice()).await?;
            ontogen_workout_set_write_field(
                &ontogen_state,
                &ontogen_entity.id,
                "workout_id",
                ontogen_linked.map(|ontogen_member| ontogen_member.id).into(),
            )
            .await?;
            Ok(response::no_content())
        }
        Some("exercise") => {
            ontogen_query?;
            let ontogen_bytes = ontogen_body.into_bytes()?;
            let ontogen_linked =
                request::to_one(&request::parse_relationship(&ontogen_bytes)?, "", "exercises", false)?
                    .map(|ontogen_member| LinkedId { id: ontogen_member, pointer: "/data".to_owned() });
            let ontogen_entity = ontogen_workout_set_read(&ontogen_state, &id).await?;
            ontogen_exercise_check_ids(&ontogen_state, ontogen_linked.as_slice()).await?;
            ontogen_workout_set_write_field(
                &ontogen_state,
                &ontogen_entity.id,
                "exercise_id",
                ontogen_linked.map(|ontogen_member| ontogen_member.id).into(),
            )
            .await?;
            Ok(response::no_content())
        }
        _ => Err(relationship_not_found("workout-sets", &rel)),
    }
}

async fn ontogen_workout_set_relationship_post(
    _: AcceptGuard,
    ontogen_path: Result<Path<(LookupKey, LookupKey)>, ErrorObject>,
    ontogen_query: Result<Query<NoParams>, ErrorObject>,
    _: Body,
) -> Result<Response, ErrorObject> {
    let Path((_, rel)) = ontogen_path?;
    match rel.as_str() {
        Some("workout") => {
            ontogen_query?;
            Err(relationship_update_unsupported("workout-sets", "workout", "POST"))
        }
        Some("exercise") => {
            ontogen_query?;
            Err(relationship_update_unsupported("workout-sets", "exercise", "POST"))
        }
        _ => Err(relationship_not_found("workout-sets", &rel)),
    }
}

async fn ontogen_workout_set_relationship_delete(
    _: AcceptGuard,
    ontogen_path: Result<Path<(LookupKey, LookupKey)>, ErrorObject>,
    ontogen_query: Result<Query<NoParams>, ErrorObject>,
    _: Body,
) -> Result<Response, ErrorObject> {
    let Path((_, rel)) = ontogen_path?;
    match rel.as_str() {
        Some("workout") => {
            ontogen_query?;
            Err(relationship_update_unsupported("workout-sets", "workout", "DELETE"))
        }
        Some("exercise") => {
            ontogen_query?;
            Err(relationship_update_unsupported("workout-sets", "exercise", "DELETE"))
        }
        _ => Err(relationship_not_found("workout-sets", &rel)),
    }
}

async fn ontogen_workout_set_related_get(
    State(ontogen_state): State<Arc<AppState>>,
    _: AcceptGuard,
    Path((id, rel)): Path<(LookupKey, LookupKey)>,
    RawQuery(ontogen_raw_query): RawQuery,
) -> Result<Response, ErrorObject> {
    let ontogen_collection = "/api/workout-sets";
    match rel.as_str() {
        Some("workout") => {
            QueryParams::parse(ontogen_raw_query.as_deref(), &QuerySpec::NONE)?;
            let ontogen_entity = ontogen_workout_set_read(&ontogen_state, &id).await?;
            let ontogen_related =
                ontogen_workout_fetch(&ontogen_state, std::slice::from_ref(&ontogen_entity.workout_id)).await?;
            let ontogen_data =
                ontogen_related.first().map(|ontogen_member| workout_as_resource(ontogen_member, "/api/workouts"));
            let ontogen_self = format!("{ontogen_collection}/{}/workout", encode_path_segment(&ontogen_entity.id));
            Ok(response::ok(&Document::new(ontogen_data, Links::new(ontogen_self))))
        }
        Some("exercise") => {
            QueryParams::parse(ontogen_raw_query.as_deref(), &QuerySpec::NONE)?;
            let ontogen_entity = ontogen_workout_set_read(&ontogen_state, &id).await?;
            let ontogen_related =
                ontogen_exercise_fetch(&ontogen_state, std::slice::from_ref(&ontogen_entity.exercise_id)).await?;
            let ontogen_data =
                ontogen_related.first().map(|ontogen_member| exercise_as_resource(ontogen_member, "/api/exercises"));
            let ontogen_self = format!("{ontogen_collection}/{}/exercise", encode_path_segment(&ontogen_entity.id));
            Ok(response::ok(&Document::new(ontogen_data, Links::new(ontogen_self))))
        }
        _ => Err(relationship_not_found("workout-sets", &rel)),
    }
}

/// Generated routes. Call this from your main router.
pub fn entity_routes() -> Router<Arc<AppState>> {
    Router::new()
        .route("/api/exercises", get(exercise_list).post(exercise_create).fallback(allow([Method::GET, Method::POST])))
        .route(
            "/api/exercises/{id}",
            get(exercise_get_by_id).patch(exercise_update).delete(exercise_delete).fallback(allow([
                Method::GET,
                Method::PATCH,
                Method::DELETE,
            ])),
        )
        .route("/api/tags", get(tag_list).post(tag_create).fallback(allow([Method::GET, Method::POST])))
        .route(
            "/api/tags/{id}",
            get(tag_get_by_id).patch(tag_update).delete(tag_delete).fallback(allow([
                Method::GET,
                Method::PATCH,
                Method::DELETE,
            ])),
        )
        .route("/api/workouts", get(workout_list).post(workout_create).fallback(allow([Method::GET, Method::POST])))
        .route(
            "/api/workouts/{id}",
            get(workout_get_by_id).patch(workout_update).delete(workout_delete).fallback(allow([
                Method::GET,
                Method::PATCH,
                Method::DELETE,
            ])),
        )
        .route(
            "/api/workouts/{id}/relationships/{rel}",
            get(ontogen_workout_relationship_get)
                .patch(ontogen_workout_relationship_patch)
                .post(ontogen_workout_relationship_post)
                .delete(ontogen_workout_relationship_delete)
                .fallback(allow([Method::GET, Method::PATCH, Method::POST, Method::DELETE])),
        )
        .route("/api/workouts/{id}/{rel}", get(ontogen_workout_related_get).fallback(allow([Method::GET])))
        .route(
            "/api/workout-sets",
            get(workout_set_list).post(workout_set_create).fallback(allow([Method::GET, Method::POST])),
        )
        .route(
            "/api/workout-sets/{id}",
            get(workout_set_get_by_id).patch(workout_set_update).delete(workout_set_delete).fallback(allow([
                Method::GET,
                Method::PATCH,
                Method::DELETE,
            ])),
        )
        .route(
            "/api/workout-sets/{id}/relationships/{rel}",
            get(ontogen_workout_set_relationship_get)
                .patch(ontogen_workout_set_relationship_patch)
                .post(ontogen_workout_set_relationship_post)
                .delete(ontogen_workout_set_relationship_delete)
                .fallback(allow([Method::GET, Method::PATCH, Method::POST, Method::DELETE])),
        )
        .route("/api/workout-sets/{id}/{rel}", get(ontogen_workout_set_related_get).fallback(allow([Method::GET])))
}
