// Auto-generated transport layer. DO NOT EDIT.
// Generated by ontogen from API source files.

import type {
  CreateTagInput,
  CreateTaskInput,
  CreateWorkoutSetInput,
  Tag,
  Task,
  UpdateTagInput,
  UpdateTaskInput,
  UpdateWorkoutSetInput,
  WorkoutSet,
} from './jsonapi-bindings';

import { Channel, invoke } from '@tauri-apps/api/core';

export interface PaginatedResult<T> {
  items: T[];
  total: number;
  limit: number;
  offset: number;
}

/** A list's sort keys, applied in order: `-` sorts a field descending, and `id` ascending is the last key unless named. */
export interface ListOptions<K extends string> {
  sort?: K[];
}

export type TagSortKey = 'id' | '-id' | 'title' | '-title';

export type TaskSortKey = 'id' | '-id' | 'title' | '-title' | 'estimate' | '-estimate';

export type WorkoutSetSortKey = 'id' | '-id' | 'reps' | '-reps';

// ── Event Subscriptions ──

export interface SubscriptionHandlers<T> {
  /** An event. `id` is its resume id, or null for an op that is not resumable. */
  onEvent: (data: T, id: string | null) => void;
  /** The subscription fell behind and `skipped` events were dropped. */
  onLag?: (skipped: number) => void;
  /** Fires on the first connect and on every reconnect: the hook for a catch-up read. */
  onOpen?: () => void;
  onError?: (err: unknown) => void;
}

type EventFrame<T> = { kind: 'event'; id: string | null; data: T } | { kind: 'lag'; skipped: number };

// ── Transport Interface ──

export interface Transport {
  boardList(limit?: number, offset?: number): Promise<PaginatedResult<Task>>;
  boardGetById(id: string): Promise<Task>;
  boardCreate(input: CreateTaskInput): Promise<Task>;
  boardUpdate(id: string, input: UpdateTaskInput): Promise<Task>;
  boardDelete(id: string): Promise<null>;
  boardListTags(boardId: string, limit?: number, offset?: number): Promise<PaginatedResult<Tag>>;
  boardAddTag(boardId: string, tagId: string): Promise<null>;
  boardRemoveTag(boardId: string, tagId: string): Promise<null>;
  boardGetSummary(id: string, includeDone: boolean | null): Promise<Task>;
  boardArchive(taskId: string, reason: string | null): Promise<Task>;
  boardImport(input: CreateTaskInput, dryRun: boolean | null): Promise<number>;
  boardReset(): Promise<null>;
  tagList(limit?: number, offset?: number, options?: ListOptions<TagSortKey>): Promise<PaginatedResult<Tag>>;
  tagGetById(id: string): Promise<Tag>;
  tagCreate(input: CreateTagInput): Promise<Tag>;
  tagUpdate(id: string, input: UpdateTagInput): Promise<Tag>;
  tagDelete(id: string): Promise<null>;
  taskList(limit?: number, offset?: number, options?: ListOptions<TaskSortKey>): Promise<PaginatedResult<Task>>;
  taskGetById(id: string): Promise<Task>;
  taskCreate(input: CreateTaskInput): Promise<Task>;
  taskUpdate(id: string, input: UpdateTaskInput): Promise<Task>;
  taskDelete(id: string): Promise<null>;
  taskListLabels(taskId: string, limit?: number, offset?: number): Promise<PaginatedResult<Tag>>;
  taskAddLabel(taskId: string, tagId: string): Promise<null>;
  taskRemoveLabel(taskId: string, tagId: string): Promise<null>;
  taskListDrafts(taskId: string): Promise<Task[]>;
  workoutSetList(limit?: number, offset?: number, options?: ListOptions<WorkoutSetSortKey>): Promise<PaginatedResult<WorkoutSet>>;
  workoutSetGetById(id: string): Promise<WorkoutSet>;
  workoutSetCreate(input: CreateWorkoutSetInput): Promise<WorkoutSet>;
  workoutSetUpdate(id: string, input: UpdateWorkoutSetInput): Promise<WorkoutSet>;
  workoutSetDelete(id: string): Promise<null>;
  workoutSetListTags(setId: string, limit?: number, offset?: number): Promise<PaginatedResult<string>>;
  workoutSetAddTag(setId: string, tagId: string): Promise<null>;
  workoutSetRemoveTag(setId: string, tagId: string): Promise<null>;
  subscribeTaskChanges(args: { resume?: string | null }, handlers: SubscriptionHandlers<Task>): Promise<() => void>;
}

// ── JSON:API ──

export interface JsonApiResourceIdentifier {
  type: string;
  id: string;
}

export interface JsonApiRelationship {
  data?: JsonApiResourceIdentifier | JsonApiResourceIdentifier[] | null;
  links?: Record<string, string | null>;
}

export interface JsonApiResource {
  type: string;
  id: string;
  attributes?: Record<string, unknown>;
  relationships?: Record<string, JsonApiRelationship>;
  links?: Record<string, string | null>;
}

export interface JsonApiErrorObject {
  id?: string;
  status?: string;
  code?: string;
  title?: string;
  detail?: string;
  source?: { pointer?: string; parameter?: string; header?: string };
  meta?: Record<string, unknown>;
}

/** A non-2xx response. `errors` is empty when the body was not a JSON:API error document. */
export class JsonApiError extends Error {
  override readonly name = 'JsonApiError';
  readonly status: number;
  readonly errors: JsonApiErrorObject[];

  constructor(status: number, errors: JsonApiErrorObject[], message: string) {
    super(message);
    this.status = status;
    this.errors = errors;
  }
}

// ── HTTP Helpers ──

const BASE = '/api';
const JSON_API_MEDIA_TYPE = 'application/vnd.api+json';

async function httpRequest(method: string, path: string, body?: unknown): Promise<Response> {
  const headers: Record<string, string> = { Accept: JSON_API_MEDIA_TYPE };
  if (body != null) headers['Content-Type'] = JSON_API_MEDIA_TYPE;
  const res = await fetch(`${BASE}${path}`, {
    method,
    headers,
    body: body != null ? JSON.stringify(body) : null,
  });
  if (!res.ok) throw await toJsonApiError(res);
  return res;
}

async function toJsonApiError(res: Response): Promise<JsonApiError> {
  const body: unknown = await res.json().catch(() => null);
  const errors =
    typeof body === 'object' && body !== null && Array.isArray((body as { errors?: unknown }).errors)
      ? (body as { errors: JsonApiErrorObject[] }).errors
      : [];
  const first = errors[0];
  return new JsonApiError(res.status, errors, first?.detail ?? first?.title ?? res.statusText);
}

async function httpGet<T>(path: string): Promise<T> {
  const res = await httpRequest('GET', path);
  return res.json();
}

async function httpPost<T>(path: string, body?: unknown): Promise<T> {
  const res = await httpRequest('POST', path, body);
  if (res.status === 204) return null as T;
  return res.json();
}

async function httpPatch<T>(path: string, body: unknown): Promise<T> {
  const res = await httpRequest('PATCH', path, body);
  return res.json();
}

async function httpDelete(path: string, body?: unknown): Promise<void> {
  await httpRequest('DELETE', path, body);
}

/**
 * Calls an op that is not served as a resource. `args` travel as the body's
 * `meta.args`, keyed by the op's parameter names; without them no body is
 * sent. Resolves to the reply's `meta.result`, or `null` for a 204.
 */
async function callOp<T>(method: string, path: string, args?: Record<string, unknown>): Promise<T> {
  const res = await httpRequest(method, path, args === undefined ? undefined : { meta: { args } });
  if (res.status === 204) return null as T;
  const doc = (await res.json()) as { meta: { result: T } };
  return doc.meta.result;
}

function toQueryString(params: Record<string, unknown>): string {
  const parts: string[] = [];
  const push = (key: string, value: unknown, member: boolean) => {
    if (value == null) return;
    const values = Array.isArray(value) ? value : [value];
    if (values.length > 0 || member) parts.push(`${key}=${values.map((v) => encodeURIComponent(String(v))).join(',')}`);
  };
  for (const [key, value] of Object.entries(params)) {
    if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
      for (const [member, v] of Object.entries(value)) {
        push(`${encodeURIComponent(key)}%5B${encodeURIComponent(member)}%5D`, v, true);
      }
    } else {
      push(encodeURIComponent(key), value, false);
    }
  }
  return parts.length > 0 ? `?${parts.join('&')}` : '';
}

const SSE_RETRY_BASE_MS = 500;
const SSE_RETRY_MAX_MS = 30000;

function subscribeSse<T>(
  url: (resume: string | null) => string,
  eventName: string,
  initialResume: string | null,
  decode: (frame: unknown) => T,
  handlers: SubscriptionHandlers<T>,
): () => void {
  let source: EventSource | null = null;
  let timer: ReturnType<typeof setTimeout> | null = null;
  let lastId = initialResume;
  let attempt = 0;
  let closed = false;
  function connect() {
    if (closed) return;
    const es = new EventSource(url(lastId));
    source = es;
    es.onopen = () => {
      attempt = 0;
      handlers.onOpen?.();
    };
    es.addEventListener(eventName, (event: MessageEvent) => {
      const id = event.lastEventId || null;
      if (id) lastId = id;
      let data: T;
      try {
        data = decode(JSON.parse(event.data));
      } catch (err) {
        handlers.onError?.(err);
        return;
      }
      handlers.onEvent(data, id);
    });
    es.addEventListener('lag', (event: MessageEvent) => {
      try {
        handlers.onLag?.(JSON.parse(event.data).skipped);
      } catch (err) {
        handlers.onError?.(err);
      }
    });
    es.onerror = (err: Event) => {
      es.close();
      if (source === es) source = null;
      if (closed) return;
      handlers.onError?.(err);
      const delay = Math.min(SSE_RETRY_MAX_MS, SSE_RETRY_BASE_MS * 2 ** attempt);
      attempt += 1;
      timer = setTimeout(connect, delay / 2 + Math.random() * (delay / 2));
    };
  }
  connect();
  return () => {
    closed = true;
    if (timer) clearTimeout(timer);
    source?.close();
    source = null;
  };
}

/** An event frame whose item is not a resource carries it as `meta.result`. */
function metaResult<T>(frame: unknown): T {
  return (frame as { meta: { result: T } }).meta.result;
}

// ── JSON:API Resources ──

interface JsonApiResourceDef {
  type: string;
  idField: string;
  /** Keyed by relationship name. */
  relationships: Record<string, { field: string; type: string; many: boolean }>;
}

interface JsonApiResourceDocument {
  data: JsonApiResource;
}

/** `T` is `JsonApiResourceIdentifier` for a relationship's linkage. */
interface JsonApiCollectionDocument<T = JsonApiResource> {
  data: T[];
}

interface JsonApiPageDocument<T = JsonApiResource> {
  data: T[];
  meta: { total: number; limit: number; offset: number };
}

interface JsonApiWriteDocument {
  data: {
    type: string;
    id?: string;
    attributes: Record<string, unknown>;
    relationships?: Record<string, JsonApiRelationship>;
  };
}

function toOneId(rel: JsonApiRelationship | undefined): string | null {
  const data = rel?.data;
  return data != null && !Array.isArray(data) ? data.id : null;
}

function toManyIds(rel: JsonApiRelationship | undefined): string[] {
  const data = rel?.data;
  return Array.isArray(data) ? data.map((i) => i.id) : [];
}

/**
 * A flat create or update input as a resource document. `undefined` keys are
 * left out, which an update reads as unchanged; `null` is kept and clears.
 * A to-many `null` is left out too: `{ data: null }` is not valid linkage for
 * it, and the flat update input reads `null` there as unchanged.
 */
function unflattenResource(def: JsonApiResourceDef, input: object, id?: string): JsonApiWriteDocument {
  let resourceId = id;
  const attributes: Record<string, unknown> = {};
  const relationships: Record<string, JsonApiRelationship> = {};
  const relByField = new Map(
    Object.entries(def.relationships).map(([name, rel]) => [rel.field, { name, ...rel }] as const),
  );
  for (const [key, value] of Object.entries(input)) {
    if (value === undefined) continue;
    if (key === def.idField) {
      // An empty create id asks the server to derive one.
      if (id === undefined && typeof value === 'string' && value !== '') resourceId = value;
      continue;
    }
    const rel = relByField.get(key);
    if (rel === undefined) {
      attributes[key] = value;
    } else if (rel.many) {
      if (Array.isArray(value)) {
        relationships[rel.name] = { data: value.map((v) => ({ type: rel.type, id: String(v) })) };
      }
    } else {
      relationships[rel.name] = { data: value === null ? null : { type: rel.type, id: String(value) } };
    }
  }
  return {
    data: {
      type: def.type,
      ...(resourceId !== undefined ? { id: resourceId } : {}),
      attributes,
      ...(Object.keys(relationships).length > 0 ? { relationships } : {}),
    },
  };
}

const TAG_RESOURCE: JsonApiResourceDef = {
  type: 'tags',
  idField: 'slug',
  relationships: {},
};

function flattenTag(r: JsonApiResource): Tag {
  return {
    slug: r.id,
    ...r.attributes,
  } as Tag;
}

function unflattenTag(input: object, id?: string): JsonApiWriteDocument {
  return unflattenResource(TAG_RESOURCE, input, id);
}

const TASK_RESOURCE: JsonApiResourceDef = {
  type: 'tasks',
  idField: 'id',
  relationships: {
    parent: { field: 'parent_id', type: 'tasks', many: false },
    subtasks: { field: 'subtasks', type: 'tasks', many: true },
    tags: { field: 'tags', type: 'tags', many: true },
  },
};

function flattenTask(r: JsonApiResource): Task {
  return {
    id: r.id,
    ...r.attributes,
    parent_id: toOneId(r.relationships?.['parent']),
    subtasks: toManyIds(r.relationships?.['subtasks']),
    tags: toManyIds(r.relationships?.['tags']),
  } as Task;
}

function unflattenTask(input: object, id?: string): JsonApiWriteDocument {
  return unflattenResource(TASK_RESOURCE, input, id);
}

const WORKOUT_SET_RESOURCE: JsonApiResourceDef = {
  type: 'workout-sets',
  idField: 'id',
  relationships: {
    tag: { field: 'tag_id', type: 'tags', many: false },
  },
};

function flattenWorkoutSet(r: JsonApiResource): WorkoutSet {
  return {
    id: r.id,
    ...r.attributes,
    tag_id: toOneId(r.relationships?.['tag']),
  } as WorkoutSet;
}

function unflattenWorkoutSet(input: object, id?: string): JsonApiWriteDocument {
  return unflattenResource(WORKOUT_SET_RESOURCE, input, id);
}

// ── HTTP Transport ──

export function createHttpTransport(): Transport {
  return {
    async boardList(limit?: number, offset?: number): Promise<PaginatedResult<Task>> {
      return callOp<PaginatedResult<Task>>('GET', `/boards${toQueryString({ opArg: { limit, offset } })}`);
    },
    async boardGetById(id: string): Promise<Task> {
      return callOp<Task>('GET', `/boards/${encodeURIComponent(id)}`);
    },
    async boardCreate(input: CreateTaskInput): Promise<Task> {
      return callOp<Task>('POST', '/boards', { input });
    },
    async boardUpdate(id: string, input: UpdateTaskInput): Promise<Task> {
      return callOp<Task>('PATCH', `/boards/${encodeURIComponent(id)}`, { input });
    },
    async boardDelete(id: string): Promise<null> {
      return callOp<null>('DELETE', `/boards/${encodeURIComponent(id)}`);
    },
    async boardListTags(boardId: string, limit?: number, offset?: number): Promise<PaginatedResult<Tag>> {
      return callOp<PaginatedResult<Tag>>('GET', `/boards/${encodeURIComponent(boardId)}/tags${toQueryString({ opArg: { limit, offset } })}`);
    },
    async boardAddTag(boardId: string, tagId: string): Promise<null> {
      return callOp<null>('POST', `/boards/${encodeURIComponent(boardId)}/tags`, { tag_id: tagId });
    },
    async boardRemoveTag(boardId: string, tagId: string): Promise<null> {
      return callOp<null>('DELETE', `/boards/${encodeURIComponent(boardId)}/tags/${encodeURIComponent(tagId)}`);
    },
    async boardGetSummary(id: string, includeDone: boolean | null): Promise<Task> {
      return callOp<Task>('GET', `/boards/summary/${encodeURIComponent(id)}${toQueryString({ opArg: { include_done: includeDone } })}`);
    },
    async boardArchive(taskId: string, reason: string | null): Promise<Task> {
      return callOp<Task>('POST', '/boards/archive', { task_id: taskId, reason });
    },
    async boardImport(input: CreateTaskInput, dryRun: boolean | null): Promise<number> {
      return callOp<number>('POST', '/boards/import', { input, dry_run: dryRun });
    },
    async boardReset(): Promise<null> {
      return callOp<null>('POST', '/boards/reset');
    },
    async tagList(limit?: number, offset?: number, options?: ListOptions<TagSortKey>): Promise<PaginatedResult<Tag>> {
      const { data, meta } = await httpGet<JsonApiPageDocument>(`/tags${toQueryString({ sort: options?.sort, page: { offset, limit } })}`);
      return { items: data.map(flattenTag), total: meta.total, limit: meta.limit, offset: meta.offset };
    },
    async tagGetById(id: string): Promise<Tag> {
      const { data } = await httpGet<JsonApiResourceDocument>(`/tags/${encodeURIComponent(id)}`);
      return flattenTag(data);
    },
    async tagCreate(input: CreateTagInput): Promise<Tag> {
      const { data } = await httpPost<JsonApiResourceDocument>('/tags', unflattenTag(input));
      return flattenTag(data);
    },
    async tagUpdate(id: string, input: UpdateTagInput): Promise<Tag> {
      const { data } = await httpPatch<JsonApiResourceDocument>(
        `/tags/${encodeURIComponent(id)}`,
        unflattenTag(input, id),
      );
      return flattenTag(data);
    },
    async tagDelete(id: string): Promise<null> {
      await httpDelete(`/tags/${encodeURIComponent(id)}`);
      return null;
    },
    async taskList(limit?: number, offset?: number, options?: ListOptions<TaskSortKey>): Promise<PaginatedResult<Task>> {
      const { data, meta } = await httpGet<JsonApiPageDocument>(`/tasks${toQueryString({ sort: options?.sort, page: { offset, limit } })}`);
      return { items: data.map(flattenTask), total: meta.total, limit: meta.limit, offset: meta.offset };
    },
    async taskGetById(id: string): Promise<Task> {
      const { data } = await httpGet<JsonApiResourceDocument>(`/tasks/${encodeURIComponent(id)}`);
      return flattenTask(data);
    },
    async taskCreate(input: CreateTaskInput): Promise<Task> {
      const { data } = await httpPost<JsonApiResourceDocument>('/tasks', unflattenTask(input));
      return flattenTask(data);
    },
    async taskUpdate(id: string, input: UpdateTaskInput): Promise<Task> {
      const { data } = await httpPatch<JsonApiResourceDocument>(
        `/tasks/${encodeURIComponent(id)}`,
        unflattenTask(input, id),
      );
      return flattenTask(data);
    },
    async taskDelete(id: string): Promise<null> {
      await httpDelete(`/tasks/${encodeURIComponent(id)}`);
      return null;
    },
    async taskListLabels(taskId: string, limit?: number, offset?: number): Promise<PaginatedResult<Tag>> {
      const { data, meta } = await httpGet<JsonApiPageDocument>(`/tasks/${encodeURIComponent(taskId)}/labels${toQueryString({ page: { offset, limit } })}`);
      return { items: data.map(flattenTag), total: meta.total, limit: meta.limit, offset: meta.offset };
    },
    async taskAddLabel(taskId: string, tagId: string): Promise<null> {
      await httpPost(`/tasks/${encodeURIComponent(taskId)}/relationships/labels`, { data: [{ type: 'tags', id: tagId }] });
      return null;
    },
    async taskRemoveLabel(taskId: string, tagId: string): Promise<null> {
      await httpDelete(`/tasks/${encodeURIComponent(taskId)}/relationships/labels`, { data: [{ type: 'tags', id: tagId }] });
      return null;
    },
    async taskListDrafts(taskId: string): Promise<Task[]> {
      return callOp<Task[]>('GET', `/tasks/list-drafts/${encodeURIComponent(taskId)}`);
    },
    async workoutSetList(limit?: number, offset?: number, options?: ListOptions<WorkoutSetSortKey>): Promise<PaginatedResult<WorkoutSet>> {
      const { data, meta } = await httpGet<JsonApiPageDocument>(`/workout-sets${toQueryString({ sort: options?.sort, page: { offset, limit } })}`);
      return { items: data.map(flattenWorkoutSet), total: meta.total, limit: meta.limit, offset: meta.offset };
    },
    async workoutSetGetById(id: string): Promise<WorkoutSet> {
      const { data } = await httpGet<JsonApiResourceDocument>(`/workout-sets/${encodeURIComponent(id)}`);
      return flattenWorkoutSet(data);
    },
    async workoutSetCreate(input: CreateWorkoutSetInput): Promise<WorkoutSet> {
      const { data } = await httpPost<JsonApiResourceDocument>('/workout-sets', unflattenWorkoutSet(input));
      return flattenWorkoutSet(data);
    },
    async workoutSetUpdate(id: string, input: UpdateWorkoutSetInput): Promise<WorkoutSet> {
      const { data } = await httpPatch<JsonApiResourceDocument>(
        `/workout-sets/${encodeURIComponent(id)}`,
        unflattenWorkoutSet(input, id),
      );
      return flattenWorkoutSet(data);
    },
    async workoutSetDelete(id: string): Promise<null> {
      await httpDelete(`/workout-sets/${encodeURIComponent(id)}`);
      return null;
    },
    async workoutSetListTags(setId: string, limit?: number, offset?: number): Promise<PaginatedResult<string>> {
      const { data, meta } = await httpGet<JsonApiPageDocument<JsonApiResourceIdentifier>>(`/workout-sets/${encodeURIComponent(setId)}/relationships/tags${toQueryString({ page: { offset, limit } })}`);
      return { items: data.map((i) => i.id), total: meta.total, limit: meta.limit, offset: meta.offset };
    },
    async workoutSetAddTag(setId: string, tagId: string): Promise<null> {
      await httpPost(`/workout-sets/${encodeURIComponent(setId)}/relationships/tags`, { data: [{ type: 'tags', id: tagId }] });
      return null;
    },
    async workoutSetRemoveTag(setId: string, tagId: string): Promise<null> {
      await httpDelete(`/workout-sets/${encodeURIComponent(setId)}/relationships/tags`, { data: [{ type: 'tags', id: tagId }] });
      return null;
    },
    async subscribeTaskChanges(args: { resume?: string | null }, handlers: SubscriptionHandlers<Task>): Promise<() => void> {
      return subscribeSse(
        (resume) => `${BASE}${`/events/task-changes`}` + toQueryString({ resume: resume }),
        'task-changes',
        args.resume ?? null,
        (frame) => flattenTask(frame as JsonApiResource),
        handlers,
      );
    },
  };
}

// ── IPC Helpers ──

async function subscribeIpc<T>(
  command: string,
  unsubscribeCommand: string,
  args: Record<string, unknown>,
  handlers: SubscriptionHandlers<T>,
): Promise<() => void> {
  const channel = new Channel<EventFrame<T>>();
  channel.onmessage = (frame) => {
    if (frame.kind === 'event') handlers.onEvent(frame.data, frame.id ?? null);
    else handlers.onLag?.(frame.skipped);
  };
  const id = await invoke<number>(command, { ...args, channel });
  handlers.onOpen?.();
  return () => {
    invoke(unsubscribeCommand, { id }).catch((err: unknown) => handlers.onError?.(err));
  };
}

// ── IPC Transport ──

export function createIpcTransport(): Transport {
  return {
    async boardList(limit?: number, offset?: number): Promise<PaginatedResult<Task>> {
      return invoke('board_list', { limit: limit ?? null, offset: offset ?? null });
    },
    async boardGetById(id: string): Promise<Task> {
      return invoke('board_get_by_id', { id });
    },
    async boardCreate(input: CreateTaskInput): Promise<Task> {
      return invoke('board_create', { input });
    },
    async boardUpdate(id: string, input: UpdateTaskInput): Promise<Task> {
      return invoke('board_update', { id, input });
    },
    async boardDelete(id: string): Promise<null> {
      await invoke('board_delete', { id });
      return null;
    },
    async boardListTags(boardId: string, limit?: number, offset?: number): Promise<PaginatedResult<Tag>> {
      return invoke('board_list_tags', { boardId, limit: limit ?? null, offset: offset ?? null });
    },
    async boardAddTag(boardId: string, tagId: string): Promise<null> {
      await invoke('board_add_tag', { boardId, tagId });
      return null;
    },
    async boardRemoveTag(boardId: string, tagId: string): Promise<null> {
      await invoke('board_remove_tag', { boardId, tagId });
      return null;
    },
    async boardGetSummary(id: string, includeDone: boolean | null): Promise<Task> {
      return invoke('board_get_summary', { id, includeDone });
    },
    async boardArchive(taskId: string, reason: string | null): Promise<Task> {
      return invoke('board_archive', { taskId, reason });
    },
    async boardImport(input: CreateTaskInput, dryRun: boolean | null): Promise<number> {
      return invoke('board_import', { input, dryRun });
    },
    async boardReset(): Promise<null> {
      await invoke('board_reset');
      return null;
    },
    async tagList(limit?: number, offset?: number, options?: ListOptions<TagSortKey>): Promise<PaginatedResult<Tag>> {
      return invoke('tag_list', { sort: options?.sort, limit: limit ?? null, offset: offset ?? null });
    },
    async tagGetById(id: string): Promise<Tag> {
      return invoke('tag_get_by_id', { id });
    },
    async tagCreate(input: CreateTagInput): Promise<Tag> {
      return invoke('tag_create', { input });
    },
    async tagUpdate(id: string, input: UpdateTagInput): Promise<Tag> {
      return invoke('tag_update', { id, input });
    },
    async tagDelete(id: string): Promise<null> {
      await invoke('tag_delete', { id });
      return null;
    },
    async taskList(limit?: number, offset?: number, options?: ListOptions<TaskSortKey>): Promise<PaginatedResult<Task>> {
      return invoke('task_list', { sort: options?.sort, limit: limit ?? null, offset: offset ?? null });
    },
    async taskGetById(id: string): Promise<Task> {
      return invoke('task_get_by_id', { id });
    },
    async taskCreate(input: CreateTaskInput): Promise<Task> {
      return invoke('task_create', { input });
    },
    async taskUpdate(id: string, input: UpdateTaskInput): Promise<Task> {
      return invoke('task_update', { id, input });
    },
    async taskDelete(id: string): Promise<null> {
      await invoke('task_delete', { id });
      return null;
    },
    async taskListLabels(taskId: string, limit?: number, offset?: number): Promise<PaginatedResult<Tag>> {
      return invoke('task_list_labels', { taskId, limit: limit ?? null, offset: offset ?? null });
    },
    async taskAddLabel(taskId: string, tagId: string): Promise<null> {
      await invoke('task_add_label', { taskId, tagId });
      return null;
    },
    async taskRemoveLabel(taskId: string, tagId: string): Promise<null> {
      await invoke('task_remove_label', { taskId, tagId });
      return null;
    },
    async taskListDrafts(taskId: string): Promise<Task[]> {
      return invoke('task_list_drafts', { taskId });
    },
    async workoutSetList(limit?: number, offset?: number, options?: ListOptions<WorkoutSetSortKey>): Promise<PaginatedResult<WorkoutSet>> {
      return invoke('workout_set_list', { sort: options?.sort, limit: limit ?? null, offset: offset ?? null });
    },
    async workoutSetGetById(id: string): Promise<WorkoutSet> {
      return invoke('workout_set_get_by_id', { id });
    },
    async workoutSetCreate(input: CreateWorkoutSetInput): Promise<WorkoutSet> {
      return invoke('workout_set_create', { input });
    },
    async workoutSetUpdate(id: string, input: UpdateWorkoutSetInput): Promise<WorkoutSet> {
      return invoke('workout_set_update', { id, input });
    },
    async workoutSetDelete(id: string): Promise<null> {
      await invoke('workout_set_delete', { id });
      return null;
    },
    async workoutSetListTags(setId: string, limit?: number, offset?: number): Promise<PaginatedResult<string>> {
      return invoke('workout_set_list_tags', { setId, limit: limit ?? null, offset: offset ?? null });
    },
    async workoutSetAddTag(setId: string, tagId: string): Promise<null> {
      await invoke('workout_set_add_tag', { setId, tagId });
      return null;
    },
    async workoutSetRemoveTag(setId: string, tagId: string): Promise<null> {
      await invoke('workout_set_remove_tag', { setId, tagId });
      return null;
    },
    async subscribeTaskChanges(args: { resume?: string | null }, handlers: SubscriptionHandlers<Task>): Promise<() => void> {
      return subscribeIpc('task_changes_subscribe', 'task_changes_unsubscribe', { resume: args.resume ?? null }, handlers);
    },
  };
}
