// TODO: review — banner strings updated from old crate names
//! Generate markdown writer functions from parsed ontology entity definitions.
//!
//! For each entity, generates a `render_{entity}(entity: &crate::schema::{Name}) -> String`
//! function that serializes the entity to a YAML-frontmatter markdown file.
//!
//! Generated code is written to `{writer_output}/{entity}.rs` and a `mod.rs`
//! re-exporting all modules.

use std::fs;
use std::path::Path;

use crate::persistence::seaorm::gen_entity::to_snake_case;
use crate::schema::model::{EntityDef, FieldDef, FieldRole, FieldType, RelationKind};

// ─── Public API ──────────────────────────────────────────────────────────────

/// Generate writer modules and write them to the output directory.
pub fn generate(entities: &[EntityDef], output_dir: &Path) -> Result<(), String> {
    fs::create_dir_all(output_dir).map_err(|e| format!("Failed to create output dir {}: {e}", output_dir.display()))?;

    // Clean stale files from previous entity names.
    // Include all fixed files (helpers, dirs, fs_ops, parser_dispatch, mod) in the expected set
    // so only renamed/deleted entity files get removed.
    let expected: std::collections::HashSet<String> = entities
        .iter()
        .map(|e| format!("{}.rs", to_snake_case(&e.name)))
        .chain(["helpers.rs", "mod.rs", "dirs.rs", "fs_ops.rs", "parser_dispatch.rs"].iter().map(|s| s.to_string()))
        .collect();
    crate::clean_generated_dir(output_dir, &expected);

    // Write helpers module
    let helpers_path = output_dir.join("helpers.rs");
    crate::write_and_format(&helpers_path, HELPERS_CODE).map_err(|e| format!("Failed to write {}: {e}", helpers_path.display()))?;

    let mut mod_names = vec!["helpers".to_string()];

    for entity in entities {
        let mod_name = to_snake_case(&entity.name);
        let code = generate_writer_code(entity);
        let path = output_dir.join(format!("{mod_name}.rs"));
        crate::write_and_format(&path, &code).map_err(|e| format!("Failed to write {}: {e}", path.display()))?;
        mod_names.push(mod_name);
    }

    // Collect entity (mod_name, snake_name) pairs for the renders block
    let entity_render_names: Vec<String> = entities.iter().map(|e| to_snake_case(&e.name)).collect();

    // Write mod.rs
    mod_names.sort();
    let mod_rs = generate_mod_rs(&mod_names, &entity_render_names);
    let path = output_dir.join("mod.rs");
    crate::write_and_format(&path, &mod_rs).map_err(|e| format!("Failed to write {}: {e}", path.display()))?;

    Ok(())
}

// ─── Shared helpers code (rendered once) ─────────────────────────────────────

const HELPERS_CODE: &str = r#"//! Generated by ontogen. DO NOT EDIT.
//!
//! Shared helper functions for markdown YAML frontmatter rendering.

/// Conditionally double-quote a scalar string if it contains YAML-special characters.
pub fn yaml_safe_scalar(s: &str) -> String {
    if s.is_empty() {
        return "\"\"".to_string();
    }

    let needs_quoting = s != s.trim()
        || s.contains(": ")
        || s.contains(" #")
        || s.contains('#')
        || s.contains('[')
        || s.contains(']')
        || s.contains('{')
        || s.contains('}')
        || s.contains(',')
        || s.contains('&')
        || s.contains('*')
        || s.contains('?')
        || s.contains('|')
        || s.contains('>')
        || s.contains('\'')
        || s.contains('"')
        || s.contains('\\')
        || s.starts_with('-')
        || s.starts_with('!')
        || s.starts_with('%')
        || s.starts_with('@');

    if needs_quoting {
        let escaped = s.replace('\\', "\\\\").replace('"', "\\\"");
        format!("\"{escaped}\"")
    } else {
        s.to_string()
    }
}

/// Render a list as a YAML inline sequence: `[a, b, c]`
pub fn yaml_inline_list(items: &[String]) -> String {
    let inner: Vec<String> = items.iter().map(|s| yaml_safe_scalar(s)).collect();
    format!("[{}]", inner.join(", "))
}

/// Wrap an ID in wikilink syntax, quoted for YAML safety: `"[[id]]"`
pub fn wikilink(id: &str) -> String {
    format!("\"[[{id}]]\"")
}

/// Render a list of IDs as a YAML inline sequence of quoted wikilinks.
pub fn yaml_inline_wikilink_list(items: &[String]) -> String {
    let inner: Vec<String> = items.iter().map(|id| wikilink(id)).collect();
    format!("[{}]", inner.join(", "))
}

/// Append the body text after the frontmatter closing delimiter.
pub fn append_body(out: &mut String, body: &str) {
    if !body.is_empty() {
        out.push_str(body);
        if !body.ends_with('\n') {
            out.push('\n');
        }
    }
}
"#;

// ─── Code Generation ─────────────────────────────────────────────────────────

/// Generate the full writer module for one entity.
fn generate_writer_code(entity: &EntityDef) -> String {
    let entity_name = &entity.name;
    let mod_name = to_snake_case(entity_name);
    let type_name = &entity.type_name;

    // Collect the set of belongs_to field names that have a corresponding has_many reverse.
    // These should NOT be rendered in the writer (the has_many side renders the data instead).
    let hidden_belongs_to = find_hidden_belongs_to(entity);

    let mut field_lines = Vec::new();

    for field in &entity.fields {
        if matches!(field.role, FieldRole::Body) {
            continue; // Body is appended at the end
        }

        // Skip belongs_to fields that have a has_many reverse on the same entity
        if hidden_belongs_to.contains(&field.name.as_str()) {
            continue;
        }

        if let Some(code) = generate_field_render(field, entity) {
            field_lines.push(code);
        }
    }

    let fields_code = field_lines.join("\n");

    let body_field = entity.body_field().map(|f| f.name.as_str()).unwrap_or("body");

    // Determine which helpers are actually used
    let imports = collect_used_helpers(&fields_code);

    format!(
        r#"//! Generated by ontogen. DO NOT EDIT.

use super::helpers::{{{imports}}};

/// Render a `{entity_name}` to a YAML-frontmatter markdown string.
pub fn render_{mod_name}(entity: &crate::schema::{entity_name}) -> String {{
    let mut fm = String::from("---\ntype: {type_name}\n");

{fields_code}

    fm.push_str("---\n");
    append_body(&mut fm, &entity.{body_field});
    fm
}}
"#
    )
}

/// Determine which helper functions are referenced in the generated field code.
fn collect_used_helpers(code: &str) -> String {
    let mut used: Vec<&str> = Vec::new();
    if code.contains("yaml_safe_scalar") {
        used.push("yaml_safe_scalar");
    }
    if code.contains("yaml_inline_list") {
        used.push("yaml_inline_list");
    }
    // Check for standalone `wikilink(` — not inside `yaml_inline_wikilink_list(`
    let has_inline_wikilink_list = code.contains("yaml_inline_wikilink_list");
    let has_standalone_wikilink = code.replace("yaml_inline_wikilink_list", "").contains("wikilink(");
    if has_standalone_wikilink {
        used.push("wikilink");
    }
    if has_inline_wikilink_list {
        used.push("yaml_inline_wikilink_list");
    }
    // append_body is always used (for the body field)
    used.push("append_body");
    used.join(", ")
}

/// Find belongs_to fields that have a corresponding has_many on the same entity.
/// For example, `parent_id` is hidden because `contains` (has_many, foreign_key = "parent_id") exists.
fn find_hidden_belongs_to(entity: &EntityDef) -> Vec<&str> {
    let has_many_fks: Vec<&str> =
        entity.has_many_relations().filter_map(|(_, info)| info.foreign_key.as_deref()).collect();

    entity
        .belongs_to_relations()
        .filter(|(field, _)| has_many_fks.contains(&field.name.as_str()))
        .map(|(field, _)| field.name.as_str())
        .collect()
}

/// Generate the rendering code for a single field.
fn generate_field_render(field: &FieldDef, entity: &EntityDef) -> Option<String> {
    let fm_key = field.name.as_str();

    match &field.role {
        FieldRole::Id => Some(generate_id_render(field, fm_key)),
        FieldRole::EnumField => Some(generate_enum_render(field, fm_key)),
        FieldRole::Relation(info) => generate_relation_render(field, fm_key, info, entity),
        FieldRole::Plain => Some(generate_plain_render(field, fm_key)),
        FieldRole::Skip => Some(generate_skip_render(field, fm_key)),
        FieldRole::Body => None, // handled separately
    }
}

/// Generate rendering for the ID field.
fn generate_id_render(field: &FieldDef, fm_key: &str) -> String {
    let field_name = &field.name;
    match &field.field_type {
        FieldType::I32 => {
            // Integer IDs (e.g., Evidence) — don't render in frontmatter
            // These are auto-assigned and will be migrated to String in Phase 7
            String::new()
        }
        _ => {
            format!(r#"    fm.push_str(&format!("{fm_key}: {{}}\n", entity.{field_name}));"#)
        }
    }
}

/// Generate rendering for an enum field.
fn generate_enum_render(field: &FieldDef, fm_key: &str) -> String {
    let field_name = &field.name;
    match &field.field_type {
        FieldType::OptionEnum(_) => {
            format!(
                r#"    if let Some(ref val) = entity.{field_name} {{
        fm.push_str(&format!("{fm_key}: {{}}\n", yaml_safe_scalar(&crate::persistence::db::conversions::enum_to_string(val))));
    }}"#
            )
        }
        // Required enum (e.g., RequirementStatus, ContractType)
        _ => {
            format!(
                r#"    fm.push_str(&format!("{fm_key}: {{}}\n", yaml_safe_scalar(&crate::persistence::db::conversions::enum_to_string(&entity.{field_name}))));"#
            )
        }
    }
}

/// Generate rendering for a relation field.
fn generate_relation_render(
    field: &FieldDef,
    fm_key: &str,
    info: &crate::schema::model::RelationInfo,
    _entity: &EntityDef,
) -> Option<String> {
    let field_name = &field.name;

    match info.kind {
        RelationKind::BelongsTo => match &field.field_type {
            FieldType::OptionString => Some(format!(
                r#"    if let Some(ref val) = entity.{field_name} {{
        fm.push_str(&format!("{fm_key}: {{}}\n", wikilink(val)));
    }}"#
            )),
            FieldType::String => {
                Some(format!(r#"    fm.push_str(&format!("{fm_key}: {{}}\n", wikilink(&entity.{field_name})));"#))
            }
            _ => None,
        },
        RelationKind::HasMany | RelationKind::ManyToMany => Some(generate_vec_wikilink_render(field, fm_key)),
    }
}

/// Generate rendering for a Vec wikilink field (has_many or many_to_many).
fn generate_vec_wikilink_render(field: &FieldDef, fm_key: &str) -> String {
    let field_name = &field.name;

    if field.multiline_list {
        format!(
            r#"    if !entity.{field_name}.is_empty() {{
        fm.push_str("{fm_key}:\n");
        for item in &entity.{field_name} {{
            fm.push_str(&format!("  - {{}}\n", wikilink(item)));
        }}
    }}"#
        )
    } else {
        format!(
            r#"    if !entity.{field_name}.is_empty() {{
        fm.push_str(&format!("{fm_key}: {{}}\n", yaml_inline_wikilink_list(&entity.{field_name})));
    }}"#
        )
    }
}

/// Generate rendering for a plain (non-relation, non-enum) field.
fn generate_plain_render(field: &FieldDef, fm_key: &str) -> String {
    let field_name = &field.name;

    // Handle default_value suppression
    if let Some(ref default) = field.default_value {
        return format!(
            r#"    if entity.{field_name} != "{default}" {{
        fm.push_str(&format!("{fm_key}: {{}}\n", yaml_safe_scalar(&entity.{field_name})));
    }}"#
        );
    }

    match &field.field_type {
        FieldType::String => {
            format!(r#"    fm.push_str(&format!("{fm_key}: {{}}\n", yaml_safe_scalar(&entity.{field_name})));"#)
        }
        FieldType::OptionString => {
            format!(
                r#"    if let Some(ref val) = entity.{field_name} {{
        fm.push_str(&format!("{fm_key}: {{}}\n", yaml_safe_scalar(val)));
    }}"#
            )
        }
        FieldType::OptionEnum(_) => {
            // Plain OptionEnum without enum_field annotation — use Display trait
            format!(
                r#"    if let Some(ref val) = entity.{field_name} {{
        fm.push_str(&format!("{fm_key}: {{}}\n", yaml_safe_scalar(&val.to_string())));
    }}"#
            )
        }
        FieldType::VecString => generate_vec_string_render(field, fm_key),
        FieldType::VecStruct(_) => {
            // VecStruct fields are too complex for generic codegen.
            // They must be handled by a manual wrapper around the generated writer.
            format!(
                r#"    // NOTE: VecStruct field `{field_name}` requires manual rendering.
    // Add custom code in a wrapper function to handle this field."#
            )
        }
        FieldType::I32 => {
            format!(r#"    fm.push_str(&format!("{fm_key}: {{}}\n", entity.{field_name}));"#)
        }
        FieldType::OptionI32 => {
            format!(
                r#"    if let Some(val) = entity.{field_name} {{
        fm.push_str(&format!("{fm_key}: {{}}\n", val));
    }}"#
            )
        }
        FieldType::Other(_) => {
            format!(r#"    // NOTE: Field `{field_name}` has an unrecognized type and was skipped."#)
        }
    }
}

/// Generate rendering for a Vec<String> field (non-relation).
fn generate_vec_string_render(field: &FieldDef, fm_key: &str) -> String {
    let field_name = &field.name;

    if field.multiline_list {
        format!(
            r#"    if !entity.{field_name}.is_empty() {{
        fm.push_str("{fm_key}:\n");
        for item in &entity.{field_name} {{
            fm.push_str(&format!("  - {{}}\n", yaml_safe_scalar(item)));
        }}
    }}"#
        )
    } else {
        format!(
            r#"    if !entity.{field_name}.is_empty() {{
        fm.push_str(&format!("{fm_key}: {{}}\n", yaml_inline_list(&entity.{field_name})));
    }}"#
        )
    }
}

/// Generate rendering for a Skip field.
/// Skip fields are excluded from DB codegen but still appear in markdown.
fn generate_skip_render(field: &FieldDef, fm_key: &str) -> String {
    // Skip fields are rendered the same as Plain fields for the writer
    generate_plain_render(field, fm_key)
}

/// Generate mod.rs content.
fn generate_mod_rs(mod_names: &[String], entity_render_names: &[String]) -> String {
    let mut code = String::from("//! Generated by ontogen. DO NOT EDIT.\n\n");

    // Module declarations — writer modules + generated support modules
    for name in mod_names {
        code.push_str(&format!("pub mod {name};\n"));
    }
    code.push_str("pub mod dirs;\n");
    code.push_str("pub mod fs_ops;\n");
    code.push_str("pub mod parser_dispatch;\n");

    // Re-export all render functions (flat, for backward compat)
    code.push('\n');
    let mut sorted_renders: Vec<&String> = entity_render_names.iter().collect();
    sorted_renders.sort();
    for name in &sorted_renders {
        code.push_str(&format!("pub use {name}::render_{name};\n"));
    }

    // Renders module for glob import
    code.push_str("\n/// Re-exports of all generated render functions.\n");
    code.push_str("/// Use `renders::*` for glob import in the writers module.\n");
    code.push_str("pub mod renders {\n");
    for name in &sorted_renders {
        code.push_str(&format!("    pub use super::{name}::render_{name};\n"));
    }
    code.push_str("}\n");

    code
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schema::model::*;

    fn make_node_entity() -> EntityDef {
        EntityDef {
            name: "Node".to_string(),
            directory: "nodes".to_string(),
            table: "nodes".to_string(),
            type_name: "node".to_string(),
            prefix: "node".to_string(),

            fields: vec![
                FieldDef::new("id", FieldType::String, FieldRole::Id),
                FieldDef::new("name", FieldType::String, FieldRole::Plain),
                FieldDef::new("kind", FieldType::OptionEnum("NodeKind".to_string()), FieldRole::EnumField),
                FieldDef::new(
                    "parent_id",
                    FieldType::OptionString,
                    FieldRole::Relation(RelationInfo {
                        kind: RelationKind::BelongsTo,
                        target: "Node".to_string(),
                        junction: None,
                        foreign_key: None,
                    }),
                ),
                FieldDef::new(
                    "contains",
                    FieldType::VecString,
                    FieldRole::Relation(RelationInfo {
                        kind: RelationKind::HasMany,
                        target: "Node".to_string(),
                        junction: None,
                        foreign_key: Some("parent_id".to_string()),
                    }),
                ),
                FieldDef::new("owner", FieldType::OptionString, FieldRole::Plain),
                FieldDef::new("tags", FieldType::VecString, FieldRole::Plain),
                {
                    let mut f = FieldDef::new("context", FieldType::VecString, FieldRole::Plain);
                    f.multiline_list = true;
                    f
                },
                FieldDef::new("body", FieldType::String, FieldRole::Body),
                FieldDef::new(
                    "fulfills",
                    FieldType::VecString,
                    FieldRole::Relation(RelationInfo {
                        kind: RelationKind::ManyToMany,
                        target: "Requirement".to_string(),
                        junction: None,
                        foreign_key: None,
                    }),
                ),
            ],
        }
    }

    #[test]
    fn node_writer_structure() {
        let code = generate_writer_code(&make_node_entity());

        // Function signature
        assert!(code.contains("pub fn render_node(entity: &crate::schema::Node) -> String"));

        // Type header
        assert!(code.contains(r#"type: node\n"#));

        // ID field
        assert!(code.contains("id: {}"));

        // Name field (plain string)
        assert!(code.contains("yaml_safe_scalar(&entity.name)"));

        // Kind field (optional enum)
        assert!(code.contains("enum_to_string(val)"));

        // parent_id should be HIDDEN (has_many `contains` covers it)
        assert!(!code.contains("parent_id"), "parent_id should be hidden by contains has_many");

        // contains (has_many, inline wikilink list by default)
        assert!(code.contains("yaml_inline_wikilink_list(&entity.contains)"));

        // owner (optional string)
        assert!(code.contains("yaml_safe_scalar(val)"));

        // tags (plain vec, inline)
        assert!(code.contains("yaml_inline_list(&entity.tags)"));

        // context (plain vec, multiline)
        assert!(code.contains(r#"fm.push_str("context:\n")"#));
        assert!(code.contains("yaml_safe_scalar(item)"));

        // fulfills (many_to_many, inline wikilink)
        assert!(code.contains("yaml_inline_wikilink_list(&entity.fulfills)"));

        // body handled at end
        assert!(code.contains("append_body(&mut fm, &entity.body)"));
    }

    #[test]
    fn contract_field_names_used_as_yaml_keys() {
        let entity = EntityDef {
            name: "Contract".to_string(),
            directory: "contract".to_string(),
            table: "contracts".to_string(),
            type_name: "contract".to_string(),
            prefix: "contract".to_string(),
            fields: vec![
                FieldDef::new("id", FieldType::String, FieldRole::Id),
                FieldDef::new("contract_type", FieldType::Other("ContractType".to_string()), FieldRole::EnumField),
                FieldDef::new(
                    "contract_state",
                    FieldType::OptionEnum("ContractState".to_string()),
                    FieldRole::EnumField,
                ),
                FieldDef::new("body", FieldType::String, FieldRole::Body),
            ],
        };

        let code = generate_writer_code(&entity);

        // field names are used directly as YAML keys
        assert!(code.contains(r#"contract_type: {}"#), "contract_type should use field name as YAML key");
        assert!(code.contains(r#"contract_state: {}"#), "contract_state should use field name as YAML key");
    }

    #[test]
    fn default_value_suppression() {
        let entity = EntityDef {
            name: "Requirement".to_string(),
            directory: "requirements".to_string(),
            table: "requirements".to_string(),
            type_name: "requirement".to_string(),
            prefix: "req".to_string(),

            fields: vec![
                FieldDef::new("id", FieldType::String, FieldRole::Id),
                {
                    let mut f = FieldDef::new("disposition", FieldType::String, FieldRole::Plain);
                    f.default_value = Some("active".to_string());
                    f
                },
                FieldDef::new("body", FieldType::String, FieldRole::Body),
            ],
        };

        let code = generate_writer_code(&entity);
        assert!(code.contains(r#"entity.disposition != "active""#), "should suppress rendering when value == default");
    }

    #[test]
    fn skip_fields_still_rendered() {
        let entity = EntityDef {
            name: "Contract".to_string(),
            directory: "contract".to_string(),
            table: "contracts".to_string(),
            type_name: "contract".to_string(),
            prefix: "contract".to_string(),

            fields: vec![
                FieldDef::new("id", FieldType::String, FieldRole::Id),
                FieldDef::new("states", FieldType::VecString, FieldRole::Skip),
                FieldDef::new("body", FieldType::String, FieldRole::Body),
            ],
        };

        let code = generate_writer_code(&entity);
        assert!(code.contains("entity.states"), "skip fields should still be rendered in writers");
        assert!(code.contains("yaml_inline_list"), "skip VecString should render as inline list");
    }

    #[test]
    fn multiline_wikilink_list() {
        let entity = EntityDef {
            name: "Task".to_string(),
            directory: "task".to_string(),
            table: "tasks".to_string(),
            type_name: "task".to_string(),
            prefix: "task".to_string(),

            fields: vec![
                FieldDef::new("id", FieldType::String, FieldRole::Id),
                {
                    let mut f = FieldDef::new(
                        "depends_on",
                        FieldType::VecString,
                        FieldRole::Relation(RelationInfo {
                            kind: RelationKind::ManyToMany,
                            target: "Task".to_string(),
                            junction: None,
                            foreign_key: None,
                        }),
                    );
                    f.multiline_list = true;
                    f
                },
                FieldDef::new("body", FieldType::String, FieldRole::Body),
            ],
        };

        let code = generate_writer_code(&entity);
        assert!(code.contains(r#"fm.push_str("depends_on:\n")"#), "multiline wikilink list should use block format");
        assert!(code.contains("wikilink(item)"), "multiline wikilink list should wrap items");
    }

    #[test]
    fn i32_id_not_rendered() {
        let entity = EntityDef {
            name: "Evidence".to_string(),
            directory: "evidence".to_string(),
            table: "evidence".to_string(),
            type_name: "evidence".to_string(),
            prefix: "evidence".to_string(),

            fields: vec![
                FieldDef::new("id", FieldType::I32, FieldRole::Id),
                FieldDef::new("source", FieldType::String, FieldRole::Plain),
                FieldDef::new("body", FieldType::String, FieldRole::Body),
            ],
        };

        let code = generate_writer_code(&entity);
        assert!(!code.contains("id: {}"), "i32 ID should not be rendered in frontmatter");
        assert!(code.contains("source: {}"), "other fields should render");
    }

    #[test]
    fn generate_all_real_schemas() {
        let schema_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../src-tauri/src/schema");
        if !schema_dir.exists() {
            eprintln!("Skipping: schema dir not found");
            return;
        }

        let entities = crate::schema::parse::parse_schema_dir(&schema_dir).unwrap();
        assert!(!entities.is_empty());

        for entity in &entities {
            let code = generate_writer_code(entity);
            let mod_name = to_snake_case(&entity.name);

            // Every entity should have a render function
            assert!(code.contains(&format!("pub fn render_{mod_name}")), "Missing render function for {}", entity.name);

            // Every entity should start with type header
            assert!(
                code.contains(&format!("type: {}\\n", entity.type_name)),
                "Missing type header for {}",
                entity.name
            );

            // Every entity should have append_body
            assert!(code.contains("append_body"), "Missing append_body for {}", entity.name);
        }

        // Spot checks for specific entities
        let find = |name: &str| entities.iter().find(|e| e.name == name).unwrap();

        // Capability: parent_id hidden, contains rendered
        let cap_code = generate_writer_code(find("Capability"));
        assert!(!cap_code.contains("parent_id:"), "Capability.parent_id should be hidden");
        assert!(cap_code.contains("entity.contains"), "Capability.contains should be rendered");

        // Contract: field names used as YAML keys
        let contract_code = generate_writer_code(find("Contract"));
        assert!(contract_code.contains(r#"contract_type: {}"#), "Contract.contract_type should use field name as key");
        assert!(
            contract_code.contains(r#"contract_state: {}"#),
            "Contract.contract_state should use field name as key"
        );
        // Skip fields rendered
        assert!(contract_code.contains("entity.states"), "Contract.states (skip) should be rendered");

        // Requirement: disposition default suppression
        let req_code = generate_writer_code(find("Requirement"));
        assert!(
            req_code.contains(r#"entity.disposition != "active""#),
            "Requirement.disposition should suppress default"
        );

        // UnitOfWork: multiline depends_on
        let uow_code = generate_writer_code(find("UnitOfWork"));
        assert!(uow_code.contains(r#"fm.push_str("depends_on:\n")"#), "UnitOfWork.depends_on should be multiline");

        // WorkExecution: required belongs_to fields rendered with wikilink
        let we_code = generate_writer_code(find("WorkExecution"));
        assert!(
            we_code.contains("wikilink(&entity.unit_of_work_id)"),
            "WorkExecution.unit_of_work_id should use wikilink"
        );
        assert!(
            we_code.contains("wikilink(&entity.workflow_template_id)"),
            "WorkExecution.workflow_template_id should use wikilink"
        );
    }
}
