//! Generate the per-entity `{Entity}Frontmatter` newtype: the typed boundary
//! between schema entities and their on-disk YAML frontmatter.
//!
//! One module per entity, each emitting:
//! - `{Entity}Frontmatter` — every persisted field except the id (the
//!   filename stem), the body (the markdown text after the fence), and
//!   `has_many` relation fields (derived views, reconstructed by reverse
//!   walk — storing them would create dual-write drift with the child FKs).
//! - `{ENTITY}_FM_FIELDS` — the full owned-key set, passed to
//!   `markdown_store::Document::merge_serialize` so cleared options are
//!   removed and hand-added keys survive.
//! - `from_{entity}` / `into_{entity}` — the only place wikilink syntax is
//!   handled: relation ids are encoded (`id` → `[[id]]`) on the way out and
//!   stripped on the way back. Generated CRUD code never touches brackets.
//!
//! The generated code depends on the `markdown-store` runtime crate (and
//! serde); it replaces the former emit-everything model — hand-rolled YAML
//! writers, a `serde_yaml_ng` parser dispatcher, and `fs_ops` helpers wired
//! to module paths nothing generated — with thin shims over the runtime.

use crate::schema::model::{EntityDef, FieldDef, FieldRole, FieldType, RelationKind};
use crate::store::helpers::to_snake_case;

// ─── Public API ──────────────────────────────────────────────────────────────

/// Generate all per-entity frontmatter modules plus the `mod.rs`.
pub fn generate(entities: &[EntityDef], output_dir: &std::path::Path) -> Result<(), String> {
    std::fs::create_dir_all(output_dir).map_err(|e| format!("create {}: {e}", output_dir.display()))?;

    let expected: std::collections::HashSet<String> = entities
        .iter()
        .map(|e| format!("{}.rs", to_snake_case(&e.name)))
        .chain(std::iter::once("mod.rs".to_string()))
        .collect();
    crate::clean_generated_dir(output_dir, &expected);

    let mut mod_names: Vec<String> = Vec::new();
    for entity in entities {
        let snake = to_snake_case(&entity.name);
        let code = generate_frontmatter_module(entity);
        crate::write_and_format(&output_dir.join(format!("{snake}.rs")), &code)
            .map_err(|e| format!("write {snake}.rs: {e}"))?;
        mod_names.push(snake);
    }

    mod_names.sort();
    let mut mod_rs = String::from("//! Generated by ontogen. DO NOT EDIT.\n\n");
    for name in &mod_names {
        mod_rs.push_str(&format!("pub mod {name};\n"));
    }
    crate::write_and_format(&output_dir.join("mod.rs"), &mod_rs).map_err(|e| format!("write mod.rs: {e}"))?;
    Ok(())
}

/// Generate one entity's frontmatter module source.
pub fn generate_frontmatter_module(entity: &EntityDef) -> String {
    let name = &entity.name;
    let snake = to_snake_case(name);
    let shout = snake.to_uppercase();
    let fields = frontmatter_fields(entity);

    let mut code = String::with_capacity(2048);
    code.push_str("//! Generated by ontogen. DO NOT EDIT.\n\n");
    code.push_str("use serde::{Deserialize, Serialize};\n\n");
    code.push_str(&format!("use crate::schema::{name};\n\n"));

    // ── struct ──
    code.push_str(&format!(
        "/// Frontmatter view of a {name}: every persisted field except the id (the\n\
         /// filename stem), the markdown body, and derived `has_many` views.\n\
         /// Relation ids are wikilink-encoded here and only here.\n"
    ));
    code.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
    code.push_str(&format!("pub struct {name}Frontmatter {{\n"));
    for field in &fields {
        for attr in serde_attrs(field) {
            code.push_str(&format!("    {attr}\n"));
        }
        code.push_str(&format!("    pub {}: {},\n", field.name, rust_type(field)));
    }
    code.push_str("}\n\n");

    // ── owned keys ──
    code.push_str(
        "/// The frontmatter keys this type owns — the full field set, so\n\
         /// `merge_serialize` removes cleared options and preserves hand-added keys.\n",
    );
    code.push_str(&format!("pub const {shout}_FM_FIELDS: &[&str] = &[\n"));
    for field in &fields {
        code.push_str(&format!("    \"{}\",\n", field.name));
    }
    code.push_str("];\n\n");

    // ── conversions ──
    code.push_str(&format!("impl {name}Frontmatter {{\n"));

    code.push_str(&format!("    pub fn from_{snake}(value: &{name}) -> Self {{\n"));
    code.push_str("        Self {\n");
    for field in &fields {
        code.push_str(&format!("            {}: {},\n", field.name, encode_expr(field)));
    }
    code.push_str("        }\n    }\n\n");

    let body_param = match entity.body_field() {
        Some(body) => format!(", {}: String", body.name),
        None => String::new(),
    };
    code.push_str(&format!("    pub fn into_{snake}(self, id: String{body_param}) -> {name} {{\n"));
    code.push_str(&format!("        {name} {{\n"));
    code.push_str("            id,\n");
    if let Some(body) = entity.body_field() {
        code.push_str(&format!("            {},\n", body.name));
    }
    for field in &fields {
        code.push_str(&format!("            {}: {},\n", field.name, decode_expr(field)));
    }
    for field in derived_fields(entity) {
        code.push_str(&format!("            // derived has_many view — reconstructed by populate_{snake}_relations\n"));
        code.push_str(&format!("            {}: Vec::new(),\n", field.name));
    }
    code.push_str("        }\n    }\n}\n");

    code
}

// ─── Field classification ────────────────────────────────────────────────────

/// Fields that live in frontmatter: everything except id, body, skip,
/// persistence-only legacy fields, and `has_many` derived views.
fn frontmatter_fields(entity: &EntityDef) -> Vec<&FieldDef> {
    entity
        .fields
        .iter()
        .filter(|f| {
            !matches!(f.role, FieldRole::Id | FieldRole::Body | FieldRole::Skip)
                && f.name != "wikilinks"
                && f.name != "source_file"
                && !is_has_many(f)
        })
        .collect()
}

/// `has_many` relation fields: derived views, never stored in frontmatter.
fn derived_fields(entity: &EntityDef) -> Vec<&FieldDef> {
    entity.fields.iter().filter(|f| is_has_many(f)).collect()
}

fn is_has_many(field: &FieldDef) -> bool {
    matches!(&field.role, FieldRole::Relation(info) if info.kind == RelationKind::HasMany)
}

fn is_relation(field: &FieldDef) -> bool {
    matches!(&field.role, FieldRole::Relation(_))
}

// ─── Emission helpers ────────────────────────────────────────────────────────

/// The frontmatter struct field type (same shape as the schema field).
fn rust_type(field: &FieldDef) -> String {
    match &field.field_type {
        FieldType::String => "String".into(),
        FieldType::OptionString => "Option<String>".into(),
        FieldType::OptionEnum(name) => format!("Option<crate::schema::{name}>"),
        FieldType::VecString => "Vec<String>".into(),
        FieldType::VecStruct(name) => format!("Vec<crate::schema::{name}>"),
        FieldType::I32 => "i32".into(),
        FieldType::OptionI32 => "Option<i32>".into(),
        FieldType::I64 => "i64".into(),
        FieldType::OptionI64 => "Option<i64>".into(),
        FieldType::F32 => "f32".into(),
        FieldType::OptionF32 => "Option<f32>".into(),
        FieldType::F64 => "f64".into(),
        FieldType::OptionF64 => "Option<f64>".into(),
        FieldType::Bool => "bool".into(),
        FieldType::OptionBool => "Option<bool>".into(),
        FieldType::Other(name) => name.clone(),
    }
}

/// Serde attributes: optionals skip-when-none (so cleared fields leave no
/// stale key, given the owned-keys merge), vecs skip-when-empty, and both
/// default on the way back in.
fn serde_attrs(field: &FieldDef) -> Vec<&'static str> {
    match &field.field_type {
        FieldType::OptionString
        | FieldType::OptionEnum(_)
        | FieldType::OptionI32
        | FieldType::OptionI64
        | FieldType::OptionF32
        | FieldType::OptionF64
        | FieldType::OptionBool => vec!["#[serde(default, skip_serializing_if = \"Option::is_none\")]"],
        FieldType::VecString | FieldType::VecStruct(_) => {
            vec!["#[serde(default, skip_serializing_if = \"Vec::is_empty\")]"]
        }
        _ => vec![],
    }
}

/// `from_{entity}` field expression: clone, wikilink-encoding relation ids.
fn encode_expr(field: &FieldDef) -> String {
    let name = &field.name;
    if is_relation(field) {
        match &field.field_type {
            FieldType::String => format!("markdown_store::wikilink::encode(&value.{name})"),
            FieldType::OptionString => {
                format!("value.{name}.as_deref().map(markdown_store::wikilink::encode)")
            }
            FieldType::VecString => {
                format!("value.{name}.iter().map(|v| markdown_store::wikilink::encode(v)).collect()")
            }
            _ => format!("value.{name}.clone()"),
        }
    } else {
        match &field.field_type {
            FieldType::I32
            | FieldType::I64
            | FieldType::F32
            | FieldType::F64
            | FieldType::Bool
            | FieldType::OptionI32
            | FieldType::OptionI64
            | FieldType::OptionF32
            | FieldType::OptionF64
            | FieldType::OptionBool => format!("value.{name}"),
            _ => format!("value.{name}.clone()"),
        }
    }
}

/// `into_{entity}` field expression: move, stripping wikilinks off relation ids.
fn decode_expr(field: &FieldDef) -> String {
    let name = &field.name;
    if is_relation(field) {
        match &field.field_type {
            FieldType::String => format!("markdown_store::wikilink::strip(&self.{name})"),
            FieldType::OptionString => format!("markdown_store::wikilink::strip_opt(self.{name})"),
            FieldType::VecString => format!("markdown_store::wikilink::strip_vec(self.{name})"),
            _ => format!("self.{name}"),
        }
    } else {
        format!("self.{name}")
    }
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schema::model::{EntityDef, FieldDef, FieldRole, FieldType, RelationInfo, RelationKind};

    fn relation(kind: RelationKind, junction: Option<&str>, fk: Option<&str>) -> FieldRole {
        FieldRole::Relation(RelationInfo {
            kind,
            target: "Other".to_string(),
            junction: junction.map(str::to_string),
            foreign_key: fk.map(str::to_string),
        })
    }

    fn task_entity() -> EntityDef {
        EntityDef {
            name: "Task".to_string(),
            directory: "tasks".to_string(),
            table: "tasks".to_string(),
            type_name: "task".to_string(),
            prefix: "task".to_string(),
            fields: vec![
                FieldDef::new("id", FieldType::String, FieldRole::Id),
                FieldDef::new("title", FieldType::String, FieldRole::Plain),
                FieldDef::new("estimate", FieldType::OptionI64, FieldRole::Plain),
                FieldDef::new("epic_id", FieldType::OptionString, relation(RelationKind::BelongsTo, None, None)),
                FieldDef::new(
                    "tags",
                    FieldType::VecString,
                    relation(RelationKind::ManyToMany, Some("task_tags"), None),
                ),
                FieldDef::new(
                    "subtasks",
                    FieldType::VecString,
                    relation(RelationKind::HasMany, None, Some("parent_id")),
                ),
                FieldDef::new("body", FieldType::String, FieldRole::Body),
            ],
        }
    }

    #[test]
    fn struct_excludes_id_body_and_has_many() {
        let code = generate_frontmatter_module(&task_entity());
        assert!(code.contains("pub struct TaskFrontmatter {"));
        assert!(code.contains("pub title: String"));
        assert!(code.contains("pub epic_id: Option<String>"));
        assert!(code.contains("pub tags: Vec<String>"));
        assert!(!code.contains("pub id:"), "id is the filename stem: {code}");
        assert!(!code.contains("pub body:"), "body lives after the fence: {code}");
        assert!(!code.contains("pub subtasks:"), "has_many is a derived view: {code}");
    }

    #[test]
    fn owned_keys_cover_exactly_the_frontmatter_fields() {
        let code = generate_frontmatter_module(&task_entity());
        assert!(code.contains("pub const TASK_FM_FIELDS: &[&str]"));
        for key in ["\"title\"", "\"estimate\"", "\"epic_id\"", "\"tags\""] {
            assert!(code.contains(key), "missing owned key {key}: {code}");
        }
        assert!(!code.contains("\"subtasks\""), "derived views are not owned keys: {code}");
        assert!(!code.contains("\"body\""));
    }

    #[test]
    fn conversions_wikilink_only_relations_and_rebuild_derived_views() {
        let code = generate_frontmatter_module(&task_entity());
        // encode on the way out…
        assert!(code.contains("value.epic_id.as_deref().map(markdown_store::wikilink::encode)"));
        assert!(code.contains("value.tags.iter().map(|v| markdown_store::wikilink::encode(v)).collect()"));
        assert!(code.contains("title: value.title.clone()"), "plain fields are plain: {code}");
        // …strip on the way back…
        assert!(code.contains("markdown_store::wikilink::strip_opt(self.epic_id)"));
        assert!(code.contains("markdown_store::wikilink::strip_vec(self.tags)"));
        // …and derived views come back empty for populate to fill.
        assert!(code.contains("subtasks: Vec::new()"));
        // body threads through the conversion signature.
        assert!(code.contains("pub fn into_task(self, id: String, body: String) -> Task"));
    }

    #[test]
    fn bodyless_entity_drops_the_body_parameter() {
        let mut entity = task_entity();
        entity.fields.retain(|f| !matches!(f.role, FieldRole::Body));
        let code = generate_frontmatter_module(&entity);
        assert!(code.contains("pub fn into_task(self, id: String) -> Task"), "no body param: {code}");
    }

    #[test]
    fn optionals_and_vecs_skip_serializing_when_absent() {
        let code = generate_frontmatter_module(&task_entity());
        assert!(code.contains("#[serde(default, skip_serializing_if = \"Option::is_none\")]"));
        assert!(code.contains("#[serde(default, skip_serializing_if = \"Vec::is_empty\")]"));
    }

    /// The generated module must parse as valid Rust.
    #[test]
    fn generated_code_is_valid_rust() {
        let code = generate_frontmatter_module(&task_entity());
        syn::parse_file(&code)
            .unwrap_or_else(|e| panic!("gen_frontmatter produced invalid Rust: {e}\n--- code ---\n{code}"));
    }
}
