// TODO: review — banner strings updated from old crate names
//! Generate markdown parser dispatch code from parsed ontology entity definitions.
//!
//! Generates:
//! - `OntologyElement` enum with variants for each entity type
//! - `ParseResult` struct with per-entity vectors
//! - `deserialize_frontmatter()` function with type-probing dispatch
//! - `push_parsed()` function with wikilink stripping and prefix checking
//!
//! All entities are deserialized directly into their schema types.
//!
//! Generated code is written to `{output_dir}/parser_dispatch.rs`.

use std::fs;
use std::path::Path;

use crate::persistence::seaorm::gen_entity::to_snake_case;
use crate::schema::model::{EntityDef, FieldRole, FieldType, RelationKind};

// ─── Public API ──────────────────────────────────────────────────────────────

/// Generate parser dispatch module and write it to the output directory.
///
/// Also appends `pub mod parser_dispatch;` to the existing `mod.rs` in the
/// output directory (which was created by `gen_writer`).
pub fn generate(entities: &[EntityDef], output_dir: &Path) -> Result<(), String> {
    fs::create_dir_all(output_dir).map_err(|e| format!("Failed to create output dir {}: {e}", output_dir.display()))?;

    let code = generate_parser_dispatch(entities);
    let path = output_dir.join("parser_dispatch.rs");
    crate::write_and_format(&path, &code).map_err(|e| format!("Failed to write {}: {e}", path.display()))?;

    // Append parser_dispatch module to mod.rs (created by gen_writer)
    let mod_path = output_dir.join("mod.rs");
    let existing = fs::read_to_string(&mod_path).unwrap_or_default();
    if !existing.contains("parser_dispatch") {
        let mut updated = existing;
        updated.push_str("\npub mod parser_dispatch;\n");
        crate::write_if_changed(&mod_path, &updated)
            .map_err(|e| format!("Failed to update {}: {e}", mod_path.display()))?;
    }

    Ok(())
}

/// Info about an entity for code generation purposes.
struct EntityInfo<'a> {
    entity: &'a EntityDef,
    snake_name: String,
}

fn build_entity_infos(entities: &[EntityDef]) -> Vec<EntityInfo<'_>> {
    entities.iter().map(|e| EntityInfo { entity: e, snake_name: to_snake_case(&e.name) }).collect()
}

// ─── Code Generation ─────────────────────────────────────────────────────────

fn generate_parser_dispatch(entities: &[EntityDef]) -> String {
    let infos = build_entity_infos(entities);

    let mut code = String::new();

    // Header
    code.push_str(
        r#"//! Generated by ontogen. DO NOT EDIT.
//!
//! Parser dispatch: OntologyElement enum, ParseResult struct, deserialize + push functions.

use std::path::Path;

use crate::schema::{ParseError, ParseWarning, Parsed, WikilinkRef};
"#,
    );

    // Import schema types
    generate_schema_imports(entities, &mut code);

    // Import wikilink utilities from hand-written ontology module
    code.push_str(
        r#"
use super::super::parser::ontology::{strip_wikilink, strip_wikilink_opt, strip_wikilinks_vec};
"#,
    );

    code.push('\n');

    // OntologyElement enum
    generate_ontology_element(&infos, &mut code);

    // ParseResult struct
    generate_parse_result(entities, &mut code);

    // deserialize_frontmatter function
    generate_deserialize_frontmatter(&infos, &mut code);

    // push_parsed function
    generate_push_parsed(&infos, &mut code);

    code
}

fn generate_schema_imports(entities: &[EntityDef], code: &mut String) {
    let type_names: Vec<&str> = entities.iter().map(|e| e.name.as_str()).collect();
    code.push_str(&format!("use crate::schema::{{{types}}};\n", types = type_names.join(", ")));
}

fn generate_ontology_element(infos: &[EntityInfo<'_>], code: &mut String) {
    code.push_str(
        r#"
/// Discriminated union of all ontology types, constructed after type probing.
#[derive(Debug)]
pub enum OntologyElement {
"#,
    );

    for info in infos {
        let name = &info.entity.name;
        code.push_str(&format!("    {name}({name}),\n"));
    }

    code.push_str("}\n\n");
}

fn generate_parse_result(entities: &[EntityDef], code: &mut String) {
    code.push_str(
        r#"/// The result of parsing a configuration directory.
///
/// Contains all successfully parsed entities and any warnings generated
/// during parsing. Malformed files produce warnings rather than preventing
/// the rest of the parse pipeline from succeeding.
#[derive(Debug, Default, Clone)]
pub struct ParseResult {
"#,
    );

    for entity in entities {
        let snake = to_snake_case(&entity.name);
        let name = &entity.name;

        // Use the pluralization from the existing code
        let field_name = parse_result_field_name(&snake);
        code.push_str(&format!("    pub {field_name}: Vec<Parsed<{name}>>,\n"));
    }

    code.push_str("    pub warnings: Vec<ParseWarning>,\n");
    code.push_str("}\n\n");
}

/// Map entity snake_case name to the ParseResult field name.
/// Follows existing conventions (e.g., "work_session" → "sessions").
fn parse_result_field_name(snake_name: &str) -> String {
    match snake_name {
        "work_session" => "sessions".to_string(),
        "unit_of_work" => "units_of_work".to_string(),
        "evidence" => "evidence".to_string(),
        _ => format!("{snake_name}s"),
    }
}

fn generate_deserialize_frontmatter(infos: &[EntityInfo<'_>], code: &mut String) {
    code.push_str(
        r#"/// A probe struct to read just the `type` field from YAML frontmatter.
#[derive(serde::Deserialize)]
struct TypeProbe {
    #[serde(rename = "type")]
    ontology_type: String,
}

/// Deserialize YAML frontmatter into a typed OntologyElement.
///
/// First probes the `type` field to determine which struct to deserialize into,
/// then deserializes the full YAML into the appropriate type.
pub fn deserialize_frontmatter(yaml: &str, file: &Path) -> Result<OntologyElement, ParseError> {
    let probe: TypeProbe = serde_yaml_ng::from_str(yaml).map_err(|e| ParseError::InvalidYaml {
        file: file.to_path_buf(),
        source: e,
    })?;

    match probe.ontology_type.as_str() {
"#,
    );

    for info in infos {
        let name = &info.entity.name;
        let type_name = &info.entity.type_name;

        code.push_str(&format!(
            r#"        "{type_name}" => {{
            let v: {name} =
                serde_yaml_ng::from_str(yaml).map_err(|e| ParseError::InvalidYaml {{
                    file: file.to_path_buf(),
                    source: e,
                }})?;
            Ok(OntologyElement::{name}(v))
        }}
"#
        ));
    }

    code.push_str(
        r#"        other => Err(ParseError::UnknownType {
            file: file.to_path_buf(),
            found: other.to_string(),
        }),
    }
}
"#,
    );
}

fn generate_push_parsed(infos: &[EntityInfo<'_>], code: &mut String) {
    code.push_str(
        r#"
/// Push a parsed ontology element into the appropriate vector in ParseResult.
///
/// Handles wikilink stripping on relation fields and ID prefix validation.
pub fn push_parsed(
    element: OntologyElement,
    body: String,
    wikilinks: Vec<WikilinkRef>,
    path: &Path,
    result: &mut ParseResult,
) {
    let source_file = path.to_path_buf();
    match element {
"#,
    );

    for info in infos {
        generate_direct_push_arm(info, code);
    }

    code.push_str(
        r#"    }
}
"#,
    );
}

/// Generate push_parsed match arm for a direct-deserialize entity.
fn generate_direct_push_arm(info: &EntityInfo<'_>, code: &mut String) {
    let name = &info.entity.name;
    let snake = &info.snake_name;
    let prefix = &info.entity.prefix;
    let field_name = parse_result_field_name(snake);

    code.push_str(&format!("        OntologyElement::{name}(mut entity) => {{\n"));

    // Prefix check
    code.push_str(&format!(
        r#"            if !entity.id.starts_with("{prefix}-") {{
                result.warnings.push(ParseWarning {{
                    file: path.to_path_buf(),
                    message: format!(
                        "ID '{{}}' does not follow the '{prefix}-' prefix convention",
                        entity.id
                    ),
                }});
            }}
"#
    ));

    // Wikilink stripping on relation fields
    for field in &info.entity.fields {
        if let FieldRole::Relation(rel_info) = &field.role {
            let field_name_str = &field.name;
            match (&rel_info.kind, &field.field_type) {
                (RelationKind::BelongsTo, FieldType::OptionString) => {
                    code.push_str(&format!(
                        "            entity.{field_name_str} = strip_wikilink_opt(entity.{field_name_str}.take());\n"
                    ));
                }
                (RelationKind::BelongsTo, FieldType::String) => {
                    code.push_str(&format!(
                        "            entity.{field_name_str} = strip_wikilink(&entity.{field_name_str});\n"
                    ));
                }
                (RelationKind::HasMany | RelationKind::ManyToMany, FieldType::VecString) => {
                    code.push_str(&format!(
                        "            entity.{field_name_str} = strip_wikilinks_vec(std::mem::take(&mut entity.{field_name_str}));\n"
                    ));
                }
                _ => {}
            }
        }
    }

    // Set body
    if info.entity.body_field().is_some() {
        let body_field = info.entity.body_field().unwrap().name.as_str();
        code.push_str(&format!("            entity.{body_field} = body;\n"));
    }

    // Push to result
    code.push_str(&format!(
        r#"            result.{field_name}.push(Parsed {{
                entity,
                source_file,
                wikilinks,
            }});
        }}
"#
    ));
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schema::model::*;

    fn make_test_entities() -> Vec<EntityDef> {
        vec![
            EntityDef {
                name: "Node".to_string(),
                directory: "node".to_string(),
                table: "nodes".to_string(),
                type_name: "node".to_string(),
                prefix: "node".to_string(),
                fields: vec![
                    FieldDef::new("id", FieldType::String, FieldRole::Id),
                    FieldDef::new("name", FieldType::String, FieldRole::Plain),
                    FieldDef::new(
                        "parent_id",
                        FieldType::OptionString,
                        FieldRole::Relation(RelationInfo {
                            kind: RelationKind::BelongsTo,
                            target: "Node".to_string(),
                            junction: None,
                            foreign_key: None,
                        }),
                    ),
                    FieldDef::new(
                        "contains",
                        FieldType::VecString,
                        FieldRole::Relation(RelationInfo {
                            kind: RelationKind::HasMany,
                            target: "Node".to_string(),
                            junction: None,
                            foreign_key: Some("parent_id".to_string()),
                        }),
                    ),
                    FieldDef::new(
                        "fulfills",
                        FieldType::VecString,
                        FieldRole::Relation(RelationInfo {
                            kind: RelationKind::ManyToMany,
                            target: "Requirement".to_string(),
                            junction: None,
                            foreign_key: None,
                        }),
                    ),
                    FieldDef::new("body", FieldType::String, FieldRole::Body),
                ],
            },
            EntityDef {
                name: "Contract".to_string(),
                directory: "contract".to_string(),
                table: "contracts".to_string(),
                type_name: "contract".to_string(),
                prefix: "contract".to_string(),
                fields: vec![
                    FieldDef::new("id", FieldType::String, FieldRole::Id),
                    FieldDef::new("contract_type", FieldType::Other("ContractType".to_string()), FieldRole::EnumField),
                    FieldDef::new("body", FieldType::String, FieldRole::Body),
                ],
            },
        ]
    }

    #[test]
    fn test_ontology_element_enum() {
        let code = generate_parser_dispatch(&make_test_entities());
        assert!(code.contains("Node(Node),"), "Node should use schema type");
        assert!(code.contains("Contract(Contract),"), "Contract should use schema type");
    }

    #[test]
    fn test_parse_result_struct() {
        let code = generate_parser_dispatch(&make_test_entities());
        assert!(code.contains("pub nodes: Vec<Parsed<Node>>"));
        assert!(code.contains("pub contracts: Vec<Parsed<Contract>>"));
        assert!(code.contains("pub warnings: Vec<ParseWarning>"));
    }

    #[test]
    fn test_deserialize_function() {
        let code = generate_parser_dispatch(&make_test_entities());
        assert!(code.contains("\"node\" =>"));
        assert!(code.contains("let v: Node ="));
        assert!(code.contains("\"contract\" =>"));
        assert!(code.contains("let v: Contract ="));
        assert!(code.contains("OntologyElement::Node(v)"));
        assert!(code.contains("OntologyElement::Contract(v)"));
    }

    #[test]
    fn test_push_parsed_wikilink_stripping() {
        let code = generate_parser_dispatch(&make_test_entities());
        // BelongsTo optional: strip_wikilink_opt
        assert!(code.contains("strip_wikilink_opt(entity.parent_id.take())"));
        // HasMany: strip_wikilinks_vec with mem::take
        assert!(code.contains("strip_wikilinks_vec(std::mem::take(&mut entity.contains))"));
        // ManyToMany: strip_wikilinks_vec with mem::take
        assert!(code.contains("strip_wikilinks_vec(std::mem::take(&mut entity.fulfills))"));
    }

    #[test]
    fn test_push_parsed_prefix_check() {
        let code = generate_parser_dispatch(&make_test_entities());
        assert!(code.contains(r#"starts_with("node-")"#));
    }

    #[test]
    fn test_push_parsed_body_assignment() {
        let code = generate_parser_dispatch(&make_test_entities());
        assert!(code.contains("entity.body = body;"));
    }

    #[test]
    fn test_parse_result_field_names() {
        assert_eq!(parse_result_field_name("node"), "nodes");
        assert_eq!(parse_result_field_name("work_session"), "sessions");
        assert_eq!(parse_result_field_name("evidence"), "evidence");
        assert_eq!(parse_result_field_name("contract"), "contracts");
    }

    #[test]
    fn generate_all_real_schemas() {
        let schema_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../src-tauri/src/schema");
        if !schema_dir.exists() {
            eprintln!("Skipping: schema dir not found");
            return;
        }

        let entities = crate::schema::parse::parse_schema_dir(&schema_dir).unwrap();
        assert!(!entities.is_empty());

        let code = generate_parser_dispatch(&entities);

        // Every entity should have an OntologyElement variant
        for entity in &entities {
            assert!(code.contains(&format!("{}(", entity.name)), "Missing OntologyElement variant for {}", entity.name);
        }

        // All entities should use schema type directly in OntologyElement
        for entity in &entities {
            let name = &entity.name;
            assert!(
                code.contains(&format!("{name}({name}),")),
                "{name} should use schema type directly in OntologyElement"
            );
        }

        // ParseResult should have a field for every entity
        for entity in &entities {
            let snake = to_snake_case(&entity.name);
            let field = parse_result_field_name(&snake);
            assert!(
                code.contains(&format!("pub {field}: Vec<Parsed<{}>>", entity.name)),
                "Missing ParseResult field for {}",
                entity.name
            );
        }

        // Deserialize function should handle all entity types
        for entity in &entities {
            assert!(
                code.contains(&format!("\"{}\" =>", entity.type_name)),
                "Missing deserialize arm for {}",
                entity.name
            );
        }
    }
}
