// TODO: review — banner strings updated from old crate names
//! Generate filesystem operation helpers from parsed ontology entity definitions.
//!
//! Generates:
//! - `dirs.rs` — directory constants derived from entity definitions
//! - `fs_ops.rs` — path helpers and write functions for each entity

use std::fs;
use std::path::Path;

use crate::persistence::seaorm::gen_entity::to_snake_case;
use crate::schema::model::EntityDef;

// ─── Public API ──────────────────────────────────────────────────────────────

/// Generate `dirs.rs` and `fs_ops.rs` and write them to the output directory.
pub fn generate(entities: &[EntityDef], output_dir: &Path) -> Result<(), String> {
    fs::create_dir_all(output_dir).map_err(|e| format!("Failed to create output dir {}: {e}", output_dir.display()))?;

    // Generate dirs.rs
    let dirs_code = generate_dirs(entities);
    let dirs_path = output_dir.join("dirs.rs");
    crate::write_and_format(&dirs_path, &dirs_code).map_err(|e| format!("Failed to write {}: {e}", dirs_path.display()))?;

    // Generate fs_ops.rs
    let fs_ops_code = generate_fs_ops(entities);
    let fs_ops_path = output_dir.join("fs_ops.rs");
    crate::write_and_format(&fs_ops_path, &fs_ops_code).map_err(|e| format!("Failed to write {}: {e}", fs_ops_path.display()))?;

    Ok(())
}

// ─── Code Generation ─────────────────────────────────────────────────────────

/// Generate `dirs.rs` — directory constants for each entity.
fn generate_dirs(entities: &[EntityDef]) -> String {
    let mut code = String::from(
        "//! Generated by ontogen. DO NOT EDIT.\n\n\
         /// Root directory for ontology files.\n\
         pub const ONTOLOGICAL_DIR: &str = \".ontological\";\n\n",
    );

    // Collect and sort for deterministic output
    let mut entries: Vec<(&str, String)> =
        entities.iter().map(|e| (e.directory.as_str(), dir_constant_name(&e.directory))).collect();
    entries.sort_by(|a, b| a.1.cmp(&b.1));

    for (dir, const_name) in &entries {
        code.push_str(&format!("pub const {const_name}: &str = \"{dir}\";\n"));
    }

    // Generate ALL_ENTITY_DIRS constant
    code.push_str("\n/// All entity subdirectory names, for use by the parser.\n");
    code.push_str("pub const ALL_ENTITY_DIRS: &[&str] = &[\n");
    for (_, const_name) in &entries {
        code.push_str(&format!("    {const_name},\n"));
    }
    code.push_str("];\n");

    code
}

/// Generate `fs_ops.rs` — path helpers and write functions for each entity.
fn generate_fs_ops(entities: &[EntityDef]) -> String {
    let mut code = String::from(
        "//! Generated by ontogen. DO NOT EDIT.\n\n\
         use std::io;\n\
         use std::path::{Path, PathBuf};\n\n\
         use super::dirs::ONTOLOGICAL_DIR;\n",
    );

    // Collect dir constant imports
    let mut dir_imports: Vec<String> = entities.iter().map(|e| dir_constant_name(&e.directory)).collect();
    dir_imports.sort();
    dir_imports.dedup();

    for dir_const in &dir_imports {
        code.push_str(&format!("use super::dirs::{dir_const};\n"));
    }

    code.push('\n');

    // Sort entities for deterministic output
    let mut sorted: Vec<&EntityDef> = entities.iter().collect();
    sorted.sort_by(|a, b| a.name.cmp(&b.name));

    for entity in sorted {
        let snake = to_snake_case(&entity.name);
        let name = &entity.name;
        let dir_const = dir_constant_name(&entity.directory);

        // Path function
        code.push_str(&format!(
            "/// Compute the markdown output path for a {name} entity.\n\
             pub fn {snake}_path(project_root: &Path, id: &str) -> PathBuf {{\n\
             \x20   project_root\n\
             \x20       .join(ONTOLOGICAL_DIR)\n\
             \x20       .join({dir_const})\n\
             \x20       .join(format!(\"{{id}}.md\"))\n\
             }}\n\n"
        ));

        // Write function
        code.push_str(&format!(
            "/// Write a {name} entity to its markdown file, creating parent directories if needed.\n\
             pub fn write_{snake}(project_root: &Path, entity: &crate::schema::{name}) -> io::Result<()> {{\n\
             \x20   let path = {snake}_path(project_root, &entity.id);\n\
             \x20   let content = crate::persistence::fs_markdown::writers::render_{snake}(entity);\n\
             \x20   crate::persistence::fs_markdown::write_file(&path, &content)\n\
             }}\n\n"
        ));
    }

    code
}

/// Derive a constant name from a directory value.
/// e.g., "session" -> "SESSION_DIR", "node" -> "NODE_DIR"
fn dir_constant_name(directory: &str) -> String {
    format!("{}_DIR", directory.replace('-', "_").to_uppercase())
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schema::model::*;

    fn make_test_entities() -> Vec<EntityDef> {
        vec![
            EntityDef {
                name: "Node".to_string(),
                directory: "node".to_string(),
                table: "nodes".to_string(),
                type_name: "node".to_string(),
                prefix: "node".to_string(),
                fields: vec![
                    FieldDef::new("id", FieldType::String, FieldRole::Id),
                    FieldDef::new("body", FieldType::String, FieldRole::Body),
                ],
            },
            EntityDef {
                name: "WorkSession".to_string(),
                directory: "session".to_string(),
                table: "work_sessions".to_string(),
                type_name: "work_session".to_string(),
                prefix: "session".to_string(),
                fields: vec![
                    FieldDef::new("id", FieldType::String, FieldRole::Id),
                    FieldDef::new("body", FieldType::String, FieldRole::Body),
                ],
            },
        ]
    }

    #[test]
    fn dirs_contains_constants() {
        let code = generate_dirs(&make_test_entities());
        assert!(code.contains("pub const ONTOLOGICAL_DIR: &str = \".ontological\";"));
        assert!(code.contains("pub const NODE_DIR: &str = \"node\";"));
        assert!(code.contains("pub const SESSION_DIR: &str = \"session\";"));
        assert!(code.contains("ALL_ENTITY_DIRS"));
        assert!(code.contains("NODE_DIR,"));
        assert!(code.contains("SESSION_DIR,"));
    }

    #[test]
    fn fs_ops_contains_path_and_write_functions() {
        let code = generate_fs_ops(&make_test_entities());
        assert!(code.contains("pub fn node_path("));
        assert!(code.contains("pub fn write_node("));
        assert!(code.contains("pub fn work_session_path("));
        assert!(code.contains("pub fn write_work_session("));
        assert!(code.contains("crate::schema::Node"));
        assert!(code.contains("crate::schema::WorkSession"));
    }

    #[test]
    fn dir_constant_name_derivation() {
        assert_eq!(dir_constant_name("node"), "NODE_DIR");
        assert_eq!(dir_constant_name("session"), "SESSION_DIR");
        assert_eq!(dir_constant_name("contract"), "CONTRACT_DIR");
    }

    #[test]
    fn generate_all_real_schemas() {
        let schema_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../src-tauri/src/schema");
        if !schema_dir.exists() {
            eprintln!("Skipping: schema dir not found");
            return;
        }

        let entities = crate::schema::parse::parse_schema_dir(&schema_dir).unwrap();
        assert!(!entities.is_empty());

        let dirs_code = generate_dirs(&entities);
        let fs_ops_code = generate_fs_ops(&entities);

        // Every entity should have a dir constant
        for entity in &entities {
            let const_name = dir_constant_name(&entity.directory);
            assert!(dirs_code.contains(&format!("pub const {const_name}")), "Missing dir constant for {}", entity.name);
        }

        // Every entity should have path and write functions
        for entity in &entities {
            let snake = to_snake_case(&entity.name);
            assert!(
                fs_ops_code.contains(&format!("pub fn {snake}_path(")),
                "Missing path function for {}",
                entity.name
            );
            assert!(
                fs_ops_code.contains(&format!("pub fn write_{snake}(")),
                "Missing write function for {}",
                entity.name
            );
        }
    }
}
