//! Markdown filesystem persistence generator.
//!
//! Emits one `{Entity}Frontmatter` module per entity — the typed boundary
//! between schema entities and on-disk YAML frontmatter, built on the
//! `markdown-store` runtime crate. This replaced the former emit-everything
//! model (hand-rolled YAML writers, a `serde_yaml_ng` parser dispatcher and
//! `fs_ops` helpers bound to module paths nothing generated): file I/O,
//! atomic writes, walking, and the lossless `Document` round-trip are the
//! runtime crate's job now; the generated code is a thin typed shim. The
//! old vault-scan dispatcher (`OntologyElement`/`ParseResult`) had no
//! generic consumer and was retired with it — bulk scanning returns as a
//! follow-up on top of `VaultHandle` if a consumer earns it.
//!
//! Their `mod.rs` also carries `open_vault`, which builds that
//! `VaultHandle` from the build-time configuration, and `VAULT_ROOT`.

pub mod gen_frontmatter;
pub mod gen_vault;
pub(crate) mod okf;

use std::collections::HashSet;

use crate::ir::{MarkdownEntityMeta, MarkdownIoOutput, SchemaOutput};
use crate::store::helpers::to_snake_case;
use crate::{CodegenError, MarkdownIoConfig};

/// Generate the markdown I/O code: per-entity `{Entity}Frontmatter` modules
/// and a `mod.rs` that declares them and holds `VAULT_ROOT` and
/// `open_vault`, which builds the runtime `VaultHandle` from `config`.
///
/// Checks run first and fail generation before anything is written: the
/// `okf.generated_by` actor (see `okf::check_generated_by`) and every
/// frontmatter key against the keys OKF reserves (see
/// `okf::check_frontmatter_keys`). Each key warning is printed as a
/// `cargo:warning=` line.
///
/// Returns the [`MarkdownIoOutput`] metadata `gen_store` consumes when the
/// store backend is [`crate::ir::Backend::Markdown`] (ADR 0001): the vault
/// configuration from `config`, plus one [`MarkdownEntityMeta`] row per
/// entity derived from the schema IR. The OKF options stay out of it: only
/// `open_vault` applies them, and the store never builds a vault.
pub fn generate(schema: &SchemaOutput, config: &MarkdownIoConfig) -> Result<MarkdownIoOutput, CodegenError> {
    let entities = &schema.entities;
    let mut errors = Vec::new();
    if let Some(actor) = &config.okf.generated_by
        && let Err(e) = okf::check_generated_by(actor)
    {
        errors.push(e);
    }
    let diagnostics = okf::check_frontmatter_keys(entities, &schema.enums, &config.okf);
    errors.extend(diagnostics.errors);
    if !errors.is_empty() {
        return Err(CodegenError::Persistence(errors.join("\n")));
    }
    for warning in &diagnostics.warnings {
        println!("cargo:warning={warning}");
    }

    write_output(entities, config).map_err(CodegenError::Persistence)?;

    let entity_meta = entities
        .iter()
        .map(|entity| MarkdownEntityMeta {
            entity_name: entity.name.clone(),
            type_name: entity.type_name.clone(),
            dir_segment: entity.directory.clone(),
            body_field: entity.body_field().map(|f| f.name.clone()),
            // v1 contract: every many_to_many field is authoritative on the
            // declaring side; the reverse view is a derived walk.
            authoritative_m2m: entity.junction_relations().map(|(field, _)| field.name.clone()).collect(),
        })
        .collect();

    Ok(MarkdownIoOutput {
        vault_root: config.vault_root.clone(),
        layout: config.layout,
        id_strategy: config.id_strategy.clone(),
        list_cap: config.list_cap,
        module_path: "crate::persistence::markdown::generated".to_string(),
        entities: entity_meta,
    })
}

/// Write every module into `config.output_dir`, remove stale ones, and
/// list them all in its `mod.rs`, followed by `VAULT_ROOT` and `open_vault`.
fn write_output(entities: &[crate::EntityDef], config: &MarkdownIoConfig) -> Result<(), String> {
    let output_dir = &config.output_dir;
    std::fs::create_dir_all(output_dir).map_err(|e| format!("create {}: {e}", output_dir.display()))?;

    let mut modules: Vec<(String, String)> = entities
        .iter()
        .map(|entity| (to_snake_case(&entity.name), gen_frontmatter::generate_frontmatter_module(entity)))
        .collect();
    modules.sort_by(|a, b| a.0.cmp(&b.0));

    let expected: HashSet<String> =
        modules.iter().map(|(name, _)| format!("{name}.rs")).chain(std::iter::once("mod.rs".to_string())).collect();
    crate::clean_generated_dir(output_dir, &expected);

    let mut mod_rs = String::from("//! Generated by ontogen. DO NOT EDIT.\n\n");
    for (name, code) in &modules {
        crate::write_and_format(&output_dir.join(format!("{name}.rs")), code)
            .map_err(|e| format!("write {name}.rs: {e}"))?;
        mod_rs.push_str(&format!("pub mod {name};\n"));
    }
    mod_rs.push('\n');
    mod_rs.push_str(&gen_vault::generate_open_vault(config));
    crate::write_and_format(&output_dir.join("mod.rs"), &mod_rs).map_err(|e| format!("write mod.rs: {e}"))
}
