// TODO: review — banner strings updated from old crate names
#![allow(clippy::too_many_lines, clippy::format_push_string)]

//! Generate Axum HTTP route handlers from API modules.

use std::fs;
use std::path::Path;

use crate::servers::classify::{OpKind, classify_op, is_read_operation};
use crate::servers::config::Config;
use crate::servers::parse::{ApiFn, ApiModule};
use crate::servers::types::{
    capitalize, collect_type_import, event_name, extract_input_type, param_to_owned_type, to_pascal_case,
};

/// Generate HTTP route handlers and write to the output file.
pub fn generate(output: &Path, modules: &[ApiModule], config: &Config) {
    let mut out = String::new();

    out.push_str(
        "\
#![allow(dead_code, unused_imports, clippy::pedantic)]
//! Auto-generated HTTP route handlers. DO NOT EDIT.
//!
//! Generated by ontogen from API source files.

use std::sync::Arc;

use axum::{
    extract::{Path, Query, State},
    http::StatusCode,
    response::Json,
    routing::{delete, get, post, put},
    Router,
};
use serde::{Deserialize, Serialize};

",
    );

    // Collect imports
    let mut service_imports: Vec<String> = modules.iter().map(|m| m.name.clone()).collect();
    service_imports.sort();
    service_imports.dedup();

    let mut type_imports: Vec<String> = Vec::new();

    for m in modules {
        for f in &m.functions {
            collect_type_import(&f.return_type, &mut type_imports);
            for p in &f.params {
                let ty = extract_input_type(&p.ty);
                if ty.contains("Input") {
                    collect_type_import(&ty, &mut type_imports);
                }
            }
        }
    }

    out.push_str(&format!("use {}::{{\n", config.service_import_path));
    for m in &service_imports {
        out.push_str(&format!("    {},\n", m));
    }
    out.push_str("};\n");

    type_imports.sort();
    type_imports.dedup();
    if !type_imports.is_empty() {
        out.push_str(&format!("use {}::{{\n", config.types_import_path));
        for t in &type_imports {
            out.push_str(&format!("    {},\n", t));
        }
        out.push_str("};\n");
    }

    out.push_str(&format!("use {};\n", config.state_import));

    // Add Store import if store_type is configured
    if let Some(ref store_import) = config.store_import {
        out.push_str(&format!("use {};\n", store_import));
    }

    // Add SSE-specific imports if any module has events
    let has_events = modules.iter().any(|m| !m.events.is_empty());
    if has_events {
        out.push_str(
            "\
use std::convert::Infallible;
use axum::response::sse::{Event, Sse};
use tokio_stream::wrappers::BroadcastStream;
use tokio_stream::StreamExt as _;
",
        );
    }

    out.push('\n');

    // Shared types
    let state_type = &config.state_type;
    out.push_str(
        "\
#[derive(Serialize)]
struct ErrorResponse {
    error: String,
}

type ApiError = (StatusCode, Json<ErrorResponse>);

fn err(msg: String) -> ApiError {
    (
        StatusCode::INTERNAL_SERVER_ERROR,
        Json(ErrorResponse { error: msg }),
    )
}

",
    );

    // Generate handlers and collect routes
    let mut route_entries: Vec<String> = Vec::new();

    for m in modules {
        let module = &m.name;
        let plural = config.naming.module_plural(module);
        let url_sing = config.naming.url_singular(module);

        if m.functions.is_empty() {
            continue;
        }

        // Skip store-based modules in unscoped handler generation.
        // They only get scoped routes (generated by generate_scoped_handlers below).
        let is_store_module = m.functions.first().is_some_and(|f| f.first_param_is_store);
        if is_store_module {
            continue;
        }

        out.push_str(&format!("// ── {} Handlers ──\n\n", capitalize(module)));

        let has_list = m.functions.iter().any(|f| f.name == "list");
        let has_get_by_id = m.functions.iter().any(|f| f.name == "get_by_id");
        let has_create = m.functions.iter().any(|f| f.name == "create");
        let has_update = m.functions.iter().any(|f| f.name == "update");
        let has_delete = m.functions.iter().any(|f| f.name == "delete");

        for f in &m.functions {
            let op = classify_op(f);
            let svc = module;
            let fn_name = &f.name;
            let is_async = f.is_async;
            let ret_type = &f.return_type;

            match op {
                OpKind::List => {
                    let handler_name = format!("list_{}", plural);
                    let await_str = if is_async { "\n        .await" } else { "" };
                    let err_map =
                        if is_async { ".map_err(|e| err(e.to_string()))" } else { ".map_err(|e| err(e.into()))" };
                    out.push_str(&format!(
                        "\
async fn {handler_name}(
    State(state): State<Arc<{state_type}>>,
) -> Result<Json<{ret_type}>, ApiError> {{
    {svc}::list(&state){await_str}
        .map(Json)
        {err_map}
}}

"
                    ));
                }

                OpKind::GetById => {
                    let handler_name = format!("get_{}_by_id", url_sing);
                    let await_str = if is_async { "\n        .await" } else { "" };
                    let err_map =
                        if is_async { ".map_err(|e| err(e.to_string()))" } else { ".map_err(|e| err(e.into()))" };
                    out.push_str(&format!(
                        "\
async fn {handler_name}(
    State(state): State<Arc<{state_type}>>,
    Path(id): Path<String>,
) -> Result<Json<{ret_type}>, ApiError> {{
    {svc}::{fn_name}(&state, &id){await_str}
        .map(Json)
        {err_map}
}}

"
                    ));
                }

                OpKind::Create => {
                    let handler_name = format!("create_{}_handler", url_sing);
                    let input_type = extract_input_type(&f.params[0].ty);
                    out.push_str(&format!(
                        "\
async fn {handler_name}(
    State(state): State<Arc<{state_type}>>,
    Json(input): Json<{input_type}>,
) -> Result<(StatusCode, Json<{ret_type}>), ApiError> {{
    {svc}::create(&state, input)
        .await
        .map(|entity| (StatusCode::CREATED, Json(entity)))
        .map_err(|e| err(e.into()))
}}

"
                    ));
                }

                OpKind::UpdateById => {
                    let handler_name = format!("update_{}_handler", url_sing);
                    let input_type = extract_input_type(&f.params[1].ty);
                    out.push_str(&format!(
                        "\
async fn {handler_name}(
    State(state): State<Arc<{state_type}>>,
    Path(id): Path<String>,
    Json(input): Json<{input_type}>,
) -> Result<Json<{ret_type}>, ApiError> {{
    {svc}::update(&state, &id, input)
        .await
        .map(Json)
        .map_err(|e| err(e.into()))
}}

"
                    ));
                }

                OpKind::DeleteById => {
                    let handler_name = format!("delete_{}_handler", url_sing);
                    out.push_str(&format!(
                        "\
async fn {handler_name}(
    State(state): State<Arc<{state_type}>>,
    Path(id): Path<String>,
) -> Result<StatusCode, ApiError> {{
    {svc}::delete(&state, &id)
        .await
        .map(|_| StatusCode::NO_CONTENT)
        .map_err(|e| err(e.into()))
}}

"
                    ));
                }

                OpKind::CustomGet | OpKind::CustomPost => {
                    generate_generic_http_handler(&mut out, &mut route_entries, module, f, config);
                }
            }
        }

        // Add standard CRUD routes for this module
        if has_list && has_create {
            let list_fn = format!("list_{}", plural);
            let create_fn = format!("create_{}_handler", url_sing);
            route_entries.push(format!("        .route(\"/api/{plural}\", get({list_fn}).post({create_fn}))"));
        } else if has_list {
            let list_fn = format!("list_{}", plural);
            route_entries.push(format!("        .route(\"/api/{plural}\", get({list_fn}))"));
        }

        if has_get_by_id || has_update || has_delete {
            let mut methods = Vec::new();
            if has_get_by_id {
                methods.push(format!("get(get_{}_by_id)", url_sing));
            }
            if has_update {
                methods.push(format!("put(update_{}_handler)", url_sing));
            }
            if has_delete {
                methods.push(format!("delete(delete_{}_handler)", url_sing));
            }
            route_entries.push(format!("        .route(\"/api/{plural}/:id\", {})", methods.join(".")));
        }
    }

    // Generate SSE handlers for event functions
    for m in modules {
        for ev in &m.events {
            let fn_name = &ev.name;
            let ev_name = event_name(fn_name);
            let handler_name = format!("{}_sse", fn_name);
            let svc = &m.name;

            out.push_str(&format!(
                "\
// ── {fn_name} SSE Handler ──

async fn {handler_name}(
    State(state): State<Arc<{state_type}>>,
) -> Sse<impl futures::Stream<Item = Result<Event, Infallible>>> {{
    let rx = {svc}::{fn_name}(&state);
    let stream = BroadcastStream::new(rx)
        .filter_map(|result: Result<_, _>| result.ok())
        .map(|delta| {{
            Ok(Event::default()
                .event(\"{ev_name}\")
                .json_data(&delta)
                .unwrap())
        }});
    Sse::new(stream)
}}

"
            ));

            let route_path = if let Some(override_path) = config.sse_route_overrides.get(fn_name) {
                override_path.clone()
            } else {
                format!("/api/events/{}", ev_name)
            };
            route_entries.push(format!("        .route(\"{route_path}\", get({handler_name}))"));
        }
    }

    // Generate project-scoped handler variants if route_prefix is configured
    if let Some(prefix) = &config.route_prefix {
        generate_scoped_handlers(&mut out, &mut route_entries, modules, config, prefix);
    }

    // Router function
    out.push_str(&format!(
        "/// Generated routes. Call this from your main router.\npub fn entity_routes() -> Router<Arc<{state_type}>> {{\n    Router::new()\n"
    ));
    for entry in &route_entries {
        out.push_str(entry);
        out.push('\n');
    }
    out.push_str("}\n");

    if let Some(parent) = output.parent() {
        fs::create_dir_all(parent).expect("Failed to create output directory");
    }
    crate::write_and_format(output, out).expect("Failed to write HTTP generated file");
}

fn generate_generic_http_handler(out: &mut String, routes: &mut Vec<String>, module: &str, f: &ApiFn, config: &Config) {
    let fn_name = &f.name;
    let svc = module;
    let is_async = f.is_async;
    let ret_type = &f.return_type;
    let is_get = is_read_operation(fn_name);
    let action = config.naming.derive_action(module, fn_name);
    let plural = config.naming.module_plural(module);
    let returns_unit = f.return_type == "()" || ret_type == "()";
    let await_str = if is_async { "\n        .await" } else { "" };
    let state_type = &config.state_type;

    // Classify params
    let body_struct: Option<&crate::servers::parse::Param> = f.params.iter().find(|p| p.ty.contains("Input"));
    let query_params: Vec<&crate::servers::parse::Param> =
        f.params.iter().filter(|p| p.ty.starts_with("Option<")).collect();
    let path_params: Vec<&crate::servers::parse::Param> = if is_get {
        f.params.iter().filter(|p| !p.ty.starts_with("Option<") && !p.ty.contains("Input")).collect()
    } else {
        vec![]
    };
    let body_fields: Vec<&crate::servers::parse::Param> = if !is_get && body_struct.is_none() {
        f.params.iter().filter(|p| !p.ty.starts_with("Option<") && !p.ty.contains("Input")).collect()
    } else {
        vec![]
    };

    // Build route path
    let mut route_path = format!("/api/{}", plural);
    if !action.is_empty() {
        route_path.push_str(&format!("/{}", action));
    }
    for p in &path_params {
        route_path.push_str(&format!("/:{}", p.name));
    }

    let handler_name = fn_name.clone();
    let method = if is_get { "get" } else { "post" };

    // Generate query struct if needed
    if !query_params.is_empty() {
        let struct_name = format!("{}Query", to_pascal_case(fn_name));
        out.push_str(&format!("#[derive(Deserialize)]\nstruct {} {{\n", struct_name));
        for qp in &query_params {
            out.push_str(&format!("    {}: {},\n", qp.name, param_to_owned_type(&qp.ty)));
        }
        out.push_str("}\n\n");
    }

    // Generate body struct if needed (for POST with plain params)
    if !body_fields.is_empty() {
        let struct_name = format!("{}Body", to_pascal_case(fn_name));
        out.push_str(&format!("#[derive(Deserialize)]\nstruct {} {{\n", struct_name));
        for bf in &body_fields {
            out.push_str(&format!("    {}: {},\n", bf.name, param_to_owned_type(&bf.ty)));
        }
        out.push_str("}\n\n");
    }

    // Generate handler function
    out.push_str(&format!("async fn {}(\n    State(state): State<Arc<{state_type}>>,\n", handler_name));

    // Path params
    if path_params.len() == 1 {
        let p = path_params[0];
        let path_type = if p.ty == "i32" { "i32" } else { "String" };
        out.push_str(&format!("    Path({}): Path<{}>,\n", p.name, path_type));
    } else if path_params.len() > 1 {
        let types: Vec<&str> = path_params.iter().map(|p| if p.ty == "i32" { "i32" } else { "String" }).collect();
        let names: Vec<&str> = path_params.iter().map(|p| p.name.as_str()).collect();
        out.push_str(&format!("    Path(({}),): Path<({},)>,\n", names.join(", "), types.join(", ")));
    }

    // Query params
    if !query_params.is_empty() {
        let struct_name = format!("{}Query", to_pascal_case(fn_name));
        out.push_str(&format!("    Query(q): Query<{}>,\n", struct_name));
    }

    // Body
    if let Some(bs) = body_struct {
        let input_type = extract_input_type(&bs.ty);
        out.push_str(&format!("    Json(input): Json<{}>,\n", input_type));
    }
    if !body_fields.is_empty() {
        let struct_name = format!("{}Body", to_pascal_case(fn_name));
        out.push_str(&format!("    Json(body): Json<{}>,\n", struct_name));
    }

    // Return type
    if returns_unit {
        out.push_str(") -> Result<StatusCode, ApiError> {\n");
    } else {
        out.push_str(&format!(") -> Result<Json<{}>, ApiError> {{\n", ret_type));
    }

    // Function call
    out.push_str(&format!("    {}::{}(&state", svc, fn_name));
    for p in &path_params {
        if p.ty == "i32" {
            out.push_str(&format!(", {}", p.name));
        } else {
            out.push_str(&format!(", &{}", p.name));
        }
    }
    for qp in &query_params {
        out.push_str(&format!(", q.{}.as_deref()", qp.name));
    }
    if body_struct.is_some() {
        out.push_str(", input");
    }
    for bf in &body_fields {
        if bf.ty == "i32" {
            out.push_str(&format!(", body.{}", bf.name));
        } else {
            out.push_str(&format!(", &body.{}", bf.name));
        }
    }
    out.push(')');
    out.push_str(await_str);
    out.push('\n');

    // Map result
    if returns_unit {
        out.push_str("        .map(|_| StatusCode::NO_CONTENT)\n");
    } else {
        out.push_str("        .map(Json)\n");
    }
    out.push_str("        .map_err(|e| err(e.to_string()))\n");
    out.push_str("}\n\n");

    // Add route
    routes.push(format!("        .route(\"{}\", {}({}))", route_path, method, handler_name));
}

/// Generate project-scoped handler variants and routes.
///
/// Only generates handlers for store-based modules (functions whose first
/// parameter is `&Store`). These handlers construct a Store via the prefix
/// accessor (e.g., `state.store_for(&project_id)`) and pass it to the
/// service function, providing real project data isolation.
fn generate_scoped_handlers(
    out: &mut String,
    routes: &mut Vec<String>,
    modules: &[ApiModule],
    config: &Config,
    prefix: &crate::servers::config::RoutePrefix,
) {
    let state_type = &config.state_type;
    let accessor = &prefix.state_accessor;
    let pp = &prefix.params[0];
    let pp_name = &pp.name;
    let pp_type = &pp.rust_type;

    out.push_str("\n// ── Project-Scoped Handlers ──\n\n");

    for m in modules {
        let module = &m.name;
        let plural = config.naming.module_plural(module);
        let url_sing = config.naming.url_singular(module);
        let scoped_base = format!("/api/{}/{}", prefix.segments, plural);

        if m.functions.is_empty() {
            continue;
        }

        // Only generate scoped handlers for store-based modules
        let is_store_module = m.functions.first().is_some_and(|f| f.first_param_is_store);
        if !is_store_module {
            continue;
        }

        let has_list = m.functions.iter().any(|f| f.name == "list");
        let has_get_by_id = m.functions.iter().any(|f| f.name == "get_by_id");
        let has_create = m.functions.iter().any(|f| f.name == "create");
        let has_update = m.functions.iter().any(|f| f.name == "update");
        let has_delete = m.functions.iter().any(|f| f.name == "delete");

        // Store construction line used by all handlers in this module
        let store_let = format!("    let store = state.{accessor}(&{pp_name}).map_err(|e| err(e.to_string()))?;");

        for f in &m.functions {
            let op = classify_op(f);
            let svc = module;
            let fn_name = &f.name;
            let is_async = f.is_async;
            let ret_type = &f.return_type;

            match op {
                OpKind::List => {
                    let handler_name = format!("list_{}_scoped", plural);
                    let await_str = if is_async { "\n        .await" } else { "" };
                    let err_map =
                        if is_async { ".map_err(|e| err(e.to_string()))" } else { ".map_err(|e| err(e.into()))" };
                    out.push_str(&format!(
                        "\
async fn {handler_name}(
    State(state): State<Arc<{state_type}>>,
    Path({pp_name}): Path<{pp_type}>,
) -> Result<Json<{ret_type}>, ApiError> {{
{store_let}
    {svc}::list(&store){await_str}
        .map(Json)
        {err_map}
}}

"
                    ));
                }

                OpKind::GetById => {
                    let handler_name = format!("get_{}_by_id_scoped", url_sing);
                    let await_str = if is_async { "\n        .await" } else { "" };
                    let err_map =
                        if is_async { ".map_err(|e| err(e.to_string()))" } else { ".map_err(|e| err(e.into()))" };
                    out.push_str(&format!(
                        "\
async fn {handler_name}(
    State(state): State<Arc<{state_type}>>,
    Path(({pp_name}, id)): Path<({pp_type}, String)>,
) -> Result<Json<{ret_type}>, ApiError> {{
{store_let}
    {svc}::{fn_name}(&store, &id){await_str}
        .map(Json)
        {err_map}
}}

"
                    ));
                }

                OpKind::Create => {
                    let handler_name = format!("create_{}_handler_scoped", url_sing);
                    let input_type = extract_input_type(&f.params[0].ty);
                    out.push_str(&format!(
                        "\
async fn {handler_name}(
    State(state): State<Arc<{state_type}>>,
    Path({pp_name}): Path<{pp_type}>,
    Json(input): Json<{input_type}>,
) -> Result<(StatusCode, Json<{ret_type}>), ApiError> {{
{store_let}
    {svc}::create(&store, input)
        .await
        .map(|entity| (StatusCode::CREATED, Json(entity)))
        .map_err(|e| err(e.into()))
}}

"
                    ));
                }

                OpKind::UpdateById => {
                    let handler_name = format!("update_{}_handler_scoped", url_sing);
                    let input_type = extract_input_type(&f.params[1].ty);
                    out.push_str(&format!(
                        "\
async fn {handler_name}(
    State(state): State<Arc<{state_type}>>,
    Path(({pp_name}, id)): Path<({pp_type}, String)>,
    Json(input): Json<{input_type}>,
) -> Result<Json<{ret_type}>, ApiError> {{
{store_let}
    {svc}::update(&store, &id, input)
        .await
        .map(Json)
        .map_err(|e| err(e.into()))
}}

"
                    ));
                }

                OpKind::DeleteById => {
                    let handler_name = format!("delete_{}_handler_scoped", url_sing);
                    out.push_str(&format!(
                        "\
async fn {handler_name}(
    State(state): State<Arc<{state_type}>>,
    Path(({pp_name}, id)): Path<({pp_type}, String)>,
) -> Result<StatusCode, ApiError> {{
{store_let}
    {svc}::delete(&store, &id)
        .await
        .map(|_| StatusCode::NO_CONTENT)
        .map_err(|e| err(e.into()))
}}

"
                    ));
                }

                OpKind::CustomGet | OpKind::CustomPost => {
                    generate_generic_http_handler_scoped(out, routes, module, f, config, prefix);
                }
            }
        }

        // Add scoped CRUD routes for this module
        if has_list && has_create {
            let list_fn = format!("list_{}_scoped", plural);
            let create_fn = format!("create_{}_handler_scoped", url_sing);
            routes.push(format!("        .route(\"{scoped_base}\", get({list_fn}).post({create_fn}))"));
        } else if has_list {
            let list_fn = format!("list_{}_scoped", plural);
            routes.push(format!("        .route(\"{scoped_base}\", get({list_fn}))"));
        }

        if has_get_by_id || has_update || has_delete {
            let mut methods = Vec::new();
            if has_get_by_id {
                methods.push(format!("get(get_{}_by_id_scoped)", url_sing));
            }
            if has_update {
                methods.push(format!("put(update_{}_handler_scoped)", url_sing));
            }
            if has_delete {
                methods.push(format!("delete(delete_{}_handler_scoped)", url_sing));
            }
            routes.push(format!("        .route(\"{scoped_base}/:id\", {})", methods.join(".")));
        }
    }

    // Scoped SSE handlers
    for m in modules {
        for ev in &m.events {
            let fn_name = &ev.name;
            let ev_name = event_name(fn_name);
            let handler_name = format!("{}_sse_scoped", fn_name);

            out.push_str(&format!(
                "\
async fn {handler_name}(
    State(state): State<Arc<{state_type}>>,
    Path({pp_name}): Path<{pp_type}>,
) -> Sse<impl futures::Stream<Item = Result<Event, Infallible>>> {{
    let rx = state.subscribe_{fn_name}_for(&{pp_name});
    let stream = BroadcastStream::new(rx)
        .filter_map(|result: Result<_, _>| result.ok())
        .map(|delta| {{
            Ok(Event::default()
                .event(\"{ev_name}\")
                .json_data(&delta)
                .unwrap())
        }});
    Sse::new(stream)
}}

"
            ));

            let route_path = if let Some(override_path) = config.sse_route_overrides.get(fn_name) {
                if let Some(rest) = override_path.strip_prefix("/api/") {
                    format!("/api/{}/{}", prefix.segments, rest)
                } else {
                    format!("/api/{}{}", prefix.segments, override_path)
                }
            } else {
                format!("/api/{}/events/{}", prefix.segments, ev_name)
            };
            routes.push(format!("        .route(\"{route_path}\", get({handler_name}))"));
        }
    }
}

/// Generate a scoped variant of a custom HTTP handler.
fn generate_generic_http_handler_scoped(
    out: &mut String,
    routes: &mut Vec<String>,
    module: &str,
    f: &ApiFn,
    config: &Config,
    prefix: &crate::servers::config::RoutePrefix,
) {
    let fn_name = &f.name;
    let svc = module;
    let is_async = f.is_async;
    let ret_type = &f.return_type;
    let is_get = is_read_operation(fn_name);
    let action = config.naming.derive_action(module, fn_name);
    let plural = config.naming.module_plural(module);
    let returns_unit = f.return_type == "()" || ret_type == "()";
    let await_str = if is_async { "\n        .await" } else { "" };
    let state_type = &config.state_type;
    let accessor = &prefix.state_accessor;
    let pp = &prefix.params[0];
    let pp_name = &pp.name;
    let pp_type = &pp.rust_type;

    // Classify params
    let body_struct: Option<&crate::servers::parse::Param> = f.params.iter().find(|p| p.ty.contains("Input"));
    let query_params: Vec<&crate::servers::parse::Param> =
        f.params.iter().filter(|p| p.ty.starts_with("Option<")).collect();
    let path_params: Vec<&crate::servers::parse::Param> = if is_get {
        f.params.iter().filter(|p| !p.ty.starts_with("Option<") && !p.ty.contains("Input")).collect()
    } else {
        vec![]
    };
    let body_fields: Vec<&crate::servers::parse::Param> = if !is_get && body_struct.is_none() {
        f.params.iter().filter(|p| !p.ty.starts_with("Option<") && !p.ty.contains("Input")).collect()
    } else {
        vec![]
    };

    // Build scoped route path
    let mut route_path = format!("/api/{}/{}", prefix.segments, plural);
    if !action.is_empty() {
        route_path.push_str(&format!("/{}", action));
    }
    for p in &path_params {
        route_path.push_str(&format!("/:{}", p.name));
    }

    let handler_name = format!("{}_scoped", fn_name);
    let method = if is_get { "get" } else { "post" };

    // Generate query/body struct definitions if needed (for store-based modules
    // these are not generated by the unscoped handler since it's skipped)
    if !query_params.is_empty() {
        let struct_name = format!("{}Query", to_pascal_case(fn_name));
        out.push_str(&format!("#[derive(Deserialize)]\nstruct {} {{\n", struct_name));
        for qp in &query_params {
            out.push_str(&format!("    {}: {},\n", qp.name, param_to_owned_type(&qp.ty)));
        }
        out.push_str("}\n\n");
    }
    if !body_fields.is_empty() {
        let struct_name = format!("{}Body", to_pascal_case(fn_name));
        out.push_str(&format!("#[derive(Deserialize)]\nstruct {} {{\n", struct_name));
        for bf in &body_fields {
            out.push_str(&format!("    {}: {},\n", bf.name, param_to_owned_type(&bf.ty)));
        }
        out.push_str("}\n\n");
    }

    // Generate handler function
    out.push_str(&format!("async fn {}(\n    State(state): State<Arc<{state_type}>>,\n", handler_name));

    // Path params (prefix param + any entity path params)
    if path_params.is_empty() {
        out.push_str(&format!("    Path({pp_name}): Path<{pp_type}>,\n"));
    } else if path_params.len() == 1 {
        let p = path_params[0];
        let path_type = if p.ty == "i32" { "i32" } else { "String" };
        out.push_str(&format!("    Path(({pp_name}, {})): Path<({pp_type}, {})>,\n", p.name, path_type));
    } else {
        let mut names = vec![pp_name.clone()];
        let mut types = vec![pp_type.clone()];
        for p in &path_params {
            names.push(p.name.clone());
            types.push(if p.ty == "i32" { "i32".to_string() } else { "String".to_string() });
        }
        out.push_str(&format!("    Path(({}),): Path<({},)>,\n", names.join(", "), types.join(", ")));
    }

    // Query params
    if !query_params.is_empty() {
        let struct_name = format!("{}Query", to_pascal_case(fn_name));
        out.push_str(&format!("    Query(q): Query<{}>,\n", struct_name));
    }

    // Body
    if let Some(bs) = body_struct {
        let input_type = extract_input_type(&bs.ty);
        out.push_str(&format!("    Json(input): Json<{}>,\n", input_type));
    }
    if !body_fields.is_empty() {
        let struct_name = format!("{}Body", to_pascal_case(fn_name));
        out.push_str(&format!("    Json(body): Json<{}>,\n", struct_name));
    }

    // Return type
    if returns_unit {
        out.push_str(") -> Result<StatusCode, ApiError> {\n");
    } else {
        out.push_str(&format!(") -> Result<Json<{}>, ApiError> {{\n", ret_type));
    }

    // Construct Store for store-based functions, or validate for state-based
    if f.first_param_is_store {
        out.push_str(&format!("    let store = state.{accessor}(&{pp_name}).map_err(|e| err(e.to_string()))?;\n"));
    } else {
        out.push_str(&format!("    state.{accessor}(&{pp_name}).map_err(|e| err(e.to_string()))?;\n"));
    }

    // Function call — pass &store for store-based, &state for state-based
    let first_arg = if f.first_param_is_store { "&store" } else { "&state" };
    out.push_str(&format!("    {}::{}({first_arg}", svc, fn_name));
    for p in &path_params {
        if p.ty == "i32" {
            out.push_str(&format!(", {}", p.name));
        } else {
            out.push_str(&format!(", &{}", p.name));
        }
    }
    for qp in &query_params {
        out.push_str(&format!(", q.{}.as_deref()", qp.name));
    }
    if body_struct.is_some() {
        out.push_str(", input");
    }
    for bf in &body_fields {
        if bf.ty == "i32" {
            out.push_str(&format!(", body.{}", bf.name));
        } else {
            out.push_str(&format!(", &body.{}", bf.name));
        }
    }
    out.push(')');
    out.push_str(await_str);
    out.push('\n');

    // Map result
    if returns_unit {
        out.push_str("        .map(|_| StatusCode::NO_CONTENT)\n");
    } else {
        out.push_str("        .map(Json)\n");
    }
    out.push_str("        .map_err(|e| err(e.to_string()))\n");
    out.push_str("}\n\n");

    // Add scoped route
    routes.push(format!("        .route(\"{}\", {}({}))", route_path, method, handler_name));
}
