#![allow(clippy::too_many_lines, clippy::format_push_string)]

//! Generate Tauri IPC command handlers from API modules.

use std::fs;
use std::path::Path;

use crate::servers::classify::{OpKind, classify_op};
use crate::servers::config::Config;
use crate::servers::parse::{ApiFn, ApiModule};
use crate::servers::types::{capitalize, collect_type_import, event_name, extract_input_type, param_to_owned_type};

/// Returns the generated prefix param line for IPC commands (e.g., `project_id: Option<String>,`).
/// Empty string if no route_prefix configured.
fn prefix_param_line(config: &Config) -> String {
    match &config.route_prefix {
        Some(prefix) => {
            let pp = &prefix.params[0];
            format!("    {}: Option<String>,\n", pp.name)
        }
        None => String::new(),
    }
}

/// Returns the validation code for state-based IPC commands (validate-only).
fn prefix_validation_line(config: &Config) -> String {
    match &config.route_prefix {
        Some(prefix) => {
            let pp = &prefix.params[0];
            let accessor = &prefix.state_accessor;
            format!(
                "    if let Some(ref pid) = {} {{\n\
                 \x20       let uuid = uuid::Uuid::parse_str(pid).map_err(|e| e.to_string())?;\n\
                 \x20       state.{}(&uuid).map_err(|e| e.to_string())?;\n\
                 \x20   }}\n",
                pp.name, accessor,
            )
        }
        None => String::new(),
    }
}

/// Returns Store construction code for store-based IPC commands.
///
/// When project_id is provided, constructs Store via store_for().
/// When not provided, falls back to the default project via store().
fn store_construction_line(config: &Config) -> String {
    match &config.route_prefix {
        Some(prefix) => {
            let pp = &prefix.params[0];
            let accessor = &prefix.state_accessor;
            format!(
                "    let store = if let Some(ref pid) = {} {{\n\
                 \x20       let uuid = uuid::Uuid::parse_str(pid).map_err(|e| e.to_string())?;\n\
                 \x20       state.{}(&uuid).map_err(|e| e.to_string())?\n\
                 \x20   }} else {{\n\
                 \x20       state.store().await.map_err(|e| e.to_string())?\n\
                 \x20   }};\n",
                pp.name, accessor,
            )
        }
        None => "    let store = state.store().await.map_err(|e| e.to_string())?;\n".to_string(),
    }
}

/// IPC command name for a given module and operation.
fn ipc_command_name(module: &str, op: &OpKind, config: &Config) -> String {
    let singular = module; // IPC keeps full module name
    let by_id_singular = config.naming.url_singular(module);
    let plural = config.naming.module_plural(module);
    match op {
        OpKind::List => format!("get_{}", plural),
        OpKind::GetById => format!("get_{}_by_id", by_id_singular),
        OpKind::Create => format!("create_{}", singular),
        OpKind::UpdateById => format!("update_{}", singular),
        OpKind::DeleteById => format!("delete_{}", singular),
        OpKind::CustomGet | OpKind::CustomPost => String::new(),
    }
}

/// Get the IPC/TS command name for a function.
pub fn ts_command_name(module: &str, f: &ApiFn, config: &Config) -> String {
    let op = classify_op(f);
    match op {
        OpKind::CustomGet | OpKind::CustomPost => f.name.clone(),
        _ => ipc_command_name(module, &op, config),
    }
}

/// Generate IPC command handlers and write to the output file.
pub fn generate(output: &Path, modules: &[ApiModule], config: &Config) {
    let mut out = String::new();
    let state_type = &config.state_type;

    out.push_str(
        "\
#![allow(unused_imports, clippy::pedantic)]
//! Auto-generated Tauri IPC command handlers. DO NOT EDIT.
//!
//! Generated by ontogen from API source files.

use std::sync::Arc;

use tauri::State;

",
    );

    // Collect imports
    let mut service_imports: Vec<String> = modules.iter().map(|m| m.name.clone()).collect();
    service_imports.sort();
    service_imports.dedup();

    let mut type_imports: Vec<String> = Vec::new();

    for m in modules {
        for f in &m.functions {
            collect_type_import(&f.return_type, &mut type_imports);
            for p in &f.params {
                let ty = extract_input_type(&p.ty);
                if ty.contains("Input") {
                    collect_type_import(&ty, &mut type_imports);
                }
            }
        }
    }

    out.push_str(&format!("use {}::{{\n", config.service_import_path));
    for m in &service_imports {
        out.push_str(&format!("    {},\n", m));
    }
    out.push_str("};\n");

    type_imports.sort();
    type_imports.dedup();
    if !type_imports.is_empty() {
        out.push_str(&format!("use {}::{{\n", config.types_import_path));
        for t in &type_imports {
            out.push_str(&format!("    {},\n", t));
        }
        out.push_str("};\n");
    }

    out.push_str(&format!("use {};\n", config.state_import));

    // Add Store import if store_type is configured
    if let Some(ref store_import) = config.store_import {
        out.push_str(&format!("use {};\n", store_import));
    }

    out.push('\n');

    let pp_line = prefix_param_line(config);
    let pp_validate = prefix_validation_line(config);
    let store_construct = store_construction_line(config);

    let mut command_names: Vec<String> = Vec::new();

    for m in modules {
        let module = &m.name;
        let svc = module;

        if m.functions.is_empty() {
            continue;
        }

        out.push_str(&format!("// ── {} IPC Commands ──\n\n", capitalize(module)));

        for f in &m.functions {
            let op = classify_op(f);
            let is_async = f.is_async;
            let ret_type = &f.return_type;

            // Determine per-function prefix and first-arg behavior
            let (fn_pp_line, fn_pp_body, first_arg) = if f.first_param_is_store {
                (pp_line.clone(), store_construct.clone(), "&store")
            } else {
                (pp_line.clone(), pp_validate.clone(), "&state")
            };

            match op {
                OpKind::List => {
                    let cmd_name = ipc_command_name(module, &op, config);
                    let await_str = if is_async { ".await" } else { "" };
                    out.push_str(&format!(
                        "\
#[tauri::command]
#[specta::specta]
pub async fn {cmd_name}(
{fn_pp_line}    state: State<'_, Arc<{state_type}>>,
) -> Result<{ret_type}, String> {{
{fn_pp_body}    {svc}::list({first_arg}){await_str}
        .map_err(|e| e.to_string())
}}

"
                    ));
                    command_names.push(cmd_name);
                }

                OpKind::GetById => {
                    let cmd_name = ipc_command_name(module, &op, config);
                    let fn_name = &f.name;
                    if is_async {
                        out.push_str(&format!(
                            "\
#[tauri::command]
#[specta::specta]
pub async fn {cmd_name}(
    id: String,
{fn_pp_line}    state: State<'_, Arc<{state_type}>>,
) -> Result<{ret_type}, String> {{
{fn_pp_body}    {svc}::{fn_name}({first_arg}, &id)
        .await
        .map_err(|e| e.to_string())
}}

"
                        ));
                    } else {
                        out.push_str(&format!(
                            "\
#[tauri::command]
#[specta::specta]
pub async fn {cmd_name}(
    id: String,
{fn_pp_line}    state: State<'_, Arc<{state_type}>>,
) -> Result<{ret_type}, String> {{
{fn_pp_body}    {svc}::{fn_name}({first_arg}, &id)
        .map_err(|e| e.to_string())
}}

"
                        ));
                    }
                    command_names.push(cmd_name);
                }

                OpKind::Create => {
                    let cmd_name = ipc_command_name(module, &op, config);
                    let input_type = extract_input_type(&f.params[0].ty);
                    out.push_str(&format!(
                        "\
#[tauri::command]
#[specta::specta]
pub async fn {cmd_name}(
    input: {input_type},
{fn_pp_line}    state: State<'_, Arc<{state_type}>>,
) -> Result<{ret_type}, String> {{
{fn_pp_body}    {svc}::create({first_arg}, input)
        .await
        .map_err(|e| e.to_string())
}}

"
                    ));
                    command_names.push(cmd_name);
                }

                OpKind::UpdateById => {
                    let cmd_name = ipc_command_name(module, &op, config);
                    let input_type = extract_input_type(&f.params[1].ty);
                    out.push_str(&format!(
                        "\
#[tauri::command]
#[specta::specta]
pub async fn {cmd_name}(
    id: String,
    input: {input_type},
{fn_pp_line}    state: State<'_, Arc<{state_type}>>,
) -> Result<{ret_type}, String> {{
{fn_pp_body}    {svc}::update({first_arg}, &id, input)
        .await
        .map_err(|e| e.to_string())
}}

"
                    ));
                    command_names.push(cmd_name);
                }

                OpKind::DeleteById => {
                    let cmd_name = ipc_command_name(module, &op, config);
                    out.push_str(&format!(
                        "\
#[tauri::command]
#[specta::specta]
pub async fn {cmd_name}(
    id: String,
{fn_pp_line}    state: State<'_, Arc<{state_type}>>,
) -> Result<(), String> {{
{fn_pp_body}    {svc}::delete({first_arg}, &id)
        .await
        .map_err(|e| e.to_string())
}}

"
                    ));
                    command_names.push(cmd_name);
                }

                OpKind::CustomGet | OpKind::CustomPost => {
                    let cmd_name = f.name.clone();
                    generate_generic_ipc_handler(&mut out, module, f, config);
                    command_names.push(cmd_name);
                }
            }
        }
    }

    // Generate event forwarding function if any module has events
    let has_events = modules.iter().any(|m| !m.events.is_empty());
    if has_events {
        out.push_str(&format!(
            "\
// ── Event Forwarding ──

use tauri::Emitter;

/// Start IPC forwarding tasks for all event streams.
/// Call this during app setup to bridge EventBus → Tauri events.
pub fn start_event_forwarding(app_handle: tauri::AppHandle, state: &{}) {{
",
            config.state_import.split("::").last().unwrap_or(&config.state_type),
        ));

        for m in modules {
            for ev in &m.events {
                let fn_name = &ev.name;
                let ev_name = event_name(fn_name);
                let svc = &m.name;

                out.push_str(&format!(
                    "\
    // {fn_name}
    {{
        let handle = app_handle.clone();
        let mut rx = {}::{svc}::{fn_name}(state);
        tauri::async_runtime::spawn(async move {{
            while let Ok(delta) = rx.recv().await {{
                if let Err(e) = handle.emit(\"{ev_name}\", &delta) {{
                    log::error!(\"Failed to forward {ev_name} to IPC: {{:?}}\", e);
                }}
            }}
        }});
    }}
",
                    config.service_import_path,
                ));
            }
        }

        out.push_str("}\n");
    }

    if let Some(parent) = output.parent() {
        fs::create_dir_all(parent).expect("Failed to create output directory");
    }
    fs::write(output, out).expect("Failed to write IPC generated file");
}

fn generate_generic_ipc_handler(out: &mut String, module: &str, f: &ApiFn, config: &Config) {
    let fn_name = &f.name;
    let svc = module;
    let is_async = f.is_async;
    let ret_type = &f.return_type;
    let await_str = if is_async { "\n        .await" } else { "" };
    let state_type = &config.state_type;
    let pp_line = prefix_param_line(config);

    let (fn_pp_body, first_arg) = if f.first_param_is_store {
        (store_construction_line(config), "&store")
    } else {
        (prefix_validation_line(config), "&state")
    };

    // Store-based custom handlers are always async (store construction is async)
    out.push_str(&format!("#[tauri::command]\n#[specta::specta]\npub async fn {}(\n", fn_name));

    for p in &f.params {
        let owned_ty = param_to_owned_type(&p.ty);
        out.push_str(&format!("    {}: {},\n", p.name, owned_ty));
    }

    out.push_str(&pp_line);
    out.push_str(&format!("    state: State<'_, Arc<{state_type}>>,\n"));
    out.push_str(&format!(") -> Result<{}, String> {{\n", ret_type));
    out.push_str(&fn_pp_body);

    out.push_str(&format!("    {}::{}({first_arg}", svc, fn_name));
    for p in &f.params {
        if p.ty.starts_with("Option<") {
            out.push_str(&format!(", {}.as_deref()", p.name));
        } else if p.ty.contains("Input") || p.ty == "i32" {
            out.push_str(&format!(", {}", p.name));
        } else {
            out.push_str(&format!(", &{}", p.name));
        }
    }
    out.push(')');
    out.push_str(await_str);
    out.push_str("\n        .map_err(|e| e.to_string())\n");
    out.push_str("}\n\n");
}
