// TODO: review — banner strings updated from old crate names
#![allow(clippy::too_many_lines, clippy::format_push_string)]

//! Generate Tauri IPC command handlers from API modules.

use std::fs;
use std::path::Path;

use ontogen_core::ir::OpKind;

use crate::servers::classify::classify_op;
use crate::servers::config::Config;
use crate::servers::parse::{ApiFn, ApiModule};
use crate::servers::types::{
    capitalize, collect_type_import, event_name, extract_input_type, inner_type, param_to_owned_type,
};

/// Returns the generated prefix param line for IPC commands (e.g., `project_id: Option<String>,`).
/// Empty string if no route_prefix configured.
fn prefix_param_line(config: &Config) -> String {
    match &config.route_prefix {
        Some(prefix) => {
            let pp = &prefix.params[0];
            format!("    {}: Option<String>,\n", pp.name)
        }
        None => String::new(),
    }
}

/// Returns the validation code for state-based IPC commands (validate-only).
fn prefix_validation_line(config: &Config) -> String {
    match &config.route_prefix {
        Some(prefix) => {
            let pp = &prefix.params[0];
            let accessor = &prefix.state_accessor;
            format!(
                "    if let Some(ref pid) = {} {{\n\
                 \x20       let uuid = uuid::Uuid::parse_str(pid).map_err(|e| e.to_string())?;\n\
                 \x20       state.{}(&uuid).map_err(|e| e.to_string())?;\n\
                 \x20   }}\n",
                pp.name, accessor,
            )
        }
        None => String::new(),
    }
}

/// Returns Store construction code for store-based IPC commands.
///
/// When project_id is provided, constructs Store via store_for().
/// When not provided, falls back to the default project via store().
fn store_construction_line(config: &Config) -> String {
    match &config.route_prefix {
        Some(prefix) => {
            let pp = &prefix.params[0];
            let accessor = &prefix.state_accessor;
            format!(
                "    let store = if let Some(ref pid) = {} {{\n\
                 \x20       let uuid = uuid::Uuid::parse_str(pid).map_err(|e| e.to_string())?;\n\
                 \x20       state.{}(&uuid).map_err(|e| e.to_string())?\n\
                 \x20   }} else {{\n\
                 \x20       state.store().await.map_err(|e| e.to_string())?\n\
                 \x20   }};\n",
                pp.name, accessor,
            )
        }
        None => "    let store = state.store().await.map_err(|e| e.to_string())?;\n".to_string(),
    }
}

/// Derive the IPC/TS command name for any function.
///
/// Uses entity-first naming with singular entity prefix:
///   CRUD:     `{entity}_list`, `{entity}_get_by_id`, `{entity}_create`, etc.
///   Junction: `{entity}_add_role`, `{entity}_list_skills`, etc.
///   Custom:   `{entity}_publish`, `{entity}_refresh`, etc.
pub fn command_name(module: &str, f: &ApiFn, config: &Config) -> String {
    let entity = config.naming.url_singular(module);
    format!("{}_{}", entity, f.name)
}

/// Generate IPC command handlers and write to the output file.
pub fn generate(output: &Path, modules: &[ApiModule], config: &Config) {
    let mut out = String::new();
    let state_type = &config.state_type;

    out.push_str(
        "\
#![allow(dead_code, unused_imports, clippy::pedantic)]
//! Auto-generated Tauri IPC command handlers. DO NOT EDIT.
//!
//! Generated by ontogen from API source files.

use std::sync::Arc;

use tauri::State;

",
    );

    // Collect imports
    let mut service_imports: Vec<String> = modules.iter().map(|m| m.name.clone()).collect();
    service_imports.sort();
    service_imports.dedup();

    let mut type_imports: Vec<String> = Vec::new();

    for m in modules {
        for f in &m.functions {
            collect_type_import(&f.return_type, &mut type_imports);
            for p in &f.params {
                let ty = extract_input_type(&p.ty);
                if ty.contains("Input") || ty.contains("Query") {
                    collect_type_import(&ty, &mut type_imports);
                }
            }
        }
    }

    // Emit use statements in sorted order (matches rustfmt alphabetical sort)
    let mut use_stmts = Vec::new();

    use_stmts.push(format!(
        "use {}::{{\n{}}};\n",
        config.service_import_path,
        service_imports.iter().map(|m| format!("    {},\n", m)).collect::<String>()
    ));

    type_imports.sort();
    type_imports.dedup();
    if !type_imports.is_empty() {
        use_stmts.push(format!(
            "use {}::{{\n{}}};\n",
            config.types_import_path,
            type_imports.iter().map(|t| format!("    {},\n", t)).collect::<String>()
        ));
    }

    use_stmts.push(format!("use {};\n", config.state_import));

    if let Some(ref store_import) = config.store_import {
        use_stmts.push(format!("use {};\n", store_import));
    }

    use_stmts.sort();
    for stmt in &use_stmts {
        out.push_str(stmt);
    }

    out.push('\n');

    if config.pagination.is_some() {
        out.push_str(
            "\
use serde::Serialize;

#[derive(Serialize)]
pub struct PaginatedResult<T: Serialize> {
    pub items: Vec<T>,
    pub total: u64,
    pub limit: u32,
    pub offset: u32,
}

",
        );
    }

    let pp_line = prefix_param_line(config);
    let pp_validate = prefix_validation_line(config);
    let store_construct = store_construction_line(config);

    let mut command_names: Vec<String> = Vec::new();

    for m in modules {
        let module = &m.name;
        let svc = module;

        if m.functions.is_empty() {
            continue;
        }

        out.push_str(&format!("// ── {} IPC Commands ──\n\n", capitalize(module)));

        for f in &m.functions {
            let op = classify_op(f);
            let is_async = f.is_async;
            let ret_type = &f.return_type;

            // Determine per-function prefix and first-arg behavior
            let (fn_pp_line, fn_pp_body, first_arg) = if f.first_param_is_store {
                (pp_line.clone(), store_construct.clone(), "store")
            } else {
                (pp_line.clone(), pp_validate.clone(), "&state")
            };

            match op {
                OpKind::List => {
                    let cmd_name = command_name(module, f, config);
                    let await_str = if is_async { ".await" } else { "" };
                    let query_param = f.params.iter().find(|p| p.ty.contains("Query"));
                    let plain_params: Vec<_> =
                        f.params.iter().filter(|p| !p.ty.contains("Query") && !p.ty.contains("Input")).collect();
                    let mut param_lines = String::new();
                    let mut extra_args = String::new();
                    if let Some(qp) = query_param {
                        let qt = extract_input_type(&qp.ty);
                        param_lines.push_str(&format!("    query: {},\n", qt));
                        extra_args.push_str(", query");
                    }
                    for pp in &plain_params {
                        let owned_ty = param_to_owned_type(&pp.ty);
                        param_lines.push_str(&format!("    {}: {},\n", pp.name, owned_ty));
                        extra_args.push_str(&format!(", &{}", pp.name));
                    }
                    if let Some(pg) = &config.pagination
                        && ret_type.starts_with("Vec<")
                    {
                        let item_type = inner_type(ret_type);
                        let default_limit = pg.default_limit;
                        let max_limit = pg.max_limit;
                        param_lines.push_str("    limit: Option<u32>,\n");
                        param_lines.push_str("    offset: Option<u32>,\n");
                        out.push_str(&format!(
                            "\
#[tauri::command]
pub async fn {cmd_name}(
{param_lines}{fn_pp_line}    state: State<'_, Arc<{state_type}>>,
) -> Result<PaginatedResult<{item_type}>, String> {{
{fn_pp_body}    let all_items = {svc}::list({first_arg}{extra_args}){await_str}
        .map_err(|e| e.to_string())?;
    let total = all_items.len() as u64;
    let limit = limit.unwrap_or({default_limit}).min({max_limit});
    let offset = offset.unwrap_or(0);
    let items = all_items.into_iter().skip(offset as usize).take(limit as usize).collect();
    Ok(PaginatedResult {{ items, total, limit, offset }})
}}

"
                        ));
                    } else {
                        out.push_str(&format!(
                            "\
#[tauri::command]
pub async fn {cmd_name}(
{param_lines}{fn_pp_line}    state: State<'_, Arc<{state_type}>>,
) -> Result<{ret_type}, String> {{
{fn_pp_body}    {svc}::list({first_arg}{extra_args}){await_str}
        .map_err(|e| e.to_string())
}}

"
                        ));
                    }
                    command_names.push(cmd_name);
                }

                OpKind::GetById => {
                    let cmd_name = command_name(module, f, config);
                    let fn_name = &f.name;
                    if is_async {
                        out.push_str(&format!(
                            "\
#[tauri::command]
pub async fn {cmd_name}(
    id: String,
{fn_pp_line}    state: State<'_, Arc<{state_type}>>,
) -> Result<{ret_type}, String> {{
{fn_pp_body}    {svc}::{fn_name}({first_arg}, &id)
        .await
        .map_err(|e| e.to_string())
}}

"
                        ));
                    } else {
                        out.push_str(&format!(
                            "\
#[tauri::command]
pub async fn {cmd_name}(
    id: String,
{fn_pp_line}    state: State<'_, Arc<{state_type}>>,
) -> Result<{ret_type}, String> {{
{fn_pp_body}    {svc}::{fn_name}({first_arg}, &id)
        .map_err(|e| e.to_string())
}}

"
                        ));
                    }
                    command_names.push(cmd_name);
                }

                OpKind::Create => {
                    let cmd_name = command_name(module, f, config);
                    let input_type = extract_input_type(&f.params[0].ty);
                    let await_str = if is_async { "\n        .await" } else { "" };
                    out.push_str(&format!(
                        "\
#[tauri::command]
pub async fn {cmd_name}(
    input: {input_type},
{fn_pp_line}    state: State<'_, Arc<{state_type}>>,
) -> Result<{ret_type}, String> {{
{fn_pp_body}    {svc}::create({first_arg}, input){await_str}
        .map_err(|e| e.to_string())
}}

"
                    ));
                    command_names.push(cmd_name);
                }

                OpKind::Update => {
                    let cmd_name = command_name(module, f, config);
                    let input_type = extract_input_type(&f.params[1].ty);
                    let await_str = if is_async { "\n        .await" } else { "" };
                    out.push_str(&format!(
                        "\
#[tauri::command]
pub async fn {cmd_name}(
    id: String,
    input: {input_type},
{fn_pp_line}    state: State<'_, Arc<{state_type}>>,
) -> Result<{ret_type}, String> {{
{fn_pp_body}    {svc}::update({first_arg}, &id, input){await_str}
        .map_err(|e| e.to_string())
}}

"
                    ));
                    command_names.push(cmd_name);
                }

                OpKind::Delete => {
                    let cmd_name = command_name(module, f, config);
                    let await_str = if is_async { "\n        .await" } else { "" };
                    out.push_str(&format!(
                        "\
#[tauri::command]
pub async fn {cmd_name}(
    id: String,
{fn_pp_line}    state: State<'_, Arc<{state_type}>>,
) -> Result<(), String> {{
{fn_pp_body}    {svc}::delete({first_arg}, &id){await_str}
        .map_err(|e| e.to_string())
}}

"
                    ));
                    command_names.push(cmd_name);
                }

                OpKind::JunctionList { .. } => {
                    let cmd_name = command_name(module, f, config);
                    if config.pagination.is_some() && ret_type.starts_with("Vec<") {
                        generate_paginated_ipc_handler(&mut out, module, f, config);
                    } else {
                        generate_generic_ipc_handler(&mut out, module, f, config);
                    }
                    command_names.push(cmd_name);
                }

                OpKind::JunctionAdd { .. } | OpKind::JunctionRemove { .. } => {
                    let cmd_name = command_name(module, f, config);
                    generate_generic_ipc_handler(&mut out, module, f, config);
                    command_names.push(cmd_name);
                }

                OpKind::CustomGet | OpKind::CustomPost => {
                    let cmd_name = command_name(module, f, config);
                    generate_generic_ipc_handler(&mut out, module, f, config);
                    command_names.push(cmd_name);
                }

                OpKind::EventStream => continue,
            }
        }
    }

    // Generate event forwarding function if any module has events
    let has_events = modules.iter().any(|m| !m.events.is_empty());
    if has_events {
        out.push_str(&format!(
            "\
// ── Event Forwarding ──

use tauri::Emitter;

/// Start IPC forwarding tasks for all event streams.
/// Call this during app setup to bridge EventBus → Tauri events.
pub fn start_event_forwarding(app_handle: tauri::AppHandle, state: &{}) {{
",
            config.state_import.split("::").last().unwrap_or(&config.state_type),
        ));

        for m in modules {
            for ev in &m.events {
                let fn_name = &ev.name;
                let ev_name = event_name(fn_name);
                let svc = &m.name;

                out.push_str(&format!(
                    "\
    // {fn_name}
    {{
        let handle = app_handle.clone();
        let mut rx = {}::{svc}::{fn_name}(state);
        tauri::async_runtime::spawn(async move {{
            while let Ok(delta) = rx.recv().await {{
                if let Err(e) = handle.emit(\"{ev_name}\", &delta) {{
                    log::error!(\"Failed to forward {ev_name} to IPC: {{:?}}\", e);
                }}
            }}
        }});
    }}
",
                    config.service_import_path,
                ));
            }
        }

        out.push_str("}\n");
    }

    // Generate ipc_handler() wrapper with tauri::generate_handler!
    out.push_str(
        "/// Generated IPC handler. Wire this into `tauri::Builder::invoke_handler()`.\n\
         pub fn ipc_handler() -> impl Fn(tauri::ipc::Invoke) -> bool + Send + Sync + 'static {\n\
         \x20   tauri::generate_handler![\n",
    );
    for name in &command_names {
        out.push_str(&format!("        {},\n", name));
    }
    out.push_str("    ]\n}\n");

    if let Some(parent) = output.parent() {
        fs::create_dir_all(parent).expect("Failed to create output directory");
    }
    crate::write_and_format(output, out).expect("Failed to write IPC generated file");
}

fn generate_generic_ipc_handler(out: &mut String, module: &str, f: &ApiFn, config: &Config) {
    let fn_name = &f.name;
    let svc = module;
    let is_async = f.is_async;
    let ret_type = &f.return_type;
    let await_str = if is_async { "\n        .await" } else { "" };
    let state_type = &config.state_type;
    let pp_line = prefix_param_line(config);

    let (fn_pp_body, first_arg) = if f.first_param_is_store {
        (store_construction_line(config), "store")
    } else {
        (prefix_validation_line(config), "&state")
    };

    // Store-based custom handlers are always async (store construction is async)
    let cmd_fn_name = command_name(module, f, config);
    out.push_str(&format!("#[tauri::command]\npub async fn {}(\n", cmd_fn_name));

    for p in &f.params {
        let owned_ty = param_to_owned_type(&p.ty);
        out.push_str(&format!("    {}: {},\n", p.name, owned_ty));
    }

    out.push_str(&pp_line);
    out.push_str(&format!("    state: State<'_, Arc<{state_type}>>,\n"));
    out.push_str(&format!(") -> Result<{}, String> {{\n", ret_type));
    out.push_str(&fn_pp_body);

    out.push_str(&format!("    {}::{}({first_arg}", svc, fn_name));
    for p in &f.params {
        if p.ty.starts_with("Option<") {
            out.push_str(&format!(", {}.as_deref()", p.name));
        } else if p.ty.contains("Input")
            || matches!(
                p.ty.as_str(),
                "bool" | "i8" | "i16" | "i32" | "i64" | "i128" | "u8" | "u16" | "u32" | "u64" | "u128" | "f32" | "f64"
            )
        {
            out.push_str(&format!(", {}", p.name));
        } else {
            out.push_str(&format!(", &{}", p.name));
        }
    }
    out.push(')');
    out.push_str(await_str);
    out.push_str("\n        .map_err(|e| e.to_string())\n");
    out.push_str("}\n\n");
}

/// Generate a paginated IPC handler for JunctionList operations.
///
/// Wraps the service call result in `PaginatedResult<T>` with limit/offset params.
fn generate_paginated_ipc_handler(out: &mut String, module: &str, f: &ApiFn, config: &Config) {
    let pg = config.pagination.as_ref().expect("pagination config required");
    let fn_name = &f.name;
    let svc = module;
    let is_async = f.is_async;
    let ret_type = &f.return_type;
    let item_type = inner_type(ret_type);
    let await_str = if is_async { ".await" } else { "" };
    let state_type = &config.state_type;
    let pp_line = prefix_param_line(config);
    let default_limit = pg.default_limit;
    let max_limit = pg.max_limit;

    let (fn_pp_body, first_arg) = if f.first_param_is_store {
        (store_construction_line(config), "store")
    } else {
        (prefix_validation_line(config), "&state")
    };

    let cmd_fn_name = command_name(module, f, config);
    out.push_str(&format!("#[tauri::command]\npub async fn {}(\n", cmd_fn_name));

    for p in &f.params {
        let owned_ty = param_to_owned_type(&p.ty);
        out.push_str(&format!("    {}: {},\n", p.name, owned_ty));
    }

    out.push_str("    limit: Option<u32>,\n");
    out.push_str("    offset: Option<u32>,\n");
    out.push_str(&pp_line);
    out.push_str(&format!("    state: State<'_, Arc<{state_type}>>,\n"));
    out.push_str(&format!(") -> Result<PaginatedResult<{}>, String> {{\n", item_type));
    out.push_str(&fn_pp_body);

    out.push_str(&format!("    let all_items = {}::{}({first_arg}", svc, fn_name));
    for p in &f.params {
        if p.ty.starts_with("Option<") {
            out.push_str(&format!(", {}.as_deref()", p.name));
        } else if p.ty.contains("Input")
            || matches!(
                p.ty.as_str(),
                "bool" | "i8" | "i16" | "i32" | "i64" | "i128" | "u8" | "u16" | "u32" | "u64" | "u128" | "f32" | "f64"
            )
        {
            out.push_str(&format!(", {}", p.name));
        } else {
            out.push_str(&format!(", &{}", p.name));
        }
    }
    out.push(')');
    out.push_str(await_str);
    out.push_str("\n        .map_err(|e| e.to_string())?;\n");
    out.push_str("    let total = all_items.len() as u64;\n");
    out.push_str(&format!("    let limit = limit.unwrap_or({default_limit}).min({max_limit});\n"));
    out.push_str("    let offset = offset.unwrap_or(0);\n");
    out.push_str("    let items = all_items.into_iter().skip(offset as usize).take(limit as usize).collect();\n");
    out.push_str("    Ok(PaginatedResult { items, total, limit, offset })\n");
    out.push_str("}\n\n");
}
