// TODO: review — banner strings updated from old crate names
#![allow(clippy::too_many_lines, clippy::format_push_string)]

//! Generate MCP (Model Context Protocol) tool registry from API modules.

use std::fs;
use std::path::Path;

use crate::servers::classify::{OpKind, classify_op};
use crate::servers::config::Config;
use crate::servers::parse::{ApiFn, ApiModule};
use crate::servers::types::{collect_type_import, extract_input_type, param_to_owned_type, to_pascal_case};

/// Wraps a schema_fn reference with project_id injection when route_prefix is set.
/// Returns either `"schema_for::<T>"` or `"|| with_project_id_schema(schema_for::<T>())"`.
fn wrap_schema(base: &str, config: &Config) -> String {
    if config.route_prefix.is_some() { format!("|| with_project_id_schema({}())", base) } else { base.to_string() }
}

/// Returns handler prefix code that extracts and validates project_id from MCP args.
fn mcp_handler_prefix(config: &Config) -> String {
    match &config.route_prefix {
        Some(prefix) => {
            let pp = &prefix.params[0];
            let accessor = &prefix.state_accessor;
            format!(
                "\
                    if let Some(pid) = args.get(\"{}\").and_then(|v| v.as_str()) {{
                        let uuid = uuid::Uuid::parse_str(pid).map_err(|e| e.to_string())?;
                        state.{}(&uuid).map_err(|e| e.to_string())?;
                    }}
",
                pp.name, accessor,
            )
        }
        None => String::new(),
    }
}

/// Returns Store construction code for MCP handlers (store-based functions).
///
/// Extracts optional project_id from args, constructs Store via state accessor.
fn mcp_store_construction(config: &Config) -> String {
    match &config.route_prefix {
        Some(prefix) => {
            let pp = &prefix.params[0];
            let accessor = &prefix.state_accessor;
            format!(
                "\
                    let store = if let Some(pid) = args.get(\"{}\").and_then(|v| v.as_str()) {{
                        let uuid = uuid::Uuid::parse_str(pid).map_err(|e| e.to_string())?;
                        state.{}(&uuid).map_err(|e| e.to_string())?
                    }} else {{
                        state.store().await.map_err(|e| e.to_string())?
                    }};
",
                pp.name, accessor,
            )
        }
        None => "                    let store = state.store().await.map_err(|e| e.to_string())?;\n".to_string(),
    }
}

/// Generate MCP tool registry and write to the output file.
pub fn generate(output: &Path, modules: &[ApiModule], config: &Config) {
    let mut out = String::new();
    let state_type = &config.state_type;

    out.push_str(
        "\
#![allow(dead_code, unused_imports, unused_variables, clippy::pedantic)]
//! Auto-generated MCP tool registry. DO NOT EDIT.
//!
//! Generated by ontogen from API source files.

use std::future::Future;
use std::pin::Pin;

use schemars::JsonSchema;
use serde::Deserialize;
use serde_json::{json, Value};

",
    );

    let mut service_imports: Vec<String> = modules.iter().map(|m| m.name.clone()).collect();
    service_imports.sort();
    service_imports.dedup();

    let mut type_imports: Vec<String> = Vec::new();
    for m in modules {
        for f in &m.functions {
            for p in &f.params {
                let ty = extract_input_type(&p.ty);
                if ty.contains("Input") || ty.contains("Query") {
                    collect_type_import(&ty, &mut type_imports);
                }
            }
        }
    }

    out.push_str(&format!("use {}::{{\n", config.service_import_path));
    for m in &service_imports {
        out.push_str(&format!("    {},\n", m));
    }
    out.push_str("};\n");

    type_imports.sort();
    type_imports.dedup();
    if !type_imports.is_empty() {
        out.push_str(&format!("use {}::{{\n", config.types_import_path));
        for t in &type_imports {
            out.push_str(&format!("    {},\n", t));
        }
        out.push_str("};\n");
    }

    out.push_str(&format!("use {};\n", config.state_import));

    // Add Store import if store_type is configured
    if let Some(ref store_import) = config.store_import {
        out.push_str(&format!("use {};\n", store_import));
    }

    out.push('\n');

    out.push_str(&format!(
        "\
/// Async handler signature for MCP tools.
type HandlerFn = for<'a> fn(
    &'a {state_type},
    &'a Value,
) -> Pin<Box<dyn Future<Output = Result<Value, String>> + Send + 'a>>;

/// A single MCP tool definition.
pub struct McpToolDef {{
    pub name: &'static str,
    pub description: &'static str,
    pub schema_fn: fn() -> Value,
    pub handler: HandlerFn,
}}

fn schema_for<T: JsonSchema>() -> Value {{
    serde_json::to_value(schemars::schema_for!(T)).expect(\"schemars schema must serialize\")
}}

fn schema_for_with_str_id<T: JsonSchema>() -> Value {{
    let mut schema = schema_for::<T>();
    if let Some(obj) = schema.as_object_mut() {{
        if let Some(props) = obj.get_mut(\"properties\").and_then(|p| p.as_object_mut()) {{
            props.insert(\"id\".to_string(), json!({{\"type\": \"string\"}}));
        }}
        if let Some(req) = obj.get_mut(\"required\").and_then(|r| r.as_array_mut()) {{
            req.push(json!(\"id\"));
        }} else {{
            obj.insert(\"required\".to_string(), json!([\"id\"]));
        }}
    }}
    schema
}}

#[allow(dead_code)]
fn schema_for_with_int_id<T: JsonSchema>() -> Value {{
    let mut schema = schema_for::<T>();
    if let Some(obj) = schema.as_object_mut() {{
        if let Some(props) = obj.get_mut(\"properties\").and_then(|p| p.as_object_mut()) {{
            props.insert(\"id\".to_string(), json!({{\"type\": \"integer\", \"format\": \"int32\"}}));
        }}
        if let Some(req) = obj.get_mut(\"required\").and_then(|r| r.as_array_mut()) {{
            req.push(json!(\"id\"));
        }} else {{
            obj.insert(\"required\".to_string(), json!([\"id\"]));
        }}
    }}
    schema
}}

fn required_str<'a>(args: &'a Value, key: &str) -> Result<&'a str, String> {{
    args.get(key)
        .and_then(|v| v.as_str())
        .ok_or_else(|| format!(\"Missing required parameter: {{key}}\"))
}}

/// Input for tools that look up a resource by string ID.
#[derive(Deserialize, JsonSchema)]
pub struct GetByIdInput {{
    pub id: String,
}}

/// Input for tools that operate on an integer id (i32).
#[derive(Deserialize, JsonSchema)]
pub struct ByIntIdInput {{
    pub id: i32,
}}

/// An empty-object schema for tools that take no parameters.
#[derive(Deserialize, JsonSchema)]
pub struct EmptyInput {{}}

",
    ));

    // Add project_id schema helper when route_prefix is configured
    if let Some(prefix) = &config.route_prefix {
        let pp = &prefix.params[0];
        out.push_str(&format!(
            "\
/// Inject an optional `{pp_name}` property into a JSON schema.
fn with_project_id_schema(mut schema: Value) -> Value {{
    if let Some(obj) = schema.as_object_mut() {{
        let props = obj.entry(\"properties\").or_insert_with(|| json!({{}}));
        if let Some(props_obj) = props.as_object_mut() {{
            props_obj.insert(\"{pp_name}\".to_string(), json!({{
                \"type\": \"string\",
                \"format\": \"uuid\",
                \"description\": \"Project ID (optional — uses default project if omitted)\"
            }}));
        }}
    }}
    schema
}}

",
            pp_name = pp.name,
        ));
    }

    // Generate input structs for custom functions with plain params
    for m in modules {
        for f in &m.functions {
            let op = classify_op(f);
            if !matches!(op, OpKind::CustomGet | OpKind::CustomPost
                | OpKind::JunctionList { .. } | OpKind::JunctionAdd { .. } | OpKind::JunctionRemove { .. }) {
                continue;
            }
            let has_body_struct = f.params.iter().any(|p| p.ty.contains("Input"));
            if has_body_struct || f.params.is_empty() {
                continue;
            }
            let struct_name = format!("{}{}Input", to_pascal_case(&m.name), to_pascal_case(&f.name));
            out.push_str(&format!("#[derive(Deserialize, JsonSchema)]\npub struct {} {{\n", struct_name));
            for p in &f.params {
                out.push_str(&format!("    pub {}: {},\n", p.name, param_to_owned_type(&p.ty)));
            }
            out.push_str("}\n\n");
        }
    }

    let hp = mcp_handler_prefix(config);
    let sc = mcp_store_construction(config);

    out.push_str(
        "/// Generated MCP tool definitions.\npub fn generated_tool_registry() -> Vec<McpToolDef> {\n    vec![\n",
    );

    for m in modules {
        if m.functions.is_empty() {
            continue;
        }

        let svc = &m.name;

        for f in &m.functions {
            // Use the canonical entity-first command name for tool names
            let tool_name = crate::servers::generators::ipc::command_name(svc, f, config);
            let op = classify_op(f);
            let is_async = f.is_async;
            let desc = if f.doc.is_empty() { format!("{} {}", f.name, svc) } else { f.doc.clone() };

            match op {
                OpKind::List => {
                    // tool_name computed above
                    let await_str = if is_async { ".await" } else { "" };
                    let (prefix, first_arg) =
                        if f.first_param_is_store { (sc.as_str(), "&store") } else { (hp.as_str(), "state") };
                    let query_param = f.params.iter().find(|p| p.ty.contains("Query"));
                    let plain_params: Vec<_> = f.params.iter()
                        .filter(|p| !p.ty.contains("Query") && !p.ty.contains("Input"))
                        .collect();
                    let mut schema_fn = wrap_schema("schema_for::<EmptyInput>", config);
                    let mut extraction = String::new();
                    let mut extra_args = String::new();
                    if let Some(qp) = query_param {
                        let qt = extract_input_type(&qp.ty);
                        schema_fn = wrap_schema(&format!("schema_for::<{qt}>"), config);
                        extraction.push_str(&format!("                    let query: {qt} = serde_json::from_value(args.clone()).unwrap_or_default();\n"));
                        extra_args.push_str(", query");
                    }
                    for pp in &plain_params {
                        extraction.push_str(&format!("                    let {} = required_str(args, \"{}\")?;\n", pp.name, pp.name));
                        extra_args.push_str(&format!(", {}", pp.name));
                    }
                    let args_param = if extraction.is_empty() { "_args" } else { "args" };
                    out.push_str(&format!(
                        "\
        McpToolDef {{
            name: \"{tool_name}\",
            description: \"{desc}\",
            schema_fn: {schema_fn},
            handler: |state, {args_param}| {{
                Box::pin(async move {{
{prefix}{extraction}                    let items = {svc}::list({first_arg}{extra_args}){await_str}.map_err(|e| e.to_string())?;
                    serde_json::to_value(items).map_err(|e| format!(\"Serialize error: {{e}}\"))
                }})
            }},
        }},
"
                    ));
                }

                OpKind::GetById => {
                    // tool_name computed above
                    let await_str = if is_async { ".await" } else { "" };
                    let fn_name = &f.name;
                    let (prefix, first_arg) =
                        if f.first_param_is_store { (sc.as_str(), "&store") } else { (hp.as_str(), "state") };
                    let schema_fn = wrap_schema("schema_for::<GetByIdInput>", config);
                    out.push_str(&format!(
                        "\
        McpToolDef {{
            name: \"{tool_name}\",
            description: \"{desc}\",
            schema_fn: {schema_fn},
            handler: |state, args| {{
                Box::pin(async move {{
{prefix}                    let id = required_str(args, \"id\")?;
                    let item = {svc}::{fn_name}({first_arg}, id){await_str}.map_err(|e| e.to_string())?;
                    serde_json::to_value(item).map_err(|e| format!(\"Serialize error: {{e}}\"))
                }})
            }},
        }},
"
                    ));
                }

                OpKind::Create => {
                    // tool_name computed above
                    let input_type = extract_input_type(&f.params[0].ty);
                    let await_str = if is_async { ".await" } else { "" };
                    let schema_fn = wrap_schema(&format!("schema_for::<{input_type}>"), config);
                    let (prefix, first_arg) =
                        if f.first_param_is_store { (sc.as_str(), "&store") } else { (hp.as_str(), "state") };
                    out.push_str(&format!(
                        "\
        McpToolDef {{
            name: \"{tool_name}\",
            description: \"{desc}\",
            schema_fn: {schema_fn},
            handler: |state, args| {{
                Box::pin(async move {{
{prefix}                    let input: {input_type} = serde_json::from_value(args.clone())
                        .map_err(|e| format!(\"Invalid input: {{e}}\"))?;
                    {svc}::create({first_arg}, input){await_str}.map_err(|e| e.to_string())?;
                    Ok(json!({{\"success\": true}}))
                }})
            }},
        }},
"
                    ));
                }

                OpKind::UpdateById => {
                    // tool_name computed above
                    let input_type = extract_input_type(&f.params[1].ty);
                    let await_str = if is_async { ".await" } else { "" };
                    let (prefix, first_arg) =
                        if f.first_param_is_store { (sc.as_str(), "&store") } else { (hp.as_str(), "state") };
                    let schema_fn = wrap_schema(&format!("schema_for_with_str_id::<{input_type}>"), config);
                    out.push_str(&format!(
                        "\
        McpToolDef {{
            name: \"{tool_name}\",
            description: \"{desc}\",
            schema_fn: {schema_fn},
            handler: |state, args| {{
                Box::pin(async move {{
{prefix}                    let id = required_str(args, \"id\")?.to_string();
                    let input: {input_type} = serde_json::from_value(args.clone())
                        .map_err(|e| format!(\"Invalid input: {{e}}\"))?;
                    {svc}::update({first_arg}, &id, input){await_str}.map_err(|e| e.to_string())?;
                    Ok(json!({{\"success\": true}}))
                }})
            }},
        }},
"
                    ));
                }

                OpKind::DeleteById => {
                    // tool_name computed above
                    let await_str = if is_async { ".await" } else { "" };
                    let (prefix, first_arg) =
                        if f.first_param_is_store { (sc.as_str(), "&store") } else { (hp.as_str(), "state") };
                    let schema_fn = wrap_schema("schema_for::<GetByIdInput>", config);
                    out.push_str(&format!(
                        "\
        McpToolDef {{
            name: \"{tool_name}\",
            description: \"{desc}\",
            schema_fn: {schema_fn},
            handler: |state, args| {{
                Box::pin(async move {{
{prefix}                    let id = required_str(args, \"id\")?.to_string();
                    {svc}::delete({first_arg}, &id){await_str}.map_err(|e| e.to_string())?;
                    Ok(json!({{\"success\": true}}))
                }})
            }},
        }},
"
                    ));
                }

                OpKind::JunctionList { .. } | OpKind::JunctionAdd { .. } | OpKind::JunctionRemove { .. } => {
                    generate_generic_mcp_tool(&mut out, svc, f, config);
                }

                OpKind::CustomGet | OpKind::CustomPost => {
                    generate_generic_mcp_tool(&mut out, svc, f, config);
                }
            }
        }
    }

    out.push_str("    ]\n}\n\n");

    // Generate simple tool_definitions() that returns static schema data
    out.push_str(&format!(
        "\
/// Simple tool definition with pre-computed schema (for MCP protocol responses).
pub struct SimpleToolDef {{
    pub name: &'static str,
    pub description: &'static str,
    pub input_schema: Value,
}}

/// Return tool definitions with pre-computed input schemas.
/// Use this for building MCP `tools/list` responses.
pub fn tool_definitions() -> Vec<SimpleToolDef> {{
    generated_tool_registry()
        .into_iter()
        .map(|t| SimpleToolDef {{
            name: t.name,
            description: t.description,
            input_schema: (t.schema_fn)(),
        }})
        .collect()
}}

/// Dispatch a tool call by name, executing the matching handler synchronously.
///
/// This creates a minimal tokio runtime to drive the async handler.
/// Suitable for MCP servers that process requests synchronously.
pub fn handle_tool_call(
    state: &{state_type},
    tool_name: &str,
    args: &serde_json::Map<String, Value>,
) -> Result<Value, String> {{
    let registry = generated_tool_registry();
    let tool = registry
        .iter()
        .find(|t| t.name == tool_name)
        .ok_or_else(|| format!(\"Unknown tool: {{tool_name}}\"))?;
    let args_value = Value::Object(args.clone());
    let rt = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .map_err(|e| format!(\"Runtime error: {{e}}\"))?;
    rt.block_on((tool.handler)(state, &args_value))
}}
"
    ));

    if let Some(parent) = output.parent() {
        fs::create_dir_all(parent).expect("Failed to create output directory");
    }
    crate::write_and_format(output, out).expect("Failed to write MCP generated file");
}

fn generate_generic_mcp_tool(out: &mut String, svc: &str, f: &ApiFn, config: &Config) {
    let fn_name = &f.name;
    let desc = if f.doc.is_empty() { fn_name.clone() } else { f.doc.clone() };
    let is_async = f.is_async;
    let await_str = if is_async { ".await" } else { "" };
    let tool_name = crate::servers::generators::ipc::command_name(svc, f, config);
    let returns_unit = f.return_type == "()";
    let (hp, first_arg) = if f.first_param_is_store {
        (mcp_store_construction(config), "&store")
    } else {
        (mcp_handler_prefix(config), "state")
    };

    let has_body_struct = f.params.iter().any(|p| p.ty.contains("Input"));
    let has_params = !f.params.is_empty();

    if !has_params {
        let schema_fn = wrap_schema("schema_for::<EmptyInput>", config);
        if returns_unit {
            out.push_str(&format!(
                "\
        McpToolDef {{
            name: \"{tool_name}\",
            description: \"{desc}\",
            schema_fn: {schema_fn},
            handler: |state, args| {{
                Box::pin(async move {{
{hp}                    {svc}::{fn_name}({first_arg}){await_str}.map_err(|e| e.to_string())?;
                    Ok(json!({{\"success\": true}}))
                }})
            }},
        }},
"
            ));
        } else {
            out.push_str(&format!(
                "\
        McpToolDef {{
            name: \"{tool_name}\",
            description: \"{desc}\",
            schema_fn: {schema_fn},
            handler: |state, args| {{
                Box::pin(async move {{
{hp}                    let result = {svc}::{fn_name}({first_arg}){await_str}.map_err(|e| e.to_string())?;
                    serde_json::to_value(result).map_err(|e| format!(\"Serialize error: {{e}}\"))
                }})
            }},
        }},
"
            ));
        }
    } else if has_body_struct {
        let input_param = f.params.iter().find(|p| p.ty.contains("Input")).unwrap();
        let input_type = extract_input_type(&input_param.ty);
        let schema_fn = wrap_schema(&format!("schema_for::<{input_type}>"), config);
        if returns_unit {
            out.push_str(&format!(
                "\
        McpToolDef {{
            name: \"{tool_name}\",
            description: \"{desc}\",
            schema_fn: {schema_fn},
            handler: |state, args| {{
                Box::pin(async move {{
{hp}                    let input: {input_type} = serde_json::from_value(args.clone())
                        .map_err(|e| format!(\"Invalid input: {{e}}\"))?;
                    {svc}::{fn_name}({first_arg}, input){await_str}.map_err(|e| e.to_string())?;
                    Ok(json!({{\"success\": true}}))
                }})
            }},
        }},
"
            ));
        } else {
            out.push_str(&format!(
                "\
        McpToolDef {{
            name: \"{tool_name}\",
            description: \"{desc}\",
            schema_fn: {schema_fn},
            handler: |state, args| {{
                Box::pin(async move {{
{hp}                    let input: {input_type} = serde_json::from_value(args.clone())
                        .map_err(|e| format!(\"Invalid input: {{e}}\"))?;
                    let result = {svc}::{fn_name}({first_arg}, input){await_str}.map_err(|e| e.to_string())?;
                    serde_json::to_value(result).map_err(|e| format!(\"Serialize error: {{e}}\"))
                }})
            }},
        }},
"
            ));
        }
    } else {
        let struct_name = format!("{}{}Input", to_pascal_case(svc), to_pascal_case(fn_name));
        let schema_fn = wrap_schema(&format!("schema_for::<{struct_name}>"), config);

        let mut extraction = String::new();
        let mut call_args = String::new();
        for p in &f.params {
            if p.ty.starts_with("Option<") {
                extraction.push_str(&format!(
                    "                    let {} = args.get(\"{}\").and_then(|v| v.as_str()).map(|s| s.to_string());\n",
                    p.name, p.name
                ));
                call_args.push_str(&format!(", {}.as_deref()", p.name));
            } else if p.ty == "i32" {
                extraction.push_str(&format!(
                    "                    let {} = args.get(\"{}\").and_then(|v| v.as_i64()).ok_or(\"Missing {}\")? as i32;\n",
                    p.name, p.name, p.name
                ));
                call_args.push_str(&format!(", {}", p.name));
            } else if p.ty == "i64" {
                extraction.push_str(&format!(
                    "                    let {} = args.get(\"{}\").and_then(|v| v.as_i64()).ok_or(\"Missing {}\")?;\n",
                    p.name, p.name, p.name
                ));
                call_args.push_str(&format!(", {}", p.name));
            } else {
                extraction
                    .push_str(&format!("                    let {} = required_str(args, \"{}\")?;\n", p.name, p.name));
                call_args.push_str(&format!(", {}", p.name));
            }
        }

        if returns_unit {
            out.push_str(&format!(
                "\
        McpToolDef {{
            name: \"{tool_name}\",
            description: \"{desc}\",
            schema_fn: {schema_fn},
            handler: |state, args| {{
                Box::pin(async move {{
{hp}{extraction}                    {svc}::{fn_name}({first_arg}{call_args}){await_str}.map_err(|e| e.to_string())?;
                    Ok(json!({{\"success\": true}}))
                }})
            }},
        }},
"
            ));
        } else {
            out.push_str(&format!(
                "\
        McpToolDef {{
            name: \"{tool_name}\",
            description: \"{desc}\",
            schema_fn: {schema_fn},
            handler: |state, args| {{
                Box::pin(async move {{
{hp}{extraction}                    let result = {svc}::{fn_name}({first_arg}{call_args}){await_str}.map_err(|e| e.to_string())?;
                    serde_json::to_value(result).map_err(|e| format!(\"Serialize error: {{e}}\"))
                }})
            }},
        }},
"
            ));
        }
    }
}
