#![allow(clippy::too_many_lines, clippy::format_push_string)]

//! Generate MCP (Model Context Protocol) tool registry from API modules.

use std::fs;
use std::path::Path;

use ontogen_core::ir::OpKind;

use crate::schema::sort::{sort_fields, sort_keys};
use crate::servers::classify::classify_op;
use crate::servers::config::{Config, PaginationConfig};
use crate::servers::generators::{filter_arg, surface_use_stmts};
use crate::servers::parse::{ApiFn, ApiModule, Param};
use crate::servers::types::{extract_input_type, forward_arg_expr, param_to_owned_type, to_pascal_case};

/// Returns handler prefix code that extracts and validates project_id from MCP args.
fn mcp_handler_prefix(config: &Config) -> String {
    match &config.route_prefix {
        Some(prefix) => {
            let pp = &prefix.params[0];
            let accessor = &prefix.state_accessor;
            format!(
                "\
                    if let Some(pid) = ontogen_args.get(\"{}\").and_then(|v| v.as_str()) {{
                        let uuid = uuid::Uuid::parse_str(pid).map_err(|e| e.to_string())?;
                        ontogen_state.{}(&uuid).map_err(|e| e.to_string())?;
                    }}
",
                pp.name, accessor,
            )
        }
        None => String::new(),
    }
}

/// Returns Store construction code for a store-based MCP handler.
///
/// Extracts optional project_id from args and constructs the Store via the
/// prefix accessor; otherwise opens it through the fn's surface accessor.
fn mcp_store_construction(config: &Config, f: &ApiFn) -> String {
    let store_accessor = &f.store_accessor;
    match &config.route_prefix {
        Some(prefix) => {
            let pp = &prefix.params[0];
            let accessor = &prefix.state_accessor;
            format!(
                "\
                    let ontogen_store = if let Some(pid) = ontogen_args.get(\"{}\").and_then(|v| v.as_str()) {{
                        let uuid = uuid::Uuid::parse_str(pid).map_err(|e| e.to_string())?;
                        ontogen_state.{}(&uuid).map_err(|e| e.to_string())?
                    }} else {{
                        ontogen_state.{store_accessor}().await.map_err(|e| e.to_string())?
                    }};
",
                pp.name, accessor,
            )
        }
        None => {
            format!(
                "                    let ontogen_store = ontogen_state.{store_accessor}().await.map_err(|e| e.to_string())?;\n"
            )
        }
    }
}

/// Generate MCP tool registry and write to the output file.
pub fn generate(output: &Path, modules: &[ApiModule], config: &Config) {
    let mut out = String::new();
    let state_type = &config.state_type;

    out.push_str(
        "\
#![allow(dead_code, unused_imports, unused_variables, clippy::pedantic, clippy::needless_borrow)]
//! Auto-generated MCP tool registry. DO NOT EDIT.
//!
//! Generated by ontogen from API source files.

use std::future::Future;
use std::pin::Pin;

use schemars::JsonSchema;
use serde::Deserialize;
use serde_json::{json, Value};

",
    );

    for stmt in surface_use_stmts(modules, config) {
        out.push_str(&stmt);
    }

    out.push_str(&format!("use {};\n", config.state_import));

    // Add Store import if store_type is configured
    if let Some(ref store_import) = config.store_import {
        out.push_str(&format!("use {};\n", store_import));
    }

    out.push('\n');

    out.push_str(&format!(
        "\
/// Async handler signature for MCP tools.
type HandlerFn = for<'a> fn(
    &'a {state_type},
    &'a Value,
) -> Pin<Box<dyn Future<Output = Result<Value, String>> + Send + 'a>>;

/// A single MCP tool definition.
pub struct McpToolDef {{
    pub name: &'static str,
    pub description: &'static str,
    pub schema_fn: fn() -> Value,
    pub handler: HandlerFn,
}}

fn schema_for<T: JsonSchema>() -> Value {{
    serde_json::to_value(schemars::schema_for!(T)).expect(\"schemars schema must serialize\")
}}

fn schema_for_with_str_id<T: JsonSchema>() -> Value {{
    let mut schema = schema_for::<T>();
    if let Some(obj) = schema.as_object_mut() {{
        if let Some(props) = obj.get_mut(\"properties\").and_then(|p| p.as_object_mut()) {{
            props.insert(\"id\".to_string(), json!({{\"type\": \"string\"}}));
        }}
        if let Some(req) = obj.get_mut(\"required\").and_then(|r| r.as_array_mut()) {{
            req.push(json!(\"id\"));
        }} else {{
            obj.insert(\"required\".to_string(), json!([\"id\"]));
        }}
    }}
    schema
}}

#[allow(dead_code)]
fn schema_for_with_int_id<T: JsonSchema>() -> Value {{
    let mut schema = schema_for::<T>();
    if let Some(obj) = schema.as_object_mut() {{
        if let Some(props) = obj.get_mut(\"properties\").and_then(|p| p.as_object_mut()) {{
            props.insert(\"id\".to_string(), json!({{\"type\": \"integer\", \"format\": \"int32\"}}));
        }}
        if let Some(req) = obj.get_mut(\"required\").and_then(|r| r.as_array_mut()) {{
            req.push(json!(\"id\"));
        }} else {{
            obj.insert(\"required\".to_string(), json!([\"id\"]));
        }}
    }}
    schema
}}

/// The string argument `key`: missing is one error, any other type another.
/// A value of another type is worded as serde words it for a `String`
/// (`expected a string`), not for a `&str` (`expected a borrowed string`).
fn required_str<'a>(args: &'a Value, key: &str) -> Result<&'a str, String> {{
    let value = args.get(key).ok_or_else(|| format!(\"Missing required parameter: {{key}}\"))?;
    value.as_str().ok_or_else(|| {{
        let e = String::deserialize(value).expect_err(\"a value that is no string is no String\");
        format!(\"Invalid parameter {{key}}: {{e}}\")
    }})
}}

/// `args` without the keys a tool reads on its own: the rest is the struct
/// it deserializes, which may refuse a field it does not declare.
fn args_without(args: &Value, keys: &[&str]) -> Value {{
    let mut rest = args.clone();
    if let Some(rest) = rest.as_object_mut() {{
        for key in keys {{
            rest.remove(*key);
        }}
    }}
    rest
}}

/// Refuses an argument the tool's input schema does not name, so a
/// misspelt argument is an error rather than one silently dropped (a
/// misspelt filter is not a wider list). A schema that leaves its object
/// open (an `additionalProperties` other than `false`) or composes it
/// (`allOf`, `anyOf`, `oneOf`, `$ref`) names no closed set of arguments, so
/// it refuses none.
fn refuse_unknown_args(args: &Value, schema: Value) -> Result<(), String> {{
    let open = schema.get(\"additionalProperties\").is_some_and(|a| a != &Value::Bool(false))
        || [\"allOf\", \"anyOf\", \"oneOf\", \"$ref\"].iter().any(|k| schema.get(*k).is_some());
    if open {{
        return Ok(());
    }}
    let named = schema.get(\"properties\").and_then(Value::as_object);
    let unknown = args.as_object().and_then(|args| args.keys().find(|key| !named.is_some_and(|n| n.contains_key(*key))));
    match unknown {{
        Some(key) => Err(format!(\"Unknown argument: {{key}}\")),
        None => Ok(()),
    }}
}}

/// Input for tools that look up a resource by string ID.
#[derive(Deserialize, JsonSchema)]
pub struct GetByIdInput {{
    pub id: String,
}}

/// Input for tools that operate on an integer id (i32).
#[derive(Deserialize, JsonSchema)]
pub struct ByIntIdInput {{
    pub id: i32,
}}

/// An empty-object schema for tools that take no parameters.
#[derive(Deserialize, JsonSchema)]
pub struct EmptyInput {{}}

",
    ));

    // Add project_id schema helper when route_prefix is configured
    if let Some(prefix) = &config.route_prefix {
        let pp = &prefix.params[0];
        out.push_str(&format!(
            "\
/// Inject an optional `{pp_name}` property into a JSON schema.
fn with_project_id_schema(mut schema: Value) -> Value {{
    if let Some(obj) = schema.as_object_mut() {{
        let props = obj.entry(\"properties\").or_insert_with(|| json!({{}}));
        if let Some(props_obj) = props.as_object_mut() {{
            props_obj.insert(\"{pp_name}\".to_string(), json!({{
                \"type\": \"string\",
                \"format\": \"uuid\",
                \"description\": \"Project ID (optional - uses default project if omitted)\"
            }}));
        }}
    }}
    schema
}}

",
            pp_name = pp.name,
        ));
    }

    // Add pagination schema helper when pagination is configured
    if config.any_pagination() {
        out.push_str(
            "\
/// Inject `limit` and `offset` pagination properties into a JSON schema.
fn with_pagination_schema(mut schema: Value) -> Value {
    if let Some(obj) = schema.as_object_mut() {
        let props = obj.entry(\"properties\").or_insert_with(|| json!({}));
        if let Some(props_obj) = props.as_object_mut() {
            props_obj.insert(\"limit\".to_string(), json!({
                \"type\": \"integer\",
                \"description\": \"Maximum number of items to return\"
            }));
            props_obj.insert(\"offset\".to_string(), json!({
                \"type\": \"integer\",
                \"description\": \"Number of items to skip\"
            }));
        }
    }
    schema
}

",
        );
    }

    if modules.iter().any(|m| m.functions.iter().any(|f| classify_op(m, f) == OpKind::List && f.takes_order())) {
        out.push_str(SORT_HELPERS);
    }

    // A custom op's input schema names each plain parameter beside its
    // body's fields, so the tool advertises every argument it reads.
    for m in modules {
        for f in &m.functions {
            let op = classify_op(m, f);
            if !matches!(
                op,
                OpKind::CustomGet
                    | OpKind::CustomPost
                    | OpKind::JunctionList { .. }
                    | OpKind::JunctionAdd { .. }
                    | OpKind::JunctionRemove { .. }
            ) {
                continue;
            }
            out.push_str(&generic_input_schema_struct(m, f).unwrap_or_default());
        }
    }

    // A list's input schema names each bare filter beside its `*Query`
    // struct's fields, so the tool advertises every argument it reads.
    for m in modules {
        for f in &m.functions {
            if classify_op(m, f) == OpKind::List && !f.bare_filters().is_empty() {
                out.push_str(&list_filter_schema_struct(m, f));
            }
        }
    }

    let hp = mcp_handler_prefix(config);

    out.push_str(
        "/// Generated MCP tool definitions.\npub fn generated_tool_registry() -> Vec<McpToolDef> {\n    vec![\n",
    );

    for m in modules {
        if m.functions.is_empty() {
            continue;
        }

        let module = &m.name;

        for f in &m.functions {
            // Use the canonical entity-first command name for tool names
            let tool_name = crate::servers::generators::ipc::command_name(module, f, config);
            let op = classify_op(m, f);
            let svc = m.service_ident(f.surface);
            let is_async = f.is_async;
            let desc = if f.doc.is_empty() { format!("{} {}", f.name, module) } else { f.doc.clone() };
            let sc = mcp_store_construction(config, f);
            let (prefix, first_arg) =
                if f.first_param_is_store { (sc.as_str(), "&ontogen_store") } else { (hp.as_str(), "ontogen_state") };

            match op {
                OpKind::List => {
                    let await_str = if is_async { ".await" } else { "" };
                    let ret_type = &f.return_type;
                    // Pagination only applies when the list function returns Vec<T>;
                    // custom result types (e.g., CodingAgentListResult) are passed through unchanged.
                    let pagination = config.pagination_for(module, f.surface).filter(|_| ret_type.starts_with("Vec<"));
                    let paginate = pagination.is_some();
                    // A pushed-down list's own limit/offset are the page, taken
                    // from `args` below — not tool arguments to extract.
                    let pushes_page = paginate && f.takes_page();
                    let schema_input = match f.filter_struct() {
                        _ if !f.bare_filters().is_empty() => list_filter_schema_name(m, f),
                        Some(qp) => extract_input_type(&qp.ty),
                        None => "EmptyInput".to_string(),
                    };
                    let schema_base = format!("schema_for::<{schema_input}>");
                    let mut extraction = String::new();
                    if let Some(qp) = f.filter_struct() {
                        let qt = extract_input_type(&qp.ty);
                        let rest = struct_args(&list_struct_skipped_keys(f, config, paginate));
                        extraction.push_str(&format!(
                            "                    let ontogen_filter: {qt} = serde_json::from_value({rest}).map_err(|e| format!(\"Invalid filter: {{e}}\"))?;\n"
                        ));
                    }
                    for pp in f.bare_filters() {
                        extraction.push_str(&arg_extraction(pp));
                    }
                    // A list that takes an order reads it from `sort` after its
                    // filter, as HTTP does, and passes it after the filter.
                    let order_arg = if f.takes_order() {
                        extraction.push_str(ORDER_FROM_SORT);
                        ", &ontogen_order"
                    } else {
                        ""
                    };
                    // A filtered page calls `count` with the same filter after
                    // `list`, which gets a clone of whatever it would consume.
                    let filter_args = |counted: bool| -> String {
                        f.filter()
                            .iter()
                            .map(|p| match p.ty.as_str() {
                                _ if p.is_filter_struct() => format!(", {}", filter_arg(p, "ontogen_filter", counted)),
                                // `required_str` already lends a `&str`.
                                "&str" => format!(", {}", p.name),
                                _ => format!(", {}", filter_arg(p, &p.name, counted)),
                            })
                            .collect()
                    };
                    let count_args = filter_args(false);
                    let extra_args = format!("{count_args}{order_arg}");
                    let body = if let Some(pg) = pagination {
                        let default_limit = pg.default_limit;
                        let max_limit = pg.max_limit;
                        // Two shapes. When `list` takes the page it is pushed down
                        // and the total comes from the module's `count` — nothing
                        // beyond the page is ever materialised. A list that does not
                        // take it (not every Vec-returning op is the checked `list`)
                        // keeps the older in-memory slice.
                        // A filtered page calls `count` with the same filter,
                        // after `list` has consumed it.
                        let read = if pushes_page {
                            let list_args = format!("{}{order_arg}", filter_args(true));
                            format!(
                                "\
                    let ontogen_limit = ontogen_args.get(\"limit\").and_then(|v| v.as_u64()).unwrap_or({default_limit}).min({max_limit});
                    let ontogen_offset = ontogen_args.get(\"offset\").and_then(|v| v.as_u64()).unwrap_or(0);
                    let ontogen_items = {svc}::list({first_arg}{list_args}, Some(ontogen_limit), Some(ontogen_offset)){await_str}.map_err(|e| e.to_string())?;
                    let ontogen_total = {svc}::count({first_arg}{count_args}){await_str}.map_err(|e| e.to_string())?;
"
                            )
                        } else {
                            format!(
                                "                    let ontogen_all = {svc}::list({first_arg}{extra_args}){await_str}.map_err(|e| e.to_string())?;\n{}",
                                in_memory_page(default_limit, max_limit)
                            )
                        };
                        format!("{prefix}{read}{PAGE_RESULT}")
                    } else {
                        // A surface with no pagination passes no page, so a list that takes one gets the whole table.
                        let page_args = if f.takes_page() { ", None, None" } else { "" };
                        format!(
                            "\
{prefix}                    let ontogen_items = {svc}::list({first_arg}{extra_args}{page_args}){await_str}.map_err(|e| e.to_string())?;
                    serde_json::to_value(ontogen_items).map_err(|e| format!(\"Serialize error: {{e}}\"))
"
                        )
                    };
                    let sort = list_sort_keys(m, f, config);
                    let schema = ToolSchema { base: &schema_base, config, paginate, sort: sort.as_deref() };
                    push_tool(&mut out, &tool_name, &desc, &schema, &format!("{extraction}{body}"));
                }

                OpKind::GetById => {
                    let await_str = if is_async { ".await" } else { "" };
                    let fn_name = &f.name;
                    let schema = ToolSchema { base: "schema_for::<GetByIdInput>", config, paginate: false, sort: None };
                    let body = format!(
                        "\
{prefix}                    let id = required_str(ontogen_args, \"id\")?;
                    let item = {svc}::{fn_name}({first_arg}, id){await_str}.map_err(|e| e.to_string())?;
                    serde_json::to_value(item).map_err(|e| format!(\"Serialize error: {{e}}\"))
"
                    );
                    push_tool(&mut out, &tool_name, &desc, &schema, &body);
                }

                OpKind::Create => {
                    let input_type = extract_input_type(&f.params[0].ty);
                    let await_str = if is_async { ".await" } else { "" };
                    let schema_base = format!("schema_for::<{input_type}>");
                    let schema = ToolSchema { base: &schema_base, config, paginate: false, sort: None };
                    let rest = struct_args(&scope_key(config).into_iter().collect::<Vec<_>>());
                    let body = format!(
                        "\
{prefix}                    let input: {input_type} = serde_json::from_value({rest})
                        .map_err(|e| format!(\"Invalid input: {{e}}\"))?;
                    {svc}::create({first_arg}, input){await_str}.map_err(|e| e.to_string())?;
                    Ok(json!({{\"success\": true}}))
"
                    );
                    push_tool(&mut out, &tool_name, &desc, &schema, &body);
                }

                OpKind::Update => {
                    let input_type = extract_input_type(&f.params[1].ty);
                    let await_str = if is_async { ".await" } else { "" };
                    let schema_base = format!("schema_for_with_str_id::<{input_type}>");
                    let schema = ToolSchema { base: &schema_base, config, paginate: false, sort: None };
                    let rest =
                        struct_args(&["id".to_string()].into_iter().chain(scope_key(config)).collect::<Vec<_>>());
                    let body = format!(
                        "\
{prefix}                    let id = required_str(ontogen_args, \"id\")?.to_string();
                    let input: {input_type} = serde_json::from_value({rest})
                        .map_err(|e| format!(\"Invalid input: {{e}}\"))?;
                    {svc}::update({first_arg}, &id, input){await_str}.map_err(|e| e.to_string())?;
                    Ok(json!({{\"success\": true}}))
"
                    );
                    push_tool(&mut out, &tool_name, &desc, &schema, &body);
                }

                OpKind::Delete => {
                    let await_str = if is_async { ".await" } else { "" };
                    let schema = ToolSchema { base: "schema_for::<GetByIdInput>", config, paginate: false, sort: None };
                    let body = format!(
                        "\
{prefix}                    let id = required_str(ontogen_args, \"id\")?.to_string();
                    {svc}::delete({first_arg}, &id){await_str}.map_err(|e| e.to_string())?;
                    Ok(json!({{\"success\": true}}))
"
                    );
                    push_tool(&mut out, &tool_name, &desc, &schema, &body);
                }

                OpKind::JunctionList { .. } => {
                    generate_generic_mcp_tool(&mut out, m, f, config, true);
                }

                OpKind::JunctionAdd { .. } | OpKind::JunctionRemove { .. } => {
                    generate_generic_mcp_tool(&mut out, m, f, config, false);
                }

                OpKind::CustomGet | OpKind::CustomPost => {
                    generate_generic_mcp_tool(&mut out, m, f, config, false);
                }

                // Event ops are skipped: an MCP tool call returns one result
                // and has no shape for a subscription.
                OpKind::EventStream => continue,
            }
        }
    }

    out.push_str("    ]\n}\n\n");

    // Generate simple tool_definitions() that returns static schema data
    out.push_str(&format!(
        "\
/// Simple tool definition with pre-computed schema (for MCP protocol responses).
pub struct SimpleToolDef {{
    pub name: &'static str,
    pub description: &'static str,
    pub input_schema: Value,
}}

/// Return tool definitions with pre-computed input schemas.
/// Use this for building MCP `tools/list` responses.
pub fn tool_definitions() -> Vec<SimpleToolDef> {{
    generated_tool_registry()
        .into_iter()
        .map(|t| SimpleToolDef {{
            name: t.name,
            description: t.description,
            input_schema: (t.schema_fn)(),
        }})
        .collect()
}}

/// Dispatch a tool call by name, executing the matching handler synchronously.
///
/// This creates a minimal tokio runtime to drive the async handler.
/// Suitable for MCP servers that process requests synchronously.
pub fn handle_tool_call(
    state: &{state_type},
    tool_name: &str,
    args: &serde_json::Map<String, Value>,
) -> Result<Value, String> {{
    let registry = generated_tool_registry();
    let tool = registry
        .iter()
        .find(|t| t.name == tool_name)
        .ok_or_else(|| format!(\"Unknown tool: {{tool_name}}\"))?;
    let args_value = Value::Object(args.clone());
    let rt = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .map_err(|e| format!(\"Runtime error: {{e}}\"))?;
    rt.block_on((tool.handler)(state, &args_value))
}}
"
    ));

    if let Some(parent) = output.parent() {
        fs::create_dir_all(parent).expect("Failed to create output directory");
    }
    crate::write_and_format(output, out).expect("Failed to write MCP generated file");
}

fn generate_generic_mcp_tool(out: &mut String, m: &ApiModule, f: &ApiFn, config: &Config, is_list_op: bool) {
    let module = m.name.as_str();
    let svc = m.service_ident(f.surface);
    let fn_name = &f.name;
    let desc = if f.doc.is_empty() { fn_name.clone() } else { f.doc.clone() };
    let await_str = if f.is_async { ".await" } else { "" };
    let tool_name = crate::servers::generators::ipc::command_name(module, f, config);
    // Pagination only applies to list operations that return Vec<T>;
    // custom result types are passed through unchanged.
    let pagination: Option<&PaginationConfig> =
        config.pagination_for(module, f.surface).filter(|_| is_list_op && f.return_type.starts_with("Vec<"));
    // Stateless tools skip the state/store handler prefix and forward no
    // positional state argument to the service function. The MCP runtime
    // still hands `ontogen_state` and `ontogen_args` to every tool handler
    // closure — the body just doesn't reference the state.
    let (hp, first_arg) = if f.is_stateless {
        (String::new(), None)
    } else if f.first_param_is_store {
        (mcp_store_construction(config, f), Some("&ontogen_store"))
    } else {
        (mcp_handler_prefix(config), Some("ontogen_state"))
    };

    let body = sole_body_param(f);
    let schema_input = match (body, f.params.is_empty()) {
        (Some(body), _) => extract_input_type(&body.ty),
        (None, true) => "EmptyInput".to_string(),
        (None, false) => generic_input_schema_name(m, f),
    };
    let schema_base = format!("schema_for::<{schema_input}>");
    let schema = ToolSchema { base: &schema_base, config, paginate: pagination.is_some(), sort: None };

    let mut extraction = String::new();
    let mut call_args: Vec<String> = first_arg.map(str::to_string).into_iter().collect();
    if let Some(body) = body {
        // A body alone is the arguments themselves, less the scope's.
        let skipped: Vec<String> = if f.is_stateless { Vec::new() } else { scope_key(config).into_iter().collect() };
        extraction.push_str(&format!(
            "                    let ontogen_input: {} = serde_json::from_value({})\n                        .map_err(|e| format!(\"Invalid input: {{e}}\"))?;\n",
            extract_input_type(&body.ty),
            struct_args(&skipped)
        ));
        call_args.push(forward_arg_expr("ontogen_input", &body.ty_ast));
    } else {
        for p in &f.params {
            extraction.push_str(&arg_extraction(p));
            // `required_str` already lends a `&str`.
            call_args.push(if p.ty == "&str" { p.name.clone() } else { forward_arg_expr(&p.name, &p.ty_ast) });
        }
    }
    let call = format!("{svc}::{fn_name}({}){await_str}.map_err(|e| e.to_string())?", call_args.join(", "));

    let result = if f.return_type == "()" {
        format!("                    {call};\n                    Ok(json!({{\"success\": true}}))\n")
    } else if let Some(pg) = pagination {
        format!(
            "                    let ontogen_all = {call};\n{}{PAGE_RESULT}",
            in_memory_page(pg.default_limit, pg.max_limit)
        )
    } else {
        format!(
            "                    let ontogen_result = {call};\n                    serde_json::to_value(ontogen_result).map_err(|e| format!(\"Serialize error: {{e}}\"))\n"
        )
    };
    push_tool(out, &tool_name, &desc, &schema, &format!("{extraction}{hp}{result}"));
}

/// Emitted once when any list tool takes an order: its schema's `sort`
/// property and the strict read of that argument.
const SORT_HELPERS: &str = "\
/// Inject the optional `sort` property, an array of `keys`, into a JSON schema.
fn with_sort_schema(mut schema: Value, keys: &[&str]) -> Value {
    if let Some(obj) = schema.as_object_mut() {
        let props = obj.entry(\"properties\").or_insert_with(|| json!({}));
        if let Some(props_obj) = props.as_object_mut() {
            props_obj.insert(\"sort\".to_string(), json!({
                \"type\": \"array\",
                \"items\": { \"type\": \"string\", \"enum\": keys },
                \"description\": \"Sort keys, applied in order: a field name sorts ascending, and `-` before it descending. The id is the final tie-break.\"
            }));
        }
    }
    schema
}

/// The keys of the `sort` argument: none when it is absent or `null`, and
/// the tool's error for anything but an array of strings.
fn sort_arg(args: &Value) -> Result<Vec<&str>, String> {
    match args.get(\"sort\") {
        None | Some(Value::Null) => Ok(Vec::new()),
        Some(Value::Array(keys)) => keys
            .iter()
            .map(|key| key.as_str().ok_or_else(|| format!(\"Invalid sort: expected a string, got {key}\")))
            .collect(),
        Some(other) => Err(format!(\"Invalid sort: expected an array of strings, got {other}\")),
    }
}

";

/// A sorted list tool's read of its `sort` argument into the order its list
/// takes, with the parser HTTP and IPC use: a bad key is the parser's error
/// text.
const ORDER_FROM_SORT: &str = "                    let ontogen_order = ontogen_core::order::parse_sort(sort_arg(ontogen_args)?).map_err(|e| e.to_string())?;
";

/// The closing of a paginated list tool: the page and its total.
const PAGE_RESULT: &str = "                    Ok(json!({
                        \"items\": serde_json::to_value(&ontogen_items).map_err(|e| format!(\"Serialize error: {e}\"))?,
                        \"total\": ontogen_total,
                        \"limit\": ontogen_limit,
                        \"offset\": ontogen_offset
                    }))
";

/// The lines slicing the page out of a whole list, `ontogen_all`.
fn in_memory_page(default_limit: u32, max_limit: u32) -> String {
    format!(
        "\
                    let ontogen_total = ontogen_all.len();
                    let ontogen_limit = ontogen_args.get(\"limit\").and_then(|v| v.as_u64()).map(|v| v as usize).unwrap_or({default_limit}_usize).min({max_limit}_usize);
                    let ontogen_offset = ontogen_args.get(\"offset\").and_then(|v| v.as_u64()).map(|v| v as usize).unwrap_or(0);
                    let ontogen_items: Vec<_> = ontogen_all.into_iter().skip(ontogen_offset).take(ontogen_limit).collect();
"
    )
}

/// A tool's input schema: `base` (a `schema_for::<T>` path), with the
/// scope's argument when a route prefix is configured, the page's when
/// `paginate`, and `sort` when `sort` lists the keys it takes.
struct ToolSchema<'a> {
    base: &'a str,
    config: &'a Config,
    paginate: bool,
    sort: Option<&'a [String]>,
}

/// One entry of the tool registry. The handler's own bindings are
/// `ontogen_`-prefixed so an argument bound under its fn param's name
/// (`state`, `store`, `limit`, ...) cannot shadow them.
///
/// The input schema names every argument the tool reads, so the handler
/// first refuses an argument it does not name, which would otherwise be
/// silently ignored, as HTTP refuses an unknown member.
fn push_tool(out: &mut String, tool_name: &str, desc: &str, schema: &ToolSchema, body: &str) {
    let schema_fn = tool_schema_fn(schema);
    let schema_value = tool_schema_value(schema);
    out.push_str(&format!(
        "\
        McpToolDef {{
            name: \"{tool_name}\",
            description: \"{desc}\",
            schema_fn: {schema_fn},
            handler: |ontogen_state, ontogen_args| {{
                Box::pin(async move {{
                    refuse_unknown_args(ontogen_args, {schema_value})?;
{body}                }})
            }},
        }},
"
    ));
}

/// The tool's input schema as an expression: `base` (a `schema_for::<T>`
/// path) called, with the scope's argument when a route prefix is
/// configured, the page's when the tool reads one, and `sort` when it reads
/// that.
fn tool_schema_value(schema: &ToolSchema<'_>) -> String {
    let mut value = format!("{}()", schema.base);
    if schema.config.route_prefix.is_some() {
        value = format!("with_project_id_schema({value})");
    }
    if schema.paginate {
        value = format!("with_pagination_schema({value})");
    }
    if let Some(keys) = schema.sort {
        let keys: Vec<String> = keys.iter().map(|k| format!("\"{k}\"")).collect();
        value = format!("with_sort_schema({value}, &[{}])", keys.join(", "));
    }
    value
}

/// The registry's `schema_fn` for [`tool_schema_value`]: `base` itself when
/// nothing is added to it, else a closure.
fn tool_schema_fn(schema: &ToolSchema<'_>) -> String {
    if schema.config.route_prefix.is_none() && !schema.paginate && schema.sort.is_none() {
        schema.base.to_string()
    } else {
        format!("|| {}", tool_schema_value(schema))
    }
}

/// The sort keys a list tool's `sort` argument takes, from the entity its
/// module serves, in the order the store's `{Entity}SortField` declares
/// them (ADR 0006 §2). `None` for a list that takes no order.
fn list_sort_keys(m: &ApiModule, f: &ApiFn, config: &Config) -> Option<Vec<String>> {
    if !f.takes_order() {
        return None;
    }
    let resource = config.resources.by_module(&m.name)?;
    Some(sort_keys(&sort_fields(&resource.entity, &config.enums)))
}

/// Refuses a sorted list whose bare filter is named `sort`: the list tool
/// reads its sort keys from the argument `sort`, so the two would share one
/// key.
pub(crate) fn check_sort_key(modules: &[ApiModule], config: &Config) -> Result<(), String> {
    for m in modules {
        for f in m.functions.iter().filter(|f| classify_op(m, f) == OpKind::List && f.takes_order()) {
            if f.bare_filters().iter().any(|p| p.name == "sort") {
                let tool = crate::servers::generators::ipc::command_name(&m.name, f, config);
                return Err(format!(
                    "ontogen: the MCP tool `{tool}` cannot be generated: `{}::{}` takes a filter named `sort`, \
                     which is the argument the tool itself reads its sort keys from, so the two would share one \
                     key. Rename the argument.",
                    m.name, f.name
                ));
            }
        }
    }
    Ok(())
}

/// Refuses, under a route prefix, a fn whose MCP tool would read an
/// argument under the prefix parameter's name (`project_id`). Every scoped
/// tool reads that argument itself to pick the store, so the op's own
/// argument and the scope would share one key. The keys checked are the
/// ones a tool reads by name: `id` for get, update and delete, each bare
/// filter of a list and `sort` when it takes an order, and each parameter
/// of a custom op or junction tool
/// (other than an `*Input` taken as the whole argument object). The fields
/// of an `*Input` or `*Query` struct read flat are not known here.
pub(crate) fn check_scope_key(modules: &[ApiModule], config: &Config) -> Result<(), String> {
    let Some(scope) = scope_key(config) else {
        return Ok(());
    };
    for m in modules {
        for f in &m.functions {
            let keys: Vec<&str> = match classify_op(m, f) {
                OpKind::GetById | OpKind::Update | OpKind::Delete => vec!["id"],
                OpKind::Create | OpKind::EventStream => vec![],
                OpKind::List => f
                    .bare_filters()
                    .into_iter()
                    .map(|p| p.name.as_str())
                    .chain(f.takes_order().then_some("sort"))
                    .collect(),
                _ if sole_body_param(f).is_some() => vec![],
                _ => f.params.iter().map(|p| p.name.as_str()).collect(),
            };
            if keys.contains(&scope.as_str()) {
                let tool = crate::servers::generators::ipc::command_name(&m.name, f, config);
                return Err(format!(
                    "ontogen: the MCP tool `{tool}` cannot be generated: `{}::{}` takes an argument named `{scope}`, \
                     which is the argument the tool itself reads for the route prefix parameter, so the two would \
                     share one key. Rename the argument.",
                    m.name, f.name
                ));
            }
        }
    }
    Ok(())
}

/// The argument naming the scope, which the handler prefix reads itself.
fn scope_key(config: &Config) -> Option<String> {
    config.route_prefix.as_ref().map(|prefix| prefix.params[0].name.clone())
}

/// The keys a list tool reads itself, beside its `*Query` struct: each
/// bare filter, `sort` when it takes an order, the page when it reads one,
/// and the scope. The struct is read from the other arguments, so one that
/// refuses unknown fields accepts a call that sends them, and a struct
/// field serialized as `sort` is never read from a sorted list's arguments.
fn list_struct_skipped_keys(f: &ApiFn, config: &Config, paginate: bool) -> Vec<String> {
    let mut keys: Vec<String> = f.bare_filters().iter().map(|p| p.name.clone()).collect();
    if f.takes_order() {
        keys.push("sort".to_string());
    }
    if paginate {
        keys.extend(["limit".to_string(), "offset".to_string()]);
    }
    keys.extend(scope_key(config));
    keys
}

/// The value a struct is deserialized from: the tool's arguments without
/// `skipped`.
fn struct_args(skipped: &[String]) -> String {
    if skipped.is_empty() {
        return "ontogen_args.clone()".to_string();
    }
    let keys: Vec<String> = skipped.iter().map(|k| format!("\"{k}\"")).collect();
    format!("args_without(ontogen_args, &[{}])", keys.join(", "))
}

/// The struct whose schema is a filtered list's tool input:
/// `Ontogen{Module}{Fn}Filter`, a name no imported user type takes.
fn list_filter_schema_name(m: &ApiModule, f: &ApiFn) -> String {
    format!("Ontogen{}{}Filter", to_pascal_case(&m.name), to_pascal_case(&f.name))
}

/// The schema-only struct of a list's filter: each bare filter as its owned
/// type, so an `Option` one is optional and any other required, with the
/// `*Query` struct's fields flattened beside them. The handler reads each
/// argument on its own; this struct only describes them.
fn list_filter_schema_struct(m: &ApiModule, f: &ApiFn) -> String {
    let mut out = format!(
        "/// The arguments the `{}` list tool reads as its filter.\n#[derive(JsonSchema)]\npub struct {} {{\n",
        m.name,
        list_filter_schema_name(m, f)
    );
    for p in f.bare_filters() {
        out.push_str(&format!("    pub {}: {},\n", p.name, param_to_owned_type(&p.ty_ast)));
    }
    if let Some(qp) = f.filter_struct() {
        out.push_str(&format!("    #[serde(flatten)]\n    pub ontogen_query: {},\n", extract_input_type(&qp.ty)));
    }
    out.push_str("}\n\n");
    out
}

/// A custom op's one parameter when it is an `*Input` struct: the tool's
/// arguments are that struct's fields. Beside other parameters it is one
/// argument among them, named as its parameter, as on IPC, so its fields
/// cannot collide with theirs.
fn sole_body_param(f: &ApiFn) -> Option<&Param> {
    match f.params.as_slice() {
        [p] if p.ty.contains("Input") => Some(p),
        _ => None,
    }
}

/// The struct whose schema is a custom op's tool input:
/// `Ontogen{Module}{Fn}Input`, a name no imported user type takes.
fn generic_input_schema_name(m: &ApiModule, f: &ApiFn) -> String {
    format!("Ontogen{}{}Input", to_pascal_case(&m.name), to_pascal_case(&f.name))
}

/// The schema-only struct of a custom op's arguments, each parameter as
/// its owned type. `None` for an op that takes no parameter or only an
/// `*Input` body, whose schema is the body's own.
fn generic_input_schema_struct(m: &ApiModule, f: &ApiFn) -> Option<String> {
    if f.params.is_empty() || sole_body_param(f).is_some() {
        return None;
    }
    let mut out = format!(
        "/// The arguments of the `{}` tool.\n#[derive(JsonSchema)]\npub struct {} {{\n",
        f.name,
        generic_input_schema_name(m, f)
    );
    for p in &f.params {
        out.push_str(&format!("    pub {}: {},\n", p.name, param_to_owned_type(&p.ty_ast)));
    }
    out.push_str("}\n\n");
    Some(out)
}

/// The lines reading the argument `p` from a tool's `ontogen_args`, bound
/// under its name: a `&str` borrowed with `required_str`, any other type
/// deserialized as its owned type, optional when it is an `Option`. A
/// missing required argument or a value of the wrong type is the tool's
/// error.
fn arg_extraction(p: &Param) -> String {
    let name = &p.name;
    if p.ty == "&str" {
        return format!("                    let {name} = required_str(ontogen_args, \"{name}\")?;\n");
    }
    let owned = param_to_owned_type(&p.ty_ast);
    let invalid = format!(".map_err(|e| format!(\"Invalid parameter {name}: {{e}}\"))?");
    match owned.strip_prefix("Option<").and_then(|t| t.strip_suffix('>')) {
        Some(inner) => format!(
            "                    let {name}: {owned} = ontogen_args.get(\"{name}\").filter(|v| !v.is_null()).cloned().map(serde_json::from_value::<{inner}>).transpose(){invalid};\n"
        ),
        None => format!(
            "                    let {name}: {owned} = serde_json::from_value(ontogen_args.get(\"{name}\").cloned().ok_or(\"Missing required parameter: {name}\")?){invalid};\n"
        ),
    }
}
