// TODO: review — banner strings updated from old crate names
#![allow(clippy::too_many_lines, clippy::format_push_string)]

//! Generate a unified TypeScript transport layer from API modules.
//!
//! Produces a single file containing:
//! - `Transport` interface
//! - `createHttpTransport()` — fetch-based HTTP implementation
//! - `createIpcTransport()` — Tauri IPC invoke-based implementation

use std::fs;
use std::path::Path;

use crate::servers::classify::{OpKind, classify_op, is_read_operation};
use crate::servers::config::Config;
use crate::servers::generators::ipc::ts_command_name;
use crate::servers::parse::{ApiModule, Param};
use crate::servers::types::{collect_ts_import, extract_input_type, rust_type_to_ts, snake_to_camel};

/// Returns `", projectId?: string"` when route_prefix is configured, else `""`.
fn ts_trailing_prefix_param(config: &Config) -> String {
    match &config.route_prefix {
        Some(prefix) => {
            let pp = &prefix.params[0];
            format!(", {}?: {}", snake_to_camel(&pp.name), pp.ts_type)
        }
        None => String::new(),
    }
}

/// Returns `"projectId?: string"` when route_prefix is configured, else `""`.
fn ts_prefix_param_only(config: &Config) -> String {
    match &config.route_prefix {
        Some(prefix) => {
            let pp = &prefix.params[0];
            format!("{}?: {}", snake_to_camel(&pp.name), pp.ts_type)
        }
        None => String::new(),
    }
}

/// Returns the IPC invoke arg fragment for project_id, e.g., `, projectId: projectId ?? null`.
///
/// Uses camelCase key because Tauri v2's `#[tauri::command]` deserializes args
/// with `#[serde(rename_all = "camelCase")]`.
fn ts_ipc_prefix_arg(config: &Config) -> String {
    match &config.route_prefix {
        Some(prefix) => {
            let pp = &prefix.params[0];
            let camel = snake_to_camel(&pp.name);
            format!(", {camel}: {camel} ?? null")
        }
        None => String::new(),
    }
}

/// Returns the IPC invoke arg fragment without leading comma, e.g., `projectId: projectId ?? null`.
///
/// Uses camelCase key because Tauri v2's `#[tauri::command]` deserializes args
/// with `#[serde(rename_all = "camelCase")]`.
fn ts_ipc_prefix_arg_only(config: &Config) -> String {
    match &config.route_prefix {
        Some(prefix) => {
            let pp = &prefix.params[0];
            let camel = snake_to_camel(&pp.name);
            format!("{camel}: {camel} ?? null")
        }
        None => String::new(),
    }
}

/// Generate the unified transport layer and write to the output file.
pub fn generate(output: &Path, bindings_path: &Path, modules: &[ApiModule], config: &Config) {
    let mut out = String::new();

    // Read bindings.ts to discover exported types
    let bindings_content = fs::read_to_string(bindings_path).unwrap_or_default();
    let exported_types: Vec<String> = bindings_content
        .lines()
        .filter_map(|line| {
            line.strip_prefix("export type ")
                .and_then(|rest| rest.split(|c: char| !c.is_alphanumeric() && c != '_').next().map(|s| s.to_string()))
        })
        .collect();

    out.push_str(
        "// Auto-generated transport layer. DO NOT EDIT.\n\
         // Generated by ontogen from API source files.\n\n",
    );

    // Collect all types needed
    let mut import_types: Vec<String> = Vec::new();
    for m in modules {
        if m.functions.is_empty() {
            continue;
        }
        for f in &m.functions {
            let cmd_name = ts_command_name(&m.name, f, config);
            if cmd_name.is_empty() || config.ts_skip_commands.contains(&cmd_name) {
                continue;
            }
            let ts_ret = rust_type_to_ts(&f.return_type);
            collect_ts_import(&ts_ret, &mut import_types);
            for p in &f.params {
                let ty = extract_input_type(&p.ty);
                let ts_ty = rust_type_to_ts(&ty);
                collect_ts_import(&ts_ty, &mut import_types);
            }
        }
    }

    import_types.sort();
    import_types.dedup();

    let (available, missing): (Vec<_>, Vec<_>) = import_types.iter().partition(|t| exported_types.contains(t));

    if !available.is_empty() {
        out.push_str("import type {\n");
        for t in &available {
            out.push_str(&format!("  {},\n", t));
        }
        out.push_str("} from '../types/bindings';\n\n");
    }

    // IPC imports — must be at top level for lint compliance
    out.push_str("import { invoke } from '@tauri-apps/api/core';\n");
    out.push_str("import { listen } from '@tauri-apps/api/event';\n\n");

    for t in &missing {
        out.push_str(&format!(
            "// TODO: Type '{t}' not yet exported from bindings.ts — using placeholder\n\
             type {t} = Record<string, unknown>;\n\n"
        ));
    }

    // ── Transport Interface ──
    generate_transport_interface(&mut out, modules, config);

    // ── HTTP Helpers ──
    generate_http_helpers(&mut out, config);

    // ── createHttpTransport ──
    generate_http_transport(&mut out, modules, config);

    // ── createIpcTransport ──
    generate_ipc_transport(&mut out, modules, config);

    if let Some(parent) = output.parent() {
        fs::create_dir_all(parent).expect("Failed to create output directory");
    }
    fs::write(output, out).expect("Failed to write transport generated file");
}

/// Generate the `Transport` interface.
fn generate_transport_interface(out: &mut String, modules: &[ApiModule], config: &Config) {
    let pp_trailing = ts_trailing_prefix_param(config);
    let pp_only = ts_prefix_param_only(config);

    out.push_str("// ── Transport Interface ──\n\n");
    out.push_str("export interface Transport {\n");

    for m in modules {
        if m.functions.is_empty() {
            continue;
        }

        for f in &m.functions {
            let cmd_name = ts_command_name(&m.name, f, config);
            if cmd_name.is_empty() || config.ts_skip_commands.contains(&cmd_name) {
                continue;
            }

            let op = classify_op(f);
            let camel = snake_to_camel(&cmd_name);
            let ts_ret = rust_type_to_ts(&f.return_type);
            let returns_unit = f.return_type == "()";
            let ret_str = if returns_unit { "null" } else { &ts_ret };

            match op {
                OpKind::List => {
                    out.push_str(&format!("  {}({pp_only}): Promise<{}>;\n", camel, ret_str));
                }
                OpKind::GetById => {
                    out.push_str(&format!("  {}(id: string{pp_trailing}): Promise<{}>;\n", camel, ret_str));
                }
                OpKind::Create => {
                    let input_type = rust_type_to_ts(&extract_input_type(&f.params[0].ty));
                    out.push_str(&format!("  {}(input: {}{pp_trailing}): Promise<{}>;\n", camel, input_type, ret_str));
                }
                OpKind::UpdateById => {
                    let input_type = rust_type_to_ts(&extract_input_type(&f.params[1].ty));
                    out.push_str(&format!(
                        "  {}(id: string, input: {}{pp_trailing}): Promise<{}>;\n",
                        camel, input_type, ret_str
                    ));
                }
                OpKind::DeleteById => {
                    out.push_str(&format!("  {}(id: string{pp_trailing}): Promise<null>;\n", camel));
                }
                OpKind::CustomGet | OpKind::CustomPost => {
                    let mut params = build_ts_params(f, config);
                    if !pp_only.is_empty() {
                        params.push(pp_only.clone());
                    }
                    let params_str = params.join(", ");
                    out.push_str(&format!("  {}({}): Promise<{}>;\n", camel, params_str, ret_str));
                }
            }
        }
    }

    // Events
    for m in modules {
        for ev in &m.events {
            let camel = snake_to_camel(&ev.name);
            out.push_str(&format!(
                "  on{}(callback: (payload: unknown) => void{pp_trailing}): Promise<() => void>;\n",
                capitalize_first(&camel)
            ));
        }
    }

    out.push_str("}\n\n");
}

/// Generate HTTP helper functions.
fn generate_http_helpers(out: &mut String, config: &Config) {
    out.push_str(
        "// ── HTTP Helpers ──\n\n\
         const BASE = '/api';\n\n\
         async function httpGet<T>(path: string): Promise<T> {\n\
         \x20 const res = await fetch(`${BASE}${path}`);\n\
         \x20 if (!res.ok) {\n\
         \x20   const body = await res.json().catch(() => ({ error: res.statusText }));\n\
         \x20   throw new Error(body.error ?? res.statusText);\n\
         \x20 }\n\
         \x20 return res.json();\n\
         }\n\n\
         async function httpPost<T>(path: string, body?: unknown): Promise<T> {\n\
         \x20 const res = await fetch(`${BASE}${path}`, {\n\
         \x20   method: 'POST',\n\
         \x20   headers: { 'Content-Type': 'application/json' },\n\
         \x20   body: body != null ? JSON.stringify(body) : undefined,\n\
         \x20 });\n\
         \x20 if (!res.ok) {\n\
         \x20   const errBody = await res.json().catch(() => ({ error: res.statusText }));\n\
         \x20   throw new Error(errBody.error ?? res.statusText);\n\
         \x20 }\n\
         \x20 if (res.status === 204) return null as T;\n\
         \x20 return res.json();\n\
         }\n\n\
         async function httpPut<T>(path: string, body: unknown): Promise<T> {\n\
         \x20 const res = await fetch(`${BASE}${path}`, {\n\
         \x20   method: 'PUT',\n\
         \x20   headers: { 'Content-Type': 'application/json' },\n\
         \x20   body: JSON.stringify(body),\n\
         \x20 });\n\
         \x20 if (!res.ok) {\n\
         \x20   const errBody = await res.json().catch(() => ({ error: res.statusText }));\n\
         \x20   throw new Error(errBody.error ?? res.statusText);\n\
         \x20 }\n\
         \x20 return res.json();\n\
         }\n\n\
         async function httpDelete(path: string): Promise<void> {\n\
         \x20 const res = await fetch(`${BASE}${path}`, { method: 'DELETE' });\n\
         \x20 if (!res.ok) {\n\
         \x20   const errBody = await res.json().catch(() => ({ error: res.statusText }));\n\
         \x20   throw new Error(errBody.error ?? res.statusText);\n\
         \x20 }\n\
         }\n\n",
    );

    // Add scopedPath helper when route_prefix is configured
    if let Some(prefix) = &config.route_prefix {
        // Build URL template from segments, e.g., "projects/:project_id" → "/projects/${encodeURIComponent(projectId)}"
        let mut url_parts = String::new();
        for segment in prefix.segments.split('/') {
            url_parts.push('/');
            if let Some(param_name) = segment.strip_prefix(':') {
                url_parts.push_str(&format!("${{encodeURIComponent({})}}", snake_to_camel(param_name)));
            } else {
                url_parts.push_str(segment);
            }
        }
        let pp_camel = snake_to_camel(&prefix.params[0].name);
        out.push_str(&format!(
            "function scopedPath({pp_camel}: string | undefined, path: string): string {{\n\
             \x20 if ({pp_camel}) {{\n\
             \x20   return `{url_parts}${{path}}`;\n\
             \x20 }}\n\
             \x20 return path;\n\
             }}\n\n",
        ));
    }
}

/// Generate `createHttpTransport()`.
fn generate_http_transport(out: &mut String, modules: &[ApiModule], config: &Config) {
    let pp_trailing = ts_trailing_prefix_param(config);
    let pp_only = ts_prefix_param_only(config);
    let has_prefix = config.route_prefix.is_some();
    let pp_camel = config.route_prefix.as_ref().map(|p| snake_to_camel(&p.params[0].name)).unwrap_or_default();

    // Helper to wrap path with scopedPath when prefix is configured
    let sp = |path: &str| -> String {
        if has_prefix { format!("scopedPath({}, '{}')", pp_camel, path) } else { format!("'{}'", path) }
    };
    let sp_template = |path: &str| -> String {
        if has_prefix { format!("scopedPath({}, `{}`)", pp_camel, path) } else { format!("`{}`", path) }
    };

    out.push_str("// ── HTTP Transport ──\n\n");
    out.push_str("export function createHttpTransport(): Transport {\n");
    out.push_str("  return {\n");

    for m in modules {
        if m.functions.is_empty() {
            continue;
        }
        let module = &m.name;
        let plural = config.naming.module_plural(module);

        for f in &m.functions {
            let op = classify_op(f);
            let cmd_name = ts_command_name(module, f, config);
            if cmd_name.is_empty() || config.ts_skip_commands.contains(&cmd_name) {
                continue;
            }

            let camel = snake_to_camel(&cmd_name);
            let ts_ret = rust_type_to_ts(&f.return_type);
            let returns_unit = f.return_type == "()";
            let ret_str = if returns_unit { "null".to_string() } else { ts_ret.clone() };

            match op {
                OpKind::List => {
                    let path_expr = sp(&format!("/{plural}"));
                    out.push_str(&format!(
                        "    async {}({pp_only}): Promise<{}> {{\n\
                         \x20     return httpGet({path_expr});\n\
                         \x20   }},\n",
                        camel, ret_str,
                    ));
                }
                OpKind::GetById => {
                    let path_expr = sp_template(&format!("/{plural}/${{encodeURIComponent(id)}}"));
                    out.push_str(&format!(
                        "    async {}(id: string{pp_trailing}): Promise<{}> {{\n\
                         \x20     return httpGet({path_expr});\n\
                         \x20   }},\n",
                        camel, ret_str,
                    ));
                }
                OpKind::Create => {
                    let input_type = rust_type_to_ts(&extract_input_type(&f.params[0].ty));
                    let path_expr = sp(&format!("/{plural}"));
                    out.push_str(&format!(
                        "    async {}(input: {}{pp_trailing}): Promise<{}> {{\n\
                         \x20     return httpPost<{}>({path_expr}, input);\n\
                         \x20   }},\n",
                        camel, input_type, ret_str, ret_str,
                    ));
                }
                OpKind::UpdateById => {
                    let input_type = rust_type_to_ts(&extract_input_type(&f.params[1].ty));
                    let path_expr = sp_template(&format!("/{plural}/${{encodeURIComponent(id)}}"));
                    out.push_str(&format!(
                        "    async {}(id: string, input: {}{pp_trailing}): Promise<{}> {{\n\
                         \x20     return httpPut<{}>({path_expr}, input);\n\
                         \x20   }},\n",
                        camel, input_type, ret_str, ret_str,
                    ));
                }
                OpKind::DeleteById => {
                    let path_expr = sp_template(&format!("/{plural}/${{encodeURIComponent(id)}}"));
                    out.push_str(&format!(
                        "    async {}(id: string{pp_trailing}): Promise<null> {{\n\
                         \x20     await httpDelete({path_expr});\n\
                         \x20     return null;\n\
                         \x20   }},\n",
                        camel,
                    ));
                }
                OpKind::CustomGet | OpKind::CustomPost => {
                    generate_http_custom_method(out, module, f, config);
                }
            }
        }
    }

    // SSE event handlers
    for m in modules {
        for ev in &m.events {
            let camel = snake_to_camel(&ev.name);
            let ev_name = ev.name.replace('_', "-");
            let route_path = if let Some(override_path) = config.sse_route_overrides.get(&ev.name) {
                override_path.clone()
            } else {
                format!("/api/events/{}", ev_name)
            };

            if config.route_prefix.is_some() {
                // When route_prefix is configured, accept optional projectId and
                // use scoped path when provided.
                // Use addEventListener with the named event type — onmessage only
                // catches unnamed SSE events, but the backend sends named events
                // via `.event("{ev_name}")`.
                out.push_str(&format!(
                    "    async on{cap}(callback: (payload: unknown) => void{pp_trailing}): Promise<() => void> {{\n\
                     \x20     let es: EventSource | null = null;\n\
                     \x20     let reconnectTimer: ReturnType<typeof setTimeout> | null = null;\n\
                     \x20     const url = `${{BASE}}${{scopedPath(projectId, '{sse_path}')}}`;\n\
                     \x20     function connect() {{\n\
                     \x20       es = new EventSource(url);\n\
                     \x20       es.addEventListener('{ev_name}', (event: MessageEvent) => {{\n\
                     \x20         try {{ callback(JSON.parse(event.data)); }}\n\
                     \x20         catch {{ callback({{}}); }}\n\
                     \x20       }});\n\
                     \x20       es.onerror = () => {{\n\
                     \x20         es?.close();\n\
                     \x20         es = null;\n\
                     \x20         reconnectTimer = setTimeout(connect, 3000);\n\
                     \x20       }};\n\
                     \x20     }}\n\
                     \x20     connect();\n\
                     \x20     return () => {{\n\
                     \x20       if (reconnectTimer) clearTimeout(reconnectTimer);\n\
                     \x20       es?.close();\n\
                     \x20       es = null;\n\
                     \x20     }};\n\
                     \x20   }},\n",
                    cap = capitalize_first(&camel),
                    sse_path = route_path.strip_prefix("/api").unwrap_or(&route_path),
                ));
            } else {
                out.push_str(&format!(
                    "    async on{cap}(callback: (payload: unknown) => void): Promise<() => void> {{\n\
                     \x20     let es: EventSource | null = null;\n\
                     \x20     let reconnectTimer: ReturnType<typeof setTimeout> | null = null;\n\
                     \x20     function connect() {{\n\
                     \x20       es = new EventSource('{route_path}');\n\
                     \x20       es.addEventListener('{ev_name}', (event: MessageEvent) => {{\n\
                     \x20         try {{ callback(JSON.parse(event.data)); }}\n\
                     \x20         catch {{ callback({{}}); }}\n\
                     \x20       }});\n\
                     \x20       es.onerror = () => {{\n\
                     \x20         es?.close();\n\
                     \x20         es = null;\n\
                     \x20         reconnectTimer = setTimeout(connect, 3000);\n\
                     \x20       }};\n\
                     \x20     }}\n\
                     \x20     connect();\n\
                     \x20     return () => {{\n\
                     \x20       if (reconnectTimer) clearTimeout(reconnectTimer);\n\
                     \x20       es?.close();\n\
                     \x20       es = null;\n\
                     \x20     }};\n\
                     \x20   }},\n",
                    cap = capitalize_first(&camel),
                ));
            }
        }
    }

    out.push_str("  };\n");
    out.push_str("}\n\n");
}

/// Generate `createIpcTransport()`.
fn generate_ipc_transport(out: &mut String, modules: &[ApiModule], config: &Config) {
    let pp_trailing = ts_trailing_prefix_param(config);
    let pp_only = ts_prefix_param_only(config);
    let ipc_arg = ts_ipc_prefix_arg(config);
    let ipc_arg_only = ts_ipc_prefix_arg_only(config);

    out.push_str(
        "// ── IPC Transport ──\n\n\
         export function createIpcTransport(): Transport {\n\
         \x20 return {\n",
    );

    for m in modules {
        if m.functions.is_empty() {
            continue;
        }
        let module = &m.name;

        for f in &m.functions {
            let op = classify_op(f);
            let cmd_name = ts_command_name(module, f, config);
            if cmd_name.is_empty() || config.ts_skip_commands.contains(&cmd_name) {
                continue;
            }

            let camel = snake_to_camel(&cmd_name);
            let ts_ret = rust_type_to_ts(&f.return_type);
            let returns_unit = f.return_type == "()";
            let ret_str = if returns_unit { "null".to_string() } else { ts_ret.clone() };
            // The Rust IPC command name (snake_case)
            let invoke_name = &cmd_name;

            match op {
                OpKind::List => {
                    if ipc_arg_only.is_empty() {
                        out.push_str(&format!(
                            "    async {}(): Promise<{}> {{\n\
                             \x20     return invoke('{invoke_name}');\n\
                             \x20   }},\n",
                            camel, ret_str,
                        ));
                    } else {
                        out.push_str(&format!(
                            "    async {}({pp_only}): Promise<{}> {{\n\
                             \x20     return invoke('{invoke_name}', {{ {ipc_arg_only} }});\n\
                             \x20   }},\n",
                            camel, ret_str,
                        ));
                    }
                }
                OpKind::GetById => {
                    out.push_str(&format!(
                        "    async {}(id: string{pp_trailing}): Promise<{}> {{\n\
                         \x20     return invoke('{invoke_name}', {{ id{ipc_arg} }});\n\
                         \x20   }},\n",
                        camel, ret_str,
                    ));
                }
                OpKind::Create => {
                    let input_type = rust_type_to_ts(&extract_input_type(&f.params[0].ty));
                    out.push_str(&format!(
                        "    async {}(input: {}{pp_trailing}): Promise<{}> {{\n\
                         \x20     return invoke('{invoke_name}', {{ input{ipc_arg} }});\n\
                         \x20   }},\n",
                        camel, input_type, ret_str,
                    ));
                }
                OpKind::UpdateById => {
                    let input_type = rust_type_to_ts(&extract_input_type(&f.params[1].ty));
                    out.push_str(&format!(
                        "    async {}(id: string, input: {}{pp_trailing}): Promise<{}> {{\n\
                         \x20     return invoke('{invoke_name}', {{ id, input{ipc_arg} }});\n\
                         \x20   }},\n",
                        camel, input_type, ret_str,
                    ));
                }
                OpKind::DeleteById => {
                    out.push_str(&format!(
                        "    async {}(id: string{pp_trailing}): Promise<null> {{\n\
                         \x20     await invoke('{invoke_name}', {{ id{ipc_arg} }});\n\
                         \x20     return null;\n\
                         \x20   }},\n",
                        camel,
                    ));
                }
                OpKind::CustomGet | OpKind::CustomPost => {
                    generate_ipc_custom_method(out, f, &cmd_name, config);
                }
            }
        }
    }

    // Event handlers via Tauri listen
    for m in modules {
        for ev in &m.events {
            let camel = snake_to_camel(&ev.name);
            let ev_name = ev.name.replace('_', "-");

            // Accept _projectId to match Transport interface, even though
            // Tauri listen is not project-scoped (IPC events are global).
            let ipc_pp = if pp_trailing.is_empty() { String::new() } else { pp_trailing.replace(", ", ", _") };
            out.push_str(&format!(
                "    async on{cap}(callback: (payload: unknown) => void{ipc_pp}): Promise<() => void> {{\n\
                 \x20     const unlisten = await listen('{ev_name}', (event: {{ payload: unknown }}) => {{\n\
                 \x20       callback(event.payload);\n\
                 \x20     }});\n\
                 \x20     return unlisten;\n\
                 \x20   }},\n",
                cap = capitalize_first(&camel),
            ));
        }
    }

    out.push_str("  };\n");
    out.push_str("}\n");
}

/// Generate a custom HTTP method (GET or POST with various param shapes).
fn generate_http_custom_method(out: &mut String, module: &str, f: &crate::servers::parse::ApiFn, config: &Config) {
    let fn_name = &f.name;
    let camel = snake_to_camel(fn_name);
    let ts_ret = rust_type_to_ts(&f.return_type);
    let is_get = is_read_operation(fn_name);
    let action = config.naming.derive_action(module, fn_name);
    let plural = config.naming.module_plural(module);
    let returns_unit = f.return_type == "()";
    let has_prefix = config.route_prefix.is_some();
    let pp_camel = config.route_prefix.as_ref().map(|p| snake_to_camel(&p.params[0].name)).unwrap_or_default();
    let pp_only = ts_prefix_param_only(config);

    let body_struct: Option<&Param> = f.params.iter().find(|p| p.ty.contains("Input"));
    let query_params: Vec<&Param> = f.params.iter().filter(|p| p.ty.starts_with("Option<")).collect();
    let path_params: Vec<&Param> = if is_get {
        f.params.iter().filter(|p| !p.ty.starts_with("Option<") && !p.ty.contains("Input")).collect()
    } else {
        vec![]
    };
    let body_fields: Vec<&Param> = if !is_get && body_struct.is_none() {
        f.params.iter().filter(|p| !p.ty.starts_with("Option<") && !p.ty.contains("Input")).collect()
    } else {
        vec![]
    };

    let mut route_path = format!("/{}", plural);
    if !action.is_empty() {
        route_path.push_str(&format!("/{}", action));
    }

    // Helper closures for scoped paths
    let sp = |path: &str| -> String {
        if has_prefix { format!("scopedPath({}, '{}')", pp_camel, path) } else { format!("'{}'", path) }
    };
    let sp_template = |path: &str| -> String {
        if has_prefix { format!("scopedPath({}, `{}`)", pp_camel, path) } else { format!("`{}`", path) }
    };

    let mut ts_params = build_ts_params(f, config);
    if !pp_only.is_empty() {
        ts_params.push(pp_only.clone());
    }
    let params_str = ts_params.join(", ");
    let ret_str = if returns_unit { "null".to_string() } else { ts_ret.clone() };

    if is_get && path_params.is_empty() && query_params.is_empty() {
        let path_expr = sp(&route_path);
        out.push_str(&format!(
            "    async {camel}({params_str}): Promise<{ret_str}> {{\n\
             \x20     return httpGet({path_expr});\n\
             \x20   }},\n",
        ));
    } else if is_get && !path_params.is_empty() && query_params.is_empty() {
        let mut url = route_path.clone();
        for p in &path_params {
            url.push_str(&format!("/${{encodeURIComponent({})}}", snake_to_camel(&p.name)));
        }
        let path_expr = sp_template(&url);
        out.push_str(&format!(
            "    async {camel}({params_str}): Promise<{ret_str}> {{\n\
             \x20     return httpGet({path_expr});\n\
             \x20   }},\n",
        ));
    } else if is_get && !query_params.is_empty() {
        let mut query_parts = Vec::new();
        for qp in &query_params {
            let camel_name = snake_to_camel(&qp.name);
            query_parts
                .push(format!("{camel_name} != null ? `{}=${{encodeURIComponent({camel_name})}}` : ''", qp.name));
        }
        let query_build = if query_parts.len() == 1 {
            format!("const params = {} ? `?${{{}}}` : ''", snake_to_camel(&query_params[0].name), query_parts[0])
        } else {
            format!(
                "const parts = [{}].filter(Boolean);\n\
                 \x20       const params = parts.length > 0 ? `?${{parts.join('&')}}` : ''",
                query_parts.join(", ")
            )
        };
        let path_expr = sp_template(&format!("{}${{params}}", route_path));
        out.push_str(&format!(
            "    async {camel}({params_str}): Promise<{ret_str}> {{\n\
             \x20     {query_build};\n\
             \x20     return httpGet({path_expr});\n\
             \x20   }},\n",
        ));
    } else if body_struct.is_some() {
        let path_expr = sp(&route_path);
        if returns_unit {
            out.push_str(&format!(
                "    async {camel}({params_str}): Promise<null> {{\n\
                 \x20     await httpPost({path_expr}, input);\n\
                 \x20     return null;\n\
                 \x20   }},\n",
            ));
        } else {
            out.push_str(&format!(
                "    async {camel}({params_str}): Promise<{ret_str}> {{\n\
                 \x20     return httpPost<{ret_str}>({path_expr}, input);\n\
                 \x20   }},\n",
            ));
        }
    } else if !body_fields.is_empty() {
        let body_obj: Vec<String> = body_fields
            .iter()
            .map(|bf| {
                let camel_name = snake_to_camel(&bf.name);
                if camel_name == bf.name { bf.name.clone() } else { format!("{}: {}", bf.name, camel_name) }
            })
            .collect();
        let body_str = format!("{{ {} }}", body_obj.join(", "));
        let path_expr = sp(&route_path);
        if returns_unit {
            out.push_str(&format!(
                "    async {camel}({params_str}): Promise<null> {{\n\
                 \x20     await httpPost({path_expr}, {body_str});\n\
                 \x20     return null;\n\
                 \x20   }},\n",
            ));
        } else {
            out.push_str(&format!(
                "    async {camel}({params_str}): Promise<{ret_str}> {{\n\
                 \x20     return httpPost<{ret_str}>({path_expr}, {body_str});\n\
                 \x20   }},\n",
            ));
        }
    } else {
        // POST with no params
        let path_expr = sp(&route_path);
        if returns_unit {
            out.push_str(&format!(
                "    async {camel}({params_str}): Promise<null> {{\n\
                 \x20     await httpPost({path_expr});\n\
                 \x20     return null;\n\
                 \x20   }},\n",
            ));
        } else {
            out.push_str(&format!(
                "    async {camel}({params_str}): Promise<{ret_str}> {{\n\
                 \x20     return httpPost<{ret_str}>({path_expr});\n\
                 \x20   }},\n",
            ));
        }
    }
}

/// Generate a custom IPC method.
fn generate_ipc_custom_method(out: &mut String, f: &crate::servers::parse::ApiFn, cmd_name: &str, config: &Config) {
    let camel = snake_to_camel(&f.name);
    let ts_ret = rust_type_to_ts(&f.return_type);
    let returns_unit = f.return_type == "()";
    let ret_str = if returns_unit { "null".to_string() } else { ts_ret.clone() };
    let pp_only = ts_prefix_param_only(config);
    let ipc_arg = ts_ipc_prefix_arg(config);

    let has_params = !f.params.is_empty();
    let has_prefix = !pp_only.is_empty();

    if !has_params && !has_prefix {
        if returns_unit {
            out.push_str(&format!(
                "    async {camel}(): Promise<null> {{\n\
                 \x20     await invoke('{cmd_name}');\n\
                 \x20     return null;\n\
                 \x20   }},\n",
            ));
        } else {
            out.push_str(&format!(
                "    async {camel}(): Promise<{ret_str}> {{\n\
                 \x20     return invoke('{cmd_name}');\n\
                 \x20   }},\n",
            ));
        }
    } else {
        // Build param list and invoke args
        let mut ts_params: Vec<String> = f
            .params
            .iter()
            .map(|p| {
                let ts_ty = rust_type_to_ts(&p.ty);
                let owned_ty = if p.ty.starts_with("Option<") {
                    format!("{} | null", ts_ty.trim_start_matches("Option<").trim_end_matches('>'))
                } else {
                    ts_ty
                };
                format!("{}: {}", snake_to_camel(&p.name), owned_ty)
            })
            .collect();
        if has_prefix {
            ts_params.push(pp_only.clone());
        }
        let params_str = ts_params.join(", ");

        // Build invoke args object — Tauri expects snake_case keys for IPC
        let invoke_args: Vec<String> = f.params.iter().map(|p| snake_to_camel(&p.name)).collect();
        let ipc_arg_only = ts_ipc_prefix_arg_only(config);
        let args_str = if invoke_args.is_empty() && !ipc_arg_only.is_empty() {
            format!("{{ {ipc_arg_only} }}")
        } else {
            format!("{{ {}{ipc_arg} }}", invoke_args.join(", "))
        };

        if returns_unit {
            out.push_str(&format!(
                "    async {camel}({params_str}): Promise<null> {{\n\
                 \x20     await invoke('{cmd_name}', {args_str});\n\
                 \x20     return null;\n\
                 \x20   }},\n",
            ));
        } else {
            out.push_str(&format!(
                "    async {camel}({params_str}): Promise<{ret_str}> {{\n\
                 \x20     return invoke('{cmd_name}', {args_str});\n\
                 \x20   }},\n",
            ));
        }
    }
}

/// Build TypeScript parameter list for a custom function.
fn build_ts_params(f: &crate::servers::parse::ApiFn, config: &Config) -> Vec<String> {
    let is_get = is_read_operation(&f.name);
    let body_struct: Option<&Param> = f.params.iter().find(|p| p.ty.contains("Input"));
    let query_params: Vec<&Param> = f.params.iter().filter(|p| p.ty.starts_with("Option<")).collect();
    let path_params: Vec<&Param> = if is_get {
        f.params.iter().filter(|p| !p.ty.starts_with("Option<") && !p.ty.contains("Input")).collect()
    } else {
        vec![]
    };
    let body_fields: Vec<&Param> = if !is_get && body_struct.is_none() {
        f.params.iter().filter(|p| !p.ty.starts_with("Option<") && !p.ty.contains("Input")).collect()
    } else {
        vec![]
    };

    let _ = config; // used for naming in the caller
    let mut ts_params = Vec::new();
    for p in &path_params {
        let ts_ty = if p.ty == "i32" { "number" } else { "string" };
        ts_params.push(format!("{}: {}", snake_to_camel(&p.name), ts_ty));
    }
    for qp in &query_params {
        ts_params.push(format!("{}: string | null", snake_to_camel(&qp.name)));
    }
    if let Some(bs) = body_struct {
        let input_type = rust_type_to_ts(&extract_input_type(&bs.ty));
        ts_params.push(format!("input: {}", input_type));
    }
    for bf in &body_fields {
        let ts_ty = if bf.ty == "i32" { "number" } else { "string" };
        ts_params.push(format!("{}: {}", snake_to_camel(&bf.name), ts_ty));
    }
    ts_params
}

/// Capitalize the first character of a string.
fn capitalize_first(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        None => String::new(),
        Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
    }
}
