//! Schema-known half of the OF-014 hybrid: emit TS type aliases for entities
//! and their generated Create/Update DTOs straight from `EntityDef`.
//!
//! The long-tail (user-owned types referenced by custom API endpoints) is
//! handled separately by `ts_sidecar` via a generated specta binary.

use std::collections::HashSet;

use ontogen_core::model::{EntityDef, FieldRole, FieldType};

use crate::servers::config::Config;
use crate::servers::generators::ipc::command_name;
use crate::servers::parse::ApiModule;
use crate::servers::types::{collect_ts_import, extract_input_type, rust_type_to_ts};

/// Collect every TS type name referenced by the generated client surface
/// (return types + parameter types of every emitted command). Mirrors the
/// inline collection currently done in `ts_client::generate` and
/// `transport::generate`.
pub fn referenced_ts_types(modules: &[ApiModule], config: &Config) -> Vec<String> {
    let mut import_types: Vec<String> = Vec::new();
    for m in modules {
        if m.functions.is_empty() {
            continue;
        }
        for f in &m.functions {
            let cmd_name = command_name(&m.name, f, config);
            if cmd_name.is_empty() || config.ts_skip_commands.contains(&cmd_name) {
                continue;
            }
            let ts_ret = rust_type_to_ts(&f.return_type);
            collect_ts_import(&ts_ret, &mut import_types);
            for p in &f.params {
                let ty = extract_input_type(&p.ty);
                let ts_ty = rust_type_to_ts(&ty);
                collect_ts_import(&ts_ty, &mut import_types);
            }
        }
    }
    import_types.sort();
    import_types.dedup();
    import_types
}

/// Names that the schema-known emitter (this module's `emit`) writes to
/// bindings.ts: the entity itself plus its Create/Update DTOs.
pub fn schema_known_names(entities: &[EntityDef]) -> HashSet<String> {
    let mut set = HashSet::new();
    for e in entities {
        set.insert(e.name.clone());
        set.insert(format!("Create{}Input", e.name));
        set.insert(format!("Update{}Input", e.name));
    }
    set
}

/// Referenced types that are NOT covered by schema-known emission. Drives
/// the specta side-car (option 3 half of the OF-014 hybrid).
pub fn long_tail(modules: &[ApiModule], config: &Config, entities: &[EntityDef]) -> Vec<String> {
    let known = schema_known_names(entities);
    referenced_ts_types(modules, config).into_iter().filter(|t| !known.contains(t)).collect()
}

pub fn emit(entities: &[EntityDef]) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by ontogen. DO NOT EDIT.\n");
    out.push_str("// Schema-known surface: entities + generated Create/Update DTOs.\n\n");
    for entity in entities {
        out.push_str(&emit_entity(entity));
        out.push('\n');
        out.push_str(&emit_create_dto(entity));
        out.push('\n');
        out.push_str(&emit_update_dto(entity));
        out.push('\n');
    }
    out
}

fn emit_entity(entity: &EntityDef) -> String {
    let mut out = format!("export type {} = {{\n", entity.name);
    for f in &entity.fields {
        if !include_in_entity(f) {
            continue;
        }
        out.push_str(&format!("  {}: {};\n", f.name, field_to_ts(&f.field_type)));
    }
    out.push_str("};\n");
    out
}

fn emit_create_dto(entity: &EntityDef) -> String {
    let mut out = format!("export type Create{}Input = {{\n", entity.name);
    for f in &entity.fields {
        if !include_in_dto(f) {
            continue;
        }
        out.push_str(&format!("  {}: {};\n", f.name, field_to_ts(&f.field_type)));
    }
    out.push_str("};\n");
    out
}

fn emit_update_dto(entity: &EntityDef) -> String {
    let mut out = format!("export type Update{}Input = {{\n", entity.name);
    for f in &entity.fields {
        if !include_in_dto(f) || matches!(f.role, FieldRole::Id) {
            continue;
        }
        out.push_str(&format!("  {}?: {} | null;\n", f.name, field_to_ts(&f.field_type)));
    }
    out.push_str("};\n");
    out
}

fn include_in_entity(f: &ontogen_core::model::FieldDef) -> bool {
    !matches!(f.role, FieldRole::Skip) && f.name != "wikilinks" && f.name != "source_file"
}

fn include_in_dto(f: &ontogen_core::model::FieldDef) -> bool {
    f.name != "wikilinks" && f.name != "source_file"
}

fn field_to_ts(ft: &FieldType) -> String {
    match ft {
        FieldType::String => "string".into(),
        FieldType::OptionString => "string | null".into(),
        FieldType::I32 | FieldType::I64 | FieldType::F32 | FieldType::F64 => "number".into(),
        FieldType::OptionI32 | FieldType::OptionI64 | FieldType::OptionF32 | FieldType::OptionF64 => {
            "number | null".into()
        }
        FieldType::Bool => "boolean".into(),
        FieldType::OptionBool => "boolean | null".into(),
        FieldType::VecString => "string[]".into(),
        FieldType::VecStruct(name) => format!("{name}[]"),
        FieldType::OptionEnum(name) => format!("{name} | null"),
        FieldType::Other(name) => name.clone(),
    }
}
