// TODO: review — banner strings updated from old crate names
#![allow(clippy::too_many_lines, clippy::format_push_string)]

//! Generate TypeScript HTTP client from API modules.

use std::fs;
use std::path::Path;

use crate::servers::classify::{OpKind, classify_op, is_read_operation};
use crate::servers::config::Config;
use crate::servers::generators::ipc::ts_command_name;
use crate::servers::parse::{ApiFn, ApiModule, Param};
use crate::servers::types::{collect_ts_import, extract_input_type, rust_type_to_ts, snake_to_camel};

/// Generate TypeScript HTTP client and write to the output file.
pub fn generate(output: &Path, bindings_path: &Path, modules: &[ApiModule], config: &Config) {
    let mut out = String::new();

    // Read bindings.ts to discover which types are actually exported
    let bindings_content = fs::read_to_string(bindings_path).unwrap_or_default();
    let exported_types: Vec<String> = bindings_content
        .lines()
        .filter_map(|line| {
            line.strip_prefix("export type ")
                .and_then(|rest| rest.split(|c: char| !c.is_alphanumeric() && c != '_').next().map(|s| s.to_string()))
        })
        .collect();

    out.push_str(
        "// Auto-generated HTTP client. DO NOT EDIT.\n\
         // Generated by ontogen from API source files.\n\n",
    );

    // Collect all types we need to import
    let mut import_types: Vec<String> = Vec::new();

    for m in modules {
        if m.functions.is_empty() {
            continue;
        }
        for f in &m.functions {
            let cmd_name = ts_command_name(&m.name, f, config);
            if cmd_name.is_empty() || config.ts_skip_commands.contains(&cmd_name) {
                continue;
            }
            let ts_ret = rust_type_to_ts(&f.return_type);
            collect_ts_import(&ts_ret, &mut import_types);
            for p in &f.params {
                let ty = extract_input_type(&p.ty);
                let ts_ty = rust_type_to_ts(&ty);
                collect_ts_import(&ts_ty, &mut import_types);
            }
        }
    }

    import_types.sort();
    import_types.dedup();

    let (available, missing): (Vec<_>, Vec<_>) = import_types.iter().partition(|t| exported_types.contains(t));

    if !available.is_empty() {
        out.push_str("import type {\n");
        for t in &available {
            out.push_str(&format!("  {},\n", t));
        }
        out.push_str("} from './bindings';\n\n");
    }

    for t in &missing {
        out.push_str(&format!(
            "// TODO: Type '{t}' not yet exported from bindings.ts — using placeholder\n\
             type {t} = Record<string, unknown>;\n\n"
        ));
    }

    out.push_str("const BASE = '/api';\n\n");

    out.push_str(
        "async function httpGet<T>(path: string): Promise<T> {\n\
         \x20 const res = await fetch(`${BASE}${path}`);\n\
         \x20 if (!res.ok) {\n\
         \x20   const body = await res.json().catch(() => ({ error: res.statusText }));\n\
         \x20   throw new Error(body.error ?? res.statusText);\n\
         \x20 }\n\
         \x20 return res.json();\n\
         }\n\n\
         async function httpPost<T>(path: string, body?: unknown): Promise<T> {\n\
         \x20 const res = await fetch(`${BASE}${path}`, {\n\
         \x20   method: 'POST',\n\
         \x20   headers: { 'Content-Type': 'application/json' },\n\
         \x20   body: body != null ? JSON.stringify(body) : undefined,\n\
         \x20 });\n\
         \x20 if (!res.ok) {\n\
         \x20   const errBody = await res.json().catch(() => ({ error: res.statusText }));\n\
         \x20   throw new Error(errBody.error ?? res.statusText);\n\
         \x20 }\n\
         \x20 if (res.status === 204) return null as T;\n\
         \x20 return res.json();\n\
         }\n\n\
         async function httpPut<T>(path: string, body: unknown): Promise<T> {\n\
         \x20 const res = await fetch(`${BASE}${path}`, {\n\
         \x20   method: 'PUT',\n\
         \x20   headers: { 'Content-Type': 'application/json' },\n\
         \x20   body: JSON.stringify(body),\n\
         \x20 });\n\
         \x20 if (!res.ok) {\n\
         \x20   const errBody = await res.json().catch(() => ({ error: res.statusText }));\n\
         \x20   throw new Error(errBody.error ?? res.statusText);\n\
         \x20 }\n\
         \x20 return res.json();\n\
         }\n\n\
         async function httpDelete(path: string): Promise<void> {\n\
         \x20 const res = await fetch(`${BASE}${path}`, { method: 'DELETE' });\n\
         \x20 if (!res.ok) {\n\
         \x20   const errBody = await res.json().catch(() => ({ error: res.statusText }));\n\
         \x20   throw new Error(errBody.error ?? res.statusText);\n\
         \x20 }\n\
         }\n\n",
    );

    out.push_str("export const httpCommands = {\n");

    for m in modules {
        if m.functions.is_empty() {
            continue;
        }
        let module = &m.name;
        let plural = config.naming.module_plural(module);

        for f in &m.functions {
            let op = classify_op(f);
            let cmd_name = ts_command_name(module, f, config);
            if cmd_name.is_empty() || config.ts_skip_commands.contains(&cmd_name) {
                continue;
            }

            let ts_ret = rust_type_to_ts(&f.return_type);
            let camel = snake_to_camel(&cmd_name);

            match op {
                OpKind::List => {
                    out.push_str(&format!(
                        "  async {camel}(): Promise<{ts_ret}> {{\n\
                         \x20   return httpGet('/{plural}');\n\
                         \x20 }},\n\n",
                    ));
                }
                OpKind::GetById => {
                    out.push_str(&format!(
                        "  async {camel}(id: string): Promise<{ts_ret}> {{\n\
                         \x20   return httpGet(`/{plural}/${{encodeURIComponent(id)}}`);\n\
                         \x20 }},\n\n",
                    ));
                }
                OpKind::Create => {
                    let input_type = rust_type_to_ts(&extract_input_type(&f.params[0].ty));
                    out.push_str(&format!(
                        "  async {camel}(input: {input_type}): Promise<{ts_ret}> {{\n\
                         \x20   return httpPost<{ts_ret}>('/{plural}', input);\n\
                         \x20 }},\n\n",
                    ));
                }
                OpKind::UpdateById => {
                    let input_type = rust_type_to_ts(&extract_input_type(&f.params[1].ty));
                    out.push_str(&format!(
                        "  async {camel}(id: string, input: {input_type}): Promise<{ts_ret}> {{\n\
                         \x20   return httpPut<{ts_ret}>(`/{plural}/${{encodeURIComponent(id)}}`, input);\n\
                         \x20 }},\n\n",
                    ));
                }
                OpKind::DeleteById => {
                    out.push_str(&format!(
                        "  async {camel}(id: string): Promise<null> {{\n\
                         \x20   await httpDelete(`/{plural}/${{encodeURIComponent(id)}}`);\n\
                         \x20   return null;\n\
                         \x20 }},\n\n",
                    ));
                }
                OpKind::CustomGet | OpKind::CustomPost => {
                    generate_generic_ts_handler(&mut out, module, f, config);
                }
            }
        }
    }

    out.push_str("};\n");

    if let Some(parent) = output.parent() {
        fs::create_dir_all(parent).expect("Failed to create output directory");
    }
    crate::write_if_changed(output, out).expect("Failed to write TS HTTP client");
}

fn generate_generic_ts_handler(out: &mut String, module: &str, f: &ApiFn, config: &Config) {
    let fn_name = &f.name;
    let camel = snake_to_camel(fn_name);
    let ts_ret = rust_type_to_ts(&f.return_type);
    let is_get = is_read_operation(fn_name);
    let action = config.naming.derive_action(module, fn_name);
    let plural = config.naming.module_plural(module);
    let returns_unit = f.return_type == "()";

    let body_struct: Option<&Param> = f.params.iter().find(|p| p.ty.contains("Input"));
    let query_params: Vec<&Param> = f.params.iter().filter(|p| p.ty.starts_with("Option<")).collect();
    let path_params: Vec<&Param> = if is_get {
        f.params.iter().filter(|p| !p.ty.starts_with("Option<") && !p.ty.contains("Input")).collect()
    } else {
        vec![]
    };
    let body_fields: Vec<&Param> = if !is_get && body_struct.is_none() {
        f.params.iter().filter(|p| !p.ty.starts_with("Option<") && !p.ty.contains("Input")).collect()
    } else {
        vec![]
    };

    let mut route_path = format!("/{}", plural);
    if !action.is_empty() {
        route_path.push_str(&format!("/{}", action));
    }

    let mut ts_params = Vec::new();
    for p in &path_params {
        let ts_ty = if p.ty == "i32" { "number" } else { "string" };
        ts_params.push(format!("{}: {}", snake_to_camel(&p.name), ts_ty));
    }
    for qp in &query_params {
        ts_params.push(format!("{}: string | null", snake_to_camel(&qp.name)));
    }
    if let Some(bs) = body_struct {
        let input_type = rust_type_to_ts(&extract_input_type(&bs.ty));
        ts_params.push(format!("input: {}", input_type));
    }
    for bf in &body_fields {
        let ts_ty = if bf.ty == "i32" { "number" } else { "string" };
        ts_params.push(format!("{}: {}", snake_to_camel(&bf.name), ts_ty));
    }

    let ts_ret_str = if returns_unit { "null".to_string() } else { ts_ret.clone() };

    if is_get && path_params.is_empty() && query_params.is_empty() {
        out.push_str(&format!(
            "  async {camel}(): Promise<{ts_ret_str}> {{\n\
             \x20   return httpGet('{route_path}');\n\
             \x20 }},\n\n",
        ));
    } else if is_get && !path_params.is_empty() && query_params.is_empty() {
        let mut url = route_path.clone();
        for p in &path_params {
            url.push_str(&format!("/${{encodeURIComponent({})}}", snake_to_camel(&p.name)));
        }
        let params_str = ts_params.join(", ");
        out.push_str(&format!(
            "  async {camel}({params_str}): Promise<{ts_ret_str}> {{\n\
             \x20   return httpGet(`{url}`);\n\
             \x20 }},\n\n",
        ));
    } else if is_get && !query_params.is_empty() {
        let params_str = ts_params.join(", ");
        let mut query_parts = Vec::new();
        for qp in &query_params {
            let camel_name = snake_to_camel(&qp.name);
            query_parts
                .push(format!("{camel_name} != null ? `{}=${{encodeURIComponent({camel_name})}}` : ''", qp.name));
        }
        let query_build = if query_parts.len() == 1 {
            format!("const params = {} ? `?${{{}}}` : ''", snake_to_camel(&query_params[0].name), query_parts[0])
        } else {
            format!(
                "const parts = [{}].filter(Boolean);\n\
                 \x20   const params = parts.length > 0 ? `?${{parts.join('&')}}` : ''",
                query_parts.join(", ")
            )
        };
        out.push_str(&format!(
            "  async {camel}({params_str}): Promise<{ts_ret_str}> {{\n\
             \x20   {query_build};\n\
             \x20   return httpGet(`{route_path}${{params}}`);\n\
             \x20 }},\n\n",
        ));
    } else if body_struct.is_some() {
        let params_str = ts_params.join(", ");
        if returns_unit {
            out.push_str(&format!(
                "  async {camel}({params_str}): Promise<null> {{\n\
                 \x20   await httpPost('{route_path}', input);\n\
                 \x20   return null;\n\
                 \x20 }},\n\n",
            ));
        } else {
            out.push_str(&format!(
                "  async {camel}({params_str}): Promise<{ts_ret_str}> {{\n\
                 \x20   return httpPost<{ts_ret_str}>('{route_path}', input);\n\
                 \x20 }},\n\n",
            ));
        }
    } else if !body_fields.is_empty() {
        let params_str = ts_params.join(", ");
        let body_obj: Vec<String> = body_fields
            .iter()
            .map(|bf| {
                let camel_name = snake_to_camel(&bf.name);
                if camel_name == bf.name { bf.name.clone() } else { format!("{}: {}", bf.name, camel_name) }
            })
            .collect();
        let body_str = format!("{{ {} }}", body_obj.join(", "));
        if returns_unit {
            out.push_str(&format!(
                "  async {camel}({params_str}): Promise<null> {{\n\
                 \x20   await httpPost('{route_path}', {body_str});\n\
                 \x20   return null;\n\
                 \x20 }},\n\n",
            ));
        } else {
            out.push_str(&format!(
                "  async {camel}({params_str}): Promise<{ts_ret_str}> {{\n\
                 \x20   return httpPost<{ts_ret_str}>('{route_path}', {body_str});\n\
                 \x20 }},\n\n",
            ));
        }
    } else {
        // POST with no params
        if returns_unit {
            out.push_str(&format!(
                "  async {camel}(): Promise<null> {{\n\
                 \x20   await httpPost('{route_path}');\n\
                 \x20   return null;\n\
                 \x20 }},\n\n",
            ));
        } else {
            out.push_str(&format!(
                "  async {camel}(): Promise<{ts_ret_str}> {{\n\
                 \x20   return httpPost<{ts_ret_str}>('{route_path}');\n\
                 \x20 }},\n\n",
            ));
        }
    }
}
