//! Generate Create/Update DTO types from parsed ontology entity definitions.
//!
//! For each entity, generates:
//! - `Create{Entity}Input` - all fields for creating a new entity
//! - `Update{Entity}Input` - all fields wrapped in `Option<T>` for partial updates;
//!   a field whose schema type is already nullable (`Option<T>`) is wrapped
//!   again into `Option<Option<T>>` (outer = "was this field provided?",
//!   inner = the value, `Some(None)` = "clear it") and paired with the
//!   `double_option` `deserialize_with` helper so JSON `null` reaches the
//!   inner `None` instead of collapsing into the outer one (see
//!   `generate_double_option_fn`)
//!
//! Generated DTOs are clean API-layer types:
//! - No persistence-only fields (wikilinks, source_file)
//! - Typed enums (not raw strings)
//! - Includes relation fields (has_many, many_to_many) as `Vec<String>` for API input
//! - Includes skip fields (entity-level data not in DB columns)

use std::fs;
use std::path::Path;

use crate::persistence::seaorm::gen_entity::to_snake_case;
use crate::schema::model::{EntityDef, FieldDef, FieldRole, FieldType};

// ─── Public API ──────────────────────────────────────────────────────────────

/// Generate DTO modules and write them to the output directory.
pub fn generate(entities: &[EntityDef], output_dir: &Path) -> Result<(), String> {
    fs::create_dir_all(output_dir).map_err(|e| format!("Failed to create output dir {}: {e}", output_dir.display()))?;

    // Clean stale files from previous entity names
    let expected: std::collections::HashSet<String> = entities
        .iter()
        .map(|e| format!("{}.rs", to_snake_case(&e.name)))
        .chain(std::iter::once("mod.rs".to_string()))
        .collect();
    crate::clean_generated_dir(output_dir, &expected);

    let mut mod_names: Vec<String> = Vec::new();

    for entity in entities {
        let mod_name = to_snake_case(&entity.name);
        let code = generate_dto_code(entity);
        let path = output_dir.join(format!("{mod_name}.rs"));
        crate::write_and_format(&path, &code).map_err(|e| format!("Failed to write {}: {e}", path.display()))?;
        mod_names.push(mod_name);
    }

    // Write mod.rs
    mod_names.sort();
    let mod_rs = generate_mod_rs(&mod_names);
    let path = output_dir.join("mod.rs");
    crate::write_and_format(&path, &mod_rs).map_err(|e| format!("Failed to write {}: {e}", path.display()))?;

    Ok(())
}

// ─── Code Generation ─────────────────────────────────────────────────────────

/// Generate the full DTO module for one entity.
fn generate_dto_code(entity: &EntityDef) -> String {
    let entity_name = &entity.name;
    let create_fields = generate_create_fields(entity);
    let update_fields = generate_update_fields(entity);
    let default_fns = generate_default_fns(entity);
    // Emitted only when at least one field needs it: an unused private fn
    // would trip the workspace's `--deny warnings` dead-code lint in every
    // entity module that has no nullable fields.
    let double_option_fn = if entity.fields.iter().any(field_appears_in_update_dto_as_double_option) {
        generate_double_option_fn()
    } else {
        String::new()
    };

    format!(
        r#"//! Generated by ontogen. DO NOT EDIT.

use schemars::JsonSchema;
use serde::Deserialize;

/// Input for creating a new {entity_name}.
#[derive(Debug, Clone, Deserialize, JsonSchema, specta::Type)]
pub struct Create{entity_name}Input {{
{create_fields}
}}

/// Input for updating an existing {entity_name}.
/// All fields are optional; only provided fields are updated.
#[derive(Debug, Clone, Deserialize, JsonSchema, specta::Type)]
pub struct Update{entity_name}Input {{
{update_fields}
}}
{default_fns}{double_option_fn}"#
    )
}

/// Generate fields for CreateXInput.
fn generate_create_fields(entity: &EntityDef) -> String {
    let mut lines = Vec::new();

    for field in &entity.fields {
        if let Some(line) = generate_create_field(field) {
            lines.push(line);
        }
    }

    lines.join("\n")
}

/// Generate a single field for CreateXInput.
fn generate_create_field(field: &FieldDef) -> Option<String> {
    let name = &field.name;

    // Persistence-only fields are never in DTOs
    if name == "wikilinks" || name == "source_file" {
        return None;
    }

    // Skip fields ARE included in DTOs (they're schema-level data, just not in DB columns)
    // Relation fields (has_many, many_to_many) ARE included as Vec<String> for API input
    let rust_type = field_to_create_type(field);
    let serde_attr = generate_serde_default_attr(field);
    Some(format!("{serde_attr}    pub {name}: {rust_type},"))
}

/// Generate fields for UpdateXInput.
fn generate_update_fields(entity: &EntityDef) -> String {
    let mut lines = Vec::new();

    for field in &entity.fields {
        if let Some(line) = generate_update_field(field) {
            lines.push(line);
        }
    }

    lines.join("\n")
}

/// Generate a single field for UpdateXInput.
fn generate_update_field(field: &FieldDef) -> Option<String> {
    let name = &field.name;

    // Persistence-only fields are never in DTOs
    if name == "wikilinks" || name == "source_file" {
        return None;
    }

    match &field.role {
        // ID is not updatable
        FieldRole::Id => None,
        // Skip fields, relation fields ARE included (same as create)
        _ => {
            let inner_type = field_to_create_type(field);
            let rust_type = format!("Option<{inner_type}>");
            let attr = if is_double_option_type(&field.field_type) {
                "    #[serde(default, deserialize_with = \"double_option\")]\n"
            } else {
                "    #[serde(default)]\n"
            };
            Some(format!("{attr}    pub {name}: {rust_type},"))
        }
    }
}

/// Whether a field's Update-DTO type is `Option<Option<T>>` — i.e. the
/// schema type itself is already nullable, so wrapping it again for
/// "was this field provided?" produces a double Option. These fields need
/// the `double_option` deserializer (see `generate_double_option_fn`);
/// serde's default handling of `Option<Option<T>>` collapses a JSON `null`
/// into the OUTER `None` ("not provided"), making the field impossible to
/// clear over the wire.
fn is_double_option_type(field_type: &FieldType) -> bool {
    matches!(
        field_type,
        FieldType::OptionString
            | FieldType::OptionI32
            | FieldType::OptionI64
            | FieldType::OptionF32
            | FieldType::OptionF64
            | FieldType::OptionBool
            | FieldType::OptionEnum(_)
    )
}

/// Whether `field` appears in the Update DTO wrapped as `Option<Option<T>>`
/// — mirrors the inclusion filter in `generate_update_field` without
/// building the formatted line, so `generate_dto_code` can decide once
/// whether the whole module needs the `double_option` helper.
fn field_appears_in_update_dto_as_double_option(field: &FieldDef) -> bool {
    let name = &field.name;
    if name == "wikilinks" || name == "source_file" {
        return false;
    }
    if matches!(field.role, FieldRole::Id) {
        return false;
    }
    is_double_option_type(&field.field_type)
}

/// Generate the shared `deserialize_with` helper for `Option<Option<T>>`
/// Update fields: the standard serde double-Option idiom. `#[serde(default)]`
/// on the field still makes an ABSENT key deserialize to the outer `None`;
/// this function only changes what a PRESENT key deserializes to, so JSON
/// `null` reaches the inner `None` (`Some(None)`, "clear this field")
/// instead of being swallowed into "field not provided".
///
/// Emitted once per generated module (see `generate_dto_code`), referenced
/// by its bare name since every field using it lives in the same file.
fn generate_double_option_fn() -> String {
    r#"
fn double_option<'de, T, D>(de: D) -> Result<Option<Option<T>>, D::Error>
where
    T: Deserialize<'de>,
    D: serde::Deserializer<'de>,
{
    Deserialize::deserialize(de).map(Some)
}
"#
    .to_string()
}

/// Map a field to its Rust type for the Create DTO.
fn field_to_create_type(field: &FieldDef) -> String {
    match &field.field_type {
        FieldType::String => "String".to_string(),
        FieldType::OptionString => "Option<String>".to_string(),
        FieldType::I32 => "i32".to_string(),
        FieldType::OptionI32 => "Option<i32>".to_string(),
        FieldType::I64 => "i64".to_string(),
        FieldType::OptionI64 => "Option<i64>".to_string(),
        FieldType::F32 => "f32".to_string(),
        FieldType::OptionF32 => "Option<f32>".to_string(),
        FieldType::F64 => "f64".to_string(),
        FieldType::OptionF64 => "Option<f64>".to_string(),
        FieldType::Bool => "bool".to_string(),
        FieldType::OptionBool => "Option<bool>".to_string(),
        FieldType::VecString => "Vec<String>".to_string(),
        FieldType::VecStruct(t) => format!("Vec<crate::schema::{t}>"),
        FieldType::OptionEnum(t) => format!("Option<{}>", qualify_type(t)),
        FieldType::Other(t) => qualify_type(t),
    }
}

/// Qualify a type with `crate::schema::` unless it's a primitive.
fn qualify_type(t: &str) -> String {
    match t {
        "u8" | "u16" | "u32" | "u64" | "u128" | "usize" | "i8" | "i16" | "i32" | "i64" | "i128" | "isize" | "f32"
        | "f64" | "bool" | "char" | "String" => t.to_string(),
        _ => format!("crate::schema::{t}"),
    }
}

/// Generate the `#[serde(default)]` or `#[serde(default = "fn_name")]` attribute for a Create field.
fn generate_serde_default_attr(field: &FieldDef) -> String {
    match &field.role {
        // Create inputs may omit the id: an empty id means "derive one"
        // under the markdown backend's id strategy (ADR 0001,
        // create-with-derived-id contract). Emitted identically for every
        // backend so DTO output stays backend-identical; SeaORM consumers
        // that require caller-supplied ids keep passing them.
        FieldRole::Id => "    #[serde(default)]\n".to_string(),
        _ => {
            let needs_default = field.serde_default
                || matches!(
                    field.field_type,
                    FieldType::OptionString
                        | FieldType::OptionI32
                        | FieldType::OptionI64
                        | FieldType::OptionF32
                        | FieldType::OptionF64
                        | FieldType::OptionBool
                        | FieldType::OptionEnum(_)
                        | FieldType::VecString
                        | FieldType::VecStruct(_)
                );

            if field.default_value.is_some() {
                // Generate serde(default = "fn_name") pointing to an inline function
                let fn_name = format!("default_{}", field.name);
                format!("    #[serde(default = \"{fn_name}\")]\n",)
            } else if needs_default {
                "    #[serde(default)]\n".to_string()
            } else {
                String::new()
            }
        }
    }
}

/// Generate default value helper functions that serde(default = "fn_name") references.
fn generate_default_fns(entity: &EntityDef) -> String {
    let mut fns = String::new();
    for field in &entity.fields {
        if let Some(ref default_val) = field.default_value {
            let fn_name = format!("default_{}", field.name);
            let rust_type = field_to_create_type(field);
            fns.push_str(&format!("\nfn {fn_name}() -> {rust_type} {{\n    \"{default_val}\".to_string()\n}}\n"));
        }
    }
    fns
}

/// Generate the `mod.rs` re-exporting all DTO modules.
fn generate_mod_rs(mod_names: &[String]) -> String {
    let mut out = String::from("//! Generated by ontogen. DO NOT EDIT.\n\n");
    for name in mod_names {
        out.push_str(&format!("pub mod {name};\npub use {name}::*;\n"));
    }
    out
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schema::model::*;

    fn make_entity() -> EntityDef {
        EntityDef {
            name: "Agent".to_string(),
            directory: "agent".to_string(),
            table: "agents".to_string(),
            type_name: "agent".to_string(),
            prefix: "agent".to_string(),

            fields: vec![
                FieldDef {
                    name: "id".to_string(),
                    field_type: FieldType::String,
                    role: FieldRole::Id,
                    serde_default: false,
                    multiline_list: false,
                    default_value: None,
                    doc: String::new(),
                },
                FieldDef {
                    name: "name".to_string(),
                    field_type: FieldType::String,
                    role: FieldRole::Plain,
                    serde_default: false,
                    multiline_list: false,
                    default_value: None,
                    doc: String::new(),
                },
                FieldDef {
                    name: "agent_type".to_string(),
                    field_type: FieldType::OptionEnum("AgentType".to_string()),
                    role: FieldRole::EnumField,
                    serde_default: true,
                    multiline_list: false,
                    default_value: None,
                    doc: String::new(),
                },
                FieldDef {
                    name: "capabilities".to_string(),
                    field_type: FieldType::VecString,
                    role: FieldRole::Plain,
                    serde_default: true,
                    multiline_list: false,
                    default_value: None,
                    doc: String::new(),
                },
                FieldDef {
                    name: "body".to_string(),
                    field_type: FieldType::String,
                    role: FieldRole::Body,
                    serde_default: false,
                    multiline_list: false,
                    default_value: None,
                    doc: String::new(),
                },
            ],
            doc: String::new(),
        }
    }

    #[test]
    fn create_dto_has_all_fields() {
        let code = generate_dto_code(&make_entity());

        assert!(code.contains("pub struct CreateAgentInput"));
        assert!(code.contains("pub id: String,"));
        assert!(code.contains("pub name: String,"));
        assert!(code.contains("pub agent_type: Option<crate::schema::AgentType>,"));
        assert!(code.contains("pub capabilities: Vec<String>,"));
        assert!(code.contains("pub body: String,"));
    }

    #[test]
    fn update_dto_wraps_in_option_and_excludes_id() {
        let code = generate_dto_code(&make_entity());

        assert!(code.contains("pub struct UpdateAgentInput"));
        // ID should NOT be in update
        assert!(!code.contains("pub id: Option<String>,"));
        // All other fields wrapped in Option
        assert!(code.contains("pub name: Option<String>,"));
        assert!(code.contains("pub agent_type: Option<Option<crate::schema::AgentType>>,"));
        assert!(code.contains("pub capabilities: Option<Vec<String>>,"));
        assert!(code.contains("pub body: Option<String>,"));
    }

    /// Entity carrying the two nullable-field shapes a client needs to be
    /// able to clear over JSON: a plain `Option<String>` and an
    /// `Option<enum>`. Named after the fields a real downstream consumer
    /// (an admin UI) hit this bug through.
    fn make_entity_with_nullable_fields() -> EntityDef {
        EntityDef {
            name: "Todo".to_string(),
            directory: "todo".to_string(),
            table: "todos".to_string(),
            type_name: "todo".to_string(),
            prefix: "todo".to_string(),
            doc: String::new(),

            fields: vec![
                FieldDef::new("id", FieldType::String, FieldRole::Id),
                FieldDef::new("title", FieldType::String, FieldRole::Plain),
                FieldDef::new("notes", FieldType::OptionString, FieldRole::Plain),
                FieldDef::new(
                    "completion_kind",
                    FieldType::OptionEnum("CompletionKind".to_string()),
                    FieldRole::EnumField,
                ),
            ],
        }
    }

    /// Regression test for the double-Option deserialization defect: a
    /// nullable Update field (`Option<Option<T>>`) must route through the
    /// `double_option` deserializer so JSON `null` reaches the inner `None`
    /// ("clear this field") instead of collapsing into the outer `None`
    /// ("field not provided", serde's default behavior for `Option<Option<T>>`).
    /// A non-nullable field (`title`) must NOT get the attribute — plain
    /// `#[serde(default)]` is correct for it.
    #[test]
    fn update_dto_emits_double_option_deserializer_for_nullable_fields() {
        let code = generate_dto_code(&make_entity_with_nullable_fields());

        assert!(
            code.contains(
                "#[serde(default, deserialize_with = \"double_option\")]\n    pub notes: Option<Option<String>>,"
            ),
            "notes (Option<String>) should deserialize through double_option, got: {code}"
        );
        assert!(
            code.contains(
                "#[serde(default, deserialize_with = \"double_option\")]\n    pub completion_kind: Option<Option<crate::schema::CompletionKind>>,"
            ),
            "completion_kind (Option<enum>) should deserialize through double_option, got: {code}"
        );
        assert!(
            code.contains("#[serde(default)]\n    pub title: Option<String>,"),
            "title (plain String) should keep plain #[serde(default)], got: {code}"
        );
        assert!(
            !code.contains("title\", deserialize_with") && !code.contains("pub title: Option<Option<String>>,"),
            "title must not be double-wrapped or route through double_option: {code}"
        );

        // The helper is emitted exactly once per module, not once per field.
        assert_eq!(
            code.matches("fn double_option").count(),
            1,
            "double_option helper should be emitted exactly once: {code}"
        );

        syn::parse_file(&code)
            .unwrap_or_else(|e| panic!("double-option DTO produced invalid Rust: {e}\n--- code ---\n{code}"));
    }

    /// An entity with no nullable fields must not carry the (otherwise
    /// unused, dead-code-lint-triggering) `double_option` helper at all.
    #[test]
    fn update_dto_omits_double_option_helper_when_unneeded() {
        let entity = EntityDef {
            name: "Role".to_string(),
            directory: "role".to_string(),
            table: "roles".to_string(),
            type_name: "role".to_string(),
            prefix: "role".to_string(),
            fields: vec![
                FieldDef::new("id", FieldType::String, FieldRole::Id),
                FieldDef::new("name", FieldType::String, FieldRole::Plain),
                FieldDef::new("body", FieldType::String, FieldRole::Body),
            ],
            doc: String::new(),
        };

        let code = generate_dto_code(&entity);
        assert!(
            !code.contains("fn double_option"),
            "entities with no Option<Option<T>> fields should not emit the helper: {code}"
        );
    }

    /// Behavioural check on the exact idiom `generate_double_option_fn`
    /// emits (kept in sync by hand — see that function's doc comment):
    /// absent key -> outer `None` (no change); JSON `null` -> `Some(None)`
    /// (clear); a present value -> `Some(Some(v))`. Run through real
    /// `serde_json`, not a hand simulation of serde's dispatch.
    #[test]
    fn double_option_idiom_distinguishes_absent_null_and_present() {
        fn double_option<'de, T, D>(de: D) -> Result<Option<Option<T>>, D::Error>
        where
            T: serde::Deserialize<'de>,
            D: serde::Deserializer<'de>,
        {
            serde::Deserialize::deserialize(de).map(Some)
        }

        #[derive(serde::Deserialize)]
        struct Probe {
            #[serde(default, deserialize_with = "double_option")]
            notes: Option<Option<String>>,
        }

        let absent: Probe = serde_json::from_str("{}").unwrap();
        assert_eq!(absent.notes, None, "absent key must stay the outer None (no change)");

        let cleared: Probe = serde_json::from_str(r#"{"notes": null}"#).unwrap();
        assert_eq!(cleared.notes, Some(None), "JSON null must clear the field: Some(None)");

        let set: Probe = serde_json::from_str(r#"{"notes": "x"}"#).unwrap();
        assert_eq!(set.notes, Some(Some("x".to_string())), "a provided value must be Some(Some(v))");
    }

    #[test]
    fn has_many_and_many_to_many_included() {
        let entity = EntityDef {
            name: "Node".to_string(),
            directory: "nodes".to_string(),
            table: "nodes".to_string(),
            type_name: "node".to_string(),
            prefix: "node".to_string(),

            fields: vec![
                FieldDef {
                    name: "id".to_string(),
                    field_type: FieldType::String,
                    role: FieldRole::Id,
                    serde_default: false,
                    multiline_list: false,
                    default_value: None,
                    doc: String::new(),
                },
                FieldDef {
                    name: "contains".to_string(),
                    field_type: FieldType::VecString,
                    role: FieldRole::Relation(RelationInfo {
                        kind: RelationKind::HasMany,
                        target: "Node".to_string(),
                        junction: None,
                        foreign_key: Some("parent_id".to_string()),
                    }),
                    serde_default: true,
                    multiline_list: false,
                    default_value: None,
                    doc: String::new(),
                },
                FieldDef {
                    name: "fulfills".to_string(),
                    field_type: FieldType::VecString,
                    role: FieldRole::Relation(RelationInfo {
                        kind: RelationKind::ManyToMany,
                        target: "Requirement".to_string(),
                        junction: None,
                        foreign_key: None,
                    }),
                    serde_default: true,
                    multiline_list: false,
                    default_value: None,
                    doc: String::new(),
                },
                FieldDef {
                    name: "body".to_string(),
                    field_type: FieldType::String,
                    role: FieldRole::Body,
                    serde_default: false,
                    multiline_list: false,
                    default_value: None,
                    doc: String::new(),
                },
            ],
            doc: String::new(),
        };

        let code = generate_dto_code(&entity);
        // Relation fields should be included in DTOs
        assert!(code.contains("contains"), "DTOs should include has_many relation fields");
        assert!(code.contains("fulfills"), "DTOs should include many_to_many relation fields");
    }

    #[test]
    fn skip_field_included() {
        let entity = EntityDef {
            name: "Contract".to_string(),
            directory: "contract".to_string(),
            table: "contracts".to_string(),
            type_name: "contract".to_string(),
            prefix: "contract".to_string(),

            fields: vec![
                FieldDef {
                    name: "id".to_string(),
                    field_type: FieldType::String,
                    role: FieldRole::Id,
                    serde_default: false,
                    multiline_list: false,
                    default_value: None,
                    doc: String::new(),
                },
                FieldDef {
                    name: "states".to_string(),
                    field_type: FieldType::VecString,
                    role: FieldRole::Skip,
                    serde_default: true,
                    multiline_list: false,
                    default_value: None,
                    doc: String::new(),
                },
                FieldDef {
                    name: "body".to_string(),
                    field_type: FieldType::String,
                    role: FieldRole::Body,
                    serde_default: false,
                    multiline_list: false,
                    default_value: None,
                    doc: String::new(),
                },
            ],
            doc: String::new(),
        };

        let code = generate_dto_code(&entity);
        // Skip fields should be included in DTOs (they're schema-level data)
        assert!(code.contains("states"), "DTOs should include skip fields");
    }

    #[test]
    fn default_value_generates_serde_default_fn() {
        let entity = EntityDef {
            name: "Requirement".to_string(),
            directory: "requirements".to_string(),
            table: "requirements".to_string(),
            type_name: "requirement".to_string(),
            prefix: "req".to_string(),

            fields: vec![
                FieldDef {
                    name: "id".to_string(),
                    field_type: FieldType::String,
                    role: FieldRole::Id,
                    serde_default: false,
                    multiline_list: false,
                    default_value: None,
                    doc: String::new(),
                },
                FieldDef {
                    name: "disposition".to_string(),
                    field_type: FieldType::String,
                    role: FieldRole::Plain,
                    serde_default: false,
                    multiline_list: false,
                    default_value: Some("active".to_string()),
                    doc: String::new(),
                },
            ],
            doc: String::new(),
        };

        let code = generate_dto_code(&entity);
        assert!(code.contains(r#"#[serde(default = "default_disposition")]"#), "Should use named default fn");
        assert!(code.contains("fn default_disposition()"), "Should generate the default fn");
        assert!(code.contains(r#""active".to_string()"#), "Default fn should return the value");
    }

    #[test]
    fn float_field_types_end_to_end() {
        // End-to-end: parse a schema struct with f32/f64 fields and verify the
        // generated DTO contains the expected types (not Other(...)).
        let source = r#"
            use ontogen_macros::OntologyEntity;

            #[derive(OntologyEntity)]
            #[ontology(entity)]
            pub struct Measurement {
                #[ontology(id)]
                pub id: String,

                pub temperature: f32,
                pub humidity: Option<f32>,
                pub pressure: f64,
                pub altitude: Option<f64>,

                #[ontology(body)]
                pub body: String,
            }
        "#;

        let entities = crate::schema::parse::parse_schema_source(source, std::path::Path::new("test.rs"))
            .expect("parse should succeed");
        assert_eq!(entities.len(), 1);

        // Verify parsed types
        let m = &entities[0];
        assert_eq!(m.fields.iter().find(|f| f.name == "temperature").unwrap().field_type, FieldType::F32);
        assert_eq!(m.fields.iter().find(|f| f.name == "humidity").unwrap().field_type, FieldType::OptionF32);
        assert_eq!(m.fields.iter().find(|f| f.name == "pressure").unwrap().field_type, FieldType::F64);
        assert_eq!(m.fields.iter().find(|f| f.name == "altitude").unwrap().field_type, FieldType::OptionF64);

        // Generate DTO code and verify it contains the float types as bare primitives
        let code = generate_dto_code(m);
        assert!(code.contains("pub temperature: f32,"), "DTO should contain bare f32 field, got: {code}");
        assert!(code.contains("pub humidity: Option<f32>,"), "DTO should contain Option<f32> field, got: {code}");
        assert!(code.contains("pub pressure: f64,"), "DTO should contain bare f64 field, got: {code}");
        assert!(code.contains("pub altitude: Option<f64>,"), "DTO should contain Option<f64> field, got: {code}");

        // Confirm Other(...) was not used as a fallback for floats
        assert!(
            !code.contains("crate::schema::f32") && !code.contains("crate::schema::f64"),
            "Floats should not be qualified through Other(...) escape hatch"
        );
    }

    #[test]
    fn no_wikilinks_or_source_file() {
        let schema_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/schema");

        let entities = crate::schema::parse::parse_schema_dir(&schema_dir).expect("Failed to parse schema dir");

        let dir = std::env::temp_dir().join("ontology_codegen_test_dtos");
        let _ = std::fs::remove_dir_all(&dir);

        generate(&entities, &dir).expect("generate failed");

        // Check every generated DTO file
        for entry in std::fs::read_dir(&dir).unwrap() {
            let entry = entry.unwrap();
            let name = entry.file_name().to_string_lossy().to_string();
            if name == "mod.rs" {
                continue;
            }
            let code = std::fs::read_to_string(entry.path()).unwrap();
            assert!(!code.contains("wikilinks"), "{name} should not contain wikilinks");
            assert!(!code.contains("source_file"), "{name} should not contain source_file");
        }

        let _ = std::fs::remove_dir_all(&dir);
    }

    /// Syntax check: verify generate_dto_code emits a syntactically valid
    /// Rust source file.
    #[test]
    fn generated_code_is_valid_rust() {
        let code = generate_dto_code(&make_entity());
        syn::parse_file(&code).unwrap_or_else(|e| {
            panic!("persistence::dto::generate_dto_code produced invalid Rust: {e}\n--- code ---\n{code}")
        });
    }
}
