// TODO: review — banner strings updated from old crate names
//! Generate Create/Update DTO types from parsed ontology entity definitions.
//!
//! For each entity, generates:
//! - `Create{Entity}Input` — all fields for creating a new entity
//! - `Update{Entity}Input` — all fields wrapped in `Option<T>` for partial updates
//!
//! Generated DTOs are clean API-layer types:
//! - No persistence-only fields (wikilinks, source_file)
//! - Typed enums (not raw strings)
//! - Includes relation fields (has_many, many_to_many) as Vec<String> for API input
//! - Includes skip fields (entity-level data not in DB columns)

use std::fs;
use std::path::Path;

use crate::persistence::seaorm::gen_entity::to_snake_case;
use crate::schema::model::{EntityDef, FieldDef, FieldRole, FieldType};

// ─── Public API ──────────────────────────────────────────────────────────────

/// Generate DTO modules and write them to the output directory.
pub fn generate(entities: &[EntityDef], output_dir: &Path) -> Result<(), String> {
    fs::create_dir_all(output_dir).map_err(|e| format!("Failed to create output dir {}: {e}", output_dir.display()))?;

    // Clean stale files from previous entity names
    let expected: std::collections::HashSet<String> = entities
        .iter()
        .map(|e| format!("{}.rs", to_snake_case(&e.name)))
        .chain(std::iter::once("mod.rs".to_string()))
        .collect();
    crate::clean_generated_dir(output_dir, &expected);

    let mut mod_names: Vec<String> = Vec::new();

    for entity in entities {
        let mod_name = to_snake_case(&entity.name);
        let code = generate_dto_code(entity);
        let path = output_dir.join(format!("{mod_name}.rs"));
        crate::write_and_format(&path, &code).map_err(|e| format!("Failed to write {}: {e}", path.display()))?;
        mod_names.push(mod_name);
    }

    // Write mod.rs
    mod_names.sort();
    let mod_rs = generate_mod_rs(&mod_names);
    let path = output_dir.join("mod.rs");
    crate::write_and_format(&path, &mod_rs).map_err(|e| format!("Failed to write {}: {e}", path.display()))?;

    Ok(())
}

// ─── Code Generation ─────────────────────────────────────────────────────────

/// Generate the full DTO module for one entity.
fn generate_dto_code(entity: &EntityDef) -> String {
    let entity_name = &entity.name;
    let create_fields = generate_create_fields(entity);
    let update_fields = generate_update_fields(entity);
    let default_fns = generate_default_fns(entity);

    format!(
        r#"//! Generated by ontogen. DO NOT EDIT.

use schemars::JsonSchema;
use serde::Deserialize;

/// Input for creating a new {entity_name}.
#[derive(Debug, Clone, Deserialize, JsonSchema, specta::Type)]
pub struct Create{entity_name}Input {{
{create_fields}
}}

/// Input for updating an existing {entity_name}.
/// All fields are optional; only provided fields are updated.
#[derive(Debug, Clone, Deserialize, JsonSchema, specta::Type)]
pub struct Update{entity_name}Input {{
{update_fields}
}}
{default_fns}"#
    )
}

/// Generate fields for CreateXInput.
fn generate_create_fields(entity: &EntityDef) -> String {
    let mut lines = Vec::new();

    for field in &entity.fields {
        if let Some(line) = generate_create_field(field) {
            lines.push(line);
        }
    }

    lines.join("\n")
}

/// Generate a single field for CreateXInput.
fn generate_create_field(field: &FieldDef) -> Option<String> {
    let name = &field.name;

    // Persistence-only fields are never in DTOs
    if name == "wikilinks" || name == "source_file" {
        return None;
    }

    // Skip fields ARE included in DTOs (they're schema-level data, just not in DB columns)
    // Relation fields (has_many, many_to_many) ARE included as Vec<String> for API input
    let rust_type = field_to_create_type(field);
    let serde_attr = generate_serde_default_attr(field);
    Some(format!("{serde_attr}    pub {name}: {rust_type},"))
}

/// Generate fields for UpdateXInput.
fn generate_update_fields(entity: &EntityDef) -> String {
    let mut lines = Vec::new();

    for field in &entity.fields {
        if let Some(line) = generate_update_field(field) {
            lines.push(line);
        }
    }

    lines.join("\n")
}

/// Generate a single field for UpdateXInput.
fn generate_update_field(field: &FieldDef) -> Option<String> {
    let name = &field.name;

    // Persistence-only fields are never in DTOs
    if name == "wikilinks" || name == "source_file" {
        return None;
    }

    match &field.role {
        // ID is not updatable
        FieldRole::Id => None,
        // Skip fields, relation fields ARE included (same as create)
        _ => {
            let inner_type = field_to_create_type(field);
            let rust_type = format!("Option<{inner_type}>");
            Some(format!("    #[serde(default)]\n    pub {name}: {rust_type},"))
        }
    }
}

/// Map a field to its Rust type for the Create DTO.
fn field_to_create_type(field: &FieldDef) -> String {
    match &field.field_type {
        FieldType::String => "String".to_string(),
        FieldType::OptionString => "Option<String>".to_string(),
        FieldType::I32 => "i32".to_string(),
        FieldType::OptionI32 => "Option<i32>".to_string(),
        FieldType::VecString => "Vec<String>".to_string(),
        FieldType::VecStruct(t) => format!("Vec<crate::schema::{t}>"),
        FieldType::OptionEnum(t) => format!("Option<{}>", qualify_type(t)),
        FieldType::Other(t) => qualify_type(t),
    }
}

/// Qualify a type with `crate::schema::` unless it's a primitive.
fn qualify_type(t: &str) -> String {
    match t {
        "u8" | "u16" | "u32" | "u64" | "u128" | "usize" | "i8" | "i16" | "i32" | "i64" | "i128" | "isize" | "f32"
        | "f64" | "bool" | "char" | "String" => t.to_string(),
        _ => format!("crate::schema::{t}"),
    }
}

/// Generate the `#[serde(default)]` or `#[serde(default = "fn_name")]` attribute for a Create field.
fn generate_serde_default_attr(field: &FieldDef) -> String {
    match &field.role {
        FieldRole::Id => String::new(),
        _ => {
            let needs_default = field.serde_default
                || matches!(
                    field.field_type,
                    FieldType::OptionString
                        | FieldType::OptionI32
                        | FieldType::OptionEnum(_)
                        | FieldType::VecString
                        | FieldType::VecStruct(_)
                );

            if field.default_value.is_some() {
                // Generate serde(default = "fn_name") pointing to an inline function
                let fn_name = format!("default_{}", field.name);
                format!("    #[serde(default = \"{fn_name}\")]\n",)
            } else if needs_default {
                "    #[serde(default)]\n".to_string()
            } else {
                String::new()
            }
        }
    }
}

/// Generate default value helper functions that serde(default = "fn_name") references.
fn generate_default_fns(entity: &EntityDef) -> String {
    let mut fns = String::new();
    for field in &entity.fields {
        if let Some(ref default_val) = field.default_value {
            let fn_name = format!("default_{}", field.name);
            let rust_type = field_to_create_type(field);
            fns.push_str(&format!("\nfn {fn_name}() -> {rust_type} {{\n    \"{default_val}\".to_string()\n}}\n"));
        }
    }
    fns
}

/// Generate the `mod.rs` re-exporting all DTO modules.
fn generate_mod_rs(mod_names: &[String]) -> String {
    let mut out = String::from("//! Generated by ontogen. DO NOT EDIT.\n\n");
    for name in mod_names {
        out.push_str(&format!("pub mod {name};\npub use {name}::*;\n"));
    }
    out
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schema::model::*;

    fn make_entity() -> EntityDef {
        EntityDef {
            name: "Agent".to_string(),
            directory: "agent".to_string(),
            table: "agents".to_string(),
            type_name: "agent".to_string(),
            prefix: "agent".to_string(),

            fields: vec![
                FieldDef {
                    name: "id".to_string(),
                    field_type: FieldType::String,
                    role: FieldRole::Id,
                    serde_default: false,
                    multiline_list: false,
                    default_value: None,
                },
                FieldDef {
                    name: "name".to_string(),
                    field_type: FieldType::String,
                    role: FieldRole::Plain,
                    serde_default: false,
                    multiline_list: false,
                    default_value: None,
                },
                FieldDef {
                    name: "agent_type".to_string(),
                    field_type: FieldType::OptionEnum("AgentType".to_string()),
                    role: FieldRole::EnumField,
                    serde_default: true,
                    multiline_list: false,
                    default_value: None,
                },
                FieldDef {
                    name: "capabilities".to_string(),
                    field_type: FieldType::VecString,
                    role: FieldRole::Plain,
                    serde_default: true,
                    multiline_list: false,
                    default_value: None,
                },
                FieldDef {
                    name: "body".to_string(),
                    field_type: FieldType::String,
                    role: FieldRole::Body,
                    serde_default: false,
                    multiline_list: false,
                    default_value: None,
                },
            ],
        }
    }

    #[test]
    fn create_dto_has_all_fields() {
        let code = generate_dto_code(&make_entity());

        assert!(code.contains("pub struct CreateAgentInput"));
        assert!(code.contains("pub id: String,"));
        assert!(code.contains("pub name: String,"));
        assert!(code.contains("pub agent_type: Option<crate::schema::AgentType>,"));
        assert!(code.contains("pub capabilities: Vec<String>,"));
        assert!(code.contains("pub body: String,"));
    }

    #[test]
    fn update_dto_wraps_in_option_and_excludes_id() {
        let code = generate_dto_code(&make_entity());

        assert!(code.contains("pub struct UpdateAgentInput"));
        // ID should NOT be in update
        assert!(!code.contains("pub id: Option<String>,"));
        // All other fields wrapped in Option
        assert!(code.contains("pub name: Option<String>,"));
        assert!(code.contains("pub agent_type: Option<Option<crate::schema::AgentType>>,"));
        assert!(code.contains("pub capabilities: Option<Vec<String>>,"));
        assert!(code.contains("pub body: Option<String>,"));
    }

    #[test]
    fn has_many_and_many_to_many_included() {
        let entity = EntityDef {
            name: "Node".to_string(),
            directory: "nodes".to_string(),
            table: "nodes".to_string(),
            type_name: "node".to_string(),
            prefix: "node".to_string(),

            fields: vec![
                FieldDef {
                    name: "id".to_string(),
                    field_type: FieldType::String,
                    role: FieldRole::Id,
                    serde_default: false,
                    multiline_list: false,
                    default_value: None,
                },
                FieldDef {
                    name: "contains".to_string(),
                    field_type: FieldType::VecString,
                    role: FieldRole::Relation(RelationInfo {
                        kind: RelationKind::HasMany,
                        target: "Node".to_string(),
                        junction: None,
                        foreign_key: Some("parent_id".to_string()),
                    }),
                    serde_default: true,
                    multiline_list: false,
                    default_value: None,
                },
                FieldDef {
                    name: "fulfills".to_string(),
                    field_type: FieldType::VecString,
                    role: FieldRole::Relation(RelationInfo {
                        kind: RelationKind::ManyToMany,
                        target: "Requirement".to_string(),
                        junction: None,
                        foreign_key: None,
                    }),
                    serde_default: true,
                    multiline_list: false,
                    default_value: None,
                },
                FieldDef {
                    name: "body".to_string(),
                    field_type: FieldType::String,
                    role: FieldRole::Body,
                    serde_default: false,
                    multiline_list: false,
                    default_value: None,
                },
            ],
        };

        let code = generate_dto_code(&entity);
        // Relation fields should be included in DTOs
        assert!(code.contains("contains"), "DTOs should include has_many relation fields");
        assert!(code.contains("fulfills"), "DTOs should include many_to_many relation fields");
    }

    #[test]
    fn skip_field_included() {
        let entity = EntityDef {
            name: "Contract".to_string(),
            directory: "contract".to_string(),
            table: "contracts".to_string(),
            type_name: "contract".to_string(),
            prefix: "contract".to_string(),

            fields: vec![
                FieldDef {
                    name: "id".to_string(),
                    field_type: FieldType::String,
                    role: FieldRole::Id,
                    serde_default: false,
                    multiline_list: false,
                    default_value: None,
                },
                FieldDef {
                    name: "states".to_string(),
                    field_type: FieldType::VecString,
                    role: FieldRole::Skip,
                    serde_default: true,
                    multiline_list: false,
                    default_value: None,
                },
                FieldDef {
                    name: "body".to_string(),
                    field_type: FieldType::String,
                    role: FieldRole::Body,
                    serde_default: false,
                    multiline_list: false,
                    default_value: None,
                },
            ],
        };

        let code = generate_dto_code(&entity);
        // Skip fields should be included in DTOs (they're schema-level data)
        assert!(code.contains("states"), "DTOs should include skip fields");
    }

    #[test]
    fn default_value_generates_serde_default_fn() {
        let entity = EntityDef {
            name: "Requirement".to_string(),
            directory: "requirements".to_string(),
            table: "requirements".to_string(),
            type_name: "requirement".to_string(),
            prefix: "req".to_string(),

            fields: vec![
                FieldDef {
                    name: "id".to_string(),
                    field_type: FieldType::String,
                    role: FieldRole::Id,
                    serde_default: false,
                    multiline_list: false,
                    default_value: None,
                },
                FieldDef {
                    name: "disposition".to_string(),
                    field_type: FieldType::String,
                    role: FieldRole::Plain,
                    serde_default: false,
                    multiline_list: false,
                    default_value: Some("active".to_string()),
                },
            ],
        };

        let code = generate_dto_code(&entity);
        assert!(code.contains(r#"#[serde(default = "default_disposition")]"#), "Should use named default fn");
        assert!(code.contains("fn default_disposition()"), "Should generate the default fn");
        assert!(code.contains(r#""active".to_string()"#), "Default fn should return the value");
    }

    #[test]
    fn no_wikilinks_or_source_file() {
        let schema_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../src-tauri/src/schema");
        if !schema_dir.exists() {
            eprintln!("Skipping: schema dir not found");
            return;
        }

        let entities = crate::schema::parse::parse_schema_dir(&schema_dir).expect("Failed to parse schema dir");

        let dir = std::env::temp_dir().join("ontology_codegen_test_dtos");
        let _ = std::fs::remove_dir_all(&dir);

        generate(&entities, &dir).expect("generate failed");

        // Check every generated DTO file
        for entry in std::fs::read_dir(&dir).unwrap() {
            let entry = entry.unwrap();
            let name = entry.file_name().to_string_lossy().to_string();
            if name == "mod.rs" {
                continue;
            }
            let code = std::fs::read_to_string(entry.path()).unwrap();
            assert!(!code.contains("wikilinks"), "{name} should not contain wikilinks");
            assert!(!code.contains("source_file"), "{name} should not contain source_file");
        }

        let _ = std::fs::remove_dir_all(&dir);
    }
}
