#![allow(dead_code, unused_imports, unused_variables, clippy::pedantic, clippy::needless_borrow)]
//! Auto-generated MCP tool registry. DO NOT EDIT.
//!
//! Generated by ontogen from API source files.

use std::future::Future;
use std::pin::Pin;

use schemars::JsonSchema;
use serde::Deserialize;
use serde_json::{Value, json};

use crate::AppState;
use crate::api::{bookmark, note, outline, section, tag, task};
use crate::schema::{
    Bookmark, BookmarkQuery, CreateBookmarkInput, CreateNoteInput, CreateSectionInput, CreateTagInput, CreateTaskInput,
    ListSectionsQuery, Note, Section, Tag, Task, TaskSummary, UpdateBookmarkInput, UpdateNoteInput, UpdateSectionInput,
    UpdateTagInput, UpdateTaskInput,
};
use crate::store::Store;

/// Async handler signature for MCP tools.
type HandlerFn =
    for<'a> fn(&'a AppState, &'a Value) -> Pin<Box<dyn Future<Output = Result<Value, String>> + Send + 'a>>;

/// A single MCP tool definition.
pub struct McpToolDef {
    pub name: &'static str,
    pub description: &'static str,
    pub schema_fn: fn() -> Value,
    pub handler: HandlerFn,
}

fn schema_for<T: JsonSchema>() -> Value {
    serde_json::to_value(schemars::schema_for!(T)).expect("schemars schema must serialize")
}

fn schema_for_with_str_id<T: JsonSchema>() -> Value {
    let mut schema = schema_for::<T>();
    if let Some(obj) = schema.as_object_mut() {
        if let Some(props) = obj.get_mut("properties").and_then(|p| p.as_object_mut()) {
            props.insert("id".to_string(), json!({"type": "string"}));
        }
        if let Some(req) = obj.get_mut("required").and_then(|r| r.as_array_mut()) {
            req.push(json!("id"));
        } else {
            obj.insert("required".to_string(), json!(["id"]));
        }
    }
    schema
}

#[allow(dead_code)]
fn schema_for_with_int_id<T: JsonSchema>() -> Value {
    let mut schema = schema_for::<T>();
    if let Some(obj) = schema.as_object_mut() {
        if let Some(props) = obj.get_mut("properties").and_then(|p| p.as_object_mut()) {
            props.insert("id".to_string(), json!({"type": "integer", "format": "int32"}));
        }
        if let Some(req) = obj.get_mut("required").and_then(|r| r.as_array_mut()) {
            req.push(json!("id"));
        } else {
            obj.insert("required".to_string(), json!(["id"]));
        }
    }
    schema
}

/// The string argument `key`: missing is one error, any other type another.
fn required_str<'a>(args: &'a Value, key: &str) -> Result<&'a str, String> {
    let value = args.get(key).ok_or_else(|| format!("Missing required parameter: {key}"))?;
    <&str>::deserialize(value).map_err(|e| format!("Invalid parameter {key}: {e}"))
}

/// `args` without the keys a tool reads on its own: the rest is the struct
/// it deserializes, which may refuse a field it does not declare.
fn args_without(args: &Value, keys: &[&str]) -> Value {
    let mut rest = args.clone();
    if let Some(rest) = rest.as_object_mut() {
        for key in keys {
            rest.remove(*key);
        }
    }
    rest
}

/// Refuses an argument the tool's input schema does not name, so a
/// misspelt filter is an error rather than a wider list.
fn refuse_unknown_args(args: &Value, schema: Value) -> Result<(), String> {
    let named = schema.get("properties").and_then(Value::as_object);
    let unknown =
        args.as_object().and_then(|args| args.keys().find(|key| !named.is_some_and(|n| n.contains_key(*key))));
    match unknown {
        Some(key) => Err(format!("Unknown argument: {key}")),
        None => Ok(()),
    }
}

/// Input for tools that look up a resource by string ID.
#[derive(Deserialize, JsonSchema)]
pub struct GetByIdInput {
    pub id: String,
}

/// Input for tools that operate on an integer id (i32).
#[derive(Deserialize, JsonSchema)]
pub struct ByIntIdInput {
    pub id: i32,
}

/// An empty-object schema for tools that take no parameters.
#[derive(Deserialize, JsonSchema)]
pub struct EmptyInput {}

/// Inject `limit` and `offset` pagination properties into a JSON schema.
fn with_pagination_schema(mut schema: Value) -> Value {
    if let Some(obj) = schema.as_object_mut() {
        let props = obj.entry("properties").or_insert_with(|| json!({}));
        if let Some(props_obj) = props.as_object_mut() {
            props_obj.insert(
                "limit".to_string(),
                json!({
                    "type": "integer",
                    "description": "Maximum number of items to return"
                }),
            );
            props_obj.insert(
                "offset".to_string(),
                json!({
                    "type": "integer",
                    "description": "Number of items to skip"
                }),
            );
        }
    }
    schema
}

/// The arguments of the `get_summary` tool.
#[derive(JsonSchema)]
pub struct OntogenTaskGetSummaryInput {
    pub status: String,
    pub verbose: Option<bool>,
    pub limit: Option<u32>,
}

/// The arguments of the `capture` tool.
#[derive(JsonSchema)]
pub struct OntogenTaskCaptureInput {
    pub input: CreateTaskInput,
    pub status: Option<String>,
}

/// The arguments of the `complete` tool.
#[derive(JsonSchema)]
pub struct OntogenTaskCompleteInput {
    pub id: String,
}

/// The arguments of the `set_state` tool.
#[derive(JsonSchema)]
pub struct OntogenTaskSetStateInput {
    pub id: String,
    pub state: String,
    pub store: Option<String>,
}

/// The arguments of the `list_tags` tool.
#[derive(JsonSchema)]
pub struct OntogenTaskListTagsInput {
    pub id: String,
}

/// The arguments of the `add_tag` tool.
#[derive(JsonSchema)]
pub struct OntogenTaskAddTagInput {
    pub id: String,
    pub tag_id: String,
}

/// The arguments of the `remove_tag` tool.
#[derive(JsonSchema)]
pub struct OntogenTaskRemoveTagInput {
    pub id: String,
    pub tag_id: String,
}

/// The arguments the `section` list tool reads as its filter.
#[derive(JsonSchema)]
pub struct OntogenSectionListFilter {
    pub parent_id: String,
    #[serde(flatten)]
    pub ontogen_query: ListSectionsQuery,
}

/// The arguments the `tag` list tool reads as its filter.
#[derive(JsonSchema)]
pub struct OntogenTagListFilter {
    pub title_prefix: Option<String>,
    pub min_title_len: Option<u32>,
}

/// The arguments the `outline` list tool reads as its filter.
#[derive(JsonSchema)]
pub struct OntogenOutlineListFilter {
    pub title_contains: Option<String>,
}

/// Generated MCP tool definitions.
pub fn generated_tool_registry() -> Vec<McpToolDef> {
    vec![
        McpToolDef {
            name: "bookmark_list",
            description: "One page of the bookmarks `query` selects, oldest first.",
            schema_fn: || with_pagination_schema(schema_for::<BookmarkQuery>()),
            handler: |ontogen_state, ontogen_args| {
                Box::pin(async move {
                    refuse_unknown_args(ontogen_args, with_pagination_schema(schema_for::<BookmarkQuery>()))?;
                    let ontogen_filter: BookmarkQuery =
                        serde_json::from_value(args_without(ontogen_args, &["limit", "offset"]))
                            .map_err(|e| format!("Invalid filter: {e}"))?;
                    let ontogen_limit = ontogen_args.get("limit").and_then(|v| v.as_u64()).unwrap_or(2).min(3);
                    let ontogen_offset = ontogen_args.get("offset").and_then(|v| v.as_u64()).unwrap_or(0);
                    let ontogen_items = bookmark::list(
                        ontogen_state,
                        ontogen_filter.clone(),
                        Some(ontogen_limit),
                        Some(ontogen_offset),
                    )
                    .await
                    .map_err(|e| e.to_string())?;
                    let ontogen_total =
                        bookmark::count(ontogen_state, ontogen_filter).await.map_err(|e| e.to_string())?;
                    Ok(json!({
                        "items": serde_json::to_value(&ontogen_items).map_err(|e| format!("Serialize error: {e}"))?,
                        "total": ontogen_total,
                        "limit": ontogen_limit,
                        "offset": ontogen_offset
                    }))
                })
            },
        },
        McpToolDef {
            name: "bookmark_get_by_id",
            description: "get_by_id bookmark",
            schema_fn: schema_for::<GetByIdInput>,
            handler: |ontogen_state, ontogen_args| {
                Box::pin(async move {
                    let id = required_str(ontogen_args, "id")?;
                    let item = bookmark::get_by_id(ontogen_state, id).await.map_err(|e| e.to_string())?;
                    serde_json::to_value(item).map_err(|e| format!("Serialize error: {e}"))
                })
            },
        },
        McpToolDef {
            name: "bookmark_create",
            description: "Save a bookmark under the next free `bm-{n}` id and publish it.",
            schema_fn: schema_for::<CreateBookmarkInput>,
            handler: |ontogen_state, ontogen_args| {
                Box::pin(async move {
                    let input: CreateBookmarkInput =
                        serde_json::from_value(ontogen_args.clone()).map_err(|e| format!("Invalid input: {e}"))?;
                    bookmark::create(ontogen_state, input).await.map_err(|e| e.to_string())?;
                    Ok(json!({"success": true}))
                })
            },
        },
        McpToolDef {
            name: "bookmark_update",
            description: "update bookmark",
            schema_fn: schema_for_with_str_id::<UpdateBookmarkInput>,
            handler: |ontogen_state, ontogen_args| {
                Box::pin(async move {
                    let id = required_str(ontogen_args, "id")?.to_string();
                    let input: UpdateBookmarkInput = serde_json::from_value(args_without(ontogen_args, &["id"]))
                        .map_err(|e| format!("Invalid input: {e}"))?;
                    bookmark::update(ontogen_state, &id, input).await.map_err(|e| e.to_string())?;
                    Ok(json!({"success": true}))
                })
            },
        },
        McpToolDef {
            name: "bookmark_delete",
            description: "delete bookmark",
            schema_fn: schema_for::<GetByIdInput>,
            handler: |ontogen_state, ontogen_args| {
                Box::pin(async move {
                    let id = required_str(ontogen_args, "id")?.to_string();
                    bookmark::delete(ontogen_state, &id).await.map_err(|e| e.to_string())?;
                    Ok(json!({"success": true}))
                })
            },
        },
        McpToolDef {
            name: "note_list",
            description: "One page of notes",
            schema_fn: || with_pagination_schema(schema_for::<EmptyInput>()),
            handler: |ontogen_state, ontogen_args| {
                Box::pin(async move {
                    refuse_unknown_args(ontogen_args, with_pagination_schema(schema_for::<EmptyInput>()))?;
                    let ontogen_store = ontogen_state.store().await.map_err(|e| e.to_string())?;
                    let ontogen_limit = ontogen_args.get("limit").and_then(|v| v.as_u64()).unwrap_or(2).min(3);
                    let ontogen_offset = ontogen_args.get("offset").and_then(|v| v.as_u64()).unwrap_or(0);
                    let ontogen_items = note::list(&ontogen_store, Some(ontogen_limit), Some(ontogen_offset))
                        .await
                        .map_err(|e| e.to_string())?;
                    let ontogen_total = note::count(&ontogen_store).await.map_err(|e| e.to_string())?;
                    Ok(json!({
                        "items": serde_json::to_value(&ontogen_items).map_err(|e| format!("Serialize error: {e}"))?,
                        "total": ontogen_total,
                        "limit": ontogen_limit,
                        "offset": ontogen_offset
                    }))
                })
            },
        },
        McpToolDef {
            name: "note_get_by_id",
            description: "Get a single note by ID",
            schema_fn: schema_for::<GetByIdInput>,
            handler: |ontogen_state, ontogen_args| {
                Box::pin(async move {
                    let ontogen_store = ontogen_state.store().await.map_err(|e| e.to_string())?;
                    let id = required_str(ontogen_args, "id")?;
                    let item = note::get_by_id(&ontogen_store, id).await.map_err(|e| e.to_string())?;
                    serde_json::to_value(item).map_err(|e| format!("Serialize error: {e}"))
                })
            },
        },
        McpToolDef {
            name: "note_create",
            description: "Create a new note",
            schema_fn: schema_for::<CreateNoteInput>,
            handler: |ontogen_state, ontogen_args| {
                Box::pin(async move {
                    let ontogen_store = ontogen_state.store().await.map_err(|e| e.to_string())?;
                    let input: CreateNoteInput =
                        serde_json::from_value(ontogen_args.clone()).map_err(|e| format!("Invalid input: {e}"))?;
                    note::create(&ontogen_store, input).await.map_err(|e| e.to_string())?;
                    Ok(json!({"success": true}))
                })
            },
        },
        McpToolDef {
            name: "note_update",
            description: "Update an existing note",
            schema_fn: schema_for_with_str_id::<UpdateNoteInput>,
            handler: |ontogen_state, ontogen_args| {
                Box::pin(async move {
                    let ontogen_store = ontogen_state.store().await.map_err(|e| e.to_string())?;
                    let id = required_str(ontogen_args, "id")?.to_string();
                    let input: UpdateNoteInput = serde_json::from_value(args_without(ontogen_args, &["id"]))
                        .map_err(|e| format!("Invalid input: {e}"))?;
                    note::update(&ontogen_store, &id, input).await.map_err(|e| e.to_string())?;
                    Ok(json!({"success": true}))
                })
            },
        },
        McpToolDef {
            name: "note_delete",
            description: "Delete a note by ID",
            schema_fn: schema_for::<GetByIdInput>,
            handler: |ontogen_state, ontogen_args| {
                Box::pin(async move {
                    let ontogen_store = ontogen_state.store().await.map_err(|e| e.to_string())?;
                    let id = required_str(ontogen_args, "id")?.to_string();
                    note::delete(&ontogen_store, &id).await.map_err(|e| e.to_string())?;
                    Ok(json!({"success": true}))
                })
            },
        },
        McpToolDef {
            name: "section_get_by_id",
            description: "Get a single section by ID",
            schema_fn: schema_for::<GetByIdInput>,
            handler: |ontogen_state, ontogen_args| {
                Box::pin(async move {
                    let ontogen_store = ontogen_state.store().await.map_err(|e| e.to_string())?;
                    let id = required_str(ontogen_args, "id")?;
                    let item = section::get_by_id(&ontogen_store, id).await.map_err(|e| e.to_string())?;
                    serde_json::to_value(item).map_err(|e| format!("Serialize error: {e}"))
                })
            },
        },
        McpToolDef {
            name: "section_create",
            description: "Create a new section",
            schema_fn: schema_for::<CreateSectionInput>,
            handler: |ontogen_state, ontogen_args| {
                Box::pin(async move {
                    let ontogen_store = ontogen_state.store().await.map_err(|e| e.to_string())?;
                    let input: CreateSectionInput =
                        serde_json::from_value(ontogen_args.clone()).map_err(|e| format!("Invalid input: {e}"))?;
                    section::create(&ontogen_store, input).await.map_err(|e| e.to_string())?;
                    Ok(json!({"success": true}))
                })
            },
        },
        McpToolDef {
            name: "section_update",
            description: "Update an existing section",
            schema_fn: schema_for_with_str_id::<UpdateSectionInput>,
            handler: |ontogen_state, ontogen_args| {
                Box::pin(async move {
                    let ontogen_store = ontogen_state.store().await.map_err(|e| e.to_string())?;
                    let id = required_str(ontogen_args, "id")?.to_string();
                    let input: UpdateSectionInput = serde_json::from_value(args_without(ontogen_args, &["id"]))
                        .map_err(|e| format!("Invalid input: {e}"))?;
                    section::update(&ontogen_store, &id, input).await.map_err(|e| e.to_string())?;
                    Ok(json!({"success": true}))
                })
            },
        },
        McpToolDef {
            name: "section_delete",
            description: "Delete a section by ID",
            schema_fn: schema_for::<GetByIdInput>,
            handler: |ontogen_state, ontogen_args| {
                Box::pin(async move {
                    let ontogen_store = ontogen_state.store().await.map_err(|e| e.to_string())?;
                    let id = required_str(ontogen_args, "id")?.to_string();
                    section::delete(&ontogen_store, &id).await.map_err(|e| e.to_string())?;
                    Ok(json!({"success": true}))
                })
            },
        },
        McpToolDef {
            name: "section_list",
            description: "One page of the sections under `parent_id` that `query` selects.",
            schema_fn: || with_pagination_schema(schema_for::<OntogenSectionListFilter>()),
            handler: |ontogen_state, ontogen_args| {
                Box::pin(async move {
                    refuse_unknown_args(
                        ontogen_args,
                        with_pagination_schema(schema_for::<OntogenSectionListFilter>()),
                    )?;
                    let ontogen_filter: ListSectionsQuery =
                        serde_json::from_value(args_without(ontogen_args, &["parent_id", "limit", "offset"]))
                            .map_err(|e| format!("Invalid filter: {e}"))?;
                    let parent_id = required_str(ontogen_args, "parent_id")?;
                    let ontogen_store = ontogen_state.store().await.map_err(|e| e.to_string())?;
                    let ontogen_limit = ontogen_args.get("limit").and_then(|v| v.as_u64()).unwrap_or(2).min(3);
                    let ontogen_offset = ontogen_args.get("offset").and_then(|v| v.as_u64()).unwrap_or(0);
                    let ontogen_items = section::list(
                        &ontogen_store,
                        ontogen_filter.clone(),
                        parent_id,
                        Some(ontogen_limit),
                        Some(ontogen_offset),
                    )
                    .await
                    .map_err(|e| e.to_string())?;
                    let ontogen_total =
                        section::count(&ontogen_store, ontogen_filter, parent_id).await.map_err(|e| e.to_string())?;
                    Ok(json!({
                        "items": serde_json::to_value(&ontogen_items).map_err(|e| format!("Serialize error: {e}"))?,
                        "total": ontogen_total,
                        "limit": ontogen_limit,
                        "offset": ontogen_offset
                    }))
                })
            },
        },
        McpToolDef {
            name: "tag_get_by_id",
            description: "Get a single tag by ID",
            schema_fn: schema_for::<GetByIdInput>,
            handler: |ontogen_state, ontogen_args| {
                Box::pin(async move {
                    let ontogen_store = ontogen_state.store().await.map_err(|e| e.to_string())?;
                    let id = required_str(ontogen_args, "id")?;
                    let item = tag::get_by_id(&ontogen_store, id).await.map_err(|e| e.to_string())?;
                    serde_json::to_value(item).map_err(|e| format!("Serialize error: {e}"))
                })
            },
        },
        McpToolDef {
            name: "tag_create",
            description: "Create a new tag",
            schema_fn: schema_for::<CreateTagInput>,
            handler: |ontogen_state, ontogen_args| {
                Box::pin(async move {
                    let ontogen_store = ontogen_state.store().await.map_err(|e| e.to_string())?;
                    let input: CreateTagInput =
                        serde_json::from_value(ontogen_args.clone()).map_err(|e| format!("Invalid input: {e}"))?;
                    tag::create(&ontogen_store, input).await.map_err(|e| e.to_string())?;
                    Ok(json!({"success": true}))
                })
            },
        },
        McpToolDef {
            name: "tag_update",
            description: "Update an existing tag",
            schema_fn: schema_for_with_str_id::<UpdateTagInput>,
            handler: |ontogen_state, ontogen_args| {
                Box::pin(async move {
                    let ontogen_store = ontogen_state.store().await.map_err(|e| e.to_string())?;
                    let id = required_str(ontogen_args, "id")?.to_string();
                    let input: UpdateTagInput = serde_json::from_value(args_without(ontogen_args, &["id"]))
                        .map_err(|e| format!("Invalid input: {e}"))?;
                    tag::update(&ontogen_store, &id, input).await.map_err(|e| e.to_string())?;
                    Ok(json!({"success": true}))
                })
            },
        },
        McpToolDef {
            name: "tag_delete",
            description: "Delete a tag by ID",
            schema_fn: schema_for::<GetByIdInput>,
            handler: |ontogen_state, ontogen_args| {
                Box::pin(async move {
                    let ontogen_store = ontogen_state.store().await.map_err(|e| e.to_string())?;
                    let id = required_str(ontogen_args, "id")?.to_string();
                    tag::delete(&ontogen_store, &id).await.map_err(|e| e.to_string())?;
                    Ok(json!({"success": true}))
                })
            },
        },
        McpToolDef {
            name: "tag_list",
            description: "One page of the tags whose title starts with `title_prefix` and is at least `min_title_len` characters long.",
            schema_fn: || with_pagination_schema(schema_for::<OntogenTagListFilter>()),
            handler: |ontogen_state, ontogen_args| {
                Box::pin(async move {
                    refuse_unknown_args(ontogen_args, with_pagination_schema(schema_for::<OntogenTagListFilter>()))?;
                    let title_prefix: Option<String> = ontogen_args
                        .get("title_prefix")
                        .filter(|v| !v.is_null())
                        .cloned()
                        .map(serde_json::from_value::<String>)
                        .transpose()
                        .map_err(|e| format!("Invalid parameter title_prefix: {e}"))?;
                    let min_title_len: Option<u32> = ontogen_args
                        .get("min_title_len")
                        .filter(|v| !v.is_null())
                        .cloned()
                        .map(serde_json::from_value::<u32>)
                        .transpose()
                        .map_err(|e| format!("Invalid parameter min_title_len: {e}"))?;
                    let ontogen_store = ontogen_state.store().await.map_err(|e| e.to_string())?;
                    let ontogen_limit = ontogen_args.get("limit").and_then(|v| v.as_u64()).unwrap_or(2).min(3);
                    let ontogen_offset = ontogen_args.get("offset").and_then(|v| v.as_u64()).unwrap_or(0);
                    let ontogen_items = tag::list(
                        &ontogen_store,
                        title_prefix.as_deref(),
                        min_title_len,
                        Some(ontogen_limit),
                        Some(ontogen_offset),
                    )
                    .await
                    .map_err(|e| e.to_string())?;
                    let ontogen_total = tag::count(&ontogen_store, title_prefix.as_deref(), min_title_len)
                        .await
                        .map_err(|e| e.to_string())?;
                    Ok(json!({
                        "items": serde_json::to_value(&ontogen_items).map_err(|e| format!("Serialize error: {e}"))?,
                        "total": ontogen_total,
                        "limit": ontogen_limit,
                        "offset": ontogen_offset
                    }))
                })
            },
        },
        McpToolDef {
            name: "task_list",
            description: "One page of tasks",
            schema_fn: || with_pagination_schema(schema_for::<EmptyInput>()),
            handler: |ontogen_state, ontogen_args| {
                Box::pin(async move {
                    refuse_unknown_args(ontogen_args, with_pagination_schema(schema_for::<EmptyInput>()))?;
                    let ontogen_store = ontogen_state.store().await.map_err(|e| e.to_string())?;
                    let ontogen_limit = ontogen_args.get("limit").and_then(|v| v.as_u64()).unwrap_or(2).min(3);
                    let ontogen_offset = ontogen_args.get("offset").and_then(|v| v.as_u64()).unwrap_or(0);
                    let ontogen_items = task::list(&ontogen_store, Some(ontogen_limit), Some(ontogen_offset))
                        .await
                        .map_err(|e| e.to_string())?;
                    let ontogen_total = task::count(&ontogen_store).await.map_err(|e| e.to_string())?;
                    Ok(json!({
                        "items": serde_json::to_value(&ontogen_items).map_err(|e| format!("Serialize error: {e}"))?,
                        "total": ontogen_total,
                        "limit": ontogen_limit,
                        "offset": ontogen_offset
                    }))
                })
            },
        },
        McpToolDef {
            name: "task_get_by_id",
            description: "Get a single task by ID",
            schema_fn: schema_for::<GetByIdInput>,
            handler: |ontogen_state, ontogen_args| {
                Box::pin(async move {
                    let ontogen_store = ontogen_state.store().await.map_err(|e| e.to_string())?;
                    let id = required_str(ontogen_args, "id")?;
                    let item = task::get_by_id(&ontogen_store, id).await.map_err(|e| e.to_string())?;
                    serde_json::to_value(item).map_err(|e| format!("Serialize error: {e}"))
                })
            },
        },
        McpToolDef {
            name: "task_create",
            description: "Create a new task",
            schema_fn: schema_for::<CreateTaskInput>,
            handler: |ontogen_state, ontogen_args| {
                Box::pin(async move {
                    let ontogen_store = ontogen_state.store().await.map_err(|e| e.to_string())?;
                    let input: CreateTaskInput =
                        serde_json::from_value(ontogen_args.clone()).map_err(|e| format!("Invalid input: {e}"))?;
                    task::create(&ontogen_store, input).await.map_err(|e| e.to_string())?;
                    Ok(json!({"success": true}))
                })
            },
        },
        McpToolDef {
            name: "task_update",
            description: "Update an existing task",
            schema_fn: schema_for_with_str_id::<UpdateTaskInput>,
            handler: |ontogen_state, ontogen_args| {
                Box::pin(async move {
                    let ontogen_store = ontogen_state.store().await.map_err(|e| e.to_string())?;
                    let id = required_str(ontogen_args, "id")?.to_string();
                    let input: UpdateTaskInput = serde_json::from_value(args_without(ontogen_args, &["id"]))
                        .map_err(|e| format!("Invalid input: {e}"))?;
                    task::update(&ontogen_store, &id, input).await.map_err(|e| e.to_string())?;
                    Ok(json!({"success": true}))
                })
            },
        },
        McpToolDef {
            name: "task_delete",
            description: "Delete a task by ID",
            schema_fn: schema_for::<GetByIdInput>,
            handler: |ontogen_state, ontogen_args| {
                Box::pin(async move {
                    let ontogen_store = ontogen_state.store().await.map_err(|e| e.to_string())?;
                    let id = required_str(ontogen_args, "id")?.to_string();
                    task::delete(&ontogen_store, &id).await.map_err(|e| e.to_string())?;
                    Ok(json!({"success": true}))
                })
            },
        },
        McpToolDef {
            name: "task_get_summary",
            description: "The tasks in `status`, counted, with their titles when `verbose`. `limit` caps the titles.",
            schema_fn: schema_for::<OntogenTaskGetSummaryInput>,
            handler: |ontogen_state, ontogen_args| {
                Box::pin(async move {
                    let status = required_str(ontogen_args, "status")?;
                    let verbose: Option<bool> = ontogen_args
                        .get("verbose")
                        .filter(|v| !v.is_null())
                        .cloned()
                        .map(serde_json::from_value::<bool>)
                        .transpose()
                        .map_err(|e| format!("Invalid parameter verbose: {e}"))?;
                    let limit: Option<u32> = ontogen_args
                        .get("limit")
                        .filter(|v| !v.is_null())
                        .cloned()
                        .map(serde_json::from_value::<u32>)
                        .transpose()
                        .map_err(|e| format!("Invalid parameter limit: {e}"))?;
                    let ontogen_store = ontogen_state.store().await.map_err(|e| e.to_string())?;
                    let ontogen_result =
                        task::get_summary(&ontogen_store, status, verbose, limit).await.map_err(|e| e.to_string())?;
                    serde_json::to_value(ontogen_result).map_err(|e| format!("Serialize error: {e}"))
                })
            },
        },
        McpToolDef {
            name: "task_capture",
            description: "Create a task, filed under `status` when given instead of the input's own.",
            schema_fn: schema_for::<OntogenTaskCaptureInput>,
            handler: |ontogen_state, ontogen_args| {
                Box::pin(async move {
                    let input: CreateTaskInput = serde_json::from_value(
                        ontogen_args.get("input").cloned().ok_or("Missing required parameter: input")?,
                    )
                    .map_err(|e| format!("Invalid parameter input: {e}"))?;
                    let status: Option<String> = ontogen_args
                        .get("status")
                        .filter(|v| !v.is_null())
                        .cloned()
                        .map(serde_json::from_value::<String>)
                        .transpose()
                        .map_err(|e| format!("Invalid parameter status: {e}"))?;
                    let ontogen_store = ontogen_state.store().await.map_err(|e| e.to_string())?;
                    let ontogen_result =
                        task::capture(&ontogen_store, input, status).await.map_err(|e| e.to_string())?;
                    serde_json::to_value(ontogen_result).map_err(|e| format!("Serialize error: {e}"))
                })
            },
        },
        McpToolDef {
            name: "task_complete",
            description: "Mark a task done.",
            schema_fn: schema_for::<OntogenTaskCompleteInput>,
            handler: |ontogen_state, ontogen_args| {
                Box::pin(async move {
                    let id = required_str(ontogen_args, "id")?;
                    let ontogen_store = ontogen_state.store().await.map_err(|e| e.to_string())?;
                    task::complete(&ontogen_store, id).await.map_err(|e| e.to_string())?;
                    Ok(json!({"success": true}))
                })
            },
        },
        McpToolDef {
            name: "task_set_state",
            description: "File a task under `state`, retitled `store` when given. The arguments are named like the bindings of a generated handler, which must still tell them apart.",
            schema_fn: schema_for::<OntogenTaskSetStateInput>,
            handler: |ontogen_state, ontogen_args| {
                Box::pin(async move {
                    let id = required_str(ontogen_args, "id")?;
                    let state: String = serde_json::from_value(
                        ontogen_args.get("state").cloned().ok_or("Missing required parameter: state")?,
                    )
                    .map_err(|e| format!("Invalid parameter state: {e}"))?;
                    let store: Option<String> = ontogen_args
                        .get("store")
                        .filter(|v| !v.is_null())
                        .cloned()
                        .map(serde_json::from_value::<String>)
                        .transpose()
                        .map_err(|e| format!("Invalid parameter store: {e}"))?;
                    let ontogen_store = ontogen_state.store().await.map_err(|e| e.to_string())?;
                    let ontogen_result =
                        task::set_state(&ontogen_store, id, state, store).await.map_err(|e| e.to_string())?;
                    serde_json::to_value(ontogen_result).map_err(|e| format!("Serialize error: {e}"))
                })
            },
        },
        McpToolDef {
            name: "task_purge_done",
            description: "Delete every done task, answering how many went.",
            schema_fn: schema_for::<EmptyInput>,
            handler: |ontogen_state, ontogen_args| {
                Box::pin(async move {
                    let ontogen_store = ontogen_state.store().await.map_err(|e| e.to_string())?;
                    let ontogen_result = task::purge_done(&ontogen_store).await.map_err(|e| e.to_string())?;
                    serde_json::to_value(ontogen_result).map_err(|e| format!("Serialize error: {e}"))
                })
            },
        },
        McpToolDef {
            name: "task_list_tags",
            description: "A task's tags, in the order the task lists them.",
            schema_fn: || with_pagination_schema(schema_for::<OntogenTaskListTagsInput>()),
            handler: |ontogen_state, ontogen_args| {
                Box::pin(async move {
                    let id = required_str(ontogen_args, "id")?;
                    let ontogen_store = ontogen_state.store().await.map_err(|e| e.to_string())?;
                    let ontogen_all = task::list_tags(&ontogen_store, id).await.map_err(|e| e.to_string())?;
                    let ontogen_total = ontogen_all.len();
                    let ontogen_limit = ontogen_args
                        .get("limit")
                        .and_then(|v| v.as_u64())
                        .map(|v| v as usize)
                        .unwrap_or(2_usize)
                        .min(3_usize);
                    let ontogen_offset =
                        ontogen_args.get("offset").and_then(|v| v.as_u64()).map(|v| v as usize).unwrap_or(0);
                    let ontogen_items: Vec<_> =
                        ontogen_all.into_iter().skip(ontogen_offset).take(ontogen_limit).collect();
                    Ok(json!({
                        "items": serde_json::to_value(&ontogen_items).map_err(|e| format!("Serialize error: {e}"))?,
                        "total": ontogen_total,
                        "limit": ontogen_limit,
                        "offset": ontogen_offset
                    }))
                })
            },
        },
        McpToolDef {
            name: "task_add_tag",
            description: "Tag a task. Tagging it twice changes nothing.",
            schema_fn: schema_for::<OntogenTaskAddTagInput>,
            handler: |ontogen_state, ontogen_args| {
                Box::pin(async move {
                    let id = required_str(ontogen_args, "id")?;
                    let tag_id = required_str(ontogen_args, "tag_id")?;
                    let ontogen_store = ontogen_state.store().await.map_err(|e| e.to_string())?;
                    task::add_tag(&ontogen_store, id, tag_id).await.map_err(|e| e.to_string())?;
                    Ok(json!({"success": true}))
                })
            },
        },
        McpToolDef {
            name: "task_remove_tag",
            description: "Untag a task.",
            schema_fn: schema_for::<OntogenTaskRemoveTagInput>,
            handler: |ontogen_state, ontogen_args| {
                Box::pin(async move {
                    let id = required_str(ontogen_args, "id")?;
                    let tag_id = required_str(ontogen_args, "tag_id")?;
                    let ontogen_store = ontogen_state.store().await.map_err(|e| e.to_string())?;
                    task::remove_tag(&ontogen_store, id, tag_id).await.map_err(|e| e.to_string())?;
                    Ok(json!({"success": true}))
                })
            },
        },
        McpToolDef {
            name: "outline_list",
            description: "One page of the sections whose title contains `title_contains`.",
            schema_fn: || with_pagination_schema(schema_for::<OntogenOutlineListFilter>()),
            handler: |ontogen_state, ontogen_args| {
                Box::pin(async move {
                    refuse_unknown_args(
                        ontogen_args,
                        with_pagination_schema(schema_for::<OntogenOutlineListFilter>()),
                    )?;
                    let title_contains: Option<String> = ontogen_args
                        .get("title_contains")
                        .filter(|v| !v.is_null())
                        .cloned()
                        .map(serde_json::from_value::<String>)
                        .transpose()
                        .map_err(|e| format!("Invalid parameter title_contains: {e}"))?;
                    let ontogen_store = ontogen_state.store().await.map_err(|e| e.to_string())?;
                    let ontogen_limit = ontogen_args.get("limit").and_then(|v| v.as_u64()).unwrap_or(2).min(3);
                    let ontogen_offset = ontogen_args.get("offset").and_then(|v| v.as_u64()).unwrap_or(0);
                    let ontogen_items = outline::list(
                        &ontogen_store,
                        title_contains.clone(),
                        Some(ontogen_limit),
                        Some(ontogen_offset),
                    )
                    .await
                    .map_err(|e| e.to_string())?;
                    let ontogen_total =
                        outline::count(&ontogen_store, title_contains).await.map_err(|e| e.to_string())?;
                    Ok(json!({
                        "items": serde_json::to_value(&ontogen_items).map_err(|e| format!("Serialize error: {e}"))?,
                        "total": ontogen_total,
                        "limit": ontogen_limit,
                        "offset": ontogen_offset
                    }))
                })
            },
        },
    ]
}

/// Simple tool definition with pre-computed schema (for MCP protocol responses).
pub struct SimpleToolDef {
    pub name: &'static str,
    pub description: &'static str,
    pub input_schema: Value,
}

/// Return tool definitions with pre-computed input schemas.
/// Use this for building MCP `tools/list` responses.
pub fn tool_definitions() -> Vec<SimpleToolDef> {
    generated_tool_registry()
        .into_iter()
        .map(|t| SimpleToolDef { name: t.name, description: t.description, input_schema: (t.schema_fn)() })
        .collect()
}

/// Dispatch a tool call by name, executing the matching handler synchronously.
///
/// This creates a minimal tokio runtime to drive the async handler.
/// Suitable for MCP servers that process requests synchronously.
pub fn handle_tool_call(
    state: &AppState,
    tool_name: &str,
    args: &serde_json::Map<String, Value>,
) -> Result<Value, String> {
    let registry = generated_tool_registry();
    let tool = registry.iter().find(|t| t.name == tool_name).ok_or_else(|| format!("Unknown tool: {tool_name}"))?;
    let args_value = Value::Object(args.clone());
    let rt = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .map_err(|e| format!("Runtime error: {e}"))?;
    rt.block_on((tool.handler)(state, &args_value))
}
