export default defineNuxtConfig({
  // @ontogen/admin-layer
  // Provides a generic CRUD admin interface for ontogen-powered apps.
  // Requires the consuming app to provide:
  //   - useTransport() composable returning a Transport interface
  //   - useAdminProjectId() composable returning Ref<string | undefined>
  //   - admin-registry.ts (generated by ontogen)
  //   - admin-fields.ts (generated by ontogen, customizable via overrides)
})
