import { fileURLToPath } from 'node:url'
import { dirname, join } from 'pathe'

const layerDir = dirname(fileURLToPath(import.meta.url))

export default defineNuxtConfig({
  // @ontogen/admin-layer
  // Provides a generic CRUD admin interface for ontogen-powered apps.
  //
  // Requirements:
  //   1. extends: ['@ontogen/admin-layer'] in consuming app's nuxt.config.ts
  //   2. app/admin/generated/admin-registry.ts (generated by ontogen AdminRegistry),
  //      or another path named in `ontogenAdmin.registry`
  //   3. useTransport() composable in consuming app (returns Transport with CRUD methods)
  //
  // Optional: provide ADMIN_DETAIL_LINK (app/composables/useAdminDetailLink.ts)
  // to link a detail page out to the host's own page for that row.
  modules: [join(layerDir, 'modules/admin')],
})
