import { fileURLToPath } from 'node:url'
import { dirname, join } from 'pathe'

const layerDir = dirname(fileURLToPath(import.meta.url))

export default defineNuxtConfig({
  // @ontogen/admin-layer
  // Provides a generic CRUD admin interface for ontogen-powered apps.
  //
  // Requirements:
  //   1. extends: ['path/to/nuxt_admin_layer'] in consuming app's nuxt.config.ts
  //   2. app/admin/generated/admin-registry.ts (generated by ontogen AdminRegistry)
  //   3. useTransport() composable in consuming app (returns Transport with CRUD methods)
  modules: [join(layerDir, 'modules/admin')],
})
