//! Generate DB ↔ Schema conversion code from parsed ontology entity definitions.
//!
//! For each entity, generates:
//! - `from_model()` - converts SeaORM Model → schema type
//! - `to_active_model()` - converts schema type → SeaORM ActiveModel
//!
//! Both return `Result<_, AppError>`: an integer primitive is stored in an
//! `i64` column, and a value that does not fit the other side fails with
//! `AppError::DbError` naming the field instead of wrapping.
//!
//! Generated code is written to `conversions/generated/{entity}.rs` and a `mod.rs`
//! re-exporting all modules.

use std::fs;
use std::path::Path;

use crate::persistence::seaorm::gen_entity::{is_integer_primitive, to_snake_case, widens_to_i64_losslessly};
use crate::schema::model::{EntityDef, FieldDef, FieldRole, FieldType, RelationKind};

// ─── Public API ──────────────────────────────────────────────────────────────

/// Generate conversion modules and write them to the output directory.
///
/// Entities whose names appear in `skip` are still generated as files (for reference)
/// but excluded from `mod.rs` to avoid duplicate `impl` conflicts with hand-written code.
pub fn generate(entities: &[EntityDef], output_dir: &Path, skip: &[String]) -> Result<(), String> {
    fs::create_dir_all(output_dir).map_err(|e| format!("Failed to create output dir {}: {e}", output_dir.display()))?;

    // Clean stale files from previous entity names
    let expected: std::collections::HashSet<String> = entities
        .iter()
        .map(|e| format!("{}.rs", to_snake_case(&e.name)))
        .chain(std::iter::once("mod.rs".to_string()))
        .collect();
    crate::clean_generated_dir(output_dir, &expected);

    let mut mod_names: Vec<String> = Vec::new();

    for entity in entities {
        let mod_name = to_snake_case(&entity.name);
        let code = generate_conversion_code(entity);
        let path = output_dir.join(format!("{mod_name}.rs"));
        crate::write_and_format(&path, &code).map_err(|e| format!("Failed to write {}: {e}", path.display()))?;
        if !skip.contains(&entity.name) {
            mod_names.push(mod_name);
        }
    }

    // Write mod.rs
    mod_names.sort();
    let mod_rs = generate_mod_rs(&mod_names);
    let path = output_dir.join("mod.rs");
    crate::write_and_format(&path, &mod_rs).map_err(|e| format!("Failed to write {}: {e}", path.display()))?;

    Ok(())
}

// ─── Code Generation ─────────────────────────────────────────────────────────

/// Generate the full conversion module for one entity.
pub(crate) fn generate_conversion_code(entity: &EntityDef) -> String {
    let entity_name = &entity.name;
    let mod_name = to_snake_case(entity_name);

    let from_model_fields = generate_from_model_fields(entity);
    let to_active_model_fields = generate_to_active_model_fields(entity);

    let needs_decode_json_vec = entity_needs_decode_json_vec(entity);
    let needs_enum_to_string = entity_needs_enum_to_string(entity);

    let helper_import = match (needs_decode_json_vec, needs_enum_to_string) {
        (true, true) => "\nuse crate::persistence::db::conversions::{decode_json_vec, enum_to_string};".to_string(),
        (true, false) => "\nuse crate::persistence::db::conversions::decode_json_vec;".to_string(),
        (false, true) => "\nuse crate::persistence::db::conversions::enum_to_string;".to_string(),
        (false, false) => String::new(),
    };

    format!(
        r#"//! Generated by ontogen. DO NOT EDIT.
{helper_import}
use crate::persistence::db::entities::{mod_name} as entity;
use crate::schema::{{AppError, {entity_name}}};

impl {entity_name} {{
    pub fn from_model(model: &entity::Model) -> Result<Self, AppError> {{
        Ok(Self {{
{from_model_fields}
        }})
    }}

    pub fn to_active_model(&self) -> Result<entity::ActiveModel, AppError> {{
        use sea_orm::Set;

        Ok(entity::ActiveModel {{
{to_active_model_fields}
        }})
    }}
}}
"#
    )
}

/// Check if any field in the entity needs `decode_json_vec` (VecString in from_model).
fn entity_needs_decode_json_vec(entity: &EntityDef) -> bool {
    entity.fields.iter().any(|f| {
        // Skip fields treated as plain, so check both Skip+VecString and Plain+VecString
        matches!(
            (&f.role, &f.field_type),
            (FieldRole::Plain, FieldType::VecString) | (FieldRole::Skip, FieldType::VecString)
        )
    })
}

/// Check if any field in the entity needs `enum_to_string` (EnumField or non-integer OptionEnum in to_active_model).
fn entity_needs_enum_to_string(entity: &EntityDef) -> bool {
    entity.fields.iter().any(|f| !is_integer_field(f) && is_enum_to_string_field(f))
}

fn is_enum_to_string_field(field: &FieldDef) -> bool {
    matches!(&field.role, FieldRole::EnumField)
        || matches!((&field.role, &field.field_type), (FieldRole::Plain | FieldRole::Skip, FieldType::OptionEnum(_)))
}

/// A plain, skip or enum-role field whose type is an integer primitive the
/// parser filed under `OptionEnum` / `Other`, stored in an `i64` column.
fn is_integer_field(field: &FieldDef) -> bool {
    matches!(field.role, FieldRole::Plain | FieldRole::Skip | FieldRole::EnumField)
        && matches!(&field.field_type, FieldType::OptionEnum(t) | FieldType::Other(t) if is_integer_primitive(t))
}

/// `from_model` assignment for an [`is_integer_field`]: the stored `i64`
/// converts back with `T::try_from`, so a value outside `T` fails the read
/// instead of wrapping.
fn integer_from_model_field(entity_name: &str, field: &FieldDef) -> String {
    let name = &field.name;
    match &field.field_type {
        FieldType::Other(t) | FieldType::OptionEnum(t) if t == "i64" => format!("{name}: model.{name},"),
        FieldType::Other(t) => format!(
            r#"{name}: {t}::try_from(model.{name}).map_err(|_| AppError::DbError(format!("{entity_name}.{name}: stored value {{}} is out of range for {t}", model.{name})))?,"#
        ),
        FieldType::OptionEnum(t) => format!(
            r#"{name}: model.{name}.map(|v| {t}::try_from(v).map_err(|_| AppError::DbError(format!("{entity_name}.{name}: stored value {{v}} is out of range for {t}")))).transpose()?,"#
        ),
        other => unreachable!("not an integer field: {other:?}"),
    }
}

/// `to_active_model` assignment for an [`is_integer_field`]: lossless types
/// widen with `i64::from`; the rest use `i64::try_from` and fail the write
/// rather than wrap.
fn integer_to_active_model_field(entity_name: &str, field: &FieldDef) -> String {
    let name = &field.name;
    match &field.field_type {
        FieldType::Other(t) | FieldType::OptionEnum(t) if t == "i64" => format!("{name}: Set(self.{name}),"),
        FieldType::Other(t) if widens_to_i64_losslessly(t) => format!("{name}: Set(i64::from(self.{name})),"),
        FieldType::OptionEnum(t) if widens_to_i64_losslessly(t) => format!("{name}: Set(self.{name}.map(i64::from)),"),
        FieldType::Other(_) => format!(
            r#"{name}: Set(i64::try_from(self.{name}).map_err(|_| AppError::DbError(format!("{entity_name}.{name}: value {{}} is out of range for i64", self.{name})))?),"#
        ),
        FieldType::OptionEnum(_) => format!(
            r#"{name}: Set(self.{name}.map(|v| i64::try_from(v).map_err(|_| AppError::DbError(format!("{entity_name}.{name}: value {{v}} is out of range for i64")))).transpose()?),"#
        ),
        other => unreachable!("not an integer field: {other:?}"),
    }
}

/// Generate field assignments for `from_model()`.
fn generate_from_model_fields(entity: &EntityDef) -> String {
    let mut lines = Vec::new();

    for field in &entity.fields {
        if let Some(line) = generate_from_model_field(&entity.name, field) {
            lines.push(format!("            {line}"));
        }
    }

    lines.join("\n")
}

/// Generate a single field assignment for `from_model()`, or None if the field
/// should be skipped (has_many, many_to_many).
/// Skip fields are treated as plain fields in conversions (they have DB columns).
fn generate_from_model_field(entity_name: &str, field: &FieldDef) -> Option<String> {
    let name = &field.name;

    if is_integer_field(field) {
        return Some(integer_from_model_field(entity_name, field));
    }

    match &field.role {
        // Skip fields are treated as plain fields in conversions - they have DB columns
        // but are excluded from writer/relation codegen. Fall through to plain handling.
        FieldRole::Skip => {
            generate_from_model_field(entity_name, &FieldDef { role: FieldRole::Plain, ..field.clone() })
        }

        // has_many and many_to_many: not in DB model, populated by Store later
        FieldRole::Relation(info) if info.kind == RelationKind::HasMany => Some(format!("{name}: Vec::new(),")),
        FieldRole::Relation(info) if info.kind == RelationKind::ManyToMany => Some(format!("{name}: Vec::new(),")),

        // ID field
        FieldRole::Id => match &field.field_type {
            FieldType::String => Some(format!("{name}: model.{name}.clone(),")),
            FieldType::I32 | FieldType::I64 | FieldType::Bool => Some(format!("{name}: model.{name},")),
            _ => Some(format!("{name}: model.{name}.clone(),")),
        },

        // Body field
        FieldRole::Body => Some(format!("{name}: model.{name}.clone(),")),

        // Enum field - parse from string stored in DB
        FieldRole::EnumField => match &field.field_type {
            FieldType::OptionEnum(type_name) => Some(format!(
                r#"{name}: model.{name}.as_deref().and_then(|s| serde_json::from_str::<crate::schema::{type_name}>(&format!("\"{{s}}\"")).ok()),"#
            )),
            // Required enum (e.g., RequirementStatus) - stored as String in DB
            // Use serde_json roundtrip: quote the string as JSON to parse the enum variant.
            _ => {
                let type_name = match &field.field_type {
                    FieldType::Other(t) => t.clone(),
                    _ => "String".to_string(),
                };
                Some(format!(
                    r#"{name}: serde_json::from_str::<crate::schema::{type_name}>(&format!("\"{{}}\"", model.{name})).unwrap_or_else(|_| serde_json::from_str::<crate::schema::{type_name}>("\"\"").expect("enum should have a fallback variant")),"#
                ))
            }
        },

        // belongs_to relation - direct clone (FK column)
        FieldRole::Relation(_) => match &field.field_type {
            FieldType::OptionString => Some(format!("{name}: model.{name}.clone(),")),
            FieldType::String => Some(format!("{name}: model.{name}.clone(),")),
            _ => Some(format!("{name}: model.{name}.clone(),")),
        },

        // Plain field
        FieldRole::Plain => match &field.field_type {
            FieldType::String => Some(format!("{name}: model.{name}.clone(),")),
            FieldType::OptionString => Some(format!("{name}: model.{name}.clone(),")),
            FieldType::I32 | FieldType::I64 | FieldType::F32 | FieldType::F64 | FieldType::Bool => {
                Some(format!("{name}: model.{name},"))
            }
            FieldType::OptionI32
            | FieldType::OptionI64
            | FieldType::OptionF32
            | FieldType::OptionF64
            | FieldType::OptionBool => Some(format!("{name}: model.{name},")),
            FieldType::VecString => Some(format!("{name}: decode_json_vec(&model.{name}),")),
            FieldType::VecStruct(_) => {
                Some(format!("{name}: serde_json::from_str(&model.{name}).unwrap_or_default(),"))
            }
            FieldType::OptionEnum(type_name) => Some(format!(
                r#"{name}: model.{name}.as_deref().and_then(|s| serde_json::from_str::<crate::schema::{type_name}>(&format!("\"{{s}}\"")).ok()),"#
            )),
            FieldType::Other(_) => Some(format!("{name}: model.{name}.clone(),")),
        },
    }
}

/// Generate field assignments for `to_active_model()`.
fn generate_to_active_model_fields(entity: &EntityDef) -> String {
    let mut lines = Vec::new();

    for field in &entity.fields {
        if let Some(line) = generate_to_active_model_field(&entity.name, field) {
            lines.push(format!("            {line}"));
        }
    }

    lines.join("\n")
}

/// Generate a single field assignment for `to_active_model()`, or None if skipped.
/// Skip fields are treated as plain fields in conversions (they have DB columns).
fn generate_to_active_model_field(entity_name: &str, field: &FieldDef) -> Option<String> {
    let name = &field.name;

    if is_integer_field(field) {
        return Some(integer_to_active_model_field(entity_name, field));
    }

    match &field.role {
        // Skip fields are treated as plain fields in conversions - they have DB columns
        FieldRole::Skip => {
            generate_to_active_model_field(entity_name, &FieldDef { role: FieldRole::Plain, ..field.clone() })
        }

        // has_many and many_to_many: not in DB model, managed by Store
        FieldRole::Relation(info) if info.kind == RelationKind::HasMany => None,
        FieldRole::Relation(info) if info.kind == RelationKind::ManyToMany => None,

        // ID field
        FieldRole::Id => match &field.field_type {
            FieldType::String => Some(format!("{name}: Set(self.{name}.clone()),")),
            FieldType::I32 | FieldType::I64 | FieldType::Bool => Some(format!("{name}: Set(self.{name}),")),
            _ => Some(format!("{name}: Set(self.{name}.clone()),")),
        },

        // Body field
        FieldRole::Body => Some(format!("{name}: Set(self.{name}.clone()),")),

        // Enum field - serialize to string for DB storage
        FieldRole::EnumField => match &field.field_type {
            FieldType::OptionEnum(_) => Some(format!("{name}: Set(self.{name}.as_ref().map(enum_to_string)),")),
            // Required enum
            _ => Some(format!("{name}: Set(enum_to_string(&self.{name})),")),
        },

        // belongs_to relation - direct clone (FK column)
        FieldRole::Relation(_) => match &field.field_type {
            FieldType::OptionString => Some(format!("{name}: Set(self.{name}.clone()),")),
            FieldType::String => Some(format!("{name}: Set(self.{name}.clone()),")),
            _ => Some(format!("{name}: Set(self.{name}.clone()),")),
        },

        // Plain field
        FieldRole::Plain => match &field.field_type {
            FieldType::String => Some(format!("{name}: Set(self.{name}.clone()),")),
            FieldType::OptionString => Some(format!("{name}: Set(self.{name}.clone()),")),
            FieldType::I32 | FieldType::I64 | FieldType::F32 | FieldType::F64 | FieldType::Bool => {
                Some(format!("{name}: Set(self.{name}),"))
            }
            FieldType::OptionI32
            | FieldType::OptionI64
            | FieldType::OptionF32
            | FieldType::OptionF64
            | FieldType::OptionBool => Some(format!("{name}: Set(self.{name}),")),
            FieldType::VecString | FieldType::VecStruct(_) => {
                Some(format!("{name}: Set(serde_json::to_string(&self.{name}).unwrap_or_default()),"))
            }
            FieldType::OptionEnum(_) => Some(format!("{name}: Set(self.{name}.as_ref().map(enum_to_string)),")),
            FieldType::Other(_) => Some(format!("{name}: Set(self.{name}.clone()),")),
        },
    }
}

/// Generate the `mod.rs` re-exporting all conversion modules.
fn generate_mod_rs(mod_names: &[String]) -> String {
    let mut out = String::from("//! Generated by ontogen. DO NOT EDIT.\n\n");
    for name in mod_names {
        out.push_str(&format!("pub mod {name};\n"));
    }
    out
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schema::model::*;

    fn make_simple_entity() -> EntityDef {
        EntityDef {
            name: "Agent".to_string(),
            directory: "agent".to_string(),
            table: "agents".to_string(),
            type_name: "agent".to_string(),
            prefix: "agent".to_string(),

            fields: vec![
                FieldDef {
                    name: "id".to_string(),
                    field_type: FieldType::String,
                    role: FieldRole::Id,
                    serde_default: false,
                    multiline_list: false,
                    default_value: None,
                    frontmatter_name: None,
                    doc: String::new(),
                },
                FieldDef {
                    name: "name".to_string(),
                    field_type: FieldType::String,
                    role: FieldRole::Plain,
                    serde_default: false,
                    multiline_list: false,
                    default_value: None,
                    frontmatter_name: None,
                    doc: String::new(),
                },
                FieldDef {
                    name: "agent_type".to_string(),
                    field_type: FieldType::OptionEnum("AgentType".to_string()),
                    role: FieldRole::EnumField,
                    serde_default: false,
                    multiline_list: false,
                    default_value: None,
                    frontmatter_name: None,
                    doc: String::new(),
                },
                FieldDef {
                    name: "capabilities".to_string(),
                    field_type: FieldType::VecString,
                    role: FieldRole::Plain,
                    serde_default: true,
                    multiline_list: false,
                    default_value: None,
                    frontmatter_name: None,
                    doc: String::new(),
                },
                FieldDef {
                    name: "body".to_string(),
                    field_type: FieldType::String,
                    role: FieldRole::Body,
                    serde_default: false,
                    multiline_list: false,
                    default_value: None,
                    frontmatter_name: None,
                    doc: String::new(),
                },
            ],
            doc: String::new(),
        }
    }

    #[test]
    fn from_model_generates_correct_fields() {
        let entity = make_simple_entity();
        let code = generate_conversion_code(&entity);

        assert!(code.contains("id: model.id.clone(),"));
        assert!(code.contains("name: model.name.clone(),"));
        assert!(code.contains(r#"agent_type: model.agent_type.as_deref().and_then"#));
        assert!(code.contains("capabilities: decode_json_vec(&model.capabilities),"));
        assert!(code.contains("body: model.body.clone(),"));
    }

    #[test]
    fn to_active_model_generates_correct_fields() {
        let entity = make_simple_entity();
        let code = generate_conversion_code(&entity);

        assert!(code.contains("id: Set(self.id.clone()),"));
        assert!(code.contains("name: Set(self.name.clone()),"));
        assert!(code.contains("agent_type: Set(self.agent_type.as_ref().map(enum_to_string)),"));
        assert!(code.contains("capabilities: Set(serde_json::to_string(&self.capabilities).unwrap_or_default()),"));
        assert!(code.contains("body: Set(self.body.clone()),"));
        assert!(!code.contains("wikilinks"));
        assert!(!code.contains("source_file"));
    }

    #[test]
    fn has_many_and_many_to_many_fields_excluded() {
        let entity = EntityDef {
            name: "Node".to_string(),
            directory: "nodes".to_string(),
            table: "nodes".to_string(),
            type_name: "node".to_string(),
            prefix: "node".to_string(),

            fields: vec![
                FieldDef {
                    name: "id".to_string(),
                    field_type: FieldType::String,
                    role: FieldRole::Id,
                    serde_default: false,
                    multiline_list: false,
                    default_value: None,
                    frontmatter_name: None,
                    doc: String::new(),
                },
                FieldDef {
                    name: "parent_id".to_string(),
                    field_type: FieldType::OptionString,
                    role: FieldRole::Relation(RelationInfo {
                        kind: RelationKind::BelongsTo,
                        target: "Node".to_string(),
                        junction: None,
                        foreign_key: None,
                    }),
                    serde_default: true,
                    multiline_list: false,
                    default_value: None,
                    frontmatter_name: None,
                    doc: String::new(),
                },
                FieldDef {
                    name: "contains".to_string(),
                    field_type: FieldType::VecString,
                    role: FieldRole::Relation(RelationInfo {
                        kind: RelationKind::HasMany,
                        target: "Node".to_string(),
                        junction: None,
                        foreign_key: Some("parent_id".to_string()),
                    }),
                    serde_default: true,
                    multiline_list: false,
                    default_value: None,
                    frontmatter_name: None,
                    doc: String::new(),
                },
                FieldDef {
                    name: "fulfills".to_string(),
                    field_type: FieldType::VecString,
                    role: FieldRole::Relation(RelationInfo {
                        kind: RelationKind::ManyToMany,
                        target: "Requirement".to_string(),
                        junction: None,
                        foreign_key: None,
                    }),
                    serde_default: true,
                    multiline_list: false,
                    default_value: None,
                    frontmatter_name: None,
                    doc: String::new(),
                },
                FieldDef {
                    name: "body".to_string(),
                    field_type: FieldType::String,
                    role: FieldRole::Body,
                    serde_default: false,
                    multiline_list: false,
                    default_value: None,
                    frontmatter_name: None,
                    doc: String::new(),
                },
            ],
            doc: String::new(),
        };

        let code = generate_conversion_code(&entity);

        // belongs_to IS included
        assert!(code.contains("parent_id: model.parent_id.clone(),"));
        assert!(code.contains("parent_id: Set(self.parent_id.clone()),"));

        // has_many and many_to_many are initialized as empty in from_model
        assert!(code.contains("contains: Vec::new(),"));
        assert!(code.contains("fulfills: Vec::new(),"));

        // But they should NOT appear in to_active_model
        let to_active = code.split("to_active_model").nth(1).unwrap();
        assert!(!to_active.contains("contains:"));
        assert!(!to_active.contains("fulfills:"));
    }

    #[test]
    fn required_enum_field() {
        let entity = EntityDef {
            name: "Requirement".to_string(),
            directory: "requirements".to_string(),
            table: "requirements".to_string(),
            type_name: "requirement".to_string(),
            prefix: "req".to_string(),

            fields: vec![
                FieldDef {
                    name: "id".to_string(),
                    field_type: FieldType::String,
                    role: FieldRole::Id,
                    serde_default: false,
                    multiline_list: false,
                    default_value: None,
                    frontmatter_name: None,
                    doc: String::new(),
                },
                FieldDef {
                    name: "status".to_string(),
                    field_type: FieldType::Other("RequirementStatus".to_string()),
                    role: FieldRole::EnumField,
                    serde_default: true,
                    multiline_list: false,
                    default_value: None,
                    frontmatter_name: None,
                    doc: String::new(),
                },
                FieldDef {
                    name: "body".to_string(),
                    field_type: FieldType::String,
                    role: FieldRole::Body,
                    serde_default: false,
                    multiline_list: false,
                    default_value: None,
                    frontmatter_name: None,
                    doc: String::new(),
                },
            ],
            doc: String::new(),
        };

        let code = generate_conversion_code(&entity);

        // from_model: parse required enum from DB string
        assert!(code.contains("serde_json::from_str::<crate::schema::RequirementStatus>"));
        assert!(code.contains("unwrap_or_else"));

        // to_active_model: serialize required enum to string
        assert!(code.contains("Set(enum_to_string(&self.status)),"));
    }

    #[test]
    fn vec_struct_field() {
        let entity = EntityDef {
            name: "Specification".to_string(),
            directory: "specification".to_string(),
            table: "specifications".to_string(),
            type_name: "specification".to_string(),
            prefix: "spec".to_string(),

            fields: vec![
                FieldDef {
                    name: "id".to_string(),
                    field_type: FieldType::String,
                    role: FieldRole::Id,
                    serde_default: false,
                    multiline_list: false,
                    default_value: None,
                    frontmatter_name: None,
                    doc: String::new(),
                },
                FieldDef {
                    name: "acceptance_criteria".to_string(),
                    field_type: FieldType::VecStruct("AcceptanceCriterion".to_string()),
                    role: FieldRole::Plain,
                    serde_default: true,
                    multiline_list: false,
                    default_value: None,
                    frontmatter_name: None,
                    doc: String::new(),
                },
                FieldDef {
                    name: "body".to_string(),
                    field_type: FieldType::String,
                    role: FieldRole::Body,
                    serde_default: false,
                    multiline_list: false,
                    default_value: None,
                    frontmatter_name: None,
                    doc: String::new(),
                },
            ],
            doc: String::new(),
        };

        let code = generate_conversion_code(&entity);

        // from_model: deserialize from JSON string
        assert!(code.contains("serde_json::from_str(&model.acceptance_criteria).unwrap_or_default()"));
        // to_active_model: serialize to JSON string
        assert!(code.contains("serde_json::to_string(&self.acceptance_criteria).unwrap_or_default()"));
    }

    #[test]
    fn skip_field_excluded() {
        let entity = EntityDef {
            name: "Test".to_string(),
            directory: "test".to_string(),
            table: "tests".to_string(),
            type_name: "test".to_string(),
            prefix: "test".to_string(),

            fields: vec![
                FieldDef {
                    name: "id".to_string(),
                    field_type: FieldType::String,
                    role: FieldRole::Id,
                    serde_default: false,
                    multiline_list: false,
                    default_value: None,
                    frontmatter_name: None,
                    doc: String::new(),
                },
                FieldDef {
                    name: "skipped".to_string(),
                    field_type: FieldType::String,
                    role: FieldRole::Skip,
                    serde_default: false,
                    multiline_list: false,
                    default_value: None,
                    frontmatter_name: None,
                    doc: String::new(),
                },
                FieldDef {
                    name: "body".to_string(),
                    field_type: FieldType::String,
                    role: FieldRole::Body,
                    serde_default: false,
                    multiline_list: false,
                    default_value: None,
                    frontmatter_name: None,
                    doc: String::new(),
                },
            ],
            doc: String::new(),
        };

        let code = generate_conversion_code(&entity);
        // Skip fields ARE included in conversions (they have DB columns).
        // They're only excluded from DTOs and writers.
        assert!(code.contains("skipped: model.skipped.clone(),"));
        assert!(code.contains("skipped: Set(self.skipped.clone()),"));
    }

    #[test]
    fn generate_all_real_schemas() {
        let schema_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/schema");
        let entities = crate::schema::parse::parse_schema_dir(&schema_dir).expect("Failed to parse schema dir");

        let dir = std::env::temp_dir().join("ontology_codegen_test_conversions");
        let _ = std::fs::remove_dir_all(&dir);

        generate(&entities, &dir, &[]).expect("generate failed");

        // Should create one file per entity + mod.rs
        let files: Vec<_> = std::fs::read_dir(&dir)
            .unwrap()
            .filter_map(|e| e.ok())
            .map(|e| e.file_name().to_string_lossy().to_string())
            .collect();

        assert!(files.contains(&"mod.rs".to_string()));
        assert!(files.contains(&"tag.rs".to_string()));
        assert!(files.contains(&"exercise.rs".to_string()));
        assert!(files.contains(&"workout.rs".to_string()));
        assert!(files.contains(&"workout_set.rs".to_string()));

        // Verify many_to_many fields are absent from to_active_model on Workout
        let workout_code = std::fs::read_to_string(dir.join("workout.rs")).unwrap();
        let to_active = workout_code.split("to_active_model").nth(1).unwrap();
        assert!(!to_active.contains("tags:"), "many_to_many field should not be in to_active_model");
        assert!(workout_code.contains("parent_id:"), "belongs_to field should appear");
        assert!(!workout_code.contains("wikilinks"), "wikilinks should not be in conversion");
        assert!(!workout_code.contains("source_file"), "source_file should not be in conversion");

        // WorkoutSet has two belongs_to fields that should appear
        let ws_code = std::fs::read_to_string(dir.join("workout_set.rs")).unwrap();
        assert!(ws_code.contains("workout_id:"), "WorkoutSet.workout_id (belongs_to) should appear");
        assert!(ws_code.contains("exercise_id:"), "WorkoutSet.exercise_id (belongs_to) should appear");

        // Cleanup
        let _ = std::fs::remove_dir_all(&dir);
    }

    /// Syntax check: verify generate_conversion_code emits a syntactically
    /// valid Rust source file.
    #[test]
    fn generated_code_is_valid_rust() {
        for entity in [make_simple_entity(), make_integer_entity(FieldRole::Plain)] {
            let code = generate_conversion_code(&entity);
            syn::parse_file(&code).unwrap_or_else(|e| {
                panic!(
                    "seaorm::gen_conversion::generate_conversion_code produced invalid Rust: {e}\n--- code ---\n{code}"
                )
            });
        }
    }

    #[test]
    fn conversions_return_result() {
        let code = generate_conversion_code(&make_simple_entity());
        assert!(code.contains("use crate::schema::{AppError, Agent};"), "{code}");
        assert!(code.contains("pub fn from_model(model: &entity::Model) -> Result<Self, AppError>"), "{code}");
        assert!(code.contains("pub fn to_active_model(&self) -> Result<entity::ActiveModel, AppError>"), "{code}");
    }

    /// ADR 0006 §2's integer primitives that reach `OptionEnum` / `Other`.
    const LOSSLESS: [&str; 5] = ["u8", "u16", "u32", "i8", "i16"];
    const FALLIBLE: [&str; 4] = ["usize", "u128", "isize", "i128"];

    /// `Counter` with a bare (`b_{t}`) and an optional (`o_{t}`) field for
    /// every integer primitive, all in `role`.
    fn make_integer_entity(role: FieldRole) -> EntityDef {
        let mut fields = vec![FieldDef::new("id", FieldType::String, FieldRole::Id)];
        for t in LOSSLESS.iter().chain(FALLIBLE.iter()) {
            fields.push(FieldDef::new(format!("b_{t}"), FieldType::Other((*t).to_string()), role.clone()));
            fields.push(FieldDef::new(format!("o_{t}"), FieldType::OptionEnum((*t).to_string()), role.clone()));
        }
        EntityDef {
            name: "Counter".to_string(),
            directory: "counters".to_string(),
            table: "counters".to_string(),
            type_name: "counter".to_string(),
            prefix: "counter".to_string(),
            fields,
            doc: String::new(),
        }
    }

    #[test]
    fn integer_reads_convert_back_with_try_from_naming_the_field() {
        for role in [FieldRole::Plain, FieldRole::EnumField, FieldRole::Skip] {
            let code = generate_conversion_code(&make_integer_entity(role.clone()));
            for t in LOSSLESS.iter().chain(FALLIBLE.iter()) {
                assert!(
                    code.contains(&format!(
                        r#"b_{t}: {t}::try_from(model.b_{t}).map_err(|_| AppError::DbError(format!("Counter.b_{t}: stored value {{}} is out of range for {t}", model.b_{t})))?,"#
                    )),
                    "bare {t} read ({role:?}):\n{code}"
                );
                assert!(
                    code.contains(&format!(
                        r#"o_{t}: model.o_{t}.map(|v| {t}::try_from(v).map_err(|_| AppError::DbError(format!("Counter.o_{t}: stored value {{v}} is out of range for {t}")))).transpose()?,"#
                    )),
                    "Option<{t}> read ({role:?}):\n{code}"
                );
            }
        }
    }

    #[test]
    fn lossless_integer_writes_widen_with_i64_from() {
        for role in [FieldRole::Plain, FieldRole::EnumField, FieldRole::Skip] {
            let code = generate_conversion_code(&make_integer_entity(role.clone()));
            for t in LOSSLESS {
                assert!(code.contains(&format!("b_{t}: Set(i64::from(self.b_{t})),")), "bare {t} ({role:?}):\n{code}");
                assert!(
                    code.contains(&format!("o_{t}: Set(self.o_{t}.map(i64::from)),")),
                    "Option<{t}> ({role:?}):\n{code}"
                );
            }
        }
    }

    #[test]
    fn wide_integer_writes_use_try_from_naming_the_field() {
        for role in [FieldRole::Plain, FieldRole::EnumField, FieldRole::Skip] {
            let code = generate_conversion_code(&make_integer_entity(role.clone()));
            for t in FALLIBLE {
                assert!(
                    code.contains(&format!(
                        r#"b_{t}: Set(i64::try_from(self.b_{t}).map_err(|_| AppError::DbError(format!("Counter.b_{t}: value {{}} is out of range for i64", self.b_{t})))?),"#
                    )),
                    "bare {t} write ({role:?}):\n{code}"
                );
                assert!(
                    code.contains(&format!(
                        r#"o_{t}: Set(self.o_{t}.map(|v| i64::try_from(v).map_err(|_| AppError::DbError(format!("Counter.o_{t}: value {{v}} is out of range for i64")))).transpose()?),"#
                    )),
                    "Option<{t}> write ({role:?}):\n{code}"
                );
            }
        }
    }

    #[test]
    fn integer_fields_never_cast_or_need_enum_helpers() {
        for role in [FieldRole::Plain, FieldRole::EnumField, FieldRole::Skip] {
            let code = generate_conversion_code(&make_integer_entity(role.clone()));
            let body = &code[code.find("impl Counter").expect("impl block")..];
            assert!(!body.contains(" as "), "{role:?}: no `as` casts:\n{code}");
            assert!(!code.contains("allow(clippy"), "{role:?}:\n{code}");
            assert!(!code.contains("enum_to_string"), "{role:?}:\n{code}");
            assert!(!code.contains("serde_json"), "{role:?}:\n{code}");
        }
    }
}
