// TODO: review — banner strings updated, to_snake_case/to_pascal_case now delegate to ontogen-core
//! Generate SeaORM entity modules from parsed ontology entity definitions.
//!
//! Generates:
//! - Entity `Model` structs with `DeriveEntityModel`
//! - `Relation` enums with `belongs_to` and `has_many` (junction link) variants
//! - `Related<>` impls for many-to-many relations via junction tables
//! - Junction table entities for each many-to-many relation
//! - A `mod.rs` re-exporting all modules

use std::collections::HashMap;
use std::fs;
use std::path::Path;

use crate::schema::model::{EntityDef, FieldDef, FieldRole, FieldType, RelationKind};

/// Check if a type name is an integer primitive that maps to a DB integer column.
fn is_integer_primitive(t: &str) -> bool {
    matches!(t, "u8" | "u16" | "u32" | "u64" | "i8" | "i16" | "i32" | "i64")
}

// ─── Public API ──────────────────────────────────────────────────────────────

/// Generate all entity modules and write them to the output directory.
pub fn generate(entities: &[EntityDef], output_dir: &Path) -> Result<(), String> {
    fs::create_dir_all(output_dir).map_err(|e| format!("Failed to create output dir {}: {e}", output_dir.display()))?;

    let modules = build_entity_module_map(entities);

    let mut entity_outputs: Vec<(String, String)> = Vec::new();
    let mut junction_outputs: Vec<(String, String)> = Vec::new();

    for entity in entities {
        let mod_name = modules[&entity.name].clone();
        let code = generate_entity_code(entity, &modules);
        entity_outputs.push((mod_name, code));

        for (field, info) in entity.junction_relations() {
            let (jmod, jcode) = generate_junction_code(entity, field, info, &modules);
            junction_outputs.push((jmod, jcode));
        }
    }

    // Clean stale files from previous entity names
    let expected: std::collections::HashSet<String> = entity_outputs
        .iter()
        .chain(junction_outputs.iter())
        .map(|(name, _)| format!("{name}.rs"))
        .chain(std::iter::once("mod.rs".to_string()))
        .collect();
    crate::clean_generated_dir(output_dir, &expected);

    // Write entity files
    for (mod_name, code) in &entity_outputs {
        let path = output_dir.join(format!("{mod_name}.rs"));
        crate::write_and_format(&path, code).map_err(|e| format!("Failed to write {}: {e}", path.display()))?;
    }

    // Write junction files
    for (mod_name, code) in &junction_outputs {
        let path = output_dir.join(format!("{mod_name}.rs"));
        crate::write_and_format(&path, code).map_err(|e| format!("Failed to write {}: {e}", path.display()))?;
    }

    // Write mod.rs
    let mod_rs = generate_mod_rs(&entity_outputs, &junction_outputs);
    let path = output_dir.join("mod.rs");
    crate::write_and_format(&path, mod_rs).map_err(|e| format!("Failed to write {}: {e}", path.display()))?;

    Ok(())
}

/// Generate the complete Rust source for one entity module.
pub fn generate_entity_code(entity: &EntityDef, entity_modules: &HashMap<String, String>) -> String {
    let mut code = String::with_capacity(2048);

    code.push_str("//! Generated by ontogen. DO NOT EDIT.\n\n");
    code.push_str("use sea_orm::entity::prelude::*;\n\n");

    // ── Model struct ─────────────────────────────────────────────────────
    code.push_str("#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]\n");
    code.push_str(&format!("#[sea_orm(table_name = \"{}\")]\n", entity.table));
    code.push_str("pub struct Model {\n");

    for field in &entity.fields {
        if let Some(col) = generate_model_column(field) {
            code.push_str(&col);
        }
    }

    code.push_str("}\n\n");

    // ── Relation enum ────────────────────────────────────────────────────
    code.push_str("#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]\n");
    code.push_str("pub enum Relation {\n");
    code.push_str(&generate_belongs_to_variants(entity, entity_modules));
    code.push_str(&generate_junction_link_variants(entity, entity_modules));
    code.push_str("}\n\n");

    // ── Related<> impls for many-to-many ─────────────────────────────────
    code.push_str(&generate_related_impls(entity, entity_modules));

    // ── ActiveModelBehavior ──────────────────────────────────────────────
    code.push_str("impl ActiveModelBehavior for ActiveModel {}\n");

    code
}

/// Generate the Rust source for a junction table entity.
/// Returns `(module_name, code)`.
pub fn generate_junction_code(
    source: &EntityDef,
    field: &FieldDef,
    info: &crate::schema::model::RelationInfo,
    entity_modules: &HashMap<String, String>,
) -> (String, String) {
    let source_mod = &entity_modules[&source.name];
    let target_mod = &entity_modules[&info.target];
    let is_self_ref = source.name == info.target;

    let junction_name = junction_table_name(source_mod, &field.name, info);

    let source_col = format!("{source_mod}_id");
    let target_col = if is_self_ref { "target_id".to_string() } else { format!("{target_mod}_id") };

    let source_col_pascal = to_pascal_case(&source_col);
    let target_col_pascal = to_pascal_case(&target_col);

    let (source_variant, target_variant) = if is_self_ref {
        ("Source".to_string(), "Target".to_string())
    } else {
        (to_pascal_case(source_mod), to_pascal_case(target_mod))
    };

    let source_entity = format!("super::{source_mod}::Entity");
    let target_entity =
        if is_self_ref { format!("super::{source_mod}::Entity") } else { format!("super::{target_mod}::Entity") };

    let source_id_col = format!("super::{source_mod}::Column::Id");
    let target_id_col = if is_self_ref {
        format!("super::{source_mod}::Column::Id")
    } else {
        format!("super::{target_mod}::Column::Id")
    };

    let mut code = String::with_capacity(1024);
    code.push_str("//! Generated by ontogen. DO NOT EDIT.\n\n");
    code.push_str("use sea_orm::entity::prelude::*;\n\n");

    code.push_str("#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]\n");
    code.push_str(&format!("#[sea_orm(table_name = \"{junction_name}\")]\n"));
    code.push_str("pub struct Model {\n");
    code.push_str("    #[sea_orm(primary_key)]\n");
    code.push_str("    pub id: i32,\n");
    code.push_str(&format!("    pub {source_col}: String,\n"));
    code.push_str(&format!("    pub {target_col}: String,\n"));
    code.push_str("}\n\n");

    code.push_str("#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]\n");
    code.push_str("pub enum Relation {\n");

    // Source belongs_to
    code.push_str("    #[sea_orm(\n");
    code.push_str(&format!("        belongs_to = \"{source_entity}\",\n"));
    code.push_str(&format!("        from = \"Column::{source_col_pascal}\",\n"));
    code.push_str(&format!("        to = \"{source_id_col}\"\n"));
    code.push_str("    )]\n");
    code.push_str(&format!("    {source_variant},\n"));

    // Target belongs_to
    code.push_str("    #[sea_orm(\n");
    code.push_str(&format!("        belongs_to = \"{target_entity}\",\n"));
    code.push_str(&format!("        from = \"Column::{target_col_pascal}\",\n"));
    code.push_str(&format!("        to = \"{target_id_col}\"\n"));
    code.push_str("    )]\n");
    code.push_str(&format!("    {target_variant},\n"));

    code.push_str("}\n\n");

    // SeaORM's DeriveRelation does NOT auto-generate `Related<T>` impls.
    // We must add them explicitly. The parent entity's `has_many` requires
    // `R: Related<Self>`, so the junction must impl `Related<ParentEntity>`.
    code.push_str(&format!(
        "impl Related<{source_entity}> for Entity {{\n\
         \x20   fn to() -> RelationDef {{\n\
         \x20       Relation::{source_variant}.def()\n\
         \x20   }}\n\
         }}\n\n"
    ));

    // For non-self-referential junctions, also add Related for the target entity
    if !is_self_ref {
        code.push_str(&format!(
            "impl Related<{target_entity}> for Entity {{\n\
             \x20   fn to() -> RelationDef {{\n\
             \x20       Relation::{target_variant}.def()\n\
             \x20   }}\n\
             }}\n\n"
        ));
    }

    code.push_str("impl ActiveModelBehavior for ActiveModel {}\n");

    (junction_name, code)
}

// ─── Internal helpers ────────────────────────────────────────────────────────

/// Build a lookup from entity struct name to snake_case module name.
fn build_entity_module_map(entities: &[EntityDef]) -> HashMap<String, String> {
    entities.iter().map(|e| (e.name.clone(), to_snake_case(&e.name))).collect()
}

/// Generate a single Model struct field, or `None` if the field has no DB column.
fn generate_model_column(field: &FieldDef) -> Option<String> {
    // has_many and many_to_many don't get DB columns
    if let FieldRole::Relation(info) = &field.role
        && matches!(info.kind, RelationKind::HasMany | RelationKind::ManyToMany)
    {
        return None;
    }

    let mut out = String::new();

    // PK attribute
    if field.role == FieldRole::Id {
        match &field.field_type {
            FieldType::I32 | FieldType::I64 => out.push_str("    #[sea_orm(primary_key)]\n"),
            _ => out.push_str("    #[sea_orm(primary_key, auto_increment = false)]\n"),
        }
    }

    // JSON doc comment for vec fields
    match &field.field_type {
        FieldType::VecString => out.push_str("    /// JSON-encoded Vec<String>\n"),
        FieldType::VecStruct(t) => out.push_str(&format!("    /// JSON-encoded Vec<{t}>\n")),
        _ => {}
    }

    let db_type = field_db_type(field);
    out.push_str(&format!("    pub {}: {db_type},\n", field.name));

    Some(out)
}

/// Map a schema field to its DB column type string.
fn field_db_type(field: &FieldDef) -> &'static str {
    if field.role == FieldRole::Id {
        return match &field.field_type {
            FieldType::I32 => "i32",
            FieldType::I64 => "i64",
            _ => "String", // String or OptionString → required String PK
        };
    }

    match &field.field_type {
        FieldType::String => "String",
        FieldType::OptionString => "Option<String>",
        FieldType::I32 => "i32",
        FieldType::OptionI32 => "Option<i32>",
        FieldType::I64 => "i64",
        FieldType::OptionI64 => "Option<i64>",
        FieldType::Bool => "bool",
        FieldType::OptionBool => "Option<bool>",
        FieldType::VecString | FieldType::VecStruct(_) => "String", // JSON
        // Primitive numeric option types map to DB integer columns
        FieldType::OptionEnum(t) if is_integer_primitive(t) => "Option<i32>",
        FieldType::OptionEnum(_) => "Option<String>",
        // Primitive numeric types map to DB integer columns
        FieldType::Other(t) if is_integer_primitive(t) => "i32",
        FieldType::Other(_) => "String", // enum or unknown
    }
}

/// Generate `Relation` enum variants for `belongs_to` fields.
fn generate_belongs_to_variants(entity: &EntityDef, entity_modules: &HashMap<String, String>) -> String {
    let mut code = String::new();

    for (field, info) in entity.belongs_to_relations() {
        let variant = to_pascal_case(&field.name);
        let col_pascal = to_pascal_case(&field.name);
        let is_self_ref = info.target == entity.name;

        let target_entity =
            if is_self_ref { "Entity".to_string() } else { format!("super::{}::Entity", entity_modules[&info.target]) };

        let target_col = if is_self_ref {
            "Column::Id".to_string()
        } else {
            format!("super::{}::Column::Id", entity_modules[&info.target])
        };

        code.push_str("    #[sea_orm(\n");
        code.push_str(&format!("        belongs_to = \"{target_entity}\",\n"));
        code.push_str(&format!("        from = \"Column::{col_pascal}\",\n"));
        code.push_str(&format!("        to = \"{target_col}\"\n"));
        code.push_str("    )]\n");
        code.push_str(&format!("    {variant},\n"));
    }

    code
}

/// Generate `Relation` enum `has_many` variants pointing to junction table entities.
fn generate_junction_link_variants(entity: &EntityDef, entity_modules: &HashMap<String, String>) -> String {
    let mut code = String::new();
    let source_mod = &entity_modules[&entity.name];

    for (field, info) in entity.junction_relations() {
        let junction = junction_table_name(source_mod, &field.name, info);
        let variant = format!("{}Link", to_pascal_case(&field.name));

        code.push_str(&format!("    #[sea_orm(has_many = \"super::{junction}::Entity\")]\n"));
        code.push_str(&format!("    {variant},\n"));
    }

    code
}

/// Generate `Related<TargetEntity>` impls for many-to-many relations via junction.
fn generate_related_impls(entity: &EntityDef, entity_modules: &HashMap<String, String>) -> String {
    let mut code = String::new();
    let source_mod = &entity_modules[&entity.name];

    for (field, info) in entity.junction_relations() {
        let target_mod = &entity_modules[&info.target];
        let is_self_ref = info.target == entity.name;
        let junction = junction_table_name(source_mod, &field.name, info);

        let target_entity_path =
            if is_self_ref { "Entity".to_string() } else { format!("super::{target_mod}::Entity") };

        let (junc_source_variant, junc_target_variant) = if is_self_ref {
            ("Source".to_string(), "Target".to_string())
        } else {
            (to_pascal_case(source_mod), to_pascal_case(target_mod))
        };

        code.push_str(&format!("impl Related<{target_entity_path}> for Entity {{\n"));
        code.push_str(&format!(
            "    fn to() -> RelationDef {{\n        super::{junction}::Relation::{junc_target_variant}.def()\n    }}\n"
        ));
        code.push_str(&format!(
            "    fn via() -> Option<RelationDef> {{\n        Some(super::{junction}::Relation::{junc_source_variant}.def().rev())\n    }}\n"
        ));
        code.push_str("}\n\n");
    }

    code
}

/// Generate `mod.rs` re-exporting all entity and junction modules.
fn generate_mod_rs(entities: &[(String, String)], junctions: &[(String, String)]) -> String {
    let mut code = String::from("//! Generated by ontogen. DO NOT EDIT.\n\n");

    let mut all_mods: Vec<&str> = entities.iter().chain(junctions.iter()).map(|(name, _)| name.as_str()).collect();
    all_mods.sort();

    for mod_name in all_mods {
        code.push_str(&format!("pub mod {mod_name};\n"));
    }

    code
}

/// Derive junction table name from source module and field name, or use override.
fn junction_table_name(source_module: &str, field_name: &str, info: &crate::schema::model::RelationInfo) -> String {
    info.junction.clone().unwrap_or_else(|| format!("{source_module}_{field_name}"))
}

/// Convert `CamelCase` to `snake_case`.
///
/// Delegates to `ontogen_core::naming::to_snake_case`.
pub fn to_snake_case(name: &str) -> String {
    ontogen_core::naming::to_snake_case(name)
}

/// Convert `snake_case` to `PascalCase`.
fn to_pascal_case(s: &str) -> String {
    ontogen_core::naming::to_pascal_case(s)
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schema::model::*;

    /// Helper: build modules map from entity names.
    fn modules(names: &[&str]) -> HashMap<String, String> {
        names.iter().map(|n| (n.to_string(), to_snake_case(n))).collect()
    }

    #[test]
    fn pascal_case() {
        assert_eq!(to_pascal_case("parent_id"), "ParentId");
        assert_eq!(to_pascal_case("from"), "From");
        assert_eq!(to_pascal_case("work_item"), "WorkItem");
        assert_eq!(to_pascal_case("node"), "Node");
        assert_eq!(to_pascal_case("id"), "Id");
        assert_eq!(to_pascal_case("target_id"), "TargetId");
    }

    #[test]
    fn snake_case() {
        assert_eq!(to_snake_case("WorkSession"), "work_session");
        assert_eq!(to_snake_case("Node"), "node");
    }

    #[test]
    fn field_db_types() {
        let mk = |ft: FieldType, role: FieldRole| FieldDef::new("x", ft, role);

        assert_eq!(field_db_type(&mk(FieldType::String, FieldRole::Id)), "String");
        assert_eq!(field_db_type(&mk(FieldType::I32, FieldRole::Id)), "i32");
        assert_eq!(field_db_type(&mk(FieldType::OptionString, FieldRole::Id)), "String");
        assert_eq!(field_db_type(&mk(FieldType::VecString, FieldRole::Plain)), "String");
        assert_eq!(field_db_type(&mk(FieldType::OptionEnum("X".into()), FieldRole::Plain)), "Option<String>");
        assert_eq!(field_db_type(&mk(FieldType::Other("Foo".into()), FieldRole::EnumField)), "String");
    }

    fn make_node_entity() -> EntityDef {
        EntityDef {
            name: "Node".into(),
            directory: "nodes".into(),
            table: "nodes".into(),
            type_name: "node".into(),
            prefix: "node".into(),

            fields: vec![
                FieldDef {
                    name: "id".into(),
                    field_type: FieldType::String,
                    role: FieldRole::Id,
                    serde_default: false,
                    multiline_list: false,
                    default_value: None,
                },
                FieldDef {
                    name: "name".into(),
                    field_type: FieldType::String,
                    role: FieldRole::Plain,
                    serde_default: false,
                    multiline_list: false,
                    default_value: None,
                },
                FieldDef {
                    name: "kind".into(),
                    field_type: FieldType::OptionEnum("NodeKind".into()),
                    role: FieldRole::EnumField,
                    serde_default: false,
                    multiline_list: false,
                    default_value: None,
                },
                FieldDef {
                    name: "parent_id".into(),
                    field_type: FieldType::OptionString,
                    role: FieldRole::Relation(RelationInfo {
                        kind: RelationKind::BelongsTo,
                        target: "Node".into(),
                        junction: None,
                        foreign_key: None,
                    }),
                    serde_default: true,
                    multiline_list: false,
                    default_value: None,
                },
                FieldDef {
                    name: "contains".into(),
                    field_type: FieldType::VecString,
                    role: FieldRole::Relation(RelationInfo {
                        kind: RelationKind::HasMany,
                        target: "Node".into(),
                        junction: None,
                        foreign_key: Some("parent_id".into()),
                    }),
                    serde_default: true,
                    multiline_list: false,
                    default_value: None,
                },
                FieldDef {
                    name: "tags".into(),
                    field_type: FieldType::VecString,
                    role: FieldRole::Plain,
                    serde_default: true,
                    multiline_list: false,
                    default_value: None,
                },
                FieldDef {
                    name: "body".into(),
                    field_type: FieldType::String,
                    role: FieldRole::Body,
                    serde_default: true,
                    multiline_list: false,
                    default_value: None,
                },
                FieldDef {
                    name: "fulfills".into(),
                    field_type: FieldType::VecString,
                    role: FieldRole::Relation(RelationInfo {
                        kind: RelationKind::ManyToMany,
                        target: "Requirement".into(),
                        junction: None,
                        foreign_key: None,
                    }),
                    serde_default: true,
                    multiline_list: false,
                    default_value: None,
                },
            ],
        }
    }

    #[test]
    fn generate_node_entity_structure() {
        let mods = modules(&["Node", "Requirement"]);
        let code = generate_entity_code(&make_node_entity(), &mods);

        // Table name
        assert!(code.contains(r#"table_name = "nodes""#), "table name");

        // PK
        assert!(code.contains("primary_key, auto_increment = false"), "pk attr");
        assert!(code.contains("pub id: String"), "id field");

        // Regular columns
        assert!(code.contains("pub name: String"), "name field");
        assert!(code.contains("pub kind: Option<String>"), "kind field");
        assert!(code.contains("pub parent_id: Option<String>"), "parent_id");
        assert!(code.contains("pub tags: String"), "tags as JSON string");
        assert!(code.contains("pub body: String"), "body field");

        // Persistence-only fields should NOT be present (removed)
        assert!(!code.contains("pub wikilinks:"), "wikilinks should not be a column");
        assert!(!code.contains("pub source_file:"), "source_file should not be a column");

        // has_many and many_to_many should NOT appear as columns
        assert!(!code.contains("pub contains:"), "contains should not be a column");
        assert!(!code.contains("pub fulfills:"), "fulfills should not be a column");

        // belongs_to variant for parent_id (self-ref)
        assert!(code.contains(r#"belongs_to = "Entity""#), "self-ref belongs_to");
        assert!(code.contains(r#"from = "Column::ParentId""#), "parent_id column");
        assert!(code.contains(r#"to = "Column::Id""#), "self-ref target id");
        assert!(code.contains("ParentId,"), "ParentId variant");

        // Junction link for fulfills
        assert!(code.contains(r#"has_many = "super::node_fulfills::Entity""#), "junction link");
        assert!(code.contains("FulfillsLink,"), "FulfillsLink variant");

        // Related impl for many-to-many
        assert!(code.contains("impl Related<super::requirement::Entity> for Entity"), "Related impl");
        assert!(code.contains("super::node_fulfills::Relation::Requirement.def()"), "Related to()");
        assert!(code.contains("super::node_fulfills::Relation::Node.def().rev()"), "Related via()");
    }

    #[test]
    fn generate_junction_non_self_ref() {
        let node = make_node_entity();
        let mods = modules(&["Node", "Requirement"]);

        let fulfills_field = &node.fields[7]; // fulfills
        let info = match &fulfills_field.role {
            FieldRole::Relation(i) => i,
            _ => panic!("expected relation"),
        };

        let (name, code) = generate_junction_code(&node, fulfills_field, info, &mods);

        assert_eq!(name, "node_fulfills");
        assert!(code.contains(r#"table_name = "node_fulfills""#));
        assert!(code.contains("pub node_id: String"));
        assert!(code.contains("pub requirement_id: String"));
        assert!(code.contains(r#"belongs_to = "super::node::Entity""#));
        assert!(code.contains(r#"belongs_to = "super::requirement::Entity""#));
        assert!(code.contains("Node,"));
        assert!(code.contains("Requirement,"));
    }

    #[test]
    fn generate_junction_self_ref() {
        let task = EntityDef {
            name: "Task".into(),
            directory: "task".into(),
            table: "tasks".into(),
            type_name: "task".into(),
            prefix: "task".into(),

            fields: vec![
                FieldDef {
                    name: "id".into(),
                    field_type: FieldType::String,
                    role: FieldRole::Id,
                    serde_default: false,
                    multiline_list: false,
                    default_value: None,
                },
                FieldDef {
                    name: "depends_on".into(),
                    field_type: FieldType::VecString,
                    role: FieldRole::Relation(RelationInfo {
                        kind: RelationKind::ManyToMany,
                        target: "Task".into(),
                        junction: None,
                        foreign_key: None,
                    }),
                    serde_default: true,
                    multiline_list: false,
                    default_value: None,
                },
            ],
        };

        let mods = modules(&["Task"]);
        let depends_field = &task.fields[1];
        let info = match &depends_field.role {
            FieldRole::Relation(i) => i,
            _ => panic!("expected relation"),
        };

        let (name, code) = generate_junction_code(&task, depends_field, info, &mods);

        assert_eq!(name, "task_depends_on");
        assert!(code.contains(r#"table_name = "task_depends_on""#));
        assert!(code.contains("pub task_id: String"), "source column");
        assert!(code.contains("pub target_id: String"), "disambiguated target column");

        // Both point to task entity
        let count = code.matches(r#"belongs_to = "super::task::Entity""#).count();
        assert_eq!(count, 2, "both variants point to task");

        // Variants are Source/Target for self-ref
        assert!(code.contains("Source,"), "Source variant");
        assert!(code.contains("Target,"), "Target variant");
    }

    #[test]
    fn generate_contract_multi_belongs_to() {
        let contract = EntityDef {
            name: "Contract".into(),
            directory: "contract".into(),
            table: "contracts".into(),
            type_name: "contract".into(),
            prefix: "contract".into(),

            fields: vec![
                FieldDef {
                    name: "id".into(),
                    field_type: FieldType::OptionString,
                    role: FieldRole::Id,
                    serde_default: false,
                    multiline_list: false,
                    default_value: None,
                },
                FieldDef {
                    name: "scope".into(),
                    field_type: FieldType::OptionString,
                    role: FieldRole::Relation(RelationInfo {
                        kind: RelationKind::BelongsTo,
                        target: "Node".into(),
                        junction: None,
                        foreign_key: None,
                    }),
                    serde_default: true,
                    multiline_list: false,
                    default_value: None,
                },
                FieldDef {
                    name: "from".into(),
                    field_type: FieldType::OptionString,
                    role: FieldRole::Relation(RelationInfo {
                        kind: RelationKind::BelongsTo,
                        target: "Node".into(),
                        junction: None,
                        foreign_key: None,
                    }),
                    serde_default: true,
                    multiline_list: false,
                    default_value: None,
                },
                FieldDef {
                    name: "to".into(),
                    field_type: FieldType::OptionString,
                    role: FieldRole::Relation(RelationInfo {
                        kind: RelationKind::BelongsTo,
                        target: "Node".into(),
                        junction: None,
                        foreign_key: None,
                    }),
                    serde_default: true,
                    multiline_list: false,
                    default_value: None,
                },
                FieldDef {
                    name: "fulfills".into(),
                    field_type: FieldType::VecString,
                    role: FieldRole::Relation(RelationInfo {
                        kind: RelationKind::ManyToMany,
                        target: "Requirement".into(),
                        junction: None,
                        foreign_key: None,
                    }),
                    serde_default: true,
                    multiline_list: false,
                    default_value: None,
                },
                FieldDef {
                    name: "body".into(),
                    field_type: FieldType::String,
                    role: FieldRole::Body,
                    serde_default: true,
                    multiline_list: false,
                    default_value: None,
                },
            ],
        };

        let mods = modules(&["Contract", "Node", "Requirement"]);
        let code = generate_entity_code(&contract, &mods);

        // OptionString id → String PK
        assert!(code.contains("pub id: String"), "OptionString id becomes String PK");

        // 3 distinct belongs_to variants, all to Node
        let bt_count = code.matches(r#"belongs_to = "super::node::Entity""#).count();
        assert_eq!(bt_count, 3, "3 belongs_to to Node");

        assert!(code.contains("Scope,"), "Scope variant");
        assert!(code.contains("From,"), "From variant");
        assert!(code.contains("To,"), "To variant");

        // fulfills should not be a column
        assert!(!code.contains("pub fulfills:"), "fulfills not a column");

        // Related impl for fulfills → Requirement via junction
        assert!(code.contains("impl Related<super::requirement::Entity>"));
    }

    /// Parse real schemas and verify generated code for all 13 entities.
    #[test]
    fn generate_all_real_schemas() {
        let schema_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../src-tauri/src/schema");

        if !schema_dir.exists() {
            eprintln!("Skipping: schema dir not found");
            return;
        }

        let entities = crate::schema::parse::parse_schema_dir(&schema_dir).expect("parse failed");
        let mods = build_entity_module_map(&entities);

        // Generate code for all entities
        for entity in &entities {
            let code = generate_entity_code(entity, &mods);
            assert!(
                code.contains(&format!("table_name = \"{}\"", entity.table)),
                "{}: missing table_name",
                entity.name
            );
            assert!(code.contains("pub struct Model"), "{}: missing Model", entity.name);
            assert!(code.contains("pub enum Relation"), "{}: missing Relation", entity.name);
            assert!(code.contains("impl ActiveModelBehavior"), "{}: missing ActiveModelBehavior", entity.name);
            assert!(!code.contains("pub wikilinks:"), "{}: should not have wikilinks column", entity.name);
            assert!(!code.contains("pub source_file:"), "{}: should not have source_file column", entity.name);
        }

        // Collect all junction tables
        let mut junctions = Vec::new();
        for entity in &entities {
            for (field, info) in entity.junction_relations() {
                junctions.push(generate_junction_code(entity, field, info, &mods));
            }
        }

        let junction_names: Vec<&str> = junctions.iter().map(|(n, _)| n.as_str()).collect();

        // Expected 8 junction tables
        assert_eq!(junctions.len(), 8, "expected 8 junction tables, got: {:?}", junction_names);
        assert!(junction_names.contains(&"capability_goal_ids"));
        assert!(junction_names.contains(&"specification_capability_ids"));
        assert!(junction_names.contains(&"specification_depends_on"));
        assert!(junction_names.contains(&"requirement_depends_on"));
        assert!(junction_names.contains(&"contract_fulfills"));
        assert!(junction_names.contains(&"constraint_scope_ids"));
        assert!(junction_names.contains(&"unit_of_work_depends_on"));
        assert!(junction_names.contains(&"unit_of_work_constraints"));
    }
}
