#![allow(dead_code, unused_imports, clippy::pedantic)]
//! Auto-generated HTTP route handlers. DO NOT EDIT.
//!
//! Generated by ontogen from API source files.

use std::sync::Arc;

use axum::{
    Router,
    extract::{Path, Query, State},
    http::StatusCode,
    response::Json,
    routing::{delete, get, post, put},
};

use serde::{Deserialize, Serialize};

use crate::AppState;
use crate::api::v1::{exercise, tag, workout, workout_set};
use crate::schema::{
    CreateExerciseInput, CreateTagInput, CreateWorkoutInput, CreateWorkoutSetInput, Exercise, Tag, UpdateExerciseInput,
    UpdateTagInput, UpdateWorkoutInput, UpdateWorkoutSetInput, Workout, WorkoutSet,
};
use crate::store::Store;

#[derive(Serialize)]
struct ErrorResponse {
    error: String,
}

type ApiError = (StatusCode, Json<ErrorResponse>);

fn err(msg: String) -> ApiError {
    (StatusCode::INTERNAL_SERVER_ERROR, Json(ErrorResponse { error: msg }))
}

// ── Exercise Handlers ──

async fn exercise_list(State(state): State<Arc<AppState>>) -> Result<Json<Vec<Exercise>>, ApiError> {
    let store = state.store().await.map_err(|e| err(e.to_string()))?;
    exercise::list(store).await.map(Json).map_err(|e| err(e.to_string()))
}

async fn exercise_get_by_id(
    State(state): State<Arc<AppState>>,
    Path(id): Path<String>,
) -> Result<Json<Exercise>, ApiError> {
    let store = state.store().await.map_err(|e| err(e.to_string()))?;
    exercise::get_by_id(store, &id).await.map(Json).map_err(|e| err(e.to_string()))
}

async fn exercise_create(
    State(state): State<Arc<AppState>>,
    Json(input): Json<CreateExerciseInput>,
) -> Result<(StatusCode, Json<Exercise>), ApiError> {
    let store = state.store().await.map_err(|e| err(e.to_string()))?;
    exercise::create(store, input)
        .await
        .map(|entity| (StatusCode::CREATED, Json(entity)))
        .map_err(|e| err(e.to_string()))
}

async fn exercise_update(
    State(state): State<Arc<AppState>>,
    Path(id): Path<String>,
    Json(input): Json<UpdateExerciseInput>,
) -> Result<Json<Exercise>, ApiError> {
    let store = state.store().await.map_err(|e| err(e.to_string()))?;
    exercise::update(store, &id, input).await.map(Json).map_err(|e| err(e.to_string()))
}

async fn exercise_delete(State(state): State<Arc<AppState>>, Path(id): Path<String>) -> Result<StatusCode, ApiError> {
    let store = state.store().await.map_err(|e| err(e.to_string()))?;
    exercise::delete(store, &id).await.map(|_| StatusCode::NO_CONTENT).map_err(|e| err(e.to_string()))
}

// ── Tag Handlers ──

async fn tag_list(State(state): State<Arc<AppState>>) -> Result<Json<Vec<Tag>>, ApiError> {
    let store = state.store().await.map_err(|e| err(e.to_string()))?;
    tag::list(store).await.map(Json).map_err(|e| err(e.to_string()))
}

async fn tag_get_by_id(State(state): State<Arc<AppState>>, Path(id): Path<String>) -> Result<Json<Tag>, ApiError> {
    let store = state.store().await.map_err(|e| err(e.to_string()))?;
    tag::get_by_id(store, &id).await.map(Json).map_err(|e| err(e.to_string()))
}

async fn tag_create(
    State(state): State<Arc<AppState>>,
    Json(input): Json<CreateTagInput>,
) -> Result<(StatusCode, Json<Tag>), ApiError> {
    let store = state.store().await.map_err(|e| err(e.to_string()))?;
    tag::create(store, input).await.map(|entity| (StatusCode::CREATED, Json(entity))).map_err(|e| err(e.to_string()))
}

async fn tag_update(
    State(state): State<Arc<AppState>>,
    Path(id): Path<String>,
    Json(input): Json<UpdateTagInput>,
) -> Result<Json<Tag>, ApiError> {
    let store = state.store().await.map_err(|e| err(e.to_string()))?;
    tag::update(store, &id, input).await.map(Json).map_err(|e| err(e.to_string()))
}

async fn tag_delete(State(state): State<Arc<AppState>>, Path(id): Path<String>) -> Result<StatusCode, ApiError> {
    let store = state.store().await.map_err(|e| err(e.to_string()))?;
    tag::delete(store, &id).await.map(|_| StatusCode::NO_CONTENT).map_err(|e| err(e.to_string()))
}

// ── Workout Handlers ──

async fn workout_list(State(state): State<Arc<AppState>>) -> Result<Json<Vec<Workout>>, ApiError> {
    let store = state.store().await.map_err(|e| err(e.to_string()))?;
    workout::list(store).await.map(Json).map_err(|e| err(e.to_string()))
}

async fn workout_get_by_id(
    State(state): State<Arc<AppState>>,
    Path(id): Path<String>,
) -> Result<Json<Workout>, ApiError> {
    let store = state.store().await.map_err(|e| err(e.to_string()))?;
    workout::get_by_id(store, &id).await.map(Json).map_err(|e| err(e.to_string()))
}

async fn workout_create(
    State(state): State<Arc<AppState>>,
    Json(input): Json<CreateWorkoutInput>,
) -> Result<(StatusCode, Json<Workout>), ApiError> {
    let store = state.store().await.map_err(|e| err(e.to_string()))?;
    workout::create(store, input)
        .await
        .map(|entity| (StatusCode::CREATED, Json(entity)))
        .map_err(|e| err(e.to_string()))
}

async fn workout_update(
    State(state): State<Arc<AppState>>,
    Path(id): Path<String>,
    Json(input): Json<UpdateWorkoutInput>,
) -> Result<Json<Workout>, ApiError> {
    let store = state.store().await.map_err(|e| err(e.to_string()))?;
    workout::update(store, &id, input).await.map(Json).map_err(|e| err(e.to_string()))
}

async fn workout_delete(State(state): State<Arc<AppState>>, Path(id): Path<String>) -> Result<StatusCode, ApiError> {
    let store = state.store().await.map_err(|e| err(e.to_string()))?;
    workout::delete(store, &id).await.map(|_| StatusCode::NO_CONTENT).map_err(|e| err(e.to_string()))
}

// ── Workout_set Handlers ──

async fn workout_set_list(State(state): State<Arc<AppState>>) -> Result<Json<Vec<WorkoutSet>>, ApiError> {
    let store = state.store().await.map_err(|e| err(e.to_string()))?;
    workout_set::list(store).await.map(Json).map_err(|e| err(e.to_string()))
}

async fn workout_set_get_by_id(
    State(state): State<Arc<AppState>>,
    Path(id): Path<String>,
) -> Result<Json<WorkoutSet>, ApiError> {
    let store = state.store().await.map_err(|e| err(e.to_string()))?;
    workout_set::get_by_id(store, &id).await.map(Json).map_err(|e| err(e.to_string()))
}

async fn workout_set_create(
    State(state): State<Arc<AppState>>,
    Json(input): Json<CreateWorkoutSetInput>,
) -> Result<(StatusCode, Json<WorkoutSet>), ApiError> {
    let store = state.store().await.map_err(|e| err(e.to_string()))?;
    workout_set::create(store, input)
        .await
        .map(|entity| (StatusCode::CREATED, Json(entity)))
        .map_err(|e| err(e.to_string()))
}

async fn workout_set_update(
    State(state): State<Arc<AppState>>,
    Path(id): Path<String>,
    Json(input): Json<UpdateWorkoutSetInput>,
) -> Result<Json<WorkoutSet>, ApiError> {
    let store = state.store().await.map_err(|e| err(e.to_string()))?;
    workout_set::update(store, &id, input).await.map(Json).map_err(|e| err(e.to_string()))
}

async fn workout_set_delete(
    State(state): State<Arc<AppState>>,
    Path(id): Path<String>,
) -> Result<StatusCode, ApiError> {
    let store = state.store().await.map_err(|e| err(e.to_string()))?;
    workout_set::delete(store, &id).await.map(|_| StatusCode::NO_CONTENT).map_err(|e| err(e.to_string()))
}

/// Generated routes. Call this from your main router.
pub fn entity_routes() -> Router<Arc<AppState>> {
    Router::new()
        .route("/api/exercises", get(exercise_list).post(exercise_create))
        .route("/api/exercises/:id", get(exercise_get_by_id).put(exercise_update).delete(exercise_delete))
        .route("/api/tags", get(tag_list).post(tag_create))
        .route("/api/tags/:id", get(tag_get_by_id).put(tag_update).delete(tag_delete))
        .route("/api/workouts", get(workout_list).post(workout_create))
        .route("/api/workouts/:id", get(workout_get_by_id).put(workout_update).delete(workout_delete))
        .route("/api/workout-sets", get(workout_set_list).post(workout_set_create))
        .route("/api/workout-sets/:id", get(workout_set_get_by_id).put(workout_set_update).delete(workout_set_delete))
}
