// TODO: review — autogenerated from src/lib.rs extraction
//! Build-time utilities shared across codegen layers.

use std::collections::HashSet;
use std::path::Path;

/// Write content to a file only if the content has changed.
///
/// This prevents unnecessary file-system modifications that trigger
/// file-watchers (e.g. Tauri dev) and cause infinite rebuild loops.
pub fn write_if_changed(path: &Path, content: impl AsRef<[u8]>) -> std::io::Result<()> {
    let content = content.as_ref();
    if path.exists()
        && let Ok(existing) = std::fs::read(path)
        && existing == content
    {
        return Ok(());
    }
    std::fs::write(path, content)
}

/// Write content to a file and run `rustfmt`, but only if the formatted
/// result differs from what's already on disk.
///
/// This avoids touching file mtimes when nothing changed, preventing
/// infinite rebuild loops with file-watchers (e.g. Tauri dev).
pub fn write_and_format(path: &Path, content: impl AsRef<str>) -> std::io::Result<()> {
    let formatted = rustfmt_string(content.as_ref());
    write_if_changed(path, formatted)
}

/// Run `rustfmt` on a string in memory, returning the formatted result.
/// Falls back to the original string if rustfmt is not available.
fn rustfmt_string(input: &str) -> String {
    use std::io::Write;
    use std::process::{Command, Stdio};

    let mut child = match Command::new("rustfmt")
        .arg("--edition")
        .arg("2024")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn()
    {
        Ok(c) => c,
        Err(_) => return input.to_string(),
    };

    if let Some(mut stdin) = child.stdin.take() {
        let _ = stdin.write_all(input.as_bytes());
    }

    match child.wait_with_output() {
        Ok(output) if output.status.success() => String::from_utf8(output.stdout).unwrap_or_else(|_| input.to_string()),
        _ => input.to_string(),
    }
}

/// Run `rustfmt` on a generated Rust file.
/// Silently ignores failures (e.g., if rustfmt is not installed).
pub fn rustfmt(path: &Path) {
    let _ = std::process::Command::new("rustfmt").arg("--edition").arg("2024").arg(path).status();
}

/// Run `prettier` on generated TypeScript files.
/// Silently ignores failures.
pub fn prettier(paths: &[&Path]) {
    if paths.is_empty() {
        return;
    }
    let mut cmd = std::process::Command::new("npx");
    cmd.arg("prettier").arg("--write");
    for p in paths {
        cmd.arg(p);
    }
    let _ = cmd.status();
}

/// Remove `.rs` files from `dir` that are not in `expected`.
///
/// Call this at the start of each generator to clean up files left behind
/// by entity renames or deletions.  `expected` should contain bare filenames
/// like `"node.rs"`, `"mod.rs"`, etc.  Files whose names are not in the set
/// are deleted.  Non-`.rs` files and subdirectories are left alone.
pub fn clean_generated_dir(dir: &Path, expected: &HashSet<String>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_file() && path.extension().is_some_and(|ext| ext == "rs") {
            let name = entry.file_name().to_string_lossy().to_string();
            if !expected.contains(&name) {
                let _ = std::fs::remove_file(&path);
            }
        }
    }
}

/// Emit `cargo:rerun-if-changed` directives for all `.rs` files in a directory.
pub fn emit_rerun_directives(dir: &Path) {
    println!("cargo:rerun-if-changed={}", dir.display());
    if let Ok(entries) = std::fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().is_some_and(|ext| ext == "rs") {
                println!("cargo:rerun-if-changed={}", path.display());
            }
        }
    }
}
