//! Generated by ontogen. DO NOT EDIT.

use schemars::JsonSchema;
use serde::Deserialize;

/// Input for creating a new Fixed.
#[derive(Debug, Clone, Deserialize, JsonSchema, specta::Type)]
pub struct CreateFixedInput {
    #[serde(default)]
    pub id: String,
    pub title: String,
}

/// Input for updating an existing Fixed.
/// All fields are optional; only provided fields are updated.
#[derive(Debug, Clone, Deserialize, JsonSchema, specta::Type)]
pub struct UpdateFixedInput {
    #[serde(default)]
    pub title: Option<String>,
}
